import type { Metadata } from "next";
import { Header, Footer } from "../components";
import { TestimonialsRail } from "../booking-components";
import { site, services } from "../data";
import StandardContactForm from "./StandardContactForm";
import styles from "./contact.module.css";
const pageUrl = "https://outsourcedcallers.com/contact-us";
export const metadata: Metadata = { title: `Contact ${site.brand} | Free Consultation`, description: "Build an outsourced calling team around clear scripts, handoffs, compliance boundaries, and reporting.", alternates: { canonical: pageUrl }, robots: { index: true, follow: true } };
const prep = ["Campaign goals, call types, and approved scripts", "Hours, systems, lists, and access limits", "Escalation owners, outcomes, and QA expectations"];
export default function ContactUsPage() { return <><Header/><main className={styles.page}>
  <section className={styles.hero}><div className={styles.shellGrid}><div><p className={styles.eyebrow}>Build a focused calling team</p><h1>Make every call support a clear next step.</h1><p className={styles.lead}>Tell us which conversations matter, where follow-up breaks down, and what your team must approve. We’ll prepare a practical staffing conversation around your call workflow.</p><div className={styles.checks}>{prep.map(x=><span key={x}>✓ {x}</span>)}</div><p className={styles.powered}>Powered by Stealth Agents</p></div><div id="consultation-form"><StandardContactForm endpoint="/api/contact" encoding="form"/></div></div></section>
  <section className={styles.section}><div className={styles.shell}><p className={styles.kicker}>Prepare the brief</p><h2>What to bring to your consultation</h2><div className={styles.cards}>{prep.map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>Concrete examples help define a useful script, ownership boundary, and reporting rhythm.</p></article>)}</div></div></section>
  <section className={`${styles.section} ${styles.soft}`}><div className={styles.shell}><p className={styles.kicker}>Client perspective</p><h2>What Stealth Agents clients say</h2><p className={styles.sub}>Attributed client feedback provides context for the staffing partner behind this consultation path.</p><TestimonialsRail contact/></div></section>
  <section className={styles.section}><div className={styles.shellGrid}><div><p className={styles.kicker}>Calling possibilities</p><h2>Shape the role around conversations your business needs.</h2><p className={styles.sub}>Start with a bounded campaign, approved messaging, and an explicit escalation path.</p><a className={styles.textLink} href="#consultation-form">Plan my calling role →</a></div><div className={styles.tags}>{services.slice(0,8).map(s=><span key={s.slug}>{s.title}</span>)}</div></div></section>
  <section className={`${styles.section} ${styles.about}`}><div className={styles.shellGrid}><img src="/blog-heroes/filipino-caller-coaching-correction-loop.png" alt={site.alt}/><div><p className={styles.kicker}>Our staffing partner</p><h2>About Stealth Agents</h2><p>Stealth Agents works with over 35+ different industries. We&apos;re featured on Forbes as the top rated virtual assistant company.</p><a className={styles.textLink} href="https://stealthagents.com/" target="_blank" rel="noopener noreferrer">Powered by Stealth Agents ↗</a></div></div></section>
  <section className={styles.section}><div className={styles.shell}><p className={styles.kicker}>A safer launch</p><h2>Clear expectations before calling starts</h2><div className={styles.cards}><article><h3>Approved language</h3><p>Keep claims, offers, and exceptions within reviewed scripts.</p></article><article><h3>Named handoffs</h3><p>Route sensitive or high-intent conversations to an owner.</p></article><article><h3>Measured quality</h3><p>Review outcomes and recordings before expanding.</p></article></div></div></section>
  <section className={styles.final}><div className={styles.shell}><h2>Ready to build reliable calling coverage?</h2><p>Share the campaign, hours, systems, and outcomes you need supported.</p><a href="#consultation-form">Book a free consultation</a></div></section>
  </main><Footer/></> }
