type Aug17Seed = readonly [slug: string, title: string, excerpt: string, question: string, decision: string, scenario: string, boundary: string, owner: string];

const seeds: readonly Aug17Seed[] = [
  ['appointment-setting-discovery-question-map', 'Appointment setting discovery-question map', 'How a Filipino appointment setter can use one useful discovery question without turning a first call into an improvised sales interview.', 'Which single fact would make the requested meeting useful to the owner?', 'whether the next question belongs in the approved appointment brief', 'a prospect offers a broad reason for meeting but names two unrelated problems', 'do not diagnose fit or recommend a service from an incomplete answer', 'the appointment owner'],
  ['lead-qualification-evidence-threshold', 'Lead qualification evidence threshold', 'A practical threshold for recording a lead signal as stated evidence, an open question, or an owner decision during Filipino qualification calls.', 'What did the prospect actually establish, and what is still only suspected?', 'whether the record has enough approved evidence for a handoff', 'a contact agrees that a problem exists but cannot confirm timing or ownership', 'do not turn enthusiasm, politeness, or a vague answer into a buying conclusion', 'the lead owner'],
  ['inbound-call-identity-mismatch-handoff', 'Inbound call identity mismatch handoff', 'How Filipino inbound callers can keep a helpful conversation moving when the caller and account record do not match.', 'What can be handled without revealing or changing the wrong person’s information?', 'whether to message, transfer, or stop for an identity owner', 'a caller knows an order reference but cannot confirm the approved identity detail', 'do not read account information aloud or improvise a verification method', 'the account owner'],
  ['customer-follow-up-commitment-repair', 'Customer follow-up commitment repair', 'A guide to repairing an unclear promise in a customer follow-up note so the next owner can respond accurately.', 'What was actually promised, by whom, and what needs correction now?', 'whether the note needs an owner-led clarification before another call', 'a prior message says someone will “take care of it” without a date or named responsibility', 'do not repeat an uncertain promise as a confirmed resolution', 'the customer-service owner'],
  ['outbound-calling-contact-window-exception', 'Outbound calling contact-window exception', 'How to handle a requested call time that falls outside the approved outbound calling window while preserving the person’s preference.', 'Can the requested time be honored under the current brief, or does it require review?', 'whether to schedule within the approved window or route an exception', 'a contact asks for an evening callback even though the released list has a narrower window', 'do not promise an exception or keep calling after a clear stop request', 'the campaign owner'],
  ['filipino-caller-name-number-confirmation', 'Filipino caller name-and-number confirmation', 'A respectful method for confirming names and numbers in Filipino calling work without treating accent or speed as a quality proxy.', 'Which detail needs repeating, spelling, or a read-back to prevent a bad handoff?', 'which confirmation method makes the record reliable for the receiving owner', 'a surname and callback number are both understood differently on the first pass', 'do not infer capability from accent; judge the confirmed information and outcome', 'the quality owner'],
  ['appointment-setting-calendar-hold-boundary', 'Appointment setting calendar-hold boundary', 'How appointment setters can distinguish a requested meeting hold from a confirmed calendar commitment.', 'Has the owner accepted a specific time, or is the prospect only offering availability?', 'whether the next state is request, hold, confirmation, or follow-up', 'a prospect offers two times while the calendar owner has not approved either one', 'do not represent a tentative window as a booked meeting', 'the calendar owner'],
  ['customer-follow-up-reason-for-contact', 'Customer follow-up reason-for-contact capture', 'A focused way to preserve why a customer wants a callback when the reason contains more than one issue.', 'Which issue should the next owner address first, and which details remain separate?', 'how to split one conversation into accountable follow-up items', 'a customer asks about a prior issue and adds a new request before the call closes', 'do not collapse separate requests into one vague “follow-up needed” label', 'the customer owner'],
  ['order-confirmation-approved-change-boundary', 'Order confirmation approved-change boundary', 'How Filipino order confirmation callers can record a requested change without implying that fulfillment has accepted it.', 'Is the customer confirming the order or requesting a new fulfillment decision?', 'whether the result is confirmed, exception, or owner review', 'a customer confirms the item but asks to change quantity after the order record is read back', 'do not edit or promise a material order change without the responsible approval', 'the fulfillment owner'],
  ['database-verification-record-provenance', 'Database verification record provenance', 'A practical note standard for showing where a spoken correction came from and how confidently it can be reviewed.', 'Who supplied the correction, which field changed, and what source can the owner verify?', 'whether the data owner can accept the correction or needs another check', 'a household member supplies a spelling correction for the named contact', 'do not treat an unverified third-party statement as final record authority', 'the data owner'],
  ['renewal-reminder-term-question-routing', 'Renewal reminder term-question routing', 'How to capture a renewal question precisely while keeping contract, eligibility, and account decisions with the authorized owner.', 'What does the customer need explained before they can decide whether to continue?', 'which question can be answered from approved wording and which needs review', 'a customer asks whether a changed term applies to their account', 'do not interpret terms or imply eligibility from a general script', 'the account owner'],
  ['win-back-refusal-complete-outcome', 'Win-back refusal as a complete outcome', 'Why a former customer’s refusal should be recorded as a complete result even when they explain why they left.', 'Has the person declined future contact, and what suppression action follows?', 'whether the record closes, suppresses, or requires a policy owner', 'a former customer shares useful feedback but clearly says not to call again', 'do not treat feedback as permission for another offer', 'the list owner'],
  ['survey-calling-uncertain-answer-label', 'Survey calling uncertain-answer label', 'How survey callers can preserve uncertainty instead of forcing a respondent into a category that does not fit their answer.', 'Did the respondent answer, ask for clarification, decline, or remain uncertain?', 'which approved result label matches the respondent’s actual state', 'a respondent understands the topic but says the available options do not describe them', 'do not suggest an answer or recast uncertainty as agreement', 'the survey owner'],
  ['reception-overflow-message-completeness', 'Reception overflow message completeness', 'A message standard for reception overflow calls that gives the recipient enough context without inventing urgency.', 'What must the recipient know to choose the next action?', 'whether the message is complete enough to route or needs one clarification', 'a caller says “it is urgent” but gives no reason, deadline, or safe callback detail', 'do not label a matter urgent solely from tone or pressure', 'the receiving manager'],
  ['outbound-calling-wrong-party-suppression', 'Outbound calling wrong-party suppression', 'A clean wrong-party close that protects contact preferences and prevents a mistaken person from remaining in an outbound queue.', 'What can be confirmed safely, and should this number be suppressed or reviewed?', 'whether the record needs suppression, correction, or owner review', 'someone answers a number and says the intended contact has never used it', 'do not ask the wrong party to supply private details about the intended contact', 'the list owner'],
  ['customer-follow-up-channel-effective-date', 'Customer follow-up channel effective date', 'How to record a customer’s requested contact-channel change with the timing needed for a safe next outreach.', 'Which channel did the customer request, and from when should it apply?', 'whether the current system preference changes now or after owner review', 'a customer wants email instead of phone but only for future follow-ups', 'do not promise that a policy or system change is already active', 'the customer-data owner'],
  ['appointment-setting-time-zone-confirmation', 'Appointment setting time-zone confirmation', 'A practical check for time zone and local date before an appointment request reaches the calendar owner.', 'Whose local time is being proposed, and what exact date and window should be reviewed?', 'whether the request is unambiguous enough to hand off', 'a prospect and owner work in different time zones and use “tomorrow morning”', 'do not translate a relative time into a confirmed slot without the owner’s check', 'the calendar owner'],
  ['inbound-call-transfer-context-packet', 'Inbound call transfer context packet', 'What an inbound caller should pass to the receiving owner so the customer does not have to repeat the whole issue.', 'What is the purpose, what was already answered, and what remains unresolved?', 'whether to transfer now or send a complete message instead', 'a caller has explained the issue once and the receiving team needs one missing detail', 'do not transfer a sensitive or unresolved matter without the required context', 'the receiving owner'],
  ['lead-qualification-role-authority-check', 'Lead qualification role-and-authority check', 'How to learn whether a prospect owns the relevant decision without treating job title or confidence as proof.', 'What part of the decision does the contact influence, and who else must be involved?', 'whether the handoff needs another participant or an owner review', 'a prospect can describe the problem but says another colleague approves the next step', 'do not claim the contact is the final decision-maker from title alone', 'the lead owner'],
  ['order-confirmation-split-shipment-question', 'Order confirmation split-shipment question', 'How to separate a customer’s delivery question from the order confirmation result when items may arrive under different schedules.', 'Is the order confirmed, or is the customer asking for a fulfillment explanation?', 'which detail belongs in the confirmation and which needs fulfillment review', 'a customer confirms the items but asks whether they will arrive together', 'do not invent a delivery schedule or combine separate fulfillment decisions', 'the fulfillment owner'],
  ['call-quality-observation-evidence-note', 'Call quality observation evidence note', 'A review method for distinguishing what a Filipino caller said, what the customer answered, and what the reviewer inferred.', 'Which exact words or record fields support the quality observation?', 'whether the coaching point is evidence-based and actionable', 'a reviewer labels a call “weak” without identifying the missed question or note field', 'do not score personality, accent, or assumed intent instead of observable work', 'the quality manager'],
  ['daily-calling-queue-reason-code', 'Daily calling queue reason code', 'How to keep a calling queue useful by tying each record to one purpose and one reason it is ready for work.', 'Why is this record in today’s queue, and what result would complete that reason?', 'whether the record is ready, blocked, or misrouted', 'a list mixes callbacks, qualification, and data checks under one generic task label', 'do not let activity volume hide a queue with no clear purpose', 'the operations owner'],
];

export const aug17BlogPosts = seeds.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 11, published: '2026-08-17' as const }));

export function makeAug17Detail(post: typeof aug17BlogPosts[number]) {
  const seed = seeds.find((item) => item[0] === post.slug)!;
  const [, title, excerpt, question, decision, scenario, boundary, owner] = seed;
  return {
    published: '2026-08-17', mainKeyword: title, metaLabel: 'Philippines staffing blog',
    directAnswerHeading: `How to handle ${title.toLowerCase()}`,
    summary: `${title} is useful when a Filipino caller keeps the conversation tied to one decision: ${question} The caller preserves the person’s answer and routes ${decision} to ${owner}.`,
    takeaways: [`Start with the question: ${question}`, 'Write the caller’s evidence separately from interpretation.', `Treat ${scenario} as a review condition, not a reason to guess.`, `Use the boundary: ${boundary}.`, 'Close with a result, next action, accountable owner, and reply point.'],
    decisionTable: [
      { lane: 'Purpose', caller: `Explains why the ${title.toLowerCase()} check is happening.`, owner: 'Defines the approved audience, wording, and result.', measure: 'The person understands the reason for contact' },
      { lane: 'Evidence', caller: 'Captures the answer, refusal, request, or uncertainty in plain language.', owner: 'Decides which source and fields are sufficient.', measure: 'The note shows what was actually established' },
      { lane: 'Boundary', caller: `Stops at ${boundary}.`, owner: `Reviews the exception and owns ${decision}.`, measure: 'No guess becomes a commitment' },
      { lane: 'Handoff', caller: 'Sends purpose, evidence, open point, and requested action.', owner: `Owns the response as ${owner}.`, measure: 'The next person can act without repeating the call' },
    ],
    planningBands: [{ label: 'Question', value: 'One', note: question }, { label: 'Evidence', value: 'Named', note: 'Separate words from inference' }, { label: 'Boundary', value: 'Visible', note: 'Pause before an unsupported decision' }, { label: 'Owner', value: 'Clear', note: owner }],
    sections: [
      { heading: 'Define the decision before dialing', paragraphs: [`Before a Filipino caller begins ${title.toLowerCase()}, the brief should state ${question.toLowerCase()} That prevents a useful conversation from becoming a broad interview.`, `The owner should also state what evidence is enough for ${decision}. If the record does not meet that threshold, the correct result is an open question or review item.`] },
      { heading: 'Preserve the scenario without over-reading it', paragraphs: [`Consider ${scenario}. The caller can acknowledge the situation, ask the approved follow-up, and record the answer without deciding more than the person said.`, 'A reliable note distinguishes a confirmed fact, a request, a refusal, and an unresolved point. Those distinctions make later review faster and protect the customer from being represented inaccurately.'] },
      { heading: 'Make the stop point usable', paragraphs: [`The practical stop point is ${boundary}. A caller can explain that the request has been recorded and that ${owner} owns the next decision.`, 'This is not an abrupt ending. It is a clear handoff that avoids an unsupported promise and gives the next person the context needed to respond well.'] },
      { heading: 'Close with a self-contained handoff', paragraphs: ['The final note should state why the call happened, what the person said, what remains open, and what action is requested. Add the approved reply timing when the brief requires it.', `For ${title.toLowerCase()}, review the handoff against the original question rather than against call volume. A short, accurate conversation is more useful than a long record with an invented conclusion.`] },
    ],
    scripts: [{ title: 'Opening', text: `I am calling about ${title.toLowerCase()}. I will keep this focused on the one question we need to clarify.` }, { title: 'Clarifying', text: 'I want to record that accurately. May I repeat the point I have so far?' }, { title: 'Boundary', text: `I can record that request, but ${owner} needs to decide the next step.` }],
    workflow: [{ step: '1', title: 'Set purpose', text: 'Write the one question and intended result.' }, { step: '2', title: 'Check context', text: 'Use only the approved record details.' }, { step: '3', title: 'Listen', text: 'Capture the exact answer or uncertainty.' }, { step: '4', title: 'Route', text: 'Send the boundary condition to its owner.' }, { step: '5', title: 'Close', text: 'Save result, action, owner, and reply point.' }],
    faqs: [{ q: `What makes ${title.toLowerCase()} useful?`, a: `It links one clear question to the person’s answer, the unresolved point, and the owner responsible for ${decision}.` }, { q: 'What if the person gives an answer outside the brief?', a: 'Record it neutrally, explain the review boundary, and route it without making a promise.' }, { q: 'How should an uncertain answer be handled?', a: 'Keep uncertainty visible. Do not force it into a positive, negative, or completed label.' }],
    related: [{ label: 'Appointment setting service', href: '/services/appointment-setting' }, { label: 'Customer follow-up service', href: '/services/customer-follow-up-calls' }, { label: 'Call quality review service', href: '/services/call-quality-review' }],
    sources: [{ name: 'FCC Telephone Consumer Protection Act guidance', url: 'https://www.fcc.gov/general/telemarketing-and-telephone-consumer-protection-act' }, { name: 'FTC business guidance on data security', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }],
  };
}
