type ResearchSeed = {
  slug: string; title: string; excerpt: string; published: string; subject: string; audience: string;
  evidence: string; measure: string; risk: string; owner: string; limitation: string;
};

const seeds: ResearchSeed[] = [
  { slug:'appointment-setting-discovery-depth-research', title:'Appointment-setting discovery-depth research', excerpt:'How a calling conversation can capture enough stated need for a useful appointment without turning a brief contact into an unsupported sales qualification.', published:'2026-08-13', subject:'discovery depth before an appointment is offered', audience:'a prospect deciding whether a conversation is worth keeping', evidence:'BLS customer-service guidance, FTC telemarketing guidance, and SBA market-research guidance', measure:'whether the handoff preserves the prospect’s stated need, timing, participants, and unresolved question', risk:'a calendar event that looks successful but gives the recipient no reliable context', owner:'the business owner who defines the meeting’s acceptance standard', limitation:'no universal question count proves that a meeting is qualified; complexity, consent, and industry change the appropriate depth' },
  { slug:'outbound-calling-answering-machine-research', title:'Outbound calling answering-machine research', excerpt:'What an outbound calling record should preserve when a person is not reached, a message is permitted, or the next attempt must stop.', published:'2026-08-13', subject:'answering-machine outcomes in outbound calling', audience:'the person whose number was called and the owner reviewing reachability', evidence:'FCC consumer guidance, FTC telemarketing guidance, and ICO live-call guidance', measure:'whether the record distinguishes no answer, permitted message, wrong party, refusal, and suppression', risk:'treating an unanswered attempt as interest or repeatedly contacting someone who has asked for no calls', owner:'the business owner responsible for contact rules and suppression', limitation:'calling permissions and message rules vary by purpose, technology, jurisdiction, and recipient' },
  { slug:'customer-follow-up-empathy-and-accuracy-research', title:'Customer follow-up empathy and accuracy research', excerpt:'How follow-up calls can acknowledge a customer’s experience while keeping the written result factual, bounded, and useful to the responsible owner.', published:'2026-08-13', subject:'empathy and factual accuracy during customer follow-up', audience:'a customer waiting for an answer and the owner who must act on the record', evidence:'BLS customer-service guidance, NIST Privacy Framework, and FTC data-security guidance', measure:'whether the note preserves the customer’s concern, approved answer, uncertainty, and next owner', risk:'warm language masking an inaccurate status or creating a promise the caller cannot keep', owner:'the service owner accountable for the resolution', limitation:'empathy is context-dependent and a short call cannot resolve every emotional or substantive concern' },
  { slug:'inbound-call-accessibility-communication-research', title:'Inbound call accessibility communication research', excerpt:'A practical research view of recording communication needs respectfully while leaving accommodation decisions with the responsible business owner.', published:'2026-08-13', subject:'accessibility communication needs in inbound calls', audience:'a caller seeking an accessible way to continue a conversation', evidence:'ADA.gov guidance, W3C accessibility principles, and NIST Privacy Framework', measure:'whether the record captures the requested communication support without diagnosing, guessing, or exposing unnecessary detail', risk:'treating an access request as a preference that can be ignored or improvising an accommodation promise', owner:'the business or event owner who controls the accommodation decision', limitation:'access needs are individual, and legal duties depend on the service, setting, and jurisdiction' },
  { slug:'database-verification-identity-confidence-research', title:'Database verification identity-confidence research', excerpt:'How a verification call can record what is known, what is uncertain, and what needs review before a customer record is changed.', published:'2026-08-13', subject:'identity confidence during database verification', audience:'a customer whose record may contain an error and the data owner reviewing it', evidence:'NIST Privacy Framework, FTC data-security guidance, and Philippines NPC Data Privacy Act resources', measure:'whether identity evidence, field accuracy, and requested change are recorded as separate conditions', risk:'a confident-sounding answer causing an unauthorized merge, disclosure, or correction', owner:'the data owner who approves changes to the authoritative record', limitation:'identity checks must follow the organization’s approved controls; a phone conversation alone is not universal proof' },
  { slug:'event-registration-reminder-effectiveness-research', title:'Event registration reminder effectiveness research', excerpt:'What makes an event reminder useful when the goal is accurate attendance information rather than pressure or an invented commitment.', published:'2026-08-13', subject:'reminder effectiveness for event registrations', audience:'an attendee deciding whether and how to participate', evidence:'SBA market-research guidance, FTC consumer guidance, and W3C accessibility principles', measure:'whether the reminder clarifies attendance intent, approved event facts, questions, and the next accountable owner', risk:'counting a completed call as attendance confirmation when the attendee is uncertain or requests a policy exception', owner:'the event owner responsible for capacity, access, and policy decisions', limitation:'attendance response rates depend on event type, timing, audience, channel, and the quality of the registration data' },
  { slug:'survey-calling-order-effects-research', title:'Survey calling question-order effects research', excerpt:'How question order and neutral clarification affect the quality of survey responses without leading the respondent or turning research into promotion.', published:'2026-08-13', subject:'question-order effects in survey calling', audience:'a respondent whose answer should be recorded in their own terms', evidence:'AAPOR best practices, Pew Research Center methods, and BLS customer-service guidance', measure:'whether respondents receive the same core questions, refusals are recorded honestly, and clarification avoids suggestion', risk:'an interviewer changing answer distributions by explaining, correcting, or rewarding a preferred response', owner:'the research owner who defines the instrument and coding rules', limitation:'telephone samples have coverage, nonresponse, mode, and social-desirability limitations that no script removes' },
  { slug:'reception-overflow-message-completeness-research', title:'Reception overflow message-completeness research', excerpt:'How an overflow message can give a business owner enough accurate context to respond without making the front desk responsible for the decision.', published:'2026-08-13', subject:'message completeness during reception overflow', audience:'a caller trying to reach the right person and the recipient deciding what happens next', evidence:'BLS customer-service guidance, NIST Privacy Framework, and FTC data-security guidance', measure:'whether the message identifies purpose, callback route, urgency stated by the caller, and unresolved question', risk:'a vague or embellished message delaying action or exposing information to the wrong recipient', owner:'the receiving business owner who determines priority and response', limitation:'urgency cannot be inferred from tone alone, and the minimum useful fields differ by business' },
  { slug:'renewal-reminder-customer-choice-research', title:'Renewal reminder customer-choice research', excerpt:'How renewal reminders can inform a customer while preserving choice, recording a contact preference, and routing account decisions safely.', published:'2026-08-13', subject:'customer choice in renewal reminders', audience:'a customer deciding whether to continue, ask a question, or stop contact', evidence:'FTC Telemarketing Sales Rule guidance, ICO live-call guidance, and FTC consumer information', measure:'whether the record separates reminder receipt, customer choice, preference, objection, and owner review', risk:'pressure language or an inaccurate “renewed” label changing the customer’s apparent decision', owner:'the account owner responsible for terms, cancellation, payment, and disputes', limitation:'renewal rights, notice periods, consent, and contact restrictions vary across products and jurisdictions' },
  { slug:'order-confirmation-item-accuracy-research', title:'Order confirmation item-accuracy research', excerpt:'How confirmation calls can test item-level accuracy while stopping cleanly when a customer raises a fulfillment, payment, or return question.', published:'2026-08-13', subject:'item-level accuracy in order confirmations', audience:'a customer checking an order and the fulfillment owner responsible for exceptions', evidence:'FTC Mail, Internet, or Telephone Order Merchandise Rule, PCI Security Standards Council guidance, and NIST Privacy Framework', measure:'whether each approved item is confirmed separately from any new request or discrepancy', risk:'a broad “confirmed” label hiding a changed quantity, unavailable item, payment issue, or return request', owner:'the fulfillment owner who controls changes, delivery promises, and remedies', limitation:'the safe fields and verification method depend on product, payment environment, and applicable consumer law' }
];

const sources = (s: ResearchSeed) => `Sources: ${s.evidence}. See https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm, https://www.ftc.gov/business-guidance/advertising-marketing/telemarketing, https://www.nist.gov/privacy-framework, and https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis. These sources describe their own populations, rules, or frameworks and are not performance claims about OutsourcedCallers.com.`;

function body(s: ResearchSeed): string[] {
  return [
    `This research examines ${s.subject} in the context of outsourced calling services. The central question is not whether a conversation occurred. It is whether the resulting record gives ${s.audience} an accurate basis for the next authorized decision. That distinction matters because contact volume can look complete while the underlying customer experience remains unresolved. A useful record must preserve what was stated, what was verified, what remains uncertain, and who owns the next action.`,
    `The first finding is that the purpose of the call must be narrow enough to test. For ${s.subject}, the relevant observation is not a general impression of helpfulness. It is a set of identifiable facts: the approved reason for contact, the person’s response, the permitted outcome, and any exception. A caller can ask for those facts in plain language and reflect the answer without converting an uncertain statement into a business conclusion. This protects both the person contacted and the owner reviewing the result.`,
    `The evidence base is useful when its limits are respected. ${s.evidence} address customer communication, privacy, contact practices, or research quality from different angles. They do not provide a single universal script or guarantee a result for one organization. Their shared implication is narrower: define the purpose, minimize unnecessary information, represent the person’s response truthfully, and keep consequential decisions with an accountable owner. That implication is applied here as an analytical lens rather than presented as a legal opinion.`,
    `A practical observation model starts with the source record. Before contact, identify the approved fields and the reason they matter. During contact, distinguish a confirmed fact from a request, a refusal, an unanswered question, and a signal that identity or authority is unclear. After contact, compare the written result with the source and with the eventual owner decision. ${s.measure} is therefore stronger than a simple count of attempts or connected calls.`,
    `The second finding concerns language. A respectful caller can acknowledge the person’s words without agreeing to an outcome the business has not approved. “I understand that you are asking for a change” is different from “the change is approved.” “You said you do not want another call” is different from “the number is invalid.” These distinctions make the record more useful because they preserve the customer’s position while leaving interpretation and authority where they belong.`,
    `For review, separate at least five states: completed from approved information; customer action still pending; owner action pending; refusal or suppression; and uncertain identity or authority. The labels should be mutually understandable to the receiving owner and should not imply a result that has not happened. A sixth state can be added when the subject requires it, such as a discrepancy, accommodation request, or research refusal. The value is not the number of labels but the decision each label unlocks.`,
    `A small evidence sample can test whether the distinction survives real work. Select records from the relevant period, compare the note with the source information, and then check the owner’s final disposition where one exists. Look for omitted requests, invented reasons, mismatched dates, missing preferences, and a completed label applied before a decision was made. Review should focus on the relationship between evidence and action, not on making notes longer or rewarding a particular accent, personality, or call length.`,
    `Measurement should use denominators that match the question. If the question is record completeness, report the number of reviewed records with all required fields divided by the number of eligible records reviewed. If the question is suppression handling, report suppression requests reflected in the authoritative list divided by suppression requests captured. If the question is appointment usefulness, define the eligible handoffs and the agreed downstream outcome before interpreting a percentage. Without a defined cohort and period, a rate invites false confidence.`,
    `The service boundary is part of the control. A caller may repeat approved information, capture a request, and route an exception. The caller should stop before taking an unauthorized payment detail, changing an account, deciding eligibility, diagnosing a complaint, disclosing restricted information, or making a promise about an outcome controlled by someone else. This is not a judgment about capability. It is a separation of evidence collection from authority, which makes accountability visible when the matter is sensitive or ambiguous.`,
    `The most important risk is not always an obviously wrong sentence. It can be a missing distinction that causes the next person to assume more than the conversation established. A “confirmed” status may hide a new request. A “not interested” label may hide a request not to be contacted. A “message delivered” label may omit that the recipient was unavailable. In each case, the remedy is to preserve the person’s stated facts and route the unresolved part rather than filling the gap with optimism.`,
    `The analysis also has a human-factors dimension. People answer more reliably when the purpose is clear, the question is understandable, and refusal is allowed without pressure. The caller should avoid leading alternatives, unnecessary repetition, and language that suggests one answer is preferred. When clarification is needed, it should narrow ambiguity without teaching the person what to say. This is especially important for survey responses, accessibility requests, complaints, and any contact where a power difference may affect candor.`,
    `A useful owner handoff contains the minimum context needed to act: source reference, date of contact, stated purpose, verified facts, exact request or refusal, uncertainty, and next owner. It should not include speculative diagnoses, unrelated personal details, or copied history that the recipient does not need. The right retention period and access policy belong to the business and jurisdiction. Minimization is still a sound starting point because every unnecessary field creates another place for error or exposure.`,
    `Interpretation must remain bounded. ${s.risk} is a plausible operational failure, not a claim that every calling program produces it. Likewise, a better record does not prove that every customer will be satisfied or that every exception will be resolved quickly. It improves the information available for a responsible decision. The business should test the result against its actual population, approved purpose, contact rules, and service commitments, then revise definitions when evidence shows that a label is ambiguous.`,
    `The main conclusion is that ${s.subject} should be judged by evidence continuity: can another authorized person trace the source fact, the person’s response, the uncertainty, and the next decision without guessing? That standard is more durable than an activity total. It supports Filipino callers and owners alike because it makes the work legible while preserving human authority for exceptions. ${s.owner} should approve the field set, outcome labels, sampling period, and escalation path before the service begins.`,
    `There are meaningful limitations. ${s.limitation}. The sources also differ in purpose, geography, date, and population, so their findings should not be blended into a fabricated benchmark. A responsible reader should treat this article as a bounded synthesis for planning and review. Local law, contractual duties, customer expectations, and the organization’s own approved information may require stricter treatment. Where those requirements conflict with a convenient call outcome, the stricter authorized path should govern.`,
    sources(s),
    `FAQ: What is the simplest test? Ask whether the next authorized owner can identify what was known, what the person requested, what remains uncertain, and what action is due. What should happen when the caller cannot establish the permitted outcome? Record the uncertainty plainly, stop before making a commitment, and route the matter to the named owner. What makes a metric credible? State its cohort, period, denominator, source records, and limitations.`
  ];
}

export const aug13ResearchPosts = seeds.map((s) => ({ ...s, body: body(s) }));
