type ResearchSeed = {
  slug: string;
  title: string;
  excerpt: string;
  question: string;
  decision: string;
  scenario: string;
  measure: string;
  boundary: string;
  sources: string;
  limitation: string;
  published: '2026-08-17';
};

const seeds: readonly ResearchSeed[] = [
  { slug: 'appointment-setting-decision-role-research', title: 'Appointment-setting decision-role research', excerpt: 'How a Filipino appointment setter can distinguish influence, participation, and approval before a meeting is treated as qualified.', question: 'whether the contact can describe their part in the decision without the caller inferring final authority from a title', decision: 'who should attend or own the next conversation', scenario: 'a prospect understands the operating problem but says a partner or department head approves the next step', measure: 'the proportion of sampled appointment records that name the contact’s stated role, other required participants, the meeting purpose, and the unresolved approval question', boundary: 'do not label a contact the final decision-maker because they sound confident or hold a senior-sounding title', sources: 'U.S. Small Business Administration market-research guidance; U.S. Bureau of Labor Statistics customer-service role description; FTC telemarketing guidance', limitation: 'role descriptions and decision structures vary widely by organization, sector, and buying process', published: '2026-08-17' },
  { slug: 'outbound-calling-answer-rate-interpretation-research', title: 'Outbound calling answer-rate interpretation research', excerpt: 'Why connection counts need contact purpose, eligibility, and outcome context before they can inform an outsourced calling decision.', question: 'what an answered call actually establishes about reachability, consent, and useful progress', decision: 'whether the record needs another approved attempt, suppression, qualification, or owner review', scenario: 'a queue shows many connected calls, but the notes mix wrong parties, refusals, short conversations, and completed qualification', measure: 'answered records separated by eligible contact, wrong party, refusal, conversation outcome, and unresolved owner action rather than one connection rate', boundary: 'do not present a connected call as a lead, a permission signal, or a completed business outcome', sources: 'Federal Trade Commission telemarketing guidance; Federal Communications Commission consumer calling guidance; U.S. Bureau of Labor Statistics customer-service role description', limitation: 'answer rates depend on list quality, calling purpose, timing, caller identification, geography, and recipient behavior', published: '2026-08-17' },
  { slug: 'customer-follow-up-first-contact-resolution-research', title: 'Customer follow-up first-contact resolution research', excerpt: 'A bounded way to distinguish information answered on a follow-up call from a request that still belongs with a service owner.', question: 'whether a customer’s issue was actually resolved from approved information or merely acknowledged and routed', decision: 'whether the record can close, needs customer action, or requires an owner response', scenario: 'a customer accepts a status update but asks a second question about a refund, account change, or promised date', measure: 'sampled follow-ups coded as answered, customer-action pending, owner-action pending, no contact, refusal, or unresolved rather than a single “completed” label', boundary: 'do not call a request resolved because the customer was reached or sounded satisfied', sources: 'U.S. Bureau of Labor Statistics customer-service role description; NIST Privacy Framework; FTC data-security guidance', limitation: 'a complete note can improve continuity but cannot prove the eventual remedy, speed, or customer satisfaction', published: '2026-08-17' },
  { slug: 'inbound-call-transfer-message-choice-research', title: 'Inbound call transfer-versus-message research', excerpt: 'How to decide whether an inbound caller should be transferred or given a complete callback route while keeping sensitive decisions with the owner.', question: 'whether an immediate transfer adds value without losing context, authority checks, or a safe stopping point', decision: 'whether to transfer, take a message, schedule a callback, or escalate to a named owner', scenario: 'a caller has explained a routine request but the available recipient is not the person who controls the requested account decision', measure: 'the share of reviewed inbound contacts where transfer choice, caller purpose, identity state, callback route, and unresolved request agree with the owner’s disposition', boundary: 'do not transfer a sensitive or unresolved matter simply to reduce queue time', sources: 'NIST Privacy Framework; FTC data-security guidance; U.S. Bureau of Labor Statistics customer-service role description', limitation: 'the right route depends on staffing, identity controls, business hours, urgency rules, and the sensitivity of the request', published: '2026-08-17' },
  { slug: 'filipino-caller-accent-quality-measurement-research', title: 'Filipino caller accent and quality-measurement research', excerpt: 'Why outsourced calling quality should be judged by observable accuracy, clarity, and outcomes rather than accent or presumed identity.', question: 'which observable communication evidence shows that a Filipino caller made the interaction understandable and the handoff accurate', decision: 'whether coaching should address wording, confirmation, note accuracy, or an actual outcome defect', scenario: 'a reviewer marks a call weak because of accent or speaking style while the customer’s information was confirmed and the note was correct', measure: 'agreement between the approved question, the customer’s confirmed detail, the saved note, and the next action, with reviewer rationale tied to observable evidence', boundary: 'do not score nationality, accent, personality, or speed as a proxy for capability', sources: 'U.S. Bureau of Labor Statistics customer-service role description; NIST Privacy Framework; AAPOR survey-research best practices', limitation: 'a desk-research framework cannot define a universal pronunciation standard or replace listening tests with the actual audience', published: '2026-08-17' },
  { slug: 'order-confirmation-address-change-evidence-research', title: 'Order confirmation address-change evidence research', excerpt: 'How to separate confirmation of an approved order address from a new request that needs fulfillment and identity review.', question: 'whether the customer confirmed the released address or requested a change that the caller is not authorized to apply', decision: 'whether the order can remain confirmed or must enter a fulfillment review path', scenario: 'a customer reads back the item correctly but says delivery should go to a different address than the one on the order', measure: 'orders sampled for separate item confirmation, address source, identity state, requested change, and final authorized fulfillment disposition', boundary: 'do not edit, promise, or imply acceptance of an address change during a confirmation call unless the approved process explicitly allows it', sources: 'FTC Mail, Internet, or Telephone Order Merchandise Rule; NIST Privacy Framework; PCI Security Standards Council merchant guidance', limitation: 'verification, delivery, payment, and address-change controls vary by product, market, and fulfillment system', published: '2026-08-17' },
  { slug: 'database-verification-field-confidence-research', title: 'Database verification field-confidence research', excerpt: 'A field-level evidence model for distinguishing direct confirmation, reported correction, uncertainty, and owner-approved change.', question: 'what confidence and source state should be attached to each field before a record correction is accepted', decision: 'whether the data owner can accept the proposed correction or needs another verification step', scenario: 'a household member supplies a spelling or phone correction for a named contact whose identity has not been established', measure: 'corrections classified by field, source person, verification method, confidence state, reviewer, and final record change', boundary: 'do not treat a plausible spoken correction as authoritative merely because it sounds specific', sources: 'NIST Privacy Framework; Philippines National Privacy Commission Data Privacy Act resources; FTC data-security guidance', limitation: 'the correct evidence threshold depends on the organization’s lawful basis, data class, jurisdiction, and record authority', published: '2026-08-17' },
  { slug: 'survey-calling-mode-effect-research', title: 'Survey calling mode-effect research', excerpt: 'How telephone interviewing can preserve respondent meaning while acknowledging that mode, interviewer behavior, and nonresponse affect interpretation.', question: 'which observed response differences may reflect the telephone mode or interviewer interaction rather than the measured subject', decision: 'whether to retain, flag, weight, or investigate a response pattern with the research owner', scenario: 'respondents answer the same question differently on a live call than in a private online form', measure: 'response distributions reported with mode, refusal, don’t-know, incomplete, interviewer, and sample-frame context rather than as a single undifferentiated total', boundary: 'do not steer, explain toward a preferred answer, or claim that a telephone sample represents all customers without design evidence', sources: 'American Association for Public Opinion Research best practices; Pew Research Center survey-question guidance; U.S. Census Bureau survey resources', limitation: 'mode effects are design- and population-dependent, and this article does not estimate an effect size for any particular survey', published: '2026-08-17' },
  { slug: 'win-back-refusal-reason-suppression-research', title: 'Win-back refusal-reason and suppression research', excerpt: 'Why a former customer’s refusal and explanation should be kept separate, with the refusal governing future contact.', question: 'whether a former customer has declined future outreach and how the business should preserve that instruction', decision: 'whether to suppress the record, retain an owner-only insight, or route a policy question without another offer', scenario: 'a former customer gives valuable feedback and then clearly says not to be called again', measure: 'win-back records where refusal, reason volunteered, suppression status, source, effective time, and any owner-only analysis are independently visible', boundary: 'do not treat useful feedback as permission for another attempt or as a reason to delay suppression', sources: 'Federal Trade Commission telemarketing guidance; FCC consumer calling guidance; ICO live-direct-marketing guidance', limitation: 'suppression law and list-management duties vary by purpose, channel, jurisdiction, and the person’s specific request', published: '2026-08-17' },
  { slug: 'reception-overflow-urgency-calibration-research', title: 'Reception overflow urgency-calibration research', excerpt: 'How to preserve a caller’s stated urgency without turning tone, pressure, or vague language into an unsupported priority label.', question: 'what evidence lets a receiving owner distinguish a time-sensitive request from a caller’s general use of the word urgent', decision: 'whether the message needs routine routing, a defined callback window, or an owner-controlled escalation', scenario: 'a caller says a matter is urgent but does not provide a deadline, safety concern, business impact, or person who should receive it', measure: 'messages with stated urgency evidence, requested timing, purpose, callback route, unknowns, and receiving-owner disposition kept as separate fields', boundary: 'do not invent an emergency, deadline, or priority from tone alone', sources: 'U.S. Bureau of Labor Statistics customer-service role description; NIST Privacy Framework; FTC data-security guidance', limitation: 'urgency definitions are business-specific, and safety or emergency procedures must come from the responsible organization', published: '2026-08-17' }
];

function body(s: ResearchSeed): string[] {
  return [
    `Research question: ${s.question}. This article examines that question for outsourced Philippines-based calling services, where a Filipino caller may be responsible for a defined queue while the client retains authority over sensitive information, commitments, and exceptions. The subject is not activity volume. It is whether a conversation leaves an evidence trail that another authorized person can understand and act on.`,
    `Evidence scope and method: this is a desk-research synthesis of ${s.sources}. The sources address different things: regulatory expectations, privacy risk, occupational tasks, or research practice. I use them to frame observable controls and bounded interpretation, not to claim that they measured OutsourcedCallers.com, Filipino callers, or any particular client. The method is to map each source’s relevant principle to the record states a calling service can actually observe, then test those states against the scenario in this article.`,
    `The central distinction is between a spoken event and a business decision. A person may answer, explain, refuse, correct, ask, or agree to a next contact. None of those words automatically authorizes a change, proves identity, establishes eligibility, or creates a completed outcome. The record should retain the narrowest statement supported by the conversation and identify the owner who controls the next material decision.`,
    `For this topic, the operating question becomes ${s.question}. That wording gives the caller a finite purpose and makes room for an honest incomplete result. Before release, the client should define the source record, approved fields, permissible wording, stop conditions, and owner route. A caller who has no safe label for an answer will be pushed toward a guess, even when the script itself sounds polished.`,
    `The specific scenario is ${s.scenario}. A weak process converts that situation into an optimistic label because the record needs to move. A stronger process records what was directly established, what was requested, what was refused, and what remains unknown. Where a repeat-back is useful, it should confirm the person’s meaning rather than lead them toward the response the business prefers.`,
    `A useful record separates source, observation, interpretation, and action. Source identifies the released list or originating request. Observation captures the person’s words or the approved field they confirmed. Interpretation states only a justified classification, such as refusal or owner review. Action names the next owner and the condition that must be met. Collapsing these layers makes later review impossible because the reviewer cannot tell whether a conclusion came from the person or from the caller.`,
    `The decision boundary matters because a calling service is often close to consequential information without owning the consequence. The caller can ask the approved question, explain approved information, preserve contact preferences, and create a clean handoff. The caller should stop at ${s.boundary}. The client must define stronger controls for payment, account access, remedies, eligibility, legal questions, complaints, emergencies, and any other matter that requires a licensed or accountable decision-maker.`,
    `A topic-specific measurement is more informative than a generic connected-call total. For this article, use ${s.measure}. Define the cohort, period, inclusion rules, source of truth, and final disposition before counting. A useful denominator should not quietly remove refusals, wrong parties, unresolved questions, or owner reviews. Those records are often where the service boundary is tested, so excluding them would reward concealment rather than reliability.`,
    `The review design should combine a source-record check with an outcome check. Select a stated sample from a stated period. Compare the original queue or request with the call note, then compare the note with the owner’s eventual decision where one exists. Mark omissions, invented certainty, altered wording, missing timing, duplicate work, and incorrect routing. The goal is to find a repeatable failure mode that the client can correct in the brief, field set, training, or owner map.`,
    `The human interaction is part of the evidence quality. A concise purpose statement helps a person understand why the call is happening. A pause allows a complete answer. A neutral clarification reduces ambiguity without supplying a preferred answer. A respectful refusal path prevents pressure from becoming a false positive. These practices support cleaner records, but they do not guarantee cooperation, satisfaction, attendance, payment, delivery, or any other downstream result.`,
    `For a Philippines-based staffing decision, the relevant capability is not a stereotype about nationality or a promise about accent. It is the ability to follow the released purpose, listen for the approved fact, record uncertainty accurately, and escalate when the authority boundary is reached. Quality review should score observable work: factual agreement, respectful wording, correct outcome, complete handoff, and appropriate stop. It should not substitute accent, personality, or speed for evidence.`,
    `A handoff should be short enough to use and complete enough to prevent repetition. Include the source reference, contact date, approved purpose, relevant response, exact request or refusal, unresolved point, permitted next action, accountable owner, and any required reply window. Do not copy unrelated history or add sensitive details the recipient does not need. The client remains responsible for retention, access, suppression, and jurisdiction-specific requirements.`,
    `The most plausible operational failure here is ${s.decision} being inferred before the evidence supports it. That is a risk hypothesis, not a claim that every program fails this way. The practical test is whether two trained reviewers would reach the same classification from the same note and whether the named owner can act without asking the person to repeat the entire conversation. If they cannot, the field design or authority boundary needs revision.`,
    `Conclusion: judge this calling lane by evidence continuity. The conversation should let an authorized owner trace what was released, what the person actually said, what the caller was allowed to do, what remains open, and who owns the next step. For this topic, the useful decision is ${s.decision}; it should follow the recorded evidence rather than the pressure to make a queue look complete. The client should approve the definitions and test them against its real population before relying on a dashboard or service report.`,
    `Limitations: ${s.limitation}. The cited sources also cannot be blended into a fabricated industry benchmark. A regulation, privacy framework, occupational description, and survey standard each answer a different question. This synthesis is a planning and review aid, not legal advice, a performance guarantee, or a substitute for the client’s approved policy. When a local rule or client control is stricter, that authorized requirement governs.`,
    `Sources: ${s.sources}. Primary references: https://www.ftc.gov/business-guidance/advertising-marketing/telemarketing; https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts; https://www.nist.gov/privacy-framework; https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm; https://aapor.org/standards-and-ethics/best-practices/. These sources describe their own rules, frameworks, methods, or populations and are not performance claims about OutsourcedCallers.com.`,
    `FAQ: What is the simplest review test? Ask whether the next authorized owner can distinguish the person’s statement from the caller’s inference. What if the answer falls outside the brief? Preserve it neutrally, stop before making a commitment, and route it. What makes the metric credible? State its cohort, period, denominator, source records, final disposition, and limitations.`
  ];
}

export const aug17ResearchPosts = seeds.map((s) => ({ ...s, body: body(s) }));
