type ResearchSeed = {
  slug: string;
  title: string;
  excerpt: string;
  published: '2026-08-14';
  question: string;
  audience: string;
  evidence: string;
  metric: string;
  case: string;
  risk: string;
  owner: string;
  limitation: string;
};

const seeds: ResearchSeed[] = [
  { slug: 'appointment-setting-agenda-evidence-research', title: 'Appointment setting agenda-evidence research', excerpt: 'How to preserve the prospect’s stated purpose and meeting question so a booked conversation has usable context.', published: '2026-08-14', question: 'whether the proposed meeting has a specific purpose that the recipient can act on', audience: 'a prospect deciding whether a conversation is worth keeping and an owner preparing for it', evidence: 'SBA market-research guidance, BLS customer-service guidance, and FTC telemarketing guidance', metric: 'the share of reviewed appointments whose purpose, stated need, participants, timing, and open question agree with the call record', case: 'a broad request to “learn more” with no named question or participant', risk: 'a calendar event being counted as success even though the recipient cannot prepare for it', owner: 'the meeting owner who defines what information makes an appointment useful', limitation: 'a clear agenda does not establish commercial fit, attendance, or a successful outcome' },
  { slug: 'outbound-calling-contact-purpose-research', title: 'Outbound calling contact-purpose research', excerpt: 'A bounded method for checking that an outbound call has an approved reason, a clear stop condition, and an honest result.', published: '2026-08-14', question: 'whether the contact purpose and permission context are clear before an outbound conversation begins', audience: 'the person receiving a call and the business responsible for its contact rules', evidence: 'FCC consumer guidance, FTC telemarketing guidance, and ICO live-call guidance', metric: 'eligible records with a documented purpose and applicable contact-preference check before disposition', case: 'a valid phone number with no reliable indication of the permitted purpose', risk: 'treating reachability as permission or recasting a refusal as a sales objection', owner: 'the business owner responsible for audience, purpose, and suppression rules', limitation: 'contact requirements vary with purpose, technology, jurisdiction, and recipient' },
  { slug: 'customer-follow-up-question-ownership-research', title: 'Customer follow-up question-ownership research', excerpt: 'How to capture a customer’s unresolved question without promising an answer that belongs to another owner.', published: '2026-08-14', question: 'whether a follow-up record makes the customer’s unresolved question and accountable answer owner visible', audience: 'a customer waiting for a useful answer and the service owner responsible for resolving it', evidence: 'BLS customer-service guidance, NIST Privacy Framework, and FTC data-security guidance', metric: 'reviewed follow-ups that preserve the exact question, approved context, uncertainty, and next owner', case: 'a customer accepting an update while asking for a detail the caller cannot verify', risk: 'a warm but vague note creating a false impression that the issue is resolved', owner: 'the service owner who can provide or authorize the answer', limitation: 'a complete handoff cannot guarantee the speed or quality of the eventual resolution' },
  { slug: 'inbound-call-identity-context-research', title: 'Inbound call identity-context research', excerpt: 'What an inbound caller can record when identity or authority is uncertain, without guessing or exposing unnecessary information.', published: '2026-08-14', question: 'whether an inbound call can be routed using sufficient context without treating an unverified identity as established', audience: 'a caller seeking help and the owner who controls access to the requested information', evidence: 'NIST Privacy Framework, FTC data-security guidance, and BLS customer-service guidance', metric: 'inbound records separating stated purpose, verified context, identity uncertainty, and owner review', case: 'a caller who knows an account detail but cannot establish the authority required for a change', risk: 'a confident handoff disclosing information or initiating an unauthorized action', owner: 'the data or service owner who defines the approved verification path', limitation: 'a phone conversation is not universal proof of identity or authority' },
  { slug: 'database-verification-field-provenance-research', title: 'Database verification field-provenance research', excerpt: 'How to distinguish a directly confirmed field from a reported correction, an assumption, and an owner-approved change.', published: '2026-08-14', question: 'whether each proposed record correction has a visible source and an appropriate review path', audience: 'a customer whose record may be wrong and the data owner maintaining the authoritative record', evidence: 'NIST Privacy Framework, Philippines NPC Data Privacy Act resources, and FTC data-security guidance', metric: 'sampled corrections classified by source, identity confidence, field affected, and final approval state', case: 'a household member reporting a change for a named record holder', risk: 'turning an unverified report into a durable merge, disclosure, or correction', owner: 'the data owner who approves changes to the authoritative record', limitation: 'the approved evidence and retention rules depend on the organization and jurisdiction' },
  { slug: 'event-registration-attendance-intent-research', title: 'Event registration attendance-intent research', excerpt: 'How reminder calls can separate confirmed attendance, uncertainty, refusal, and accommodation questions.', published: '2026-08-14', question: 'whether a registration record reflects what the attendee actually said rather than an optimistic completion label', audience: 'an attendee deciding whether to participate and the event owner managing capacity and access', evidence: 'ADA.gov effective-communication guidance, SBA market-research guidance, and W3C accessibility principles', metric: 'registrations with separate attendance, contact, question, accessibility, and owner-review outcomes', case: 'an attendee who is interested but cannot confirm until an access question is answered', risk: 'overstating attendance or hiding an accommodation request inside a yes/no field', owner: 'the event owner responsible for capacity, policy, and accommodation decisions', limitation: 'attendance intent can change and cannot be inferred from a completed reminder' },
  { slug: 'survey-calling-response-clarity-research', title: 'Survey calling response-clarity research', excerpt: 'A research view of neutral clarification that protects respondent meaning without leading the answer.', published: '2026-08-14', question: 'whether a clarification makes the approved question understandable without supplying a preferred response', audience: 'a respondent whose answer should remain their own and the research owner interpreting it', evidence: 'AAPOR best practices, Pew Research Center survey-method guidance, and U.S. Census Bureau resources', metric: 'interviews where the approved wording, clarification type, response, refusal, and incomplete state are separately coded', case: 'a respondent asking what one survey term means before answering', risk: 'an interviewer changing the response distribution through explanation, correction, or approval signals', owner: 'the research owner who defines instruments, probes, coding, and sampling', limitation: 'neutral interviewing cannot remove coverage, nonresponse, mode, or social-desirability error' },
  { slug: 'reception-overflow-callback-route-research', title: 'Reception overflow callback-route research', excerpt: 'How to make an overflow message actionable by preserving the caller’s purpose, route, stated urgency, and open question.', published: '2026-08-14', question: 'whether a receiving owner can act without replaying the original call or guessing its priority', audience: 'a caller trying to reach the right person and the owner deciding the next response', evidence: 'BLS customer-service guidance, NIST Privacy Framework, and FTC data-security guidance', metric: 'messages containing an approved callback route, stated purpose, urgency as stated, and unresolved point', case: 'a caller saying the matter is time-sensitive without describing an emergency', risk: 'a vague or embellished message delaying action or exposing information to the wrong recipient', owner: 'the receiving owner who determines priority and response', limitation: 'urgency cannot be inferred from tone alone and field requirements differ by business' },
  { slug: 'renewal-reminder-choice-evidence-research', title: 'Renewal reminder choice-evidence research', excerpt: 'How to record a customer’s renewal choice or question while keeping terms, payment, and cancellation decisions with the owner.', published: '2026-08-14', question: 'whether a reminder record preserves customer choice without implying a renewal decision that has not occurred', audience: 'a customer deciding whether to continue and the account owner responsible for the account', evidence: 'FTC Telemarketing Sales Rule guidance, ICO live-call guidance, and FTC consumer information', metric: 'reminders separating receipt, stated choice, contact preference, objection, question, and owner review', case: 'a customer who wants to understand a renewal detail before deciding', risk: 'a “renewed” label or pressure language changing the apparent account history', owner: 'the account owner responsible for terms, cancellation, payment, and disputes', limitation: 'notice periods, consent, rights, and contact restrictions vary across products and jurisdictions' },
  { slug: 'order-confirmation-item-exception-research', title: 'Order confirmation item-exception research', excerpt: 'How item-level confirmation can surface a discrepancy without turning the caller into the fulfillment decision-maker.', published: '2026-08-14', question: 'whether each approved order item is confirmed separately from any new request or discrepancy', audience: 'a customer checking an order and the fulfillment owner responsible for exceptions', evidence: 'FTC Mail, Internet, or Telephone Order Merchandise Rule, PCI Security Standards Council guidance, and NIST Privacy Framework', metric: 'orders where item facts, customer requests, and fulfillment-review outcomes are separately recorded', case: 'a spoken quantity that differs from the approved order record', risk: 'a broad “confirmed” result hiding a changed quantity, unavailable item, or return request', owner: 'the fulfillment owner who controls changes, delivery promises, and remedies', limitation: 'safe fields and verification methods depend on the product, payment environment, and market' }
];

function body(s: ResearchSeed): string[] {
  return [
    `This research examines ${s.question} in the context of outsourced calling services. The subject is narrower than activity volume. A call is useful when its record preserves the approved purpose, the person’s stated response, the boundary of what was verified, and the next accountable decision. ${s.audience} needs that continuity because a connected call can still leave the important question unresolved.`,
    `The first finding is that the call objective should be written as a testable question before contact. For this topic, the question is ${s.question}. That wording prevents a broad status such as “complete,” “interested,” or “urgent” from becoming a substitute for evidence. It also gives the caller a fair stopping point: once the approved question is answered, refused, or shown to require review, the conversation does not need to expand by improvisation.`,
    `The evidence base combines ${s.evidence}. These sources have different purposes, populations, dates, and legal or methodological scopes. They do not establish a performance benchmark for OutsourcedCallers.com and do not prove that one script will work for every organization. Their bounded contribution is to support clear purpose, truthful representation, data minimization, respectful communication, and accountable handling of consequential exceptions.`,
    `A useful observation model has four layers. First, identify the released source record and the approved reason for contact. Second, capture what the person directly says or confirms. Third, mark what is unknown, refused, newly requested, or outside the caller’s authority. Fourth, route the unresolved part to the named owner. The record should make those layers distinguishable instead of blending them into a single positive or negative outcome.`,
    `The practical case is ${s.case}. A weak process would fill the gap with a likely interpretation. A stronger process asks only the permitted clarifying question, repeats the answer when accuracy matters, and labels the remaining uncertainty. This preserves the person’s position without making a promise. It also gives the owner a better basis for deciding whether the matter can proceed, needs more information, or should stop.`,
    `Language matters because a caller’s paraphrase can quietly change the result. “You said you want to ask about the timing” is evidence of a question. “You are ready to proceed” is an interpretation. “You confirmed the approved item” is different from “you asked us to change the item.” The record should prefer the narrower statement when the broader conclusion has not been authorized or established.`,
    `For review, separate at least these states: completed from approved information; customer or respondent action pending; owner action pending; refusal or suppression; and identity, authority, or source uncertainty. Add a topic-specific state when necessary, such as an accommodation request, item discrepancy, attendance uncertainty, or survey refusal. The value is not a large taxonomy. The value is that each label points to a different next action and does not imply more than the conversation established.`,
    `Measurement should use an explicit cohort and period. For this topic, ${s.metric}. A reviewer should define eligible records, the required fields, the source of truth, and the final disposition before calculating a rate. Counts of attempted calls or connected calls cannot answer a record-quality question by themselves. A denominator that silently excludes refusals, exceptions, or uncertain records will make the result look better while reducing its usefulness.`,
    `A small sample can test whether evidence survives the handoff. Select records from a stated period, compare the note with the source record, and check the owner’s eventual disposition where one exists. Look for omitted requests, guessed reasons, altered names or quantities, missing preferences, and a completion label applied before a decision. Sampling should reveal failure patterns, not become a contest about call length, accent, or personality.`,
    `The service boundary is part of the finding. A caller can explain approved information, ask the released question, capture a response, and route an exception. The caller should stop before taking payment details, changing an account, deciding eligibility, diagnosing a complaint, disclosing restricted information, making an accommodation promise, or committing the business to an outcome controlled by another owner. Keeping evidence collection separate from authority makes escalation legible and safer.`,
    `The human-factors implication is equally important. People give clearer information when the purpose is understandable, the question is proportionate, and refusal does not trigger pressure. A caller can use plain language, allow a pause, and confirm a detail without suggesting the preferred answer. When clarification is necessary, it should narrow ambiguity rather than teach the person what to say. This protects both the quality of the record and the dignity of the person contacted.`,
    `A self-contained handoff contains the minimum context needed to act: source reference, date of contact, approved purpose, relevant response, exact request or refusal, uncertainty, and next owner. It should not include speculative diagnoses, unrelated personal details, or copied history that the recipient does not need. The business must set retention, access, and jurisdiction-specific rules. Minimization remains a sound starting point because every unnecessary field creates another opportunity for error or exposure.`,
    `Interpretation must remain bounded. ${s.risk} is a plausible failure mode, not a claim that every calling program produces it. A clearer note does not guarantee a satisfied customer, a held meeting, a valid survey, or a fulfillment result. It improves the information available for the responsible decision. The owner should test the definitions against the actual population, purpose, contact rules, and service commitments, then revise any label that repeatedly causes different reviewers to infer different outcomes.`,
    `The central conclusion is that this topic should be judged by evidence continuity. Can an authorized person trace the source, the person’s response, the unresolved point, and the next decision without guessing? If not, the process has produced activity but not a dependable handoff. ${s.owner} should approve the field set, outcome labels, sample period, access rules, and escalation route before the service begins.`,
    `There are important limitations. ${s.limitation}. The cited sources also should not be blended into a fabricated industry average: a regulatory rule, a privacy framework, a survey-method principle, and a labor description answer different questions. This article is a bounded desk-research synthesis for planning and review, not legal advice, a guarantee, or a substitute for the organization’s approved policy. Where local requirements are stricter, the stricter authorized path should govern.`,
    `Sources: ${s.evidence}. Primary references include https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm, https://www.nist.gov/privacy-framework, https://www.ftc.gov/business-guidance/advertising-marketing/telemarketing, and https://www.sba.gov/business-guide/plan-your-business/market-research-competitive-analysis. These references describe their own rules, frameworks, or populations and are not performance claims about OutsourcedCallers.com.`,
    `FAQ: What is the simplest review test? Ask whether the next authorized owner can identify what was known, what the person said, what remains uncertain, and what action is due. What if the caller cannot establish the permitted outcome? Record the uncertainty plainly, stop before making a commitment, and route it. What makes a metric credible? State its cohort, period, denominator, source records, and limitations.`
  ];
}

export const aug14ResearchPosts = seeds.map((s) => ({ ...s, body: body(s) }));
