type Seed = readonly [slug: string, title: string, excerpt: string, question: string, decision: string, scenario: string, boundary: string, owner: string];
type Section = { heading: string; paragraphs: string[] };

const seeds: readonly Seed[] = [
  ['filipino-caller-daily-capacity-board', 'Filipino caller daily capacity board', 'How to set a useful daily capacity board for Filipino callers without confusing activity targets with safe, complete calling work.', 'What work can be completed today without weakening accuracy or the handoff?', 'whether the queue needs more records, a different lane, or owner review', 'a caller finishes the released list early but several records need exception handling', 'do not add unreviewed records simply to fill an activity target', 'the operations owner'],
  ['appointment-setting-meeting-purpose-confirmation', 'Appointment setting meeting-purpose confirmation', 'A focused way to confirm why a prospect wants a meeting before a Filipino caller sends a request to the calendar owner.', 'What should the meeting accomplish for the prospect and the receiving owner?', 'whether the request has a clear purpose or needs clarification', 'a prospect asks for a meeting but describes three unrelated topics', 'do not promise an outcome or convert a broad interest statement into a qualified meeting', 'the appointment owner'],
  ['lead-qualification-timing-signal', 'Lead qualification timing signal', 'How Filipino qualification callers can record timing evidence without manufacturing urgency from a prospect’s general interest.', 'What event, deadline, or planning window did the contact actually state?', 'whether timing is known, open, or requires an owner question', 'a contact says the problem matters but cannot name a decision window', 'do not label a lead urgent because the conversation sounded enthusiastic', 'the lead owner'],
  ['inbound-call-safe-callback-number', 'Inbound call safe callback number', 'A practical check for capturing a callback number on inbound calls while keeping identity and account disclosure within the approved boundary.', 'Which number can the receiving owner use safely, and who supplied it?', 'whether to record, verify, or route the callback detail', 'a caller gives a number different from the one on the account record', 'do not read back private record details to prove that the number matches', 'the account owner'],
  ['customer-follow-up-open-loop-register', 'Customer follow-up open-loop register', 'How to keep unfinished customer follow-ups visible by separating promised action, owner, due point, and customer expectation.', 'What remains open, who owns it, and what should the customer hear next?', 'whether the follow-up is ready, waiting, or needs escalation', 'a note says “check back soon” but names neither a task nor a responsible owner', 'do not close an open customer matter because a message was sent', 'the customer-service owner'],
  ['outbound-calling-attempt-limit-review', 'Outbound calling attempt-limit review', 'A controlled method for reviewing outbound attempts so Filipino callers do not keep retrying records that need suppression or a new instruction.', 'What does the approved attempt history allow next?', 'whether to retry, pause, suppress, or route the record', 'a contact has several unanswered attempts and one prior request for a different time', 'do not extend an attempt sequence by personal judgment', 'the list owner'],
  ['filipino-caller-script-version-check', 'Filipino caller script version check', 'A simple pre-call control for ensuring Filipino callers use the released script and can identify wording that needs review.', 'Which approved version applies to this queue and call purpose?', 'whether the record is ready to call or must be held for a script decision', 'a caller sees a familiar script but the queue references a newer campaign brief', 'do not blend old and new wording into an improvised promise', 'the campaign owner'],
  ['appointment-setting-attendee-role-capture', 'Appointment setting attendee-role capture', 'How to record who should attend a proposed meeting so the calendar owner can judge preparation without guessing from job titles.', 'Which people need to be present for the stated meeting purpose?', 'whether the request has enough participant context for review', 'a prospect wants an evaluation but cannot say who owns implementation', 'do not infer authority or add attendees without the owner’s approval', 'the meeting owner'],
  ['customer-follow-up-callback-window-record', 'Customer follow-up callback-window record', 'A precise way to capture a customer’s preferred callback window without turning availability into a guaranteed appointment.', 'What local window did the customer request, and what remains subject to confirmation?', 'whether the request is clear enough to route or needs a scheduling owner', 'a customer offers a broad afternoon window while the responsible team has limited hours', 'do not promise a callback time outside the released schedule', 'the customer owner'],
  ['order-confirmation-address-change-request', 'Order confirmation address-change request', 'How to separate order read-back from an address-change request when a Filipino confirmation caller receives a new fulfillment instruction.', 'Is the customer confirming the saved address or requesting a controlled change?', 'whether the result is confirmation, change review, or a failed identity check', 'a customer confirms the order and then asks to send it somewhere else', 'do not treat a spoken address change as an approved fulfillment update', 'the fulfillment owner'],
  ['database-verification-duplicate-email-check', 'Database verification duplicate-email check', 'A field-level workflow for spotting a possible duplicate email during database verification without merging records by assumption.', 'What evidence shows duplication, and which record owner can decide the remedy?', 'whether to retain, investigate, or route the duplicate signal', 'two records share an email while names and contact histories differ', 'do not merge, overwrite, or delete records from a spoken similarity alone', 'the data owner'],
  ['renewal-reminder-preference-change-capture', 'Renewal reminder preference-change capture', 'How to record a customer’s preferred reminder method while keeping account eligibility and renewal terms with the authorized owner.', 'What reminder preference did the customer request and when should it apply?', 'whether the request is a preference note or an approved account change', 'a customer wants fewer calls but still needs a renewal reminder', 'do not imply that a preference request changes contract terms or eligibility', 'the account owner'],
  ['win-back-feedback-vs-permission', 'Win-back feedback versus permission', 'A boundary guide for capturing useful former-customer feedback without treating a detailed explanation as permission for another sales attempt.', 'Did the person permit future contact, or only explain why they declined?', 'whether to suppress, close, or route feedback separately', 'a former customer gives a thoughtful reason for leaving and then says not to call again', 'do not use helpful feedback to reopen a refused conversation', 'the suppression owner'],
  ['survey-calling-clarification-limit', 'Survey calling clarification limit', 'How survey callers can explain an approved term once while keeping the respondent’s answer separate from the caller’s interpretation.', 'What clarification is allowed before the response must remain as given?', 'whether to clarify, record uncertainty, or stop the question', 'a respondent asks what a study term means and then gives an answer outside the options', 'do not teach the respondent which answer would be preferable', 'the survey owner'],
  ['reception-overflow-message-deadline', 'Reception overflow message deadline', 'A message standard for capturing a real deadline on reception overflow calls without escalating every caller who uses urgent language.', 'What response time did the caller state, and what consequence did they describe?', 'whether the message needs priority handling or routine routing', 'a caller says “today” but cannot say whether the request has a fixed deadline', 'do not invent a deadline or priority from tone alone', 'the receiving manager'],
  ['outbound-calling-opt-out-source-note', 'Outbound calling opt-out source note', 'How to preserve the exact source and scope of an opt-out so the next outbound list does not misunderstand the contact’s instruction.', 'Who asked to stop, what channel or number was covered, and what action is required?', 'whether to suppress immediately or route an ambiguous request', 'a household member asks that calls stop but the record contains several numbers', 'do not narrow a clear stop request because the scope feels inconvenient', 'the compliance owner'],
  ['filipino-caller-record-lock-escalation', 'Filipino caller record-lock escalation', 'A safe response when a calling record is locked, stale, or already being handled by another owner.', 'Can the caller proceed with the released information, or must the record wait?', 'whether to pause, leave a note, or route an ownership conflict', 'two callers receive the same callback task and one record shows a pending update', 'do not work around a lock or overwrite another owner’s active note', 'the operations owner'],
  ['appointment-setting-reschedule-reason-note', 'Appointment setting reschedule-reason note', 'How to record a reschedule request so the calendar owner sees the reason, preferred window, and unresolved constraints.', 'What changed, what new window was requested, and what still needs confirmation?', 'whether to offer the released options or route a scheduling exception', 'a prospect cannot attend the held time and asks for a different week', 'do not promise a new slot before the calendar owner confirms availability', 'the calendar owner'],
  ['inbound-call-language-preference-route', 'Inbound call language-preference route', 'A respectful way to record a caller’s language preference while preserving the service boundary and a clear next owner.', 'What communication support did the caller request, and which route can provide it?', 'whether to continue with approved wording or transfer for language support', 'a caller can explain the purpose but asks for a conversation in another language', 'do not judge competence or disclose account information while improvising translation', 'the service owner'],
  ['call-quality-silence-interpretation-check', 'Call quality silence interpretation check', 'A fair review method for distinguishing a meaningful pause from a missed response in Filipino calling quality checks.', 'What observable evidence shows that the caller or customer needed another prompt?', 'whether coaching should address a missed check, a recording gap, or no defect', 'a short silence is scored as poor handling even though the caller completed the approved close', 'do not score silence, accent, or style as failure without a process effect', 'the quality owner'],
  ['daily-calling-end-of-day-reconciliation', 'Daily calling end-of-day reconciliation', 'A practical close routine that reconciles released records, attempts, outcomes, open actions, and exceptions before the calling day is reported.', 'Does each released record have a truthful result and a visible next state?', 'whether the day is complete, partially blocked, or needs owner action', 'the activity count is high but several calls have no disposition or owner', 'do not report volume as completion when the record state is unknown', 'the operations owner'],
  ['outsourced-calling-approval-boundary-map', 'Outsourced calling approval boundary map', 'How to map routine caller actions to owner approvals so outsourced calling work stays useful without transferring business decisions to the caller.', 'Which action is routine, which needs review, and which must stop?', 'whether the brief gives the caller a safe next step for each common exception', 'a customer asks for a commercial concession during an otherwise routine follow-up call', 'do not let a caller make a pricing, eligibility, contract, or policy decision', 'the business owner'],
];

const sections: readonly Section[][] = [
  [
    { heading: 'Measure a day by useful states', paragraphs: ['A capacity board should show more than calls attempted. For a Filipino caller, the meaningful unit is a released record moved to a truthful state: reached and completed, callback requested, refused, unreachable within the approved sequence, or waiting for an owner. The board gives the operations owner a way to see whether the queue supports accurate work.', 'Set the board before the day begins. Count the records that are actually ready, the fields required for each lane, and the exceptions that cannot be handled by the caller. If a list is small because it is carefully scoped, that is operational information rather than a reason to manufacture more activity.'] },
    { heading: 'Protect completion quality', paragraphs: ['A caller who reaches the end of a list may have created useful capacity by closing clean outcomes and identifying blocked records. Review the disposition mix and the open handoffs before releasing another batch. The next list should respond to evidence from the first one, not to a target chosen without regard to the work.', 'A simple board can separate ready records, active work, owner review, and closed outcomes. It can also show why a record stopped. That distinction helps a manager decide whether to improve the source list, clarify the script, or change the release size.'] },
    { heading: 'Use the shortfall as a decision', paragraphs: ['If capacity is unused, ask whether the constraint was list quality, contact availability, missing information, or a deliberate stop. Each reason has a different remedy. More records will not solve a queue that lacks permission, a usable phone number, or an accountable owner.', 'If capacity is exceeded, pause before extending the day. Unfinished notes and rushed handoffs can create more work than the extra calls remove. Let the board show what must be carried forward and who decides the next release.'] },
    { heading: 'Review the board consistently', paragraphs: ['At close, compare the released count with the result count and open-action count. Investigate records that have activity but no state, and records marked complete without the required evidence. The review should improve tomorrow’s queue, not punish a caller for refusing an unsafe action.', 'A useful capacity practice leaves the owner with an answer to three questions: what was ready, what changed, and what is still waiting. That is a better basis for routine calling management than a raw total.'] },
  ],
  [
    { heading: 'Name the meeting job', paragraphs: ['A meeting request is easier to review when it states the job the conversation is meant to do. The Filipino caller can ask what prompted the request, what the prospect hopes to understand, and who should leave with a next decision. These questions create context without turning the call into an improvised sales interview.', 'The answer may be exploratory, technical, operational, or related to a specific process. Preserve the prospect’s language and avoid upgrading it into a promise. A purpose can be clear even when fit, timing, or commercial details remain open.'] },
    { heading: 'Separate topic from outcome', paragraphs: ['A prospect may list several topics because the underlying problem is still being framed. Ask which topic should anchor the meeting and record the other items as context. This gives the calendar owner a chance to prepare the right people and decide whether the proposed slot is appropriate.', 'Do not tell the prospect that the meeting will solve the issue, approve a request, or produce a particular result. The caller can explain the handoff and confirm what information will be passed along. The owner decides the meeting’s scope and outcome.'] },
    { heading: 'Make the request reviewable', paragraphs: ['A useful request includes the stated purpose, the desired conversation, relevant participants, preferred timing, and one unresolved question. It should be short enough for a calendar owner to scan and specific enough to prevent a repeat discovery call.', 'When the purpose remains broad after one neutral clarification, label it open. A request can be sent for review without being described as qualified. Honest uncertainty helps the receiving owner prepare a better response.'] },
    { heading: 'Check for drift', paragraphs: ['Review a sample of meeting requests beside the source call notes. Look for outcomes that were added after the call, titles treated as authority, and broad topics presented as settled business needs.', 'The quality measure is not the number of meetings placed. It is whether the meeting owner receives a faithful, bounded reason for the conversation and can make the next decision with the available context.'] },
  ],
  [
    { heading: 'Ask for an observable window', paragraphs: ['Timing is useful when it comes from something the contact actually said: a planning cycle, internal review, renewal point, launch event, staffing need, or desired start period. A Filipino caller can ask a neutral follow-up and record the answer without pressing the contact to invent a deadline.', 'If the contact says the issue matters but cannot name a window, preserve that as an open timing signal. It still helps the lead owner, because the owner knows which question belongs in the next conversation.'] },
    { heading: 'Keep urgency out of tone', paragraphs: ['An energetic conversation can be encouraging, but it does not establish priority. Conversely, a cautious contact may have a firm internal date. Use stated events and requested timing rather than confidence, speed, or enthusiasm as the evidence.', 'The note should distinguish “wants to explore,” “review planned in September,” and “needs a response before a stated date.” These descriptions allow the owner to choose a route without inheriting an unsupported urgency label.'] },
    { heading: 'Route missing timing', paragraphs: ['When the queue requires a timing field and the contact cannot provide it, send the record to the defined review state. The caller can capture the question asked and the answer received, then stop at the released boundary.', 'The lead owner may decide to proceed with an exploratory meeting, request a second participant, or leave the record open. That decision belongs to the owner because it depends on the business’s qualification rules.'] },
    { heading: 'Audit timing labels', paragraphs: ['Compare timing labels with the actual notes. Look for “hot,” “urgent,” or “soon” where no date, event, or planning window was recorded. Replace interpretation with a traceable statement.', 'A disciplined timing signal makes a lead queue more useful and a handoff more honest. It also gives the caller permission to say that a fact is not yet known.'] },
  ],
  [
    { heading: 'Treat the callback number as a separate fact', paragraphs: ['When an inbound caller offers a callback number, record it as information supplied during the call, not as proof that the account record is correct. Note who supplied it, whether it is for the caller or another person, and what the receiving owner needs to confirm.', 'Read back only the number the caller just gave when the approved script permits it. Do not reveal the saved number to make the caller agree with the record. Identity and callback routing are related, but they are not the same check.'] },
    { heading: 'Clarify purpose and scope', paragraphs: ['Ask whether the number is for this request, future contact, or a specific person. A household or office number may be reachable but inappropriate for sensitive information. The note should preserve the requested scope for the receiving owner.', 'If the caller cannot provide a safe callback route, use the approved message or transfer path. Do not pressure the caller to disclose extra details merely to make the record look complete.'] },
    { heading: 'Route mismatches carefully', paragraphs: ['A difference between the spoken number and the saved number may reflect a new preference, a stale record, a shared line, or an identity concern. Label the mismatch and route it; do not select a winner by guess.', 'The account owner decides whether the new number can be stored, whether a verification step is required, and whether the requested contact channel is allowed. The caller’s job is to preserve the distinction.'] },
    { heading: 'Review callback safety', paragraphs: ['Sample notes for source, scope, read-back, and owner action. Check that the next person can see which number may be used and which saved details must not be disclosed.', 'A good inbound close is not the one that captures the most data. It is the one that gives the owner a safe route to respond without creating a new identity or privacy mistake.'] },
  ],
  [
    { heading: 'Define the open loop', paragraphs: ['A follow-up remains open when the customer is waiting for an answer, action, correction, or owner decision. Register the specific open item instead of relying on a general note that someone will respond. The next person should know what the customer expects and why the item is still unresolved.', 'Separate the customer’s requested result from the internal task. A customer may want confirmation, while the owner must check a record or approve an exception first. Both belong in the register, but they should not be merged into one vague status.'] },
    { heading: 'Name the owner and due point', paragraphs: ['Every open loop needs a responsible owner and a review point. “Soon” is not a due point unless the released workflow defines it. Capture the date or trigger the customer and owner actually discussed.', 'A Filipino caller can update a customer that the request was recorded and route the open item. The caller should not close the loop merely because an internal message was sent or because no immediate answer is available.'] },
    { heading: 'Keep waiting visible', paragraphs: ['Waiting is a legitimate state when the next action depends on another person, system, or approved answer. Record the dependency and the reply path so it does not disappear in a completed-call count.', 'If the customer adds a second issue, create a separate open item when the workflow requires it. This keeps one owner from appearing responsible for several unrelated questions without the information needed to act.'] },
    { heading: 'Reconcile the register', paragraphs: ['Review open loops against outbound follow-up, owner notes, and customer responses. Close only when the requested action is complete or the owner has documented the approved disposition.', 'The register succeeds when an unfinished matter remains findable, assigned, and accurately described. It should reduce repeat explanations for the customer, not hide the work still waiting.'] },
  ],
  [
    { heading: 'Start with the released attempt rule', paragraphs: ['An attempt limit is part of the calling brief, not a suggestion to extend when the queue is quiet. Before another outbound call, check the record’s history, prior time preference, refusal language, and any owner note that changes the route.', 'A Filipino caller can apply the released sequence and record its result. The list owner decides whether an exception is permitted, whether the record should be suppressed, or whether new contact information needs review.'] },
    { heading: 'Distinguish no answer from instruction', paragraphs: ['No answer, voicemail, wrong party, requested callback, and opt-out are different outcomes. They create different future actions. A record with repeated no answers is not equivalent to one where the contact asked for a specific later window.', 'Use the approved disposition that describes what happened. Do not add another attempt simply because a record has not produced a conversation. The absence of contact is evidence about reachability, not permission to call indefinitely.'] },
    { heading: 'Pause for conflicting signals', paragraphs: ['If a prior note requests a different time or channel, preserve it beside the attempt count. A conflict between the queue and the contact instruction should move to review rather than be resolved by the next caller.', 'The owner can decide whether the instruction changes the sequence, requires suppression, or is too ambiguous to apply. The handoff should state the source and the exact unresolved point.'] },
    { heading: 'Audit sequence discipline', paragraphs: ['Compare a sample of attempt histories with the final disposition and next queue. Look for attempts beyond the limit, ignored preferences, and records incorrectly labeled unreachable after a clear stop request.', 'The right measure is controlled opportunity: each attempt followed the brief, produced an honest state, and left a visible reason for what happens next.'] },
  ],
  [
    { heading: 'Make the version a pre-call fact', paragraphs: ['A script version check should happen before a Filipino caller begins the queue. The record needs a purpose, a released brief, approved language, and a way to identify whether an update applies. This prevents a caller from relying on memory when two campaigns sound similar.', 'The check can be small: match the queue label, version identifier, effective date, and required fields. If any part is missing, record the gap and hold the record for the campaign owner.'] },
    { heading: 'Keep old wording out of new promises', paragraphs: ['A familiar line may no longer reflect the current boundary. Do not copy a sentence from a previous script into a new call because it sounds helpful. Differences in eligibility, timing, escalation, or allowed answers can matter even when the opening is unchanged.', 'The caller can ask which released wording applies and flag the conflict. The campaign owner owns the decision to amend, replace, or retire the script.'] },
    { heading: 'Record changes as instructions', paragraphs: ['When a script changes, the handoff should say what changed, which queue is affected, and what the caller should do with records already in progress. A vague “new script” note leaves the next person to interpret the change.', 'Keep training and call work aligned by making the effective point visible. Do not claim that a caller was trained or that a queue is safe merely because a file was edited.'] },
    { heading: 'Review version drift', paragraphs: ['Sample call notes against the released brief and look for phrases that belong to an older version. Check exception handling as closely as the opening line; boundary language is often where drift creates risk.', 'A reliable version check makes it easy to pause, ask, and resume. That is more valuable than silently producing calls whose wording no longer matches the approved purpose.'] },
  ],
];

function makeSection(seed: Seed, index: number): Section[] {
  const base = sections[index % sections.length];
  return base.map((section) => ({ heading: section.heading, paragraphs: section.paragraphs.map((p) => `${p} In this ${seed[1].toLowerCase()} workflow, ${seed[3].toLowerCase()} The caller records the answer and routes ${seed[4]} to ${seed[7]}.`) }));
}

export const aug19BlogPosts = seeds.map(([slug, title, excerpt]) => ({ slug, title, excerpt, minutes: 12, published: '2026-08-19' as const }));

export function makeAug19Detail(post: typeof aug19BlogPosts[number]) {
  const seed = seeds.find((item) => item[0] === post.slug)!;
  const [, title, , question, decision, scenario, boundary, owner] = seed;
  const index = seeds.findIndex((item) => item[0] === post.slug);
  return {
    published: '2026-08-19', mainKeyword: title, metaLabel: 'Philippines staffing blog',
    directAnswerHeading: `How to handle ${title.toLowerCase()}`,
    summary: `${title} keeps a Filipino caller focused on one operational question: ${question} The caller preserves evidence and routes ${decision} to ${owner}.`,
    takeaways: [`Start with the question: ${question}`, 'Separate the caller’s evidence from an owner’s decision.', `Treat ${scenario} as a review condition, not a reason to guess.`, `Stop at the boundary: ${boundary}.`, `Close with a result, next action, and accountable owner.`],
    decisionTable: [
      { lane: 'Purpose', caller: `Explains why the ${title.toLowerCase()} check is happening.`, owner: 'Defines the approved audience, wording, and result.', measure: 'The person understands the reason for contact' },
      { lane: 'Evidence', caller: 'Captures the answer, request, refusal, or uncertainty.', owner: 'Decides which source and fields are sufficient.', measure: 'The note shows what was established' },
      { lane: 'Boundary', caller: `Stops at ${boundary}.`, owner: `Reviews the exception and owns ${decision}.`, measure: 'No guess becomes a commitment' },
      { lane: 'Handoff', caller: 'Sends purpose, evidence, open point, and requested action.', owner: `Owns the response as ${owner}.`, measure: 'The next person can act without repeating the call' },
    ],
    planningBands: [{ label: 'Question', value: 'One', note: question }, { label: 'Evidence', value: 'Named', note: 'Separate words from inference' }, { label: 'Boundary', value: 'Visible', note: 'Pause before an unsupported decision' }, { label: 'Owner', value: 'Clear', note: owner }],
    sections: makeSection(seed, index),
    scripts: [{ title: 'Opening', text: `I am calling about ${title.toLowerCase()}. I will keep this focused on the question we need to clarify.` }, { title: 'Clarifying', text: 'I want to record that accurately. May I repeat the point I have so far?' }, { title: 'Boundary', text: `I can record that request, but ${owner} needs to decide the next step.` }],
    workflow: [{ step: '1', title: 'Set purpose', text: 'Write the one question and intended result.' }, { step: '2', title: 'Check context', text: 'Use only the approved record details.' }, { step: '3', title: 'Listen', text: 'Capture the exact answer or uncertainty.' }, { step: '4', title: 'Route', text: 'Send the boundary condition to its owner.' }, { step: '5', title: 'Close', text: 'Save result, action, owner, and reply point.' }],
    faqs: [{ q: `What makes ${title.toLowerCase()} useful?`, a: `It links one clear question to the person’s answer, the unresolved point, and the owner responsible for ${decision}.` }, { q: 'What if the answer falls outside the brief?', a: 'Record it neutrally, explain the review boundary, and route it without making a promise.' }, { q: 'How should uncertainty be handled?', a: 'Keep uncertainty visible. Do not force it into a positive, negative, or completed label.' }],
    related: [{ label: 'Appointment setting service', href: '/services/appointment-setting' }, { label: 'Customer follow-up service', href: '/services/customer-follow-up-calls' }, { label: 'Call quality review service', href: '/services/call-quality-review' }],
    sources: [{ name: 'FCC Telephone Consumer Protection Act guidance', url: 'https://www.fcc.gov/general/telemarketing-and-telephone-consumer-protection-act' }, { name: 'FTC business guidance on data security', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }],
  };
}
