type Aug13Seed = {
  slug: string;
  title: string;
  excerpt: string;
  published: '2026-08-13';
  focus: string;
  detail: string;
};

export const aug13BlogPosts = [
  { slug: 'appointment-setting-meeting-brief-quality', title: 'Appointment setting meeting brief quality guide', excerpt: 'A practical guide to giving an owner the context needed before a qualified meeting, including the prospect’s stated need, timing, and unanswered question.', published: '2026-08-13', focus: 'meeting briefs', detail: 'A meeting brief should make the conversation easier before it starts, not merely prove that a calendar slot exists.' },
  { slug: 'lead-qualification-authority-signal-questions', title: 'Lead qualification authority-signal questions', excerpt: 'How to learn who belongs in a buying conversation without pressing for sensitive information or making a commercial decision on the caller’s behalf.', published: '2026-08-13', focus: 'authority signals', detail: 'Authority questions work best when they clarify who should join the next conversation rather than trying to force a decision on the first call.' },
  { slug: 'inbound-call-language-access-handoff', title: 'Inbound call language-access handoff guide', excerpt: 'A respectful way to identify a language need, preserve the caller’s request, and connect the conversation to the right person.', published: '2026-08-13', focus: 'language-access handoffs', detail: 'A language-access handoff should preserve dignity and context while making the next human connection obvious.' },
  { slug: 'customer-follow-up-success-check-in', title: 'Customer follow-up success check-in questions', excerpt: 'A focused set of questions for learning whether a customer reached the intended outcome and what support is still needed.', published: '2026-08-13', focus: 'success check-ins', detail: 'A success check-in is useful when it discovers the customer’s current outcome instead of reopening every part of the relationship.' },
  { slug: 'outbound-calling-industry-segment-notes', title: 'Outbound calling industry-segment notes', excerpt: 'How to keep industry context visible in a prospecting conversation while separating known facts from assumptions.', published: '2026-08-13', focus: 'industry-segment notes', detail: 'Industry notes help a caller sound prepared only when they distinguish evidence in the record from a guess about the business.' },
  { slug: 'filipino-caller-active-listening-cues', title: 'Filipino caller active-listening cues', excerpt: 'Short cues that help Filipino callers clarify meaning, reflect a customer’s answer, and avoid rushing to the next question.', published: '2026-08-13', focus: 'active listening', detail: 'Active listening is visible in the small follow-up question that checks meaning before a result is recorded.' },
  { slug: 'appointment-setting-time-zone-confirmation', title: 'Appointment setting time-zone confirmation guide', excerpt: 'A clear way to confirm time zone, preferred contact details, and calendar expectations before a meeting request is handed over.', published: '2026-08-13', focus: 'time-zone confirmation', detail: 'Time-zone confirmation protects the customer’s calendar and gives the owner a precise handoff rather than a vague booking request.' },
  { slug: 'customer-follow-up-product-feedback-capture', title: 'Customer follow-up product feedback capture', excerpt: 'A neutral structure for capturing what a customer noticed, what outcome they expected, and which product questions need review.', published: '2026-08-13', focus: 'product feedback', detail: 'Product feedback becomes useful when the note separates the observed experience from the interpretation of why it happened.' },
  { slug: 'order-confirmation-call-partial-order-review', title: 'Order confirmation partial-order review guide', excerpt: 'How to confirm which items belong to an order, record a discrepancy, and pause before making a fulfillment promise.', published: '2026-08-13', focus: 'partial-order reviews', detail: 'A partial-order call should narrow the discrepancy to identifiable items and route fulfillment decisions to the responsible owner.' },
  { slug: 'database-verification-call-source-confidence', title: 'Database verification source-confidence guide', excerpt: 'A field-by-field method for recording where a customer detail came from and how confident the business should be before updating it.', published: '2026-08-13', focus: 'source confidence', detail: 'Source confidence keeps a spoken correction from becoming an unquestioned database fact.' },
  { slug: 'renewal-reminder-call-value-recap', title: 'Renewal reminder value-recap guide', excerpt: 'A concise way to recap the customer’s stated use and open questions while leaving renewal terms and account decisions with the owner.', published: '2026-08-13', focus: 'value recaps', detail: 'A value recap should reflect the customer’s own use case, not introduce an unsupported claim about what renewal will deliver.' },
  { slug: 'win-back-call-reason-for-leaving', title: 'Win-back call reason-for-leaving guide', excerpt: 'Questions for learning why a former customer left, recording the answer without pressure, and routing any requested remedy for review.', published: '2026-08-13', focus: 'reasons for leaving', detail: 'A former customer’s reason for leaving deserves a clean record and a respectful close, even when there is no immediate next step.' },
  { slug: 'survey-calling-open-ended-answer-notes', title: 'Survey calling open-ended answer notes', excerpt: 'How to capture open-ended survey answers faithfully without compressing a nuanced response into a misleading label.', published: '2026-08-13', focus: 'open-ended answers', detail: 'Open-ended responses need enough of the respondent’s meaning to remain useful after the call is over.' },
  { slug: 'reception-overflow-caller-callback-window', title: 'Reception overflow callback-window guide', excerpt: 'A practical way to capture when a caller can receive a reply, what the reply concerns, and who should own it.', published: '2026-08-13', focus: 'callback windows', detail: 'A callback window is only actionable when it is paired with the reason for the call and the person responsible for replying.' },
  { slug: 'outbound-caller-second-attempt-context', title: 'Outbound caller second-attempt context guide', excerpt: 'What to review before a second call so the conversation respects the first attempt, the stated preference, and the reason for trying again.', published: '2026-08-13', focus: 'second-attempt context', detail: 'A second attempt should add context or honor a stated request; it should never be an automatic repeat with no new reason.' },
  { slug: 'filipino-caller-customer-preference-summary', title: 'Filipino caller customer-preference summary guide', excerpt: 'A compact format for recording contact preferences, effective timing, and the limits of what the customer agreed to discuss.', published: '2026-08-13', focus: 'preference summaries', detail: 'A preference summary gives the next caller a useful boundary, not permission to infer more than the customer said.' },
  { slug: 'appointment-setting-competing-priority-discovery', title: 'Appointment setting competing-priority discovery', excerpt: 'How to understand what else is competing for a prospect’s attention and give the owner a realistic next-conversation brief.', published: '2026-08-13', focus: 'competing priorities', detail: 'Competing priorities explain timing better than a generic urgency label and can make a handoff materially more useful.' },
  { slug: 'inbound-call-missing-detail-recovery', title: 'Inbound call missing-detail recovery guide', excerpt: 'A calm method for recovering a missing name, number, or request detail without making the caller repeat the whole conversation.', published: '2026-08-13', focus: 'missing-detail recovery', detail: 'Recovering one missing detail should reduce friction while keeping the caller’s original purpose intact.' },
  { slug: 'outbound-calling-referral-introduction-notes', title: 'Outbound calling referral-introduction notes', excerpt: 'A note structure for referral conversations that records the connection, permission, purpose, and next action clearly.', published: '2026-08-13', focus: 'referral introductions', detail: 'Referral context is valuable only when the note identifies how the introduction was made and what the recipient expects next.' },
  { slug: 'customer-follow-up-delayed-resolution-update', title: 'Customer follow-up delayed-resolution update guide', excerpt: 'How to update a customer when an answer is not ready, state what remains open, and avoid promising a result you cannot control.', published: '2026-08-13', focus: 'delayed-resolution updates', detail: 'A delayed-resolution update builds trust by naming what is known, what is still being checked, and who owns the next reply.' },
  { slug: 'database-verification-call-duplicate-evidence', title: 'Database verification duplicate-evidence guide', excerpt: 'A careful way to collect evidence when two records may belong to one person without merging, deleting, or exposing extra information.', published: '2026-08-13', focus: 'duplicate evidence', detail: 'Duplicate evidence should help the data owner decide without asking a caller to make an irreversible record change.' },
  { slug: 'call-quality-review-context-reconstruction', title: 'Call quality context-reconstruction guide', excerpt: 'A review method for checking whether a call note preserves the customer’s purpose, answer, uncertainty, and next owner.', published: '2026-08-13', focus: 'context reconstruction', detail: 'Context reconstruction tests whether another person can understand the call without relying on the reviewer’s assumptions.' },
] as const satisfies readonly Aug13Seed[];

export function makeAug13Detail(post: typeof aug13BlogPosts[number]) {
  const title = post.title;
  return {
    published: '2026-08-13',
    mainKeyword: title,
    summary: `${post.detail} For Outsourced Callers, the practical standard is to give Filipino callers a narrow brief, capture the customer’s own words, and make the next owner decision easy to see.`,
    takeaways: [
      `Define the purpose of the ${post.focus} before the conversation begins.`,
      'Use only the record fields and approved questions needed for that purpose.',
      'Separate a confirmed answer from an interpretation or an unresolved question.',
      'Stop for sensitive requests, identity uncertainty, complaints, opt-outs, or unapproved commitments.',
      'Close with one result, one next action, one owner, and a realistic reply point.',
    ],
    decisionTable: [
      { lane: 'Conversation purpose', caller: `Explains the ${post.focus} in plain language and checks that the person can continue.`, owner: 'Defines the audience, approved wording, and intended result.', measure: 'The reason is visible before questions begin' },
      { lane: 'Useful context', caller: 'Uses the smallest relevant record context and confirms rather than assumes.', owner: 'Chooses which fields may be shown and which must remain out of scope.', measure: 'No unrelated detail enters the call' },
      { lane: 'Customer answer', caller: 'Records the answer neutrally, including a refusal or uncertainty.', owner: 'Decides how disputed, sensitive, or incomplete answers are resolved.', measure: 'The note distinguishes fact from interpretation' },
      { lane: 'Next decision', caller: 'Routes the question or request with enough context to act.', owner: 'Owns commitments, account changes, exceptions, and final replies.', measure: 'Every open item has a named owner' },
    ],
    planningBands: [
      { label: 'Purpose', value: 'One', note: `${post.focus} stays focused` },
      { label: 'Context', value: 'Relevant', note: 'Use the smallest useful field set' },
      { label: 'Answer', value: 'Verbatim', note: 'Preserve the customer’s meaning' },
      { label: 'Next step', value: 'Owned', note: 'Name the responsible person' },
    ],
    sections: [
      { heading: `Start with the ${post.focus}`, paragraphs: [`Before a Filipino caller reaches out, write the one outcome this ${post.focus} should produce. The opening should explain why the business is calling and give the customer a fair chance to continue or decline.`, 'A narrow purpose protects the conversation from turning into an improvised survey. It also gives the reviewer a fair way to judge whether the call reached its intended result.'] },
      { heading: 'Keep evidence separate from assumption', paragraphs: [`The record may contain useful context for ${post.focus}, but context is not proof. Ask a short confirming question, preserve the answer in plain language, and mark anything that still needs checking.`, 'Avoid translating a hesitant answer into a confident label. The owner can decide what an uncertain answer means; the caller’s job is to make the uncertainty visible.'] },
      { heading: 'Make the boundary easy to use', paragraphs: ['A good boundary gives the caller a safe response when the person asks for something outside the approved brief. The caller can acknowledge the request, record it accurately, and explain that the responsible owner will review it.', 'Identity concerns, opt-out requests, sensitive account details, complaints, and promises about outcomes should be clear stop points. A pause is a successful handoff when it prevents a guess from becoming a commitment.'] },
      { heading: 'Review the note for the next person', paragraphs: [`Read the finished note as if you were the owner receiving a ${post.focus} handoff for the first time. It should answer why the call happened, what the person said, what remains open, and what should happen next.`, 'The strongest notes are concise without being vague. They preserve the customer’s purpose and give the next person a practical starting point.'] },
    ],
    scripts: [{ title: 'Opening', text: `I am calling about the ${post.focus} noted in our records. I will keep this focused and ask only what is needed for this request.` }, { title: 'Boundary', text: 'I want to record that accurately rather than guess. I will pass your request to the person who can review the next step.' }],
    workflow: [{ step: '1', title: 'Set purpose', text: `Write the intended outcome for the ${post.focus}.` }, { step: '2', title: 'Check context', text: 'Confirm the smallest useful record detail.' }, { step: '3', title: 'Listen', text: 'Capture the answer and any uncertainty plainly.' }, { step: '4', title: 'Route', text: 'Send sensitive or unresolved matters to the named owner.' }, { step: '5', title: 'Close', text: 'Record the result, next action, owner, and reply point.' }],
    faqs: [{ q: `What makes a ${post.focus} useful?`, a: 'It connects a clear reason for contact with the customer’s answer, unresolved detail, and an accountable next action.' }, { q: 'What should happen when the caller cannot answer?', a: 'Record the question neutrally, explain that it needs review, and route it to the named owner without making a promise.' }],
    related: [{ label: 'Appointment setting service', href: '/services/appointment-setting' }, { label: 'Customer follow-up service', href: '/services/customer-follow-up-calls' }, { label: 'Call quality review service', href: '/services/call-quality-review' }],
    sources: [{ name: 'FCC Telephone Consumer Protection Act guidance', url: 'https://www.fcc.gov/general/telemarketing-and-telephone-consumer-protection-act' }, { name: 'FTC business guidance on data security', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' }],
  };
}
