type Aug17Seed = readonly [slug: string, title: string, excerpt: string, question: string, decision: string, scenario: string, boundary: string, owner: string, published: '2026-08-17'];

const seeds: readonly Aug17Seed[] = [
  ['appointment-setting-discovery-question-map', 'Appointment setting discovery-question map', 'How a Filipino appointment setter can use one useful discovery question without turning a first call into an improvised sales interview.', 'Which single fact would make the requested meeting useful to the owner?', 'whether the next question belongs in the approved appointment brief', 'a prospect offers a broad reason for meeting but names two unrelated problems', 'do not diagnose fit or recommend a service from an incomplete answer', 'the appointment owner', '2026-08-17'],
  ['lead-qualification-evidence-threshold', 'Lead qualification evidence threshold', 'A practical threshold for recording a lead signal as stated evidence, an open question, or an owner decision during Filipino qualification calls.', 'What did the prospect actually establish, and what is still only suspected?', 'whether the record has enough approved evidence for a handoff', 'a contact agrees that a problem exists but cannot confirm timing or ownership', 'do not turn enthusiasm, politeness, or a vague answer into a buying conclusion', 'the lead owner', '2026-08-17'],
  ['inbound-call-identity-mismatch-handoff', 'Inbound call identity mismatch handoff', 'How Filipino inbound callers can keep a helpful conversation moving when the caller and account record do not match.', 'What can be handled without revealing or changing the wrong person’s information?', 'whether to message, transfer, or stop for an identity owner', 'a caller knows an order reference but cannot confirm the approved identity detail', 'do not read account information aloud or improvise a verification method', 'the account owner', '2026-08-17'],
  ['customer-follow-up-commitment-repair', 'Customer follow-up commitment repair', 'A guide to repairing an unclear promise in a customer follow-up note so the next owner can respond accurately.', 'What was actually promised, by whom, and what needs correction now?', 'whether the note needs an owner-led clarification before another call', 'a prior message says someone will “take care of it” without a date or named responsibility', 'do not repeat an uncertain promise as a confirmed resolution', 'the customer-service owner', '2026-08-17'],
  ['outbound-calling-contact-window-exception', 'Outbound calling contact-window exception', 'How to handle a requested call time that falls outside the approved outbound calling window while preserving the person’s preference.', 'Can the requested time be honored under the current brief, or does it require review?', 'whether to schedule within the approved window or route an exception', 'a contact asks for an evening callback even though the released list has a narrower window', 'do not promise an exception or keep calling after a clear stop request', 'the campaign owner', '2026-08-17'],
  ['filipino-caller-name-number-confirmation', 'Filipino caller name-and-number confirmation', 'A respectful method for confirming names and numbers in Filipino calling work without treating accent or speed as a quality proxy.', 'Which detail needs repeating, spelling, or a read-back to prevent a bad handoff?', 'which confirmation method makes the record reliable for the receiving owner', 'a surname and callback number are both understood differently on the first pass', 'do not infer capability from accent; judge the confirmed information and outcome', 'the quality owner', '2026-08-17'],
  ['appointment-setting-calendar-hold-boundary', 'Appointment setting calendar-hold boundary', 'How appointment setters can distinguish a requested meeting hold from a confirmed calendar commitment.', 'Has the owner accepted a specific time, or is the prospect only offering availability?', 'whether the next state is request, hold, confirmation, or follow-up', 'a prospect offers two times while the calendar owner has not approved either one', 'do not represent a tentative window as a booked meeting', 'the calendar owner', '2026-08-17'],
  ['customer-follow-up-reason-for-contact', 'Customer follow-up reason-for-contact capture', 'A focused way to preserve why a customer wants a callback when the reason contains more than one issue.', 'Which issue should the next owner address first, and which details remain separate?', 'how to split one conversation into accountable follow-up items', 'a customer asks about a prior issue and adds a new request before the call closes', 'do not collapse separate requests into one vague “follow-up needed” label', 'the customer owner', '2026-08-17'],
  ['order-confirmation-approved-change-boundary', 'Order confirmation approved-change boundary', 'How Filipino order confirmation callers can record a requested change without implying that fulfillment has accepted it.', 'Is the customer confirming the order or requesting a new fulfillment decision?', 'whether the result is confirmed, exception, or owner review', 'a customer confirms the item but asks to change quantity after the order record is read back', 'do not edit or promise a material order change without the responsible approval', 'the fulfillment owner', '2026-08-17'],
  ['database-verification-record-provenance', 'Database verification record provenance', 'A practical note standard for showing where a spoken correction came from and how confidently it can be reviewed.', 'Who supplied the correction, which field changed, and what source can the owner verify?', 'whether the data owner can accept the correction or needs another check', 'a household member supplies a spelling correction for the named contact', 'do not treat an unverified third-party statement as final record authority', 'the data owner', '2026-08-17'],
  ['renewal-reminder-term-question-routing', 'Renewal reminder term-question routing', 'How to capture a renewal question precisely while keeping contract, eligibility, and account decisions with the authorized owner.', 'What does the customer need explained before they can decide whether to continue?', 'which question can be answered from approved wording and which needs review', 'a customer asks whether a changed term applies to their account', 'do not interpret terms or imply eligibility from a general script', 'the account owner', '2026-08-17'],
  ['win-back-refusal-complete-outcome', 'Win-back refusal as a complete outcome', 'Why a former customer’s refusal should be recorded as a complete result even when they explain why they left.', 'Has the person declined future contact, and what suppression action follows?', 'whether the record closes, suppresses, or requires a policy owner', 'a former customer shares useful feedback but clearly says not to call again', 'do not treat feedback as permission for another offer', 'the list owner', '2026-08-17'],
  ['survey-calling-uncertain-answer-label', 'Survey calling uncertain-answer label', 'How survey callers can preserve uncertainty instead of forcing a respondent into a category that does not fit their answer.', 'Did the respondent answer, ask for clarification, decline, or remain uncertain?', 'which approved result label matches the respondent’s actual state', 'a respondent understands the topic but says the available options do not describe them', 'do not suggest an answer or recast uncertainty as agreement', 'the survey owner', '2026-08-17'],
  ['reception-overflow-message-completeness', 'Reception overflow message completeness', 'A message standard for reception overflow calls that gives the recipient enough context without inventing urgency.', 'What must the recipient know to choose the next action?', 'whether the message is complete enough to route or needs one clarification', 'a caller says “it is urgent” but gives no reason, deadline, or safe callback detail', 'do not label a matter urgent solely from tone or pressure', 'the receiving manager', '2026-08-17'],
  ['outbound-calling-wrong-party-suppression', 'Outbound calling wrong-party suppression', 'A clean wrong-party close that protects contact preferences and prevents a mistaken person from remaining in an outbound queue.', 'What can be confirmed safely, and should this number be suppressed or reviewed?', 'whether the record needs suppression, correction, or owner review', 'someone answers a number and says the intended contact has never used it', 'do not ask the wrong party to supply private details about the intended contact', 'the list owner', '2026-08-17'],
  ['customer-follow-up-channel-effective-date', 'Customer follow-up channel effective date', 'How to record a customer’s requested contact-channel change with the timing needed for a safe next outreach.', 'Which channel did the customer request, and from when should it apply?', 'whether the current system preference changes now or after owner review', 'a customer wants email instead of phone but only for future follow-ups', 'do not promise that a policy or system change is already active', 'the customer-data owner', '2026-08-17'],
  ['appointment-setting-time-zone-confirmation', 'Appointment setting time-zone confirmation', 'A practical check for time zone and local date before an appointment request reaches the calendar owner.', 'Whose local time is being proposed, and what exact date and window should be reviewed?', 'whether the request is unambiguous enough to hand off', 'a prospect and owner work in different time zones and use “tomorrow morning”', 'do not translate a relative time into a confirmed slot without the owner’s check', 'the calendar owner', '2026-08-17'],
  ['inbound-call-transfer-context-packet', 'Inbound call transfer context packet', 'What an inbound caller should pass to the receiving owner so the customer does not have to repeat the whole issue.', 'What is the purpose, what was already answered, and what remains unresolved?', 'whether to transfer now or send a complete message instead', 'a caller has explained the issue once and the receiving team needs one missing detail', 'do not transfer a sensitive or unresolved matter without the required context', 'the receiving owner', '2026-08-17'],
  ['lead-qualification-role-authority-check', 'Lead qualification role-and-authority check', 'How to learn whether a prospect owns the relevant decision without treating job title or confidence as proof.', 'What part of the decision does the contact influence, and who else must be involved?', 'whether the handoff needs another participant or an owner review', 'a prospect can describe the problem but says another colleague approves the next step', 'do not claim the contact is the final decision-maker from title alone', 'the lead owner', '2026-08-17'],
  ['order-confirmation-split-shipment-question', 'Order confirmation split-shipment question', 'How to separate a customer’s delivery question from the order confirmation result when items may arrive under different schedules.', 'Is the order confirmed, or is the customer asking for a fulfillment explanation?', 'which detail belongs in the confirmation and which needs fulfillment review', 'a customer confirms the items but asks whether they will arrive together', 'do not invent a delivery schedule or combine separate fulfillment decisions', 'the fulfillment owner', '2026-08-17'],
  ['call-quality-observation-evidence-note', 'Call quality observation evidence note', 'A review method for distinguishing what a Filipino caller said, what the customer answered, and what the reviewer inferred.', 'Which exact words or record fields support the quality observation?', 'whether the coaching point is evidence-based and actionable', 'a reviewer labels a call “weak” without identifying the missed question or note field', 'do not score personality, accent, or assumed intent instead of observable work', 'the quality manager', '2026-08-17'],
  ['daily-calling-queue-reason-code', 'Daily calling queue reason code', 'How to keep a calling queue useful by tying each record to one purpose and one reason it is ready for work.', 'Why is this record in today’s queue, and what result would complete that reason?', 'whether the record is ready, blocked, or misrouted', 'a list mixes callbacks, qualification, and data checks under one generic task label', 'do not let activity volume hide a queue with no clear purpose', 'the operations owner', '2026-08-17'],
];

export const aug17BlogPosts = seeds.map(([slug, title, excerpt, , , , , , published]) => ({ slug, title, excerpt, minutes: 11, published }));

type AuthoredSection = { heading: string; paragraphs: string[] };

// These are the article bodies, authored per topic. The shared route component supplies
// presentation only; it must not manufacture the substance of an article.
const authoredSections: Record<string, AuthoredSection[]> = {
  'appointment-setting-discovery-question-map': [
    { heading: 'Make the first question earn its place', paragraphs: ['A discovery question in appointment setting should identify the reason a meeting could be useful, not invite a prospect to retell an entire business history. Ask what prompted the request and listen for the operating problem in the person’s own terms.', 'The appointment owner should define in advance what answer is enough to pass along. A stated problem, affected process, desired change, and broad timing may be sufficient for a meeting request; a caller should not invent urgency or fit when those details are absent.'] },
    { heading: 'Separate a useful answer from a sales conclusion', paragraphs: ['When a prospect names two unrelated problems, record both and ask which one the requested conversation should address first. That small distinction keeps the calendar entry useful to the recipient.', 'The caller can clarify scope and participants. The owner decides whether the proposed meeting belongs on the calendar, whether another person should join, and whether the request needs a different route.'] },
    { heading: 'Use a clear handoff threshold', paragraphs: ['A strong handoff states the question asked, the prospect’s answer, the problem selected for discussion, the requested timing, and the unresolved point. It should allow the appointment owner to prepare without calling the prospect back for basic context.', 'If the answer is broad or uncertain, label it that way. A meeting request can remain open for review without turning a polite conversation into a qualification claim.'] },
    { heading: 'Review the meeting request, not the call length', paragraphs: ['Sample appointment records for agreement between the call note and the calendar description. Check whether the stated need, participants, and next action are traceable to the conversation.', 'The useful result is a bounded request that an owner can accept, clarify, or decline. Caller activity alone cannot establish that a meeting is appropriate.'] },
  ],
  'lead-qualification-evidence-threshold': [
    { heading: 'Define evidence before the call', paragraphs: ['Lead qualification becomes unreliable when every positive-sounding answer is treated as proof of readiness. Define the minimum evidence for the lane: a stated problem, relevant context, timing, and the contact’s role in the decision.', 'The caller should know which fields are observations and which are owner decisions. This prevents a vague expression of interest from becoming an unsupported status.'] },
    { heading: 'Record what the contact actually established', paragraphs: ['A contact may confirm that a problem exists while being unable to say who approves the next step. Preserve those as separate facts. The open authority question is useful information, not a failure to qualify.', 'Use a neutral follow-up to identify participants or timing, then stop when the answer is not available. Do not use confidence, seniority, or friendliness as evidence of buying authority.'] },
    { heading: 'Make the threshold visible to the owner', paragraphs: ['A handoff should show the evidence that met the released threshold and the evidence still missing. The lead owner can then decide whether to proceed, invite another participant, or request a controlled follow-up.', 'If a record cannot support the proposed label, use an open or review state. Honest incompleteness protects the next conversation from starting with a false premise.'] },
    { heading: 'Audit classifications against notes', paragraphs: ['Review a sample by comparing the source list, call note, and final owner disposition. Look specifically for enthusiasm recorded as intent, a title recorded as authority, and an unresolved question hidden inside a positive label.', 'A good qualification process makes disagreements visible. It does not make the caller responsible for a decision that belongs to the lead owner.'] },
  ],
  'inbound-call-identity-mismatch-handoff': [
    { heading: 'Stop when the record and caller do not match', paragraphs: ['An inbound call can be helpful without revealing information to a person whose identity has not been established. When the caller and account record do not match, use only the approved verification step and explain the next safe route.', 'An order reference or familiar detail is not automatically enough to disclose account information. The account owner should define the accepted match and the failed-check outcome.'] },
    { heading: 'Keep the conversation useful', paragraphs: ['Record the caller’s purpose without repeating private account details aloud. If the person needs a general route, provide approved public information or take a message that does not expose the disputed record.', 'The note should distinguish identity not established, wrong record, and routine request. Those states lead to different owner actions and should not be collapsed into one failed-call label.'] },
    { heading: 'Choose transfer, message, or stop deliberately', paragraphs: ['Transfer only when the receiving team can perform the required identity and account work under its own controls. Otherwise capture a safe callback route and the unresolved request for the account owner.', 'Never improvise a second verification method because the caller sounds credible. A clean stop protects both the caller and the person whose information is in the record.'] },
    { heading: 'Review exposure as well as completion', paragraphs: ['Quality review should ask whether the caller disclosed anything before the mismatch was resolved, whether the note preserved the uncertainty, and whether the route matched the owner’s policy.', 'A short call with no disclosure can be the correct outcome. Completion is not measured by how much account information the caller managed to provide.'] },
  ],
  'customer-follow-up-commitment-repair': [
    { heading: 'Unpack the promise before repeating it', paragraphs: ['“Someone will take care of it” is not a complete customer commitment. Before another follow-up, identify what action was promised, who owned it, when it was expected, and what the customer still needs.', 'The caller can acknowledge the ambiguity and record the customer’s current concern. The service owner decides whether to clarify, correct, or honor the earlier promise.'] },
    { heading: 'Repair the note with facts', paragraphs: ['A repair note should quote the practical meaning without pretending to know intent: prior message had no named owner or date; customer is waiting for a specific answer; owner review requested.', 'Separate the customer’s account of the promise from the business’s verified status. That distinction prevents a vague commitment from becoming a repeated but inaccurate assurance.'] },
    { heading: 'Give the next owner a usable route', paragraphs: ['Include the original issue, the unclear commitment, the customer’s requested outcome, and any safe reply window. Do not add a resolution that has not been approved.', 'If the owner cannot meet the earlier expectation, the owner should decide how to explain the correction. The caller should not bargain, apologize for an unverified cause, or promise a new date.'] },
    { heading: 'Measure repair quality', paragraphs: ['Sample repaired notes for four things: the promise is identifiable, the current status is separated from the customer’s expectation, the next owner is named, and the reply condition is clear.', 'The point of repair is continuity. A precise correction is more useful than a cheerful follow-up that leaves the same ambiguity in the record.'] },
  ],
  'outbound-calling-contact-window-exception': [
    { heading: 'Treat a requested time as a preference first', paragraphs: ['An evening callback request is information about the contact’s preference, not permission to bypass the released calling window. Record the requested time and compare it with the approved brief.', 'The campaign owner decides whether an exception exists and who may approve it. The caller should never imply that a special window has been granted.'] },
    { heading: 'Preserve the preference without overpromising', paragraphs: ['Tell the contact that the requested time can be recorded for review or scheduled within the available window. Give only the approved expectation for the next response.', 'A clear note includes local date or time zone when known, the requested window, the permitted alternative, and the stop request if the person does not want another attempt.'] },
    { heading: 'Use an exception route', paragraphs: ['The owner’s review should answer whether the request is allowed, whether another channel is appropriate, and whether the record needs suppression. Keep those decisions out of the caller’s improvised close.', 'If no exception is approved, the correct result may be an unavailable window rather than a failed lead. That preserves the contact’s choice and the campaign boundary.'] },
    { heading: 'Check the queue after the decision', paragraphs: ['Review whether the requested window was copied accurately, whether the next attempt falls inside the approved hours, and whether a stop instruction was respected.', 'A queue that records preferences but ignores them is not controlled. The quality measure is agreement between the request, the approved rule, and the next action.'] },
  ],
  'filipino-caller-name-number-confirmation': [
    { heading: 'Make read-back a reliability tool', paragraphs: ['Name and number confirmation should be judged by whether the final record is accurate, not by accent, speed, or assumptions about a Filipino caller. Ask permission to repeat the detail and use spelling or grouped digits when useful.', 'The customer can correct the record in their own words. The caller records the confirmed value and any unresolved portion without turning pronunciation into a quality score.'] },
    { heading: 'Handle two uncertain fields separately', paragraphs: ['When both a surname and callback number are unclear, resolve them one at a time. A successful number read-back does not prove the name was understood, and vice versa.', 'Mark the field that remains uncertain and route it according to the owner’s rule. Do not fill a gap from a nearby record or a guess about what the person meant.'] },
    { heading: 'Keep the note evidence-based', paragraphs: ['A useful note states which field was repeated, what the person confirmed, and what still needs review. It should not contain commentary about accent, nationality, or perceived confidence.', 'The receiving owner needs the reliable value and the confidence state. That is more actionable than a general claim that the call was difficult.'] },
    { heading: 'Coach the behavior you can observe', paragraphs: ['Review recordings or notes for permission to repeat, accurate grouping, correction handling, and final field agreement. Coach the method when it fails; do not substitute identity or speaking style for evidence.', 'The goal is a clean handoff to the right number and name. Respectful confirmation helps both the caller and the customer reach that result.'] },
  ],
  'appointment-setting-calendar-hold-boundary': [
    { heading: 'Name the calendar state', paragraphs: ['A prospect offering two times is not the same as an owner confirming a meeting. Use separate states for availability, request, temporary hold, and confirmed appointment.', 'The appointment setter can capture the options and purpose. The calendar owner controls acceptance and should be the source of truth for a booked event.'] },
    { heading: 'Write the handoff around the unresolved choice', paragraphs: ['Include the prospect’s preferred windows, local time zone, meeting purpose, participants, and the owner decision still needed. Avoid language such as “booked” until the calendar owner accepts.', 'If the owner cannot use either time, the next action is a clarification or alternate proposal. It is not permission to represent an unapproved slot as fixed.'] },
    { heading: 'Protect trust at the close', paragraphs: ['Use wording that makes the state clear: the request was recorded and is awaiting confirmation. That gives the prospect a truthful expectation without making the caller sound evasive.', 'A later confirmation should repeat the exact date, time zone, participants, and channel. Relative language such as “that morning” should not survive into the final event.'] },
    { heading: 'Audit event identity', paragraphs: ['Compare the call note, calendar record, and confirmation message. Look for mismatched times, missing participants, and tentative requests presented as held meetings.', 'The useful metric is accurate state transition, not the number of calendar records created.'] },
  ],
  'customer-follow-up-reason-for-contact': [
    { heading: 'Do not compress two issues into one', paragraphs: ['When a customer asks about an old problem and adds a new request, write two issue threads even if the same person owns both. The next owner needs to know what can be answered together and what must remain separate.', 'Ask which matter should be addressed first, then preserve the second as an explicit open item. A generic “follow-up needed” label hides priority and accountability.'] },
    { heading: 'Keep the customer’s order of concern', paragraphs: ['The note should distinguish the customer’s stated reason from the caller’s routing choice. If the customer did not prioritize the issues, say that rather than inventing an order.', 'This makes the next call more respectful: the customer does not have to reconstruct both requests just because the first note was too broad.'] },
    { heading: 'Route each decision to its owner', paragraphs: ['A status explanation may be available from approved wording while a new request needs a service or account owner. Record those different authority paths beside the corresponding issue.', 'Do not close both items because one answer was available. Completion belongs to each issue, not to the fact that a conversation occurred.'] },
    { heading: 'Review for issue loss', paragraphs: ['Sample notes for missing second requests, merged outcomes, and next actions that do not identify which concern they address. Include both the customer’s wording and the owner route.', 'A concise split note is better than a long transcript. Its job is to make the next accountable action obvious.'] },
  ],
  'order-confirmation-approved-change-boundary': [
    { heading: 'Separate confirmation from change request', paragraphs: ['A customer can confirm the released item and then request a quantity change. Those are two different outcomes and should not be recorded as one completed confirmation.', 'The caller can repeat the released order, capture the requested change, and explain the review boundary. Fulfillment or order control owns acceptance.'] },
    { heading: 'Record the released value and requested value', paragraphs: ['The note should preserve what was confirmed, what the customer asked to change, when the request was made, and which approval route applies. Do not overwrite the released value with the requested value.', 'This distinction is especially important when a later owner must determine inventory, payment, delivery, or identity implications.'] },
    { heading: 'Use a truthful close', paragraphs: ['Say that the request was recorded for review and identify the next owner if approved wording allows. Do not promise that the change will be made or imply that confirmation settled the exception.', 'If the customer withdraws the request, record that separately. A withdrawn change should not remain hidden in an otherwise positive confirmation note.'] },
    { heading: 'Test the boundary in samples', paragraphs: ['Review calls with changed quantities, addresses, or items. Check that the original order remains visible, the request is routed, and no unsupported fulfillment promise appears.', 'The reliable result is a clear split between what the customer confirmed and what the owner must still decide.'] },
  ],
  'database-verification-record-provenance': [
    { heading: 'Give every correction a source', paragraphs: ['A spoken correction is not self-proving. Record who supplied it, which field they addressed, when it was supplied, and what verification state applies.', 'A household member may know a spelling or phone number while still lacking authority to change the named contact’s record. Provenance preserves that distinction.'] },
    { heading: 'Separate report from acceptance', paragraphs: ['The caller can capture the proposed value and source person. The data owner decides whether the evidence meets the organization’s correction rule.', 'Use labels such as reported, directly confirmed, disputed, or owner-approved only when the released definitions support them. Do not use “verified” as a synonym for plausible.'] },
    { heading: 'Make uncertain data safe to review', paragraphs: ['A reviewer should be able to compare the prior value, proposed value, source, method, and final disposition without searching a narrative for the important detail.', 'Do not copy unrelated personal information into the note. Provenance is useful only when it is limited to the decision the owner must make.'] },
    { heading: 'Measure correction integrity', paragraphs: ['Sample changed records and check whether the final value can be traced to an approved source and whether rejected or pending proposals remain visible as such.', 'A high number of updates is not evidence of quality. The useful measure is whether each update has a defensible chain from report to decision.'] },
  ],
  'renewal-reminder-term-question-routing': [
    { heading: 'Find the exact term question', paragraphs: ['A renewal call should distinguish a request for approved general information from a question about a particular account’s term, eligibility, or exception. Ask the customer which point needs explanation.', 'The caller can use released wording for the general case. The account owner decides anything that depends on contract state or customer-specific facts.'] },
    { heading: 'Do not infer eligibility', paragraphs: ['A customer may ask whether a changed term applies to them. Record the question and relevant context, but do not turn a general policy statement into an account decision.', 'A safe note names the term in question, the customer’s requested outcome, and the owner route needed to answer accurately.'] },
    { heading: 'Keep renewal timing honest', paragraphs: ['If the customer needs an answer before deciding, record the requested decision window without promising that the owner can meet it. A renewal reminder should not become an accidental commitment.', 'When the customer declines further contact, record that preference separately from the term discussion and follow the suppression rule.'] },
    { heading: 'Review the answer boundary', paragraphs: ['Quality checks should compare the question asked with the wording used and identify whether any account-specific conclusion was made without owner evidence.', 'A good renewal note supports a decision; it does not make the decision on behalf of the account owner.'] },
  ],
  'win-back-refusal-complete-outcome': [
    { heading: 'Let refusal govern the result', paragraphs: ['A former customer can offer valuable feedback and still clearly decline future calls. The refusal is the contact outcome; the explanation is a separate insight.', 'Record the stop request immediately according to the list owner’s suppression process. Do not delay it while seeking a better reason or another offer.'] },
    { heading: 'Capture volunteered feedback carefully', paragraphs: ['If the person chooses to explain why they left, preserve the explanation without framing it as permission for a follow-up. Mark what was volunteered and what the business should analyze internally.', 'The caller should not debate the reason or use it to reopen the sale. A respectful close protects both the person’s preference and the quality of the insight.'] },
    { heading: 'Keep suppression visible', paragraphs: ['The handoff should name the refusal, effective time, source, and suppression action. If policy review is needed, route it without creating another outbound task.', 'A feedback record and an eligible marketing record are not the same thing. Their separation prevents useful commentary from leaking back into the calling queue.'] },
    { heading: 'Audit the next list', paragraphs: ['Check a sample of refused records against future queue exports. A complete outcome is one that stays complete after the list is rebuilt.', 'The measure is not how many reasons were collected. It is whether the refusal was honored and the insight remained bounded.'] },
  ],
  'survey-calling-uncertain-answer-label': [
    { heading: 'Give uncertainty a real state', paragraphs: ['Survey respondents do not always fit the available options. Preserve clarification requests, uncertainty, and “none of these” answers rather than steering a person toward the nearest category.', 'The survey owner should define the allowed labels and how out-of-frame answers are reviewed. The caller should not redesign the instrument during an interview.'] },
    { heading: 'Clarify without leading', paragraphs: ['A neutral clarification repeats the question or explains an approved term without suggesting the answer. If the respondent remains uncertain, record that state.', 'Do not convert hesitation into agreement or treat a refusal to choose as missing compliance. The distinction matters when results are interpreted later.'] },
    { heading: 'Protect respondent meaning', paragraphs: ['The note or coded result should preserve the respondent’s selected category, uncertainty, refusal, or request for explanation. Add a short verbatim context only when the study design permits it.', 'The research owner decides whether an answer is excluded, recoded, or analyzed separately. That choice should not be hidden inside the caller’s shorthand.'] },
    { heading: 'Review coding agreement', paragraphs: ['Compare a sample of call notes with the final survey labels and look for forced positives, missing uncertainty, and explanations that were treated as answers.', 'Good survey calling makes the respondent’s meaning visible. It does not make the dataset look cleaner by deleting ambiguity.'] },
  ],
  'reception-overflow-message-completeness': [
    { heading: 'Turn urgency into evidence', paragraphs: ['When a caller says “urgent,” ask what the receiving manager needs to know: purpose, deadline, impact, safe callback route, and any approved escalation trigger.', 'Tone alone is not a priority label. A pressure-filled call may still be routine, while a quiet request may have a real deadline.'] },
    { heading: 'Write for the receiving decision', paragraphs: ['A complete overflow message lets the manager choose the next action without replaying the conversation. Include who called, why, when they need a response, and what remains unknown.', 'Do not add an emergency description, business consequence, or deadline the caller did not state. Missing information should remain visible.'] },
    { heading: 'Keep transfer and message choices distinct', paragraphs: ['Transfer when the available recipient owns the issue and the caller has supplied the context required for a safe handoff. Otherwise take a message or use the approved callback route.', 'The purpose of a message is not merely to clear the line. It is to preserve enough context for the next owner to act responsibly.'] },
    { heading: 'Check priority calibration', paragraphs: ['Review messages for stated evidence, requested timing, and the receiving owner’s disposition. Compare the word “urgent” with the facts that support or limit it.', 'A calibrated queue helps managers respond to actual deadlines without training callers to exaggerate.'] },
  ],
  'outbound-calling-wrong-party-suppression': [
    { heading: 'End the wrong-party conversation safely', paragraphs: ['When someone says the intended contact has never used the number, do not ask them to disclose details about that person. Record the wrong-party result and follow the approved suppression or correction path.', 'The caller can confirm only what is needed to classify the number. The list owner decides whether to suppress, investigate, or source a replacement.'] },
    { heading: 'Do not treat reachability as identity', paragraphs: ['A live answer proves that a person picked up, not that the record is accurate or that the intended contact consented to outreach. Keep connection, identity, and permission as separate fields.', 'If the person asks not to be contacted, record that instruction directly and stop according to the calling rules.'] },
    { heading: 'Keep the queue from reintroducing the record', paragraphs: ['A suppression result should include source, time, reason, and the action expected before the number can return to a queue. Do not leave a wrong-party record as a generic “no answer.”', 'The next owner needs a clear reason not to retry the same mistake.'] },
    { heading: 'Audit list hygiene', paragraphs: ['Compare wrong-party outcomes with subsequent queue versions and review whether suppression and correction actions actually persisted.', 'A clean close is measured by preventing another inappropriate attempt, not by extracting more information from the wrong person.'] },
  ],
  'customer-follow-up-channel-effective-date': [
    { heading: 'Capture the requested channel and timing', paragraphs: ['A customer may want email instead of phone for future follow-ups but not for a message already in progress. Record the requested channel, scope, effective date, and any exceptions separately.', 'The caller can acknowledge the preference and route the change. The customer-data owner decides when the system or policy change becomes active.'] },
    { heading: 'Do not promise an update you cannot see', paragraphs: ['If the caller cannot confirm that the preference has been changed, say that the request was recorded for review. Do not tell the customer that every future contact will use the new channel.', 'A truthful limitation is better than a promise that causes the next team to violate the customer’s expressed choice.'] },
    { heading: 'Preserve current and future instructions', paragraphs: ['The note should distinguish the current contact method from the requested future method. It should also identify whether a pending owner response still needs a safe channel.', 'This prevents a broad preference from being applied to a matter the customer intended to finish by phone, or from being ignored after its effective date.'] },
    { heading: 'Review preference propagation', paragraphs: ['Sample changes across the source record, calling queue, and next contact. Check that the effective date and scope survive each handoff.', 'The outcome is reliable only when the customer’s instruction remains visible where the next outreach decision is made.'] },
  ],
  'appointment-setting-time-zone-confirmation': [
    { heading: 'Replace relative time with a local date', paragraphs: ['“Tomorrow morning” is incomplete when a prospect and calendar owner work in different time zones. Ask whose local time is intended and capture the exact date and window for review.', 'The setter can remove ambiguity. The calendar owner confirms the final slot and remains responsible for the event.'] },
    { heading: 'Keep proposed and confirmed separate', paragraphs: ['A request should show the prospect’s time zone, preferred window, meeting purpose, and participants. It should not be presented as a confirmed appointment until the owner accepts it.', 'If the time zone is unknown, leave it open rather than converting the request by assumption. A confident guess can create a missed meeting and a poor customer experience.'] },
    { heading: 'Confirm the final event precisely', paragraphs: ['The confirmation should state the date, clock time, time zone, channel, and participants in one place. Avoid relying on “your morning” or “our afternoon” after the slot is accepted.', 'If either party changes the window, update the state and note the new source rather than silently editing the old request.'] },
    { heading: 'Audit conversion accuracy', paragraphs: ['Compare the call note with the calendar event and confirmation message. Look for date rollover, daylight-saving assumptions, and missing time zones.', 'The practical measure is whether the proposed request becomes the same event the prospect and owner each expect.'] },
  ],
  'inbound-call-transfer-context-packet': [
    { heading: 'Transfer context, not just the caller', paragraphs: ['A transfer is useful when the receiving owner knows why the person called, what has already been established, and what remains unresolved. Capture that packet before moving the call.', 'If the available recipient cannot act on the issue, a complete message may be safer than a rushed transfer that forces the customer to start over.'] },
    { heading: 'Keep sensitive details bounded', paragraphs: ['Include only the context needed for the receiving decision. Identity state, requested action, and safe callback route may matter; unrelated account history does not.', 'The caller should not expose sensitive information simply to make the transfer feel complete. The receiving owner applies the stronger account controls.'] },
    { heading: 'Make the unresolved point explicit', paragraphs: ['A good packet names the question the recipient must answer. It does not bury the request inside a long narrative or imply that the caller already resolved it.', 'When a missing detail blocks the transfer, ask the approved clarification or route the gap to the owner. Do not invent context from a nearby record.'] },
    { heading: 'Review repeat-contact prevention', paragraphs: ['Sample transfers for agreement between the caller’s note, the receiving owner’s action, and the customer’s next required step.', 'The success condition is continuity: the next person can act from the packet and the customer does not have to repeat the entire issue.'] },
  ],
  'lead-qualification-role-authority-check': [
    { heading: 'Ask about influence, not title', paragraphs: ['A job title can suggest context but cannot prove approval authority. Ask what part of the decision the contact owns, who else participates, and what the next conversation must accomplish.', 'The caller records the contact’s stated role. The lead owner decides whether another participant or an owner-led review is needed.'] },
    { heading: 'Keep confidence out of the evidence', paragraphs: ['A prospect may speak confidently about a problem while another colleague controls budget or implementation. Record both facts without downgrading the contact or promoting them to final decision-maker.', 'This produces a more useful appointment request because the recipient knows who needs to be present.'] },
    { heading: 'Make participant gaps actionable', paragraphs: ['The handoff should name the missing role, the contact’s influence, the meeting purpose, and the question still open. Do not disguise a missing approver as a completed qualification.', 'If the contact cannot identify the next participant, route the uncertainty rather than pressing for a title-based conclusion.'] },
    { heading: 'Review role evidence', paragraphs: ['Compare labels with the note and look for authority inferred from senior-sounding titles, years of experience, or enthusiasm.', 'A disciplined role check improves meeting preparation while leaving the decision itself with the people authorized to make it.'] },
  ],
  'order-confirmation-split-shipment-question': [
    { heading: 'Separate item confirmation from delivery explanation', paragraphs: ['A customer may confirm every item and still ask whether the shipment will arrive together. Record those as a confirmed order result and a fulfillment question.', 'The caller can capture the question and use approved status wording. The fulfillment owner controls the actual delivery explanation.'] },
    { heading: 'Do not manufacture a schedule', paragraphs: ['If the source record does not state whether items will ship together, say that the question needs review. Do not infer a date or promise one delivery from the fact that the items appear on one order.', 'The note should identify the items affected, the customer’s requested clarity, and the owner route.'] },
    { heading: 'Keep the close precise', paragraphs: ['A truthful close can confirm what was read back and explain that the delivery question was recorded. Avoid language that makes the customer believe the shipment plan is already known.', 'If the customer changes the order while asking about shipment, open a separate change request rather than attaching it to the confirmation result.'] },
    { heading: 'Check split-shipment notes', paragraphs: ['Review records for missing item detail, merged confirmation and delivery outcomes, and unsupported timing promises.', 'A high-quality confirmation leaves the customer with an accurate order state and the fulfillment owner with a specific question to answer.'] },
  ],
  'call-quality-observation-evidence-note': [
    { heading: 'Name the observable behavior', paragraphs: ['A quality note should identify the approved question, the customer’s answer, the saved field, and the next action. “Weak call” is not an observation until the reviewer says what failed.', 'This makes coaching fair to Filipino callers and useful to the client: the discussion concerns accuracy and process, not accent, personality, or presumed intent.'] },
    { heading: 'Keep speaker and reviewer separate', paragraphs: ['Distinguish what the caller said, what the customer answered, and what the reviewer inferred. If the recording is unclear, mark that limitation rather than filling the gap.', 'A reviewer can then test whether the coaching point follows from the evidence or from an impression of the interaction.'] },
    { heading: 'Make the coaching point actionable', paragraphs: ['A useful recommendation might be to repeat the callback number in grouped digits, capture the refusal label, or stop before an account decision. It should identify the behavior to repeat or change.', 'Do not prescribe a personality change when the actual defect is a missing field or an unsupported promise.'] },
    { heading: 'Calibrate reviewers', paragraphs: ['Have reviewers score the same samples and compare rationales. Resolve differences by returning to the approved brief and the observable record.', 'Agreement improves when the scorecard rewards evidence, respectful handling, correct boundaries, and complete handoffs rather than a preferred accent or style.'] },
  ],
  'daily-calling-queue-reason-code': [
    { heading: 'Give each record one current purpose', paragraphs: ['A daily calling queue becomes difficult to manage when callbacks, qualification, verification, and exception work share a generic reason code. Assign the record to the purpose that explains why it is ready today.', 'The queue owner should define the result that completes each purpose and the condition that blocks it.'] },
    { heading: 'Make readiness visible', paragraphs: ['A usable reason code points to the source, required fields, approved action, and accountable owner. If the record lacks a necessary detail, mark it blocked or misrouted instead of sending it into activity.', 'This prevents callers from spending time discovering why a record should never have entered the queue.'] },
    { heading: 'Keep outcomes aligned with purpose', paragraphs: ['A callback queue should distinguish requested callback, wrong party, refusal, unreachable, and owner review. A verification queue needs field-level results. One generic completed label cannot serve both.', 'The note should explain whether the record met its original reason or needs a different lane.'] },
    { heading: 'Review queue drift', paragraphs: ['At the end of the day, compare reason code, call result, and next action. Look for records that changed purpose silently or accumulated attempts without a decision.', 'A smaller queue with clear reasons is more operationally useful than a larger queue whose volume hides misrouting.'] },
  ],
};

export function makeAug17Detail(post: typeof aug17BlogPosts[number]) {
  const seed = seeds.find((item) => item[0] === post.slug)!;
  const [, title, excerpt, question, decision, scenario, boundary, owner, published] = seed;
  return {
    published, mainKeyword: title, metaLabel: 'Philippines staffing blog',
    directAnswerHeading: `How to handle ${title.toLowerCase()}`,
    summary: `${title} is useful when a Filipino caller keeps the conversation tied to one decision: ${question} The caller preserves the person’s answer and routes ${decision} to ${owner}.`,
    takeaways: [`Start with the question: ${question}`, 'Write the caller’s evidence separately from interpretation.', `Treat ${scenario} as a review condition, not a reason to guess.`, `Use the boundary: ${boundary}.`, 'Close with a result, next action, accountable owner, and reply point.'],
    decisionTable: [
      { lane: 'Purpose', caller: `Explains why the ${title.toLowerCase()} check is happening.`, owner: 'Defines the approved audience, wording, and result.', measure: 'The person understands the reason for contact' },
      { lane: 'Evidence', caller: 'Captures the answer, refusal, request, or uncertainty in plain language.', owner: 'Decides which source and fields are sufficient.', measure: 'The note shows what was actually established' },
      { lane: 'Boundary', caller: `Stops at ${boundary}.`, owner: `Reviews the exception and owns ${decision}.`, measure: 'No guess becomes a commitment' },
      { lane: 'Handoff', caller: 'Sends purpose, evidence, open point, and requested action.', owner: `Owns the response as ${owner}.`, measure: 'The next person can act without repeating the call' },
    ],
    planningBands: [{ label: 'Question', value: 'One', note: question }, { label: 'Evidence', value: 'Named', note: 'Separate words from inference' }, { label: 'Boundary', value: 'Visible', note: 'Pause before an unsupported decision' }, { label: 'Owner', value: 'Clear', note: owner }],
    sections: authoredSections[post.slug],
    scripts: [{ title: 'Opening', text: `I am calling about ${title.toLowerCase()}. I will keep this focused on the one question we need to clarify.` }, { title: 'Clarifying', text: 'I want to record that accurately. May I repeat the point I have so far?' }, { title: 'Boundary', text: `I can record that request, but ${owner} needs to decide the next step.` }],
    workflow: [{ step: '1', title: 'Set purpose', text: 'Write the one question and intended result.' }, { step: '2', title: 'Check context', text: 'Use only the approved record details.' }, { step: '3', title: 'Listen', text: 'Capture the exact answer or uncertainty.' }, { step: '4', title: 'Route', text: 'Send the boundary condition to its owner.' }, { step: '5', title: 'Close', text: 'Save result, action, owner, and reply point.' }],
    faqs: [{ q: `What makes ${title.toLowerCase()} useful?`, a: `It links one clear question to the person’s answer, the unresolved point, and the owner responsible for ${decision}.` }, { q: 'What if the person gives an answer outside the brief?', a: 'Record it neutrally, explain the review boundary, and route it without making a promise.' }, { q: 'How should an uncertain answer be handled?', a: 'Keep uncertainty visible. Do not force it into a positive, negative, or completed label.' }],
    related: [{ label: 'Appointment setting service', href: '/services/appointment-setting' }, { label: 'Customer follow-up service', href: '/services/customer-follow-up-calls' }, { label: 'Call quality review service', href: '/services/call-quality-review' }],
    sources: [{ name: 'FCC Telephone Consumer Protection Act guidance', url: 'https://www.fcc.gov/general/telemarketing-and-telephone-consumer-protection-act' }, { name: 'FTC business guidance on data security', url: 'https://www.ftc.gov/business-guidance/privacy-security/data-security' }, { name: 'NIST Privacy Framework', url: 'https://www.nist.gov/privacy-framework' }],
  };
}
