export type Aug20Post = {
  slug: string;
  title: string;
  excerpt: string;
  minutes: number;
  published: '2026-08-20';
  focus: string;
  question: string;
  owner: string;
  angles: readonly string[];
  image: string;
};

const topics: readonly Aug20Post[] = [
  { slug: 'filipino-caller-precall-record-review', title: 'Filipino caller pre-call record review', excerpt: 'A practical pre-call review for Filipino callers that checks purpose, permissions, script version, and the right owner before dialing.', minutes: 14, published: '2026-08-20', focus: 'pre-call record review', question: 'What should a Filipino caller confirm before a record enters the live queue?', owner: 'the queue owner', angles: ['record purpose', 'source freshness', 'permission check', 'script match', 'stop condition', 'result label', 'owner route', 'daily repair'], image: '/blog-heroes/filipino-caller-precall-record-review.png' },
  { slug: 'appointment-setting-held-meeting-context-packet', title: 'Appointment setting held meeting context packet', excerpt: 'How Filipino appointment setters can leave the owner a useful context packet after a meeting is held, not just a calendar entry.', minutes: 14, published: '2026-08-20', focus: 'held meeting context', question: 'Which details make a held appointment useful to the person who will conduct it?', owner: 'the meeting owner', angles: ['meeting purpose', 'participant role', 'source notes', 'readiness signal', 'calendar boundary', 'attendance state', 'handoff packet', 'review loop'], image: '/blog-heroes/appointment-setting-held-meeting-context-packet.png' },
  { slug: 'lead-qualification-authority-signal', title: 'Lead qualification authority signal', excerpt: 'A grounded way to record who can influence a buying conversation while keeping commercial authority and commitments with the owner.', minutes: 14, published: '2026-08-20', focus: 'authority signals', question: 'How can a Filipino qualification caller record decision context without pretending to control the sale?', owner: 'the qualification owner', angles: ['role evidence', 'question sequence', 'influence signal', 'commercial boundary', 'uncertainty note', 'disposition state', 'owner handoff', 'queue learning'], image: '/blog-heroes/lead-qualification-authority-signal.png' },
  { slug: 'inbound-call-message-completeness-check', title: 'Inbound call message completeness check', excerpt: 'A message-quality routine for Filipino inbound callers that captures the details a recipient needs and stops short of unsupported urgency claims.', minutes: 14, published: '2026-08-20', focus: 'message completeness', question: 'What makes an inbound message actionable without asking a caller to decide the recipient’s priority?', owner: 'the receiving owner', angles: ['caller context', 'callback path', 'stated need', 'urgency evidence', 'privacy boundary', 'message state', 'transfer choice', 'sample review'], image: '/blog-heroes/inbound-call-message-completeness-check.png' },
  { slug: 'customer-follow-up-next-action-proof', title: 'Customer follow-up next-action proof', excerpt: 'A customer follow-up guide for proving what was agreed, what remains open, and who owns the next action.', minutes: 14, published: '2026-08-20', focus: 'next-action proof', question: 'How should a Filipino follow-up caller show that the next action came from the conversation rather than an assumption?', owner: 'the follow-up owner', angles: ['conversation source', 'customer wording', 'consent state', 'commitment boundary', 'due point', 'open loop', 'owner decision', 'trend review'], image: '/blog-heroes/customer-follow-up-next-action-proof.png' },
  { slug: 'outbound-calling-attempt-outcome-reconciliation', title: 'Outbound calling attempt outcome reconciliation', excerpt: 'A practical reconciliation method for matching outbound attempts, conversations, dispositions, and follow-up work.', minutes: 14, published: '2026-08-20', focus: 'attempt reconciliation', question: 'How can an owner tell whether an outbound queue’s results describe the actual calling work?', owner: 'the list owner', angles: ['attempt source', 'contact result', 'duplicate state', 'suppression check', 'disposition match', 'follow-up proof', 'owner exception', 'list repair'], image: '/blog-heroes/outbound-calling-attempt-outcome-reconciliation.png' },
  { slug: 'filipino-caller-training-readiness-check', title: 'Filipino caller training readiness check', excerpt: 'A readiness check that helps managers decide whether a Filipino caller can work a lane safely and consistently.', minutes: 14, published: '2026-08-20', focus: 'training readiness', question: 'What evidence should a manager review before widening a Filipino caller’s approved workload?', owner: 'the quality owner', angles: ['brief recall', 'sample accuracy', 'tone control', 'note quality', 'escalation habit', 'access scope', 'readiness decision', 'coaching plan'], image: '/blog-heroes/filipino-caller-training-readiness-check.png' },
  { slug: 'appointment-setting-attendee-readiness-note', title: 'Appointment setting attendee readiness note', excerpt: 'A focused note structure for Filipino appointment setters to capture whether a meeting participant is prepared for the agreed conversation.', minutes: 14, published: '2026-08-20', focus: 'attendee readiness', question: 'What can an appointment setter record about readiness without turning a meeting into a promise?', owner: 'the calendar owner', angles: ['participant identity', 'meeting purpose', 'preparation evidence', 'permission boundary', 'question log', 'calendar state', 'owner route', 'quality sample'], image: '/blog-heroes/appointment-setting-attendee-readiness-note.png' },
  { slug: 'customer-follow-up-unreachable-close-rule', title: 'Customer follow-up unreachable close rule', excerpt: 'A respectful close rule for customer follow-up sequences when the person cannot be reached or does not provide a next step.', minutes: 14, published: '2026-08-20', focus: 'unreachable follow-up close', question: 'When should a Filipino follow-up caller close an unreachable sequence instead of adding another attempt?', owner: 'the customer owner', angles: ['attempt history', 'contact preference', 'stop request', 'sequence limit', 'close label', 'owner exception', 'record clarity', 'routine review'], image: '/blog-heroes/customer-follow-up-unreachable-close-rule.png' },
  { slug: 'order-confirmation-quantity-discrepancy-handoff', title: 'Order confirmation quantity discrepancy handoff', excerpt: 'How Filipino confirmation callers can surface a quantity mismatch without changing fulfillment instructions or making a promise.', minutes: 14, published: '2026-08-20', focus: 'quantity discrepancy', question: 'What evidence should accompany a quantity mismatch before fulfillment decides what happens next?', owner: 'the fulfillment owner', angles: ['order source', 'readback method', 'customer correction', 'inventory boundary', 'exception label', 'handoff evidence', 'reply control', 'sample audit'], image: '/blog-heroes/order-confirmation-quantity-discrepancy-handoff.png' },
  { slug: 'database-verification-field-change-evidence', title: 'Database verification field change evidence', excerpt: 'A field-change evidence guide for Filipino callers that preserves source, requested value, and owner approval.', minutes: 14, published: '2026-08-20', focus: 'field-change evidence', question: 'How can a Filipino verification caller document a requested change without treating a spoken request as approval?', owner: 'the data owner', angles: ['field purpose', 'old value', 'requested value', 'identity boundary', 'source trace', 'change state', 'approval route', 'record audit'], image: '/blog-heroes/database-verification-field-change-evidence.png' },
  { slug: 'renewal-reminder-contact-window-exception', title: 'Renewal reminder contact-window exception', excerpt: 'A careful workflow for renewal callers when the preferred contact window conflicts with the released reminder routine.', minutes: 14, published: '2026-08-20', focus: 'contact-window exception', question: 'How should a Filipino renewal caller record a timing conflict while leaving account decisions with the owner?', owner: 'the account owner', angles: ['preference source', 'window detail', 'reminder purpose', 'consent boundary', 'exception code', 'owner route', 'reply expectation', 'process review'], image: '/blog-heroes/renewal-reminder-contact-window-exception.png' },
];

function buildBody(post: Aug20Post) {
  const [a,b,c,d,e,f,g,h] = post.angles;
  return [
    `Published 2026-08-20. ${post.title} answers a specific operating question: ${post.question} In a Philippines-based calling lane, the first responsibility is to make the work understandable before the call begins. The Filipino caller needs a released record, a stated purpose, approved fields, current wording, and a named person for exceptions. That preparation keeps a routine conversation from turning into an improvised policy decision. It also gives a manager a way to inspect the work later without relying on memory or a vague success label.`,
    `${a} is the starting point. A queue should explain why each record is present and which answer the caller is expected to obtain. A caller can read the approved context, ask the narrow question, and preserve the response. The caller should not widen the assignment because an adjacent issue sounds interesting. If the reason is missing, stale, or inconsistent with the record, pause before dialing and return the item to ${post.owner}. A clear entry test protects time and makes errors visible at the source.`,
    `Good ${b} depends on provenance rather than confidence. Record where a phone number, requested date, account note, or meeting detail came from, and distinguish a current business record from something said during the call. When sources disagree, keep the disagreement visible. Do not silently choose the value that makes the queue easier to complete. The person who owns the process can decide which source controls, whether a new check is needed, and whether the record should leave the active lane.`,
    `The caller then applies ${c} in a small sequence. State the reason for contact, ask one focused question, listen without leading the answer, and repeat the important point in plain language. The goal is not to sound impressive; it is to create a record another person can understand. A customer’s answer may be complete, partial, uncertain, or a request for something outside the brief. Those states should remain separate. A request is not consent, a preference is not approval, and silence is not agreement.`,
    `Use an explicit boundary for ${d}. Stop when identity is uncertain, a sensitive field is exposed, a customer disputes the record, a policy exception is requested, or the caller would need to make a commercial or account decision. The stop message can be simple: the caller can record the request, but ${post.owner} must decide the next step. Managers should treat a truthful pause as useful work. It prevents unsupported promises and protects the next person from inheriting a note that sounds final but has no authority behind it.`,
    `The result should make ${e} measurable. Choose labels that describe the state of the work: completed, awaiting owner, unreachable within the allowed sequence, refused, opted out, wrong record, or blocked by missing context. The exact labels belong to the business, but they should not reward optimism. A caller who records “interested” when the person only asked for information creates a misleading queue. A caller who records “awaiting owner” gives the right reviewer a fair chance to act.`,
    `A useful handoff for ${f} includes the record identifier, the relevant observed answer, the unresolved question, and the next owner. Add the customer’s exact wording only when it clarifies the decision; avoid unnecessary personal details. Keep the handoff short enough to use during a busy day, but complete enough that the recipient does not need to replay the whole conversation. Routine released actions stay with the Filipino caller. Exceptions, sensitive changes, policy interpretation, and commitments stay with the named owner.`,
    `Review ${g} on a small sample. Compare the source record, the call note, the result label, and the resulting queue state. Look for missing context, invented certainty, poor suppression handling, unclear ownership, and wording that causes customers to expect more than the business authorized. A quality check should ask what evidence supports the label, not simply whether the call was long or pleasant. When the same issue recurs, repair the brief, field list, example, or escalation route instead of asking callers to guess better.`,
    `For ${h}, keep an operating loop that fits the real work. Prepare the lane, inspect the record, make the focused contact, capture evidence, apply a truthful label, and route any open decision. At the end of the review period, count blocked records, repeated questions, missing sources, stop requests, wrong-owner routes, and corrections. Those counts are process signals, not a reason to publish unsupported performance claims. They show where the service lane needs clearer inputs or a better boundary.`,
    `A practical launch can begin with a limited sample and a named reviewer. Write the allowed fields, the opening wording, the permitted action, the stop conditions, the result labels, and the handoff destination in one brief. Let the Filipino caller practice on representative records, then inspect notes before releasing more work. Keep access limited to the systems required for that lane, and remove access when the role or assignment changes. The goal is a routine that is repeatable without pretending every situation is routine.`,
    `The customer-facing close deserves the same care as the opening. Confirm what was recorded, explain whether another person must review it, and give only a response window that the owner has approved. If no timing is known, say that the request was captured and routed. Do not use urgency, confidence, or friendliness to fill a gap in authority. This plain close is especially important for outsourced callers because it keeps the business’s promise boundary visible while still giving the customer a respectful next step.`,
    `Finally, use ${post.title.toLowerCase()} to improve tomorrow’s queue. Preserve examples of clean records and difficult exceptions, then change one part of the routine at a time. Keep the new rule beside the reason for the change so coaching does not rely on hearsay. The best daily calling systems make ordinary work easy to repeat and unusual work easy to stop. When source, evidence, ownership, and next action remain visible, Filipino callers can contribute reliable follow-up and appointment-setting work while the business keeps the decisions that require its judgment.`,
  ].join('\n\n');
}

export const aug20BlogPosts = topics.map((post) => ({ slug: post.slug, title: post.title, excerpt: post.excerpt, minutes: post.minutes, published: post.published }));
export const aug20BlogDetails = Object.fromEntries(topics.map((post) => {
  const body = buildBody(post);
  const paragraphs = body.split('\n\n');
  return [post.slug, {
    published: '2026-08-20', mainKeyword: post.title, metaLabel: 'Philippines staffing blog', directAnswerHeading: `How to manage ${post.focus}`, body,
    summary: `${post.title} gives Filipino callers and their owners a bounded way to handle ${post.focus}. It keeps evidence, uncertainty, and ownership visible so the next decision can be made without guessing.`,
    takeaways: ['Start with the stated operating question.', 'Separate observed evidence from an owner decision.', 'Use only the approved record details.', 'Keep pause conditions visible.', 'Route unresolved decisions to the named owner.'],
    decisionTable: [{lane:'Purpose',caller:'Uses the released brief and explains the immediate question.',owner:`Defines the purpose and approved outcome.`,measure:'The call has a named reason'}, {lane:'Evidence',caller:'Records the answer, refusal, uncertainty, and source.',owner:'Decides whether evidence is sufficient.',measure:'The note can be checked'}, {lane:'Boundary',caller:'Pauses at a sensitive or unsupported request.',owner:'Owns the exception decision.',measure:'No guess becomes a promise'}, {lane:'Handoff',caller:'Sends result, open point, and requested action.',owner:'Reviews and updates the workflow.',measure:'The next action has an owner'}],
    planningBands: [{label:'Question',value:'One',note:post.question},{label:'Evidence',value:'Named',note:'Record source and answer'},{label:'Boundary',value:'Visible',note:'Pause before guessing'},{label:'Owner',value:'Clear',note:post.owner}],
    sections: post.angles.map((angle, index) => ({ heading: `${angle[0].toUpperCase()}${angle.slice(1)} for ${post.focus}`, paragraphs: [paragraphs[index + 1], paragraphs[(index + 2) % paragraphs.length]] })),
    scripts: [{title:'Opening',text:`I am calling about ${post.focus}. I will keep this focused on the approved question.`},{title:'Clarifying',text:'I want to record that accurately. May I confirm the point you just described?'},{title:'Boundary',text:`I can record that request, but ${post.owner} needs to decide the next step.`}],
    workflow: [{step:'1',title:'Prepare',text:'Check the queue, source, purpose, and release rules.'},{step:'2',title:'Ask',text:'Use neutral wording and capture the answer.'},{step:'3',title:'Label',text:'Choose a truthful result and preserve uncertainty.'},{step:'4',title:'Route',text:`Send the open decision to ${post.owner}.`},{step:'5',title:'Review',text:'Compare the note with the resulting system state.'}],
    faqs: [{q:`What makes ${post.focus} useful?`,a:'It links one clear question to evidence, an unresolved point, and the owner responsible for the next decision.'},{q:'What if the record does not support the next step?',a:'Pause, record what is missing, and route the exception. Do not fill a required field with an assumption.'},{q:'What should the manager review?',a:'Review source fidelity, complete dispositions, respectful handling, and whether the caller stopped at the approved boundary.'}],
    related: [{label:'Appointment setting service',href:'/services/appointment-setting'},{label:'Customer follow-up service',href:'/services/customer-follow-up-calls'},{label:'Call quality review service',href:'/services/call-quality-review'}],
    sources: [{name:'FCC Telephone Consumer Protection Act guidance',url:'https://www.fcc.gov/general/telemarketing-and-telephone-consumer-protection-act'},{name:'FTC business guidance on data security',url:'https://www.ftc.gov/business-guidance/privacy-security/data-security'},{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'}], image: post.image,
  }];
}));

