type Topic = { slug:string; title:string; excerpt:string; lane:string; situation:string; facts:string; owner:string; forbidden:string; opening:string; detail:string };

const topics: Topic[] = [
  {slug:'filipino-caller-shift-overlap-handoff-ledger',title:'Filipino caller shift overlap handoff ledger',excerpt:'A practical ledger for passing open calls and owner questions between Filipino caller shifts without duplicating contact.',lane:'daily caller operations',situation:'one caller shift ends while callbacks and owner questions remain open',facts:'the last contact event, current state, next permitted action, named owner, due point, and suppression status',owner:'queue manager',forbidden:'restart the sequence, copy a vague summary, or assume silence means the next attempt is allowed',opening:'I am reviewing the open handoff before this queue changes shifts.',detail:'Shift overlap is safest when the incoming caller can see both what happened and what must not happen next.'},
  {slug:'live-call-escalation-wait-choice',title:'Live call escalation wait choice',excerpt:'How an outsourced caller can offer a truthful choice when an owner is not immediately available during a live escalation.',lane:'inbound call handling',situation:'a caller needs an owner decision but the escalation destination does not answer',facts:'the reason for escalation, attempted destination, attempt time, caller preference, callback route, and stated urgency',owner:'receiving team lead',forbidden:'leave the person on an indefinite hold, invent an availability estimate, or answer outside the script',opening:'The person who handles this decision is not available on the line. I can take a callback message or follow the approved alternate route.',detail:'A live escalation needs an exit choice, not an open-ended hold that transfers uncertainty to the customer.'},
  {slug:'appointment-attendee-email-correction-check',title:'Appointment attendee email correction check',excerpt:'A controlled readback for correcting an attendee email without exposing the calendar or confirming the wrong person.',lane:'appointment setting',situation:'a prospect corrects the email address intended for a meeting invitation',facts:'the meeting request, attendee name, corrected address as read back, identity state, calendar owner, and invitation status',owner:'calendar owner',forbidden:'read other attendee addresses aloud, send an invitation from an unapproved account, or treat delivery as attendance',opening:'I will read back the corrected address once and ask the calendar owner to send the approved invitation.',detail:'An email correction changes the delivery route for an invitation. It does not confirm identity, attendance, or meeting fit.'},
  {slug:'inbound-duplicate-message-linking-rule',title:'Inbound duplicate message linking rule',excerpt:'A routing rule for duplicate inbound messages that preserves new facts without creating competing owner tasks.',lane:'reception overflow',situation:'the same caller leaves a second message about an open request',facts:'both contact times, the original message identifier, changed facts, repeated facts, requested recipient, and callback preference',owner:'message queue owner',forbidden:'delete either contact event, increase urgency automatically, or create two unrelated owner assignments',opening:'I found the earlier message and will attach this update while keeping today\'s wording separate.',detail:'A repeat message can contain a useful correction even when the underlying request has not changed.'},
  {slug:'lead-qualification-competitor-mention-note',title:'Lead qualification competitor mention note',excerpt:'How to record a competitor mention as prospect context without turning a qualification call into a comparison pitch.',lane:'outbound lead qualification',situation:'a prospect names another provider while answering an approved qualification question',facts:'the question asked, the provider name volunteered, stated concern, current process, decision timing, and requested follow-up',owner:'sales owner',forbidden:'criticize the provider, claim comparative results, infer a contract end date, or improvise commercial terms',opening:'I will note the provider context in your words and keep to the approved questions for this call.',detail:'A competitor name is context supplied by the prospect, not proof of dissatisfaction or permission to make a comparison.'},
  {slug:'database-verification-deceased-contact-hold',title:'Database verification deceased contact hold',excerpt:'A respectful stop and data-owner handoff when a verification call reaches news that the named contact has died.',lane:'database verification',situation:'the person reached says the contact on the released record is deceased',facts:'the disputed contact record, statement received, relationship only if volunteered, call time, stop state, and review owner',owner:'data privacy owner',forbidden:'ask for cause or date of death, seek family details, continue the original purpose, or overwrite the record',opening:'I am sorry. I will stop this call and mark the contact record for private review.',detail:'The humane response is brief. The operational response is a restricted hold that prevents another routine call while the record owner reviews it.'},
  {slug:'event-registration-accessibility-request-route',title:'Event registration accessibility request route',excerpt:'A clear handoff for accessibility requests raised during event registration without asking the caller to judge what can be provided.',lane:'event registration calling',situation:'an attendee asks for an accessibility arrangement during registration',facts:'the attendee\'s requested arrangement in their words, event reference, contact preference, response deadline, consent to route, and assigned owner',owner:'event accessibility owner',forbidden:'question whether the request is necessary, promise availability, request a diagnosis, or place sensitive detail in a broad note',opening:'I can record the arrangement you requested and send it through the event\'s approved accessibility route.',detail:'Registration callers can capture an accommodation request accurately while the event owner handles feasibility and private follow-up.'},
  {slug:'win-back-active-dispute-exclusion',title:'Win-back active dispute exclusion',excerpt:'Why an unresolved complaint or account dispute should remove a record from routine win-back calling until an owner clears it.',lane:'win-back calling',situation:'the campaign record shows or reveals an unresolved complaint or dispute',facts:'the campaign source, dispute indicator, last known owner, customer stop wording, call time, and exclusion state',owner:'resolution owner',forbidden:'present a return offer, debate the dispute, promise resolution, or schedule another campaign attempt',opening:'I will stop the win-back conversation and send the open issue to the team responsible for it.',detail:'A win-back offer can conflict with an unresolved dispute. Exclusion keeps the campaign from speaking over work the business still owes.'},
  {slug:'renewal-reminder-autopay-uncertainty-route',title:'Renewal reminder autopay uncertainty route',excerpt:'A safe response when a customer asks whether a renewal will charge automatically and the caller cannot verify the account setting.',lane:'renewal reminder calls',situation:'a customer asks whether automatic payment is active but the released view does not prove it',facts:'the renewal reference, question asked, visible setting label, verification limit, preferred response channel, and renewal date',owner:'billing account owner',forbidden:'confirm a charge, collect payment details, change the setting, or infer enrollment from a prior transaction',opening:'I cannot verify the payment setting from this reminder view, so I will route the question to the account owner.',detail:'A reminder date and an automatic payment state are separate facts. The caller should not combine them into a billing promise.'},
  {slug:'order-confirmation-gift-recipient-privacy',title:'Order confirmation gift recipient privacy',excerpt:'A privacy boundary for confirming a gift order when the person answering is the recipient rather than the purchaser.',lane:'order confirmation calls',situation:'a gift recipient answers a confirmation call intended for the purchaser',facts:'the order reference, person reached, identity mismatch, safe callback route, disclosure limit, and stopped disposition',owner:'fulfillment privacy owner',forbidden:'name the purchaser, reveal the item, disclose payment or delivery detail, or ask the recipient to authenticate for someone else',opening:'I cannot discuss the order on this line. I will use the approved contact route for the purchaser.',detail:'A gift recipient may be connected to delivery without being authorized to hear purchaser or order information.'},
  {slug:'survey-proxy-respondent-boundary',title:'Survey proxy respondent boundary',excerpt:'A neutral stop rule when someone offers to answer a survey on behalf of the selected respondent.',lane:'survey calling',situation:'another person answers and offers opinions for the selected respondent',facts:'the sample record, person reached, proxy offer, eligibility rule, callback preference if permitted, and final disposition',owner:'survey method owner',forbidden:'accept proxy answers without an approved rule, coach the proxy, reveal prior answers, or mark the selected person as refusing',opening:'This survey needs the selected respondent under the study rules, so I cannot record answers from another person.',detail:'A helpful proxy offer is still a sampling decision. The caller should follow the study rule rather than choose whose answers count.'},
  {slug:'call-quality-silence-and-hold-scoring',title:'Call quality silence and hold scoring',excerpt:'A fair way to review long pauses and holds by checking context, notice, duration, and return rather than penalizing silence alone.',lane:'call quality review',situation:'a recorded call contains a long pause or hold whose purpose is not obvious from audio alone',facts:'the timestamp, duration, notice given, task performed, return wording, customer response, and system evidence',owner:'quality calibration lead',forbidden:'treat every silence as poor service, infer the caller abandoned the line, or award a passing score without observable evidence',opening:'I will score the hold against the stated procedure and mark any missing context as unscorable.',detail:'Silence has different meanings during a lookup, transfer, connection problem, or abandoned call. A score needs the surrounding evidence.'}
];

const sources = [
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'},
  {name:'National Privacy Commission of the Philippines',url:'https://privacy.gov.ph/data-privacy-act/'}
];

function makeDetail(t: Topic) {
  const paragraphs = [
    `${t.detail} Use this routine when ${t.situation}. In ${t.lane}, the caller's job is to preserve the record and make the next action obvious.`,
    `Start with the released call purpose and the fields the caller may use. Capture ${t.facts}. If the source and the conversation disagree, keep both versions rather than smoothing the conflict away.`,
    `Say what happened in plain language. Quote a short phrase when the exact wording affects the route. Otherwise, summarize the request without adding a motive, diagnosis, or prediction.`,
    `The caller must not ${t.forbidden}. That boundary belongs in the script, not only in a training deck, because the difficult moment happens while another person is waiting on the line.`,
    `Give the ${t.owner} a note that can be acted on without replaying the conversation. Include the record identifier, the new evidence, the unresolved decision, the requested response channel, and any real deadline.`,
    `Choose a specific queue state after the call. Awaiting owner review, correction requested, contact stopped, and closed are more useful than a generic escalated label. Add the owner and review due time.`,
    `Prepare the queue for this case before a Filipino caller encounters it. The record should show the approved purpose, the source that supplied the contact, the latest review time, and the exact instruction that applies when ${t.situation}. A caller should not have to search a training folder while the person waits. Put the usable instruction beside the record and give it a version that a quality reviewer can identify later.`,
    `Keep identity checks proportional to the conversation. The caller needs enough assurance to avoid disclosing information to the wrong person, but should not collect extra personal data merely to make the note look complete. When identity remains uncertain, record the limit and move the item to the approved hold. The ${t.owner} can decide whether another verified channel is appropriate.`,
    `The result label should describe the observed state, not the result the team hoped to obtain. A positive tone does not turn an unresolved question into approval. A quick conversation does not prove the record is correct. For ${t.lane}, reviewers should be able to trace the label to a sentence, field, or system event that supports it. If they cannot, the label needs correction before the next action is released.`,
    `Write the note for the next person who has not heard the call. Put the purpose first, then the new information, the unresolved point, and the requested response. Separate a direct statement from the caller's interpretation. If an exact phrase changes the route, preserve only that short phrase and avoid copying unrelated personal detail. A concise evidence trail is more useful than a polished narrative that hides uncertainty.`,
    `Timing belongs in the control because calling queues keep moving. Record when the contact happened, when the owner should review it, and when any approved next attempt becomes eligible. A due point is not permission to call again. The queue must also show that contact preferences and suppression checks still allow the action. This distinction prevents an old reminder from overriding a newer request to stop or change channels.`,
    `Design the escalation so it can fail visibly. If the ${t.owner} is unavailable, the item should remain in a named review state with an alternate owner or a defined next review point. Do not send the same question through several channels and hope one person acts. Duplicate escalation can create contradictory answers, while an ownerless message can disappear. One accountable route gives the caller and reviewer a clear place to check.`,
    `Daily reporting should keep activity separate from resolution. Count the conversation as contact only under the queue's definition. Count the handoff as sent when the approved route accepts it. Count the issue as resolved only after the responsible owner records a decision or completed action. These distinctions stop a busy calling day from masking open work and make the report useful to the business that owns the queue.`,
    `Quality review should examine the difficult moment, not just the greeting and close. Listen or read around the point where ${t.situation}. Check whether the caller used the released wording, captured ${t.facts}, and avoided the prohibited action. Then compare the note with the queue state. A coaching comment should identify the exact choice to repeat or repair rather than offer a broad instruction to communicate better.`,
    `A script change needs controlled release. When this case exposes unclear wording, the business owner should approve a revised line, record why it changed, and remove the superseded version from active use. Filipino callers should acknowledge the new instruction before receiving affected records. Review the first few relevant contacts under the new version, because a sentence that reads clearly in a document can still create confusion in conversation.`,
    `Access should follow the role boundary. Show the caller only the fields, communication tools, and history needed to handle ${t.lane}. Restrict exports, sensitive account views, broad customer searches, and settings that change authoritative records unless the role explicitly requires them. Limited access is not a substitute for training, but it reduces the chance that a routine call becomes an unauthorized account or policy decision.`,
    `When the owner resolves the item, preserve the original evidence and append the decision. Do not rewrite the caller's note so it appears the answer was known during the conversation. The difference between what the caller knew and what the owner later decided helps managers test the brief fairly. It also reveals whether the same exception is recurring often enough to deserve a new queue rule, system field, or owner response standard.`,
    `Review a small sample of these cases at the end of the operating period. Look for repeated missing fields, conflicting source systems, delayed owner responses, stale scripts, and attempted contacts that should have remained held. The remedy should match the defect. Repair the intake when context is absent, the route when ownership is unclear, and the script when callers interpret the same instruction differently. More calling does not repair a broken release rule.`,
    `At daily close, compare the note with the live queue. Confirm that restrictions reached the active list and that open decisions still have an owner. The note is only half the control; the system state must agree with it.`,
    `Coach this situation with one real example. Ask the caller to point to the source fact, the fact learned on the call, and the decision they deliberately left with the owner. Repair the exact field or script line that caused confusion.`,
    `For OutsourcedCallers.com teams, this split lets Filipino callers handle careful conversations and accountable notes while the client keeps authority over policy, accounts, commercial terms, sensitive data, and exceptions.`
  ];
  return {published:'2026-08-23',mainKeyword:t.title,metaLabel:'Philippines staffing blog',directAnswerHeading:`How to respond when ${t.situation}`,
    summary:paragraphs[0],takeaways:[`Record ${t.facts}.`,'Keep source data separate from the caller response.',`Route the unresolved decision to the ${t.owner}.`,'Reconcile the queue after review.'],
    decisionTable:[
      {lane:'Prepare',caller:'Checks purpose, permitted fields, and current source.',owner:'Releases the queue and boundary.',measure:'Source and script version are visible'},
      {lane:'Listen',caller:'Records the response without inference.',owner:'Defines which evidence changes the route.',measure:'Observed facts stay separate'},
      {lane:'Stop point',caller:'Uses the approved boundary and handoff.',owner:`The ${t.owner} decides the exception.`,measure:'No unsupported promise'},
      {lane:'Close',caller:'Checks the note against the queue.',owner:'Records the final decision and reason.',measure:'Queue and review state agree'}],
    planningBands:[{label:'Purpose',value:'Checked',note:t.lane},{label:'Evidence',value:'Named',note:'Source plus response'},{label:'Owner',value:'Assigned',note:t.owner},{label:'Queue',value:'Matched',note:'Final state'}],
    sections:[{heading:'Read the source before responding',paragraphs:paragraphs.slice(0,2)},{heading:'Record the difference without inventing context',paragraphs:paragraphs.slice(2,4)},{heading:'Send a decision-ready handoff',paragraphs:paragraphs.slice(4,6)},{heading:'Check the live queue at close',paragraphs:paragraphs.slice(6,7)},{heading:'Coach the boundary from a real call',paragraphs:paragraphs.slice(7)}],
    scripts:[{title:'Opening',text:t.opening},{title:'Boundary',text:'I can record the correction, but I cannot approve the account or policy change from this call.'},{title:'Close',text:`I have sent the open decision to the ${t.owner} through the approved route.`}],
    workflow:[{step:'1',title:'Check',text:'Read the released purpose and source.'},{step:'2',title:'Hear',text:'Capture the person\'s own words.'},{step:'3',title:'Separate',text:'Preserve both source and response.'},{step:'4',title:'Route',text:`Assign the decision to the ${t.owner}.`},{step:'5',title:'Match',text:'Reconcile the note and queue.'}],
    faqs:[{q:'What may the caller decide?',a:'The caller may choose the accurate call result and approved route. The business owner decides exceptions and authoritative changes.'},{q:'What belongs in the handoff?',a:`Include ${t.facts}, the unresolved decision, requested response, and named owner.`},{q:'What if the owner has not replied?',a:'Keep the record awaiting review, surface it in the exception report, and do not replace the owner decision with a caller guess.'}],
    related:[{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Inbound call handling',href:'/services/inbound-call-handling'},{label:'Call quality review',href:'/services/call-quality-review'}],sources};
}

export const aug23V8BlogPosts = topics.map((t) => ({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:10,published:'2026-08-23',image:''}));
export const aug23V8BlogDetails = Object.fromEntries(topics.map((t) => [t.slug,makeDetail(t)]));
