import { type Source, type Study } from './sep18-run2-research';

const checked = '2026-10-02';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'National Privacy Commission of the Philippines', url: 'https://privacy.gov.ph/data-privacy-act/', checked };
const tsr: Source = { title: 'Complying with the Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };

type ExpandedStudy = Study & { deepDive: string[] };

const studies: ExpandedStudy[] = [
  {
    slug: 'lead-qualification-procurement-timeline-evidence-research',
    title: 'What counts as procurement-timeline evidence in a qualification call?',
    excerpt: 'A lead-qualification study for separating a prospect’s planning context from an approved buying schedule or caller-created forecast.',
    service: 'lead qualification calls',
    decision: 'whether the prospect supplied a dated procurement constraint, a conditional planning signal, or only a caller inference that must remain unqualified',
    unit: 'one released lead, the approved timing question, the prospect’s material words, dependencies named, caller note, qualification state, sales-owner review, and later authoritative milestone',
    scenario: 'A prospect says a review could begin after the next budget meeting if a technical stakeholder supports it. The statement contains sequence and conditions, but it is not an approved purchase date.',
    failure: 'a quarter or month mentioned in conversation becomes a committed close date, a conditional dependency disappears from the note, or the absence of a date is treated as lack of interest',
    owner: 'sales or qualification owner',
    link: '/services/outbound-lead-qualification',
    sources: [tsr, calls, privacy, security, records],
    deepDive: [
      `Methodology. Start with a prospective cohort of leads whose approved qualification brief includes a timing question. Freeze the question wording, answer codes, lead-source label, and observation cutoff before review. Preserve the prospect’s relevant words, then have two reviewers independently classify the statement without seeing the later sales outcome. Compare their codes, adjudicate disagreements, and publish both the original disagreement rate and the final counts. This design tests whether the record supports a timing classification; it does not test whether the caller caused a purchase.`,
      `The central distinction is between chronology and commitment. Chronology places activities in order: security review comes before contracting, or a budget meeting follows technical evaluation. Commitment adds authorized intent and a sufficiently defined milestone. A contact may describe an organization’s normal annual planning cycle without saying this opportunity will enter it. The research should reward faithful capture of that distinction, even when the resulting handoff is less convenient for forecasting.`,
      `Use a decision table with separate columns for the event named, precision of the date, stated conditions, speaker role, source freshness, and unresolved question. Test the table with deliberately awkward examples: “maybe this summer,” “our renewal is in January,” “ask me after the board meets,” and “implementation must finish before peak season.” Each points to a different object. Reviewers should not be allowed to force all four into a single buying-time field.`,
      `Outcome analysis should follow the evidence path rather than celebrate conversion. The primary outcomes are verbatim-note fidelity, correct event classification, preservation of conditions, appropriate owner-review routing, and correction before a forecast is published. Secondary observations may include later milestone agreement and repeated-contact avoidance. A won opportunity with a distorted note is still a documentation failure; a lost opportunity with an accurate unknown date is not caller failure.`,
      `A counterfactual review can expose overstatement. Ask reviewers what conclusion would remain supportable if the later CRM stage and revenue outcome were hidden. If the original words only support “review after budget meeting,” the conclusion cannot become “purchase next quarter” merely because a deal later closed. Conversely, later delay does not invalidate a truthful target window stated at contact time. This protects the record from hindsight in both directions.`,
      `Limitations and non-claims. The cohort may reflect one script, seller, period, or lead mix; later sales records can be incomplete; and a contact may change plans after the call. Agreement between reviewers does not prove the commercial forecast is correct. This study supplies no OutsourcedCallers.com performance result, legal conclusion, conversion promise, or causal estimate. It evaluates whether one workflow keeps stated planning evidence separate from interpretation.`,
      `Niche-specific conclusion. A Philippines-based qualification lane is useful when it hands sales a traceable statement, its conditions, and the next unanswered timing question. The client should evaluate that chain before comparing pipeline-speed totals. Caller training should focus on clarifying which event a date describes and on preserving uncertainty, while forecast stages, probability, pricing, and pursuit decisions remain with the client’s sales owner.`,
      `Quality review should challenge apparent precision. A date copied from a form may predate the conversation; a month may refer to a committee meeting rather than vendor selection; a fiscal quarter may not match the calendar year. Reviewers should verify the source and object of each time expression, then mark unsupported precision as a correction opportunity. They should not coach callers to extract a date when the honest answer is that the prospect has not decided.`,
      `Operational examples need different dispositions. A prospect with an approved request-for-proposal deadline can receive a dated-evidence code. A prospect waiting for an unnamed stakeholder receives dependency captured. A prospect who refuses the question receives declined, not unknown through missing data. A person who says “not this year” supplies a boundary but no positive start date. These distinctions let sales choose follow-up without turning every statement into a forecast.`,
      `Monitor changes at the handoff boundary. If sales edits the caller’s timing field, retain the prior value, editor, reason, and new evidence. Compare correction patterns by question and source rather than ranking callers from raw counts. A concentration of edits after one ambiguous script suggests a design problem; scattered unsupported dates may suggest coaching. Both remain hypotheses until the underlying records are examined.`,
      `The final report should publish a flow from eligible timing conversations through supported dates, conditional windows, dependency-only statements, refusals, unknowns, owner corrections, and later reconciled milestones. Include counts and denominators at every branch. This presentation makes missing and uncertain evidence visible and prevents a headline percentage from implying that every lead supplied a purchase schedule.`,
      `Before launch, run calibration with sales managers using fictional but realistic call notes. Require each manager to identify the event, evidence strength, dependency, and permitted next step without seeing another manager’s answer. Disagreement reveals where the qualification brief or forecast taxonomy needs repair. Repeat calibration after material script or CRM changes, and retain the old version so historical records are interpreted under the rules that existed when they were created.`,
      `Timeline vocabulary must be coded before the study begins. Separate an event already scheduled, a target window, a prerequisite, a recurring planning cycle, an estimate, and an explicitly unknown date. “After legal review” supplies a dependency but no duration. “In Q1” supplies a broad window but may describe evaluation rather than purchase. “We need this live by March” describes a desired outcome whose feasibility and approval remain open. Reviewers should retain the prospect’s wording alongside the code so a sales owner can reverse an overconfident interpretation.`,
      `A useful evidence chain contains the question actually asked, the answer, the subject of the date, the timezone or calendar convention when material, every stated prerequisite, and the person who owns the next decision. It should also identify whether the caller offered answer choices that may have shaped the response. A forced choice between this month and next quarter is not equivalent to a spontaneous schedule. Do not infer purchasing authority merely because the speaker can describe an internal process.`,
      `Sample qualified, unqualified, deferred, and owner-review outcomes. Stratify by lead source and script version because a form field may preload an old target date that the contact later corrects. At a fixed follow-up point, compare the caller record with sales-owner review and any observable milestone, but do not grade the original statement using hindsight. A timeline can change after the call without making the note inaccurate, and a coincidental close does not validate unsupported certainty.`,
      `Report exact-date evidence, bounded-window evidence, dependency-only evidence, unknown timing, note fidelity, owner acknowledgement, and later correction separately. Forecast accuracy is a different analysis with additional assumptions about pipeline stages and elapsed time. For operations, the immediate question is whether the handoff lets sales see what is known, what remains conditional, and which next action could resolve uncertainty without repeatedly asking the prospect the same question.`,
      `The buyer control is a compact timing codebook with examples of conditional language, a field for the event being dated, a dependency field, and a verbatim evidence note bounded to the qualification purpose. Callers may clarify whether a date concerns evaluation, approval, contracting, implementation, or another stage. They should not negotiate deadlines, promise delivery, or convert a planning preference into an authorized procurement schedule. The client owns forecast rules and all commercial conclusions.`
    ]
  },
  {
    slug: 'appointment-attendee-replacement-authority-research',
    title: 'Who may replace an attendee on a scheduled appointment?',
    excerpt: 'An appointment-control study for distinguishing a requested participant change from an authorized calendar and access update.',
    service: 'appointment setting',
    decision: 'whether the caller may collect replacement details, must obtain organizer approval, or should preserve the request without changing invitations, access, or confidential context',
    unit: 'one attendee-change request, original invitation and purpose, requester identity and role, proposed participant, organizer rule, caller action, owner decision, notification state, and final attendee list',
    scenario: 'A registered participant asks a colleague to attend instead. The meeting invitation contains a private link and customer context, while the released workflow does not say that invitees may transfer their place.',
    failure: 'possession of an invitation is treated as authority to transfer it, a new participant receives context beyond the meeting purpose, or the old attendee remains active after an approved replacement',
    owner: 'calendar, meeting, or account owner',
    link: '/services/appointment-setting',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `Begin with the asset being controlled: a calendar invitation is simultaneously a time commitment, a participant roster, a delivery channel, and sometimes an access token. Replacing a person can affect each layer differently. A meeting owner may approve a roster change while requiring a new link, or accept an observer without transferring the original attendee’s decision role. The research must therefore reconstruct the change across calendar, conferencing, CRM, and host instructions instead of treating one edited name as completion.`,
      `Methodology. Select consecutive attendee-change requests during a fixed period, then enrich the sample with high-risk cases such as external domains, capacity limits, recurring meetings, and private links. Freeze a codebook for requester role, requested action, governing rule, approval event, systems changed, notices delivered, and meeting-time state. Reviewers examine the evidence available before the meeting; post-meeting attendance is analyzed later and cannot retroactively supply authority.`,
      `A rights matrix makes the operational question testable. Rows represent organizer, required attendee, optional attendee, administrative assistant, account contact, and unknown requester. Columns represent request replacement, nominate a person, disclose agenda, receive a link, remove the original participant, and change commercial purpose. The client fills the permitted intersections for each meeting class. Blank intersections route to an owner; callers do not interpret silence as permission.`,
      `Privacy review should inspect the invitation text as well as the roster. A subject line, attached brief, participant list, customer name, or conferencing transcript option can reveal more than the substitute needs. Record which fields were released and whether the replacement received a clean invitation. Forwarding the original message may be operationally fast but can carry historical replies, private addresses, or access that the meeting owner did not approve.`,
      `Analyze failure by transition. Request-to-review failure means the owner never received a usable packet. Review-to-calendar failure means an approved decision was not represented correctly. Calendar-to-access failure leaves stale links or permissions. Access-to-notification failure means affected people were not told. This sequence differs from a generic handoff funnel because the original attendee may need removal at several points and because reversal must remain possible until the meeting starts.`,
      `Limitations and non-claims. Calendar logs may omit forwarded links, a platform may not expose access history, and the meeting owner may approve changes outside the observed systems. A person’s attendance does not establish authorization or suitability. Results from one meeting class do not transfer automatically to interviews, clinical appointments, sales demos, or public events. The study reports control evidence, not legal advice or a promise that a meeting will occur.`,
      `Niche-specific conclusion. An outsourced appointment setter should have bounded authority to capture a proposed replacement and execute only the system changes released for that meeting class. The buyer should judge whether the roster, access, notices, and owner decision reconcile—not merely whether a new invitation was sent. Eligibility, confidentiality, capacity, and changes to meeting purpose remain client decisions.`,
      `Reversal deserves an explicit test. If an organizer rejects the replacement or the requester withdraws it, the workflow should restore the correct participant state without reviving an exposed link or deleting the evidence trail. Review whether reminders, waiting-room permissions, recording consent, and host notes follow the reversal. A process that handles approval but cannot safely undo a pending change is not ready for delegated execution.`,
      `Time pressure should not silently expand authority. Compare requests received days in advance with those arriving minutes before the meeting. Late requests may justify a faster escalation channel, but they do not make an unapproved substitute eligible. Record owner response windows and what the caller tells the requester while waiting. “I have sent this for review” is supportable; “your colleague is confirmed” is not until the required systems and owner decision agree.`,
      `Accessibility and interpretation requests require careful classification. A support person or interpreter may be necessary for participation without replacing the invited decision-maker. The meeting owner should define whether that person is added, what context they receive, and whether consent or confidentiality steps apply. Treating every additional person as a transferable attendee can block access or expose information, so the research codes these requests separately.`,
      `The report should show request types, governing-rule availability, approvals and denials, pending states at cutoff, systems reconciled, stale-access findings, and notification outcomes. Break results down by meeting class and requester role where sample sizes permit. Do not publish a single replacement-success rate that rewards unreviewed changes or hides cases where the meeting proceeded with an outdated roster.`,
      `Pilot release should be narrow. Let setters capture every request but execute replacements only for one low-risk meeting class with explicit organizer rules. Sample the resulting calendar and access states daily, review exceptions with the meeting owner, and expand only when reversals and late requests are handled consistently. This staged approach tests the actual systems while preventing a broad permission grant from becoming the accidental policy for every appointment type.`,
      `Reviewers should also examine the meeting-purpose handoff. A replacement may have the right calendar access but lack the background, authority, or preparation expected of the original participant. The setter can ask approved logistical questions and pass the answer to the host; deciding whether the substitute satisfies the business purpose remains with the owner. Record that decision separately from the mechanical success of sending an invitation.`,
      `Define replacement, addition, forwarding, and substitution as different events. A replacement removes or deactivates one participant and adds another under an approved rule. An addition expands the audience. Forwarding may expose a link without changing the authoritative roster. Substitution can also change the person expected to make a decision. The study should observe which event was requested and which event the calendar ultimately recorded; a generic “attendee updated” code conceals important differences.`,
      `Authority depends on meeting type and source, not caller confidence. An organizer may permit open registration transfers, require account-owner approval, or prohibit changes after identity checks or capacity deadlines. A participant can accurately name a colleague without being allowed to share customer information or private access links. The caller should identify the released rule and route exceptions. Where no rule exists, the appropriate state is pending owner decision rather than silent acceptance.`,
      `Test ordinary substitutions alongside edge cases: external-to-internal replacement, a different company domain, a meeting with limited seats, a regulated or sensitive topic, a disabled original account, a calendar series, and a request made shortly before start time. Record whether the conferencing platform, calendar, CRM, reminders, and host roster agree after the decision. A corrected invitation is incomplete evidence if the original private link remains usable against policy.`,
      `Measures should include request classification, authority-source availability, minimum-data collection, organizer acknowledgement, roster reconciliation, access revocation where required, notification delivery, and unresolved changes at meeting time. Attendance alone is not proof that the change was authorized. Conversely, an approved substitute may fail to attend for reasons unrelated to the caller. Report both control completion and meeting outcome without merging them into one success label.`,
      `A buyer-ready packet names transferable meeting types, permitted requester roles, fields needed for the proposed attendee, information that must not be forwarded, approval owners, cutoff times, notification rules, and the system that controls access. Appointment setters can preserve the request and execute bounded changes after approval. The client retains decisions about confidentiality, capacity, participant eligibility, and whether a replacement changes the meeting’s commercial purpose.`
    ]
  },
  {
    slug: 'order-delivery-address-correction-evidence-research',
    title: 'What evidence supports a delivery-address correction on a confirmation call?',
    excerpt: 'An order-confirmation study for separating a customer correction from identity, payment, fulfillment, and delivery decisions.',
    service: 'order confirmation calls',
    decision: 'whether the caller may record a proposed address correction, which verification and readback are required, and when fulfillment or fraud review must decide the executable order state',
    unit: 'one address-change request, original order version, approved verification path, proposed fields, material customer wording, caller readback, owner acceptance, carrier state, and final fulfillment address',
    scenario: 'A customer notices a missing apartment number after ordering, but the shipment may already be allocated and the calling workflow does not authorize the caller to override fraud or carrier controls.',
    failure: 'a plausible correction bypasses identity checks, free-text notes diverge from structured address fields, the caller promises rerouting after carrier cutoff, or unnecessary personal details are copied into the research record',
    owner: 'commerce, fraud, or fulfillment owner',
    link: '/services/order-confirmation-calls',
    sources: [privacy, security, dpa, records, tsr],
    deepDive: [
      `Methodology. Build the cohort from orders where a customer requests any destination change during confirmation, including requests the agent cannot execute. Freeze correction categories, order-state snapshots, verification outcomes, system fields, and observation cutoff. Trace each request from the original order through the proposed address, authorized decision, printed label, carrier event when available, and customer notification. Reviewers should compare structured values field by field rather than relying on a narrative note that says the address was fixed.`,
      `The analysis begins with change magnitude. Normalizing capitalization differs from adding a unit; adding a unit differs from changing a street; changing a street differs from changing recipient or country. Each can trigger different tax, fraud, inventory, serviceability, or cutoff consequences. The client’s release matrix should say which category a caller may enter, which only an owner may approve, and which requires cancellation and a new transaction.`,
      `Design a reconciliation grid with rows for recipient, organization, street lines, locality, region, postal code, country, delivery instructions, and contact channel. Columns show original value, customer-proposed value, standardized candidate, approved value, fulfillment value, and carrier-visible value. This grid exposes partial updates, such as a corrected apartment number in CRM but not on the warehouse label, without copying unrelated order history into the study.`,
      `Use scenario tests before reviewing production outcomes. Include a transposed digit, missing apartment, postal-code conflict, rural address, unsupported country, recipient change, safe-delivery instruction, and a request after label creation. Ask agents to explain what they can record, what they can promise, and which owner receives the exception. The goal is consistent boundary recognition, not memorizing a single “correct address” script.`,
      `Outcome reporting should distinguish faithful request capture, successful verification, authorized acceptance, system synchronization, label reconciliation, customer acknowledgement, and eventual delivery evidence. A delivered parcel can mask an unauthorized change; an authorized correction can still fail because of carrier or customer factors. Repeat-contact and cancellation rates are useful secondary signals only when denominators retain every change request, including rejected and unresolved ones.`,
      `Limitations and non-claims. Carrier scans may be unavailable or ambiguous, address-standardization tools can change over time, and fulfillment staff may act outside the observed system. Delivery does not prove that verification or approval was proper. This protocol does not determine fraud liability, tax treatment, carrier responsibility, or legal compliance, and it reports no OutsourcedCallers.com delivery or accuracy result.`,
      `Niche-specific conclusion. For order-confirmation outsourcing, the defensible product is a reconciled change record: what the customer asked, which verification path passed, who accepted the executable change, and whether downstream fields matched. A caller can perform careful capture and readback. The client must own fraud rules, commercial effects, carrier escalation, and irreversible fulfillment decisions.`,
      `Readback should be observed as a sequence, not a checkbox. The caller states the recipient and complete proposed destination from the approved structured fields, invites correction, and explains that final acceptance depends on the current order state. Review whether the customer affirmed the material change and whether the note preserves ambiguity. Repeating a malformed system suggestion quickly is not meaningful confirmation.`,
      `Test competing-source cases. The customer may cite a saved profile while the order contains a one-time destination; the commerce system may differ from the carrier validation tool; a marketplace order may restrict merchant edits. The workflow needs a source hierarchy for each state. Agents should record the conflict and route it rather than selecting the address that appears newest or most complete.`,
      `Security analysis should look for overcollection in both production notes and exports used for review. Full payment numbers, identity answers, unrelated purchase history, and copies of documents are unnecessary for comparing address-state transitions. Use pseudonymous order identifiers and access controls. Deletion schedules should account for the purpose of the study and any separate operational retention rule without assuming that keeping more data improves evidence.`,
      `Present a reconciliation table by correction class and order state: requests received, verification completed, accepted changes, rejected changes, cutoff conflicts, labels matched, customer notices, delivery evidence, and unknowns. This makes process constraints visible. A high acceptance percentage among only early, simple formatting changes should not be generalized to late street or country changes.`,
      `Pilot with reversible cases and a shadow comparison. The agent records the proposed correction and readback, while an authorized fulfillment owner independently determines the executable change. Compare their field-level results and reasons before granting any bounded edit permission. Continue sampling after release because catalog, carrier, and fraud-system changes can alter the boundary even when the calling script remains unchanged.`,
      `Customer communication should reflect the last confirmed operational state. If fulfillment has accepted the edit but no new label exists, say that the change was accepted for processing rather than shipped to the new address. If cutoff review is pending, identify the review without promising rerouting. Sampling these phrases against system events helps distinguish accurate bounded updates from well-intended assurances that the evidence cannot support.`,
      `Owner review should record reasons consistently: verification failure, prohibited change class, cutoff passed, carrier restriction, tax or price effect, suspected fraud, customer withdrawal, or source conflict. These codes help buyers see whether failures arise from calling quality or from downstream constraints. Free-text explanation can supplement the code, but it should not contain extra personal information or replace the authoritative order-state update.`,
      `Model the order state at contact time. A correction before payment review, a change after authorization, a warehouse release, and a carrier intercept are operationally different. The caller needs an authoritative status and a bounded action for that status. A note that says “address changed” is misleading when the caller only captured a request. Preserve the old and proposed structured fields, the order version, and the system or owner that made the final executable change.`,
      `Verification should be proportional and defined by the client. The research record needs evidence that an approved path passed, not the secret answers or full payment details used in that path. Caller ID, knowledge of an order number, or a familiar voice may contribute context but should not silently become authorization. If a proxy calls, record the relationship and route rather than assuming that possession of delivery details permits a change.`,
      `Address quality is not the same as authority. Standardization software may correct abbreviations or postal formatting, but it cannot establish that the customer requested the destination or that fulfillment can accept it. Compare the proposed address, standardized candidate, customer readback, and final label as separate states. When the tool returns several candidates, the caller should not choose based on appearance unless the released workflow expressly permits that bounded selection.`,
      `Measure verification-path completion, structured-field fidelity, readback completeness, owner acknowledgement, cutoff disclosure, final-label reconciliation, preventable repeat contacts, and unauthorized or failed changes. Separate correction type: formatting, unit addition, street change, recipient change, and country or region change. Risk and operational options differ. Report unknowns when the final carrier record is unavailable rather than treating an internal accepted status as delivery proof.`,
      `The operating control set includes order states, allowed correction classes, approved verification, prohibited data capture, structured address fields, normalization review, carrier cutoffs, price or tax escalation, owner queues, and customer-safe status language. Outsourced callers can make the requested correction legible and route it quickly. The client remains responsible for fraud policy, tax and shipping effects, carrier claims, irreversible fulfillment actions, and any guarantee about delivery.`
    ]
  },
  {
    slug: 'inbound-wrong-account-callback-routing-research',
    title: 'How should inbound teams handle a callback tied to the wrong account?',
    excerpt: 'An inbound-call study for routing a legitimate callback request without confirming another customer’s relationship or exposing case details.',
    service: 'inbound call handling',
    decision: 'whether the caller can be matched through an approved path, should receive a neutral intake route, or must be transferred without confirming the account suggested by phone number, ticket, or prior note',
    unit: 'one inbound callback, the presented reference, claimed identity and purpose, account candidate, verification outcome, disclosure class, route, owner receipt, correction, and final resolution',
    scenario: 'A caller returns a missed call from a shared business number, but the CRM opens a different person’s record because that number appears on more than one account.',
    failure: 'the screen-pop is treated as identity, the agent reveals a name or case to clarify the mismatch, the legitimate caller is discarded as a wrong party, or a correction overwrites evidence needed to repair the duplicate link',
    owner: 'service, account, or privacy owner',
    link: '/services/inbound-call-handling',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `The study starts from an information asymmetry: the interface may confidently display a customer while the human caller knows only that they received or returned a call. A safe workflow must let the agent help without testing the displayed identity through revealing questions. This makes neutral language an operational control, not a courtesy. The evidence review should examine the words used before any approved match, because later verification cannot erase an earlier disclosure.`,
      `Methodology. Capture consecutive inbound callbacks that produce multiple account candidates, a failed candidate, or a caller dispute. Add a blinded audit sample of callbacks the system labeled as clean. Freeze codes for candidate source, neutral opening, identifiers requested, match result, disclosures, temporary restrictions, route, owner acknowledgement, correction action, and final resolution. Reviewers first assess the transcript up to the match decision, then reveal downstream records.`,
      `A conversation map should branch on purpose before account detail. The caller can identify the organization reached, ask for a non-sensitive reason, and offer an approved secure route. If the person supplies a reference, the agent checks it without reading back candidate information. A failed match leads to no-match intake or transfer, not increasingly specific hints. Emergency and accessibility paths should be separately released so neutrality does not become abandonment.`,
      `Root-cause work happens after the safe interaction. Compare callback number fields, communication preferences, outbound attempt logs, duplicate contacts, forwarding rules, and corrections using pseudonymous identifiers. Keep hypotheses separate: a shared line is not reassignment; a duplicate record is not spoofing; an old callback field is not proof that the caller is unauthorized. Owners should record the evidence used when merging, separating, or restricting records.`,
      `Outcomes form two families. Interaction outcomes include unnecessary disclosure, safe-route completion, caller abandonment, and repeat contact. Data outcomes include candidate correction, duplicate resolution, source-lineage preservation, and later false match. Report them independently. A fast successful route may still disclose another person’s relationship, while a cautious unresolved route may protect privacy but reveal a process gap that needs owner attention.`,
      `Limitations and non-claims. Recordings can start late, caller ID can be missing or manipulated, and account owners may correct data beyond the review window. Neutral wording cannot guarantee that a caller infers nothing from context. The study cannot establish identity, intent, or legal compliance and makes no claim about OutsourcedCallers.com error rates. It evaluates whether a defined callback workflow contains mismatches safely.`,
      `Niche-specific conclusion. An inbound outsourced team needs a deliberately useful no-match state, not pressure to attach every call to a customer. Buyers should inspect neutral openings, minimum match fields, correction ownership, and preservation of the original link. Agents may capture purpose and route uncertainty; the client controls identity policy, account merges, disclosures, and durable correction.`,
      `Language testing should include indirect confirmation. Phrases such as “that account is closed,” “she is not listed here,” or “the ticket number belongs to someone else” reveal relationships even when the agent refuses details. Reviewers should compare these with neutral alternatives that acknowledge a mismatch without naming the candidate. Score whether the interaction still offers a practical path so privacy protection is not achieved by simply ending difficult calls.`,
      `Correction quality requires provenance. When an owner changes a phone field or separates duplicate accounts, retain the source that supported the action, the previous link, the effective time, and any queue restrictions lifted or added. The caller’s mismatch report remains an observation, not authority for deletion. Later reviewers need to see whether the repair addressed the same identifier and prevented another incorrect callback.`,
      `Test service continuity after no-match intake. Measure whether a legitimate caller reaches an appropriate general queue, secure callback process, or named owner; whether the bounded purpose survives transfer; and whether the caller must repeat sensitive context. A neutral workflow that never resolves valid requests imposes a different harm. Report safe resolution and privacy failures together without treating either as a complete proxy for the other.`,
      `The final analysis should show candidate source, mismatch category, disclosure result, route, acknowledgement, correction, repeat contact, and unresolved state. Include the clean-match audit denominator to estimate interface blind spots. Avoid a leaderboard by agent unless exposure and system behavior are comparable; the central decision is whether workflow controls contain an uncertain match and create an accountable repair path.`,
      `A controlled pilot should seed synthetic duplicate and shared-number scenarios alongside ordinary calls, without placing real customer data in training records. Review whether agents use neutral language, choose the no-match state, preserve the stated purpose, and reach the correction owner. Repeat after interface changes because a new screen-pop or autocomplete feature can reintroduce confident but unsupported matching even when the written procedure has not changed.`,
      `Supervisors need a correction loop that does not punish safe uncertainty. Review a sample of no-match outcomes, identify whether better released sources could have resolved them, and repair interface or routing gaps before changing agent targets. If productivity measures reward attached accounts, agents may guess to avoid an unresolved code. The buyer should align metrics so correct containment and useful routing count as legitimate outcomes.`,
      `Document the customer-safe closure for each branch. A matched caller receives only the information and action permitted after the approved check. An unmatched caller receives a general route or secure callback option. A suspected data defect receives a reference that does not expose another account. Clear closure language reduces repeated explanation while keeping account repair and identity decisions with authorized owners.`,
      `Start with a neutral-response protocol. A displayed account, inbound number, reference string, or recent outbound attempt is a candidate link, not proof of identity or authority. The caller should ask only the approved minimum needed to find a safe route and avoid questions that reveal the candidate record. “Which organization were you trying to reach?” is different from naming the customer shown on screen. The study should code both direct disclosures and indirect confirmations created by phrasing.`,
      `Classify mismatch causes without forcing certainty: shared household or business line, recycled number, data-entry error, duplicate record, forwarded call, proxy contact, outdated callback field, spoofed caller ID, or unknown. The calling agent can preserve the observed conflict and apply a temporary routing state. Durable merge, deletion, identity, and account-ownership decisions belong to a data or account owner with access to authoritative sources and a correction trail.`,
      `Build the cohort from inbound callbacks that open multiple candidates or fail the expected match. Include resolved calls, safe transfers, abandoned contacts, unverifiable references, and corrections made later. Audit a sample of apparently clean matches for hidden duplicates so the observed mismatch rate does not merely describe what the interface flags. Keep the original link visible in the study copy as a pseudonymous event; otherwise later cleanup erases the condition being evaluated.`,
      `Report neutral-intake adherence, unnecessary disclosure, safe-route completion, owner acknowledgement, duplicate-link correction, repeated contact, unresolved callback, and false mismatch. Resolution time should pause only under a predeclared rule and should not hide time waiting for an authorized owner. A quick transfer can still be poor if it reveals the wrong relationship, while a bounded unresolved outcome can be appropriate when no secure match is available.`,
      `The practical control is a candidate-account warning, a neutral intake script, a minimum matching path, an explicit no-match state, temporary suppression where relevant, and a correction queue that preserves source lineage. Buyers should test shared numbers and duplicated identifiers before launch. Filipino inbound callers can collect a bounded purpose and route uncertainty; the client owns account matching, identity policy, correction approval, and disclosure permissions.`
    ]
  },
  {
    slug: 'renewal-reminder-payment-pending-state-research',
    title: 'How should renewal reminders treat a payment that is still pending?',
    excerpt: 'A renewal-state study for avoiding duplicate pressure or unsupported coverage claims while a payment event remains unresolved.',
    service: 'renewal reminder calls',
    decision: 'whether the approved source supports pausing reminders, communicating a bounded pending status, or escalating a conflict to billing or the account owner',
    unit: 'one renewal record, payment-event identifier and timestamp, reminder state, source versions, customer statement, caller wording, owner review, settlement or failure event, and final renewal status',
    scenario: 'A customer says payment was submitted, while the billing dashboard shows a pending transaction and the reminder queue still marks the renewal unpaid.',
    failure: 'pending becomes paid, unpaid becomes failed, repeated reminders continue during an approved review pause, or the caller promises uninterrupted service without a governing source',
    owner: 'billing, contract, or account owner',
    link: '/services/renewal-reminder-calls',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `Begin by separating the two clocks. Payment processing moves through processor or bank events; renewal administration moves through contract and account events. They may update on different schedules and neither automatically controls the other. The caller-facing screen should show the approved statement for the observed combination, such as payment pending and reminder paused, rather than compressing both clocks into a reassuring or threatening conclusion.`,
      `Methodology. Identify every renewal record that enters a pending-payment state during a fixed intake window. Preserve the payment-event token, timestamps, source version, account state, queue decision, contact attempt, customer statement, owner action, and final state through a predeclared follow-up cutoff. Review a stratified set of settled, failed, reversed, long-pending, and conflicting-source cases. Do not exclude records simply because the final answer is unavailable.`,
      `Construct a state-transition diagram from observed evidence. Allowed payment transitions might include initiated to pending to settled, or pending to failed, but the client must define the source of truth and exceptional routes. Renewal transitions may pause while billing reviews a discrepancy. Reviewers flag impossible jumps, overwritten states, missing event times, and reminders sent from a stale snapshot. The diagram is descriptive until the responsible owners approve it as policy.`,
      `Customer wording belongs in a separate channel. “I paid yesterday,” “my bank shows a charge,” and “I scheduled a transfer” are materially different, yet none alone establishes the platform’s settlement state. The caller should preserve the bounded statement and reference already supplied without soliciting secret banking information. Billing can then reconcile the statement against authorized systems while the reminder queue follows a released pause rule.`,
      `The main outcomes are correct source attribution, faithful pending-language, timely pause, absence of duplicate pressure during review, owner acknowledgement, state reconciliation, and correct restart or closure. Show time distributions by terminal state because a single average hides long unresolved tails. Report customer complaints and repeat contacts as consequences, not proof of the underlying payment event or of caller intent.`,
      `Limitations and non-claims. Processor feeds may lag, reversals can occur after the cutoff, and contract status may change through unobserved owner action. A settled payment does not prove earlier reminder wording was accurate; a failed payment does not justify stating failure while only pending evidence existed. This study offers no financial or legal advice, no continuity guarantee, and no OutsourcedCallers.com collection-performance claim.`,
      `Niche-specific conclusion. Renewal-reminder outsourcing works best when callers communicate the narrow state an approved source supports and stop at billing or contract boundaries. Buyers should test pause propagation, conflict routing, and restart evidence before scaling contact volume. Callers can reduce repeated pressure through disciplined records; the client retains settlement interpretation, fees, service status, and every financial commitment.`,
      `Queue behavior should be tested at event boundaries. Observe what happens when pending appears after a reminder is already assigned, when settlement arrives during a call, when failure follows a long pause, and when a reversal occurs after apparent renewal. The system needs deterministic rules for cancelling, pausing, or regenerating work. A caller refreshing one screen cannot compensate for stale batches created elsewhere.`,
      `Wording review should distinguish source report from account consequence. “The billing system shows pending as of 10:15 UTC” is bounded. “Your renewal is complete” or “service will continue” adds conclusions that may require contract evidence. Review whether the agent names the next responsible team and avoids requesting payment again while an approved pause is active. Customer reassurance must remain truthful even under pressure to reduce handle time.`,
      `Exception ownership should be measurable. Each conflict packet needs the payment reference token, observed states and times, customer’s bounded statement, contact status, and precise decision requested. Track acknowledgement and resolution separately. Returning a task to the reminder queue without resolving the conflict is not owner completion, and a queue closure without an authoritative state should remain unknown in the research results.`,
      `Publish a transition report with intake counts, source conflicts, pauses applied, contacts prevented, contacts made, owner receipts, settled, failed, reversed, still-pending, corrected, and unknown outcomes. Show elapsed-time bands rather than one mean. This reveals whether late tails or one integration drive repeated reminders and supports a targeted control change instead of broad caller coaching.`,
      `Pilot the control with a shadow queue that calculates which reminders would pause without automatically suppressing them. Billing owners review disagreements between the current queue and proposed state rules, then authorize a limited live release with daily reconciliation. Record false pauses and missed pauses separately. This tests whether the rule protects customers from duplicate pressure without allowing unresolved records to disappear from accountable review.`,
      `Governance should include an expiry for the pause. Expiry does not mean the caller can declare failure; it means the record returns to a named review state with fresh source checks. Define who can extend, close, or restart contact and what evidence each action requires. This prevents indefinite pending records while avoiding an automatic reminder that ignores an unresolved payment event.`,
      `Audit customer-contact history after reconciliation. When a payment settles, confirm that obsolete reminder tasks close and the customer receives only any approved status update. When it fails or reverses, ensure the next communication uses the new source time and permitted wording rather than replaying the original pending script. This final check tests whether resolution propagates through the whole contact workflow.`,
      `Training examples should include partial evidence and uncomfortable unknowns, not only clean settlements. Agents practice naming the observed source and time, preserving the customer’s statement, applying the released pause, and requesting one owner decision. Reviewers then check whether the call avoided duplicate collection pressure without implying that payment, renewal, coverage, or account standing had already been resolved.`,
      `Define payment and renewal states independently. Initiated, authorized, pending, settled, failed, reversed, refunded, disputed, and unknown describe payment evidence. Approaching renewal, due, active, grace, suspended, expired, and cancelled describe the account or contract. A workflow that collapses both into “paid” or “unpaid” invites unsupported statements. The caller should identify the state visible in the approved source and avoid interpreting what that state guarantees about service.`,
      `The study needs event provenance: payment reference token, source system, event time, last update time, reminder-queue snapshot, and any client rule that pauses contact. Do not copy card, bank, or authentication data. A customer statement that payment was submitted is material evidence for routing but not system settlement. Likewise, a pending platform event is not proof that the customer’s bank completed or rejected the transaction.`,
      `Observe all pending states entering the reminder queue during a fixed period. Follow them until a predeclared cutoff and retain settled, failed, reversed, still-pending, corrected-record, and unavailable outcomes. Compare whether reminder suppression happened before another attempt, whether an owner received the conflict, and whether later messages reflected the new state. Long-running unknowns must remain in the denominator because excluding them makes reconciliation appear stronger.`,
      `Key measures include state-statement fidelity, review-pause application, duplicate reminder after pause, owner acknowledgement, time to authoritative update, final reconciliation, and unsupported assurance. Conversion or retained revenue does not validate the communication. A customer may pay after inaccurate pressure, and a correct bounded call may not produce immediate settlement. Separate operational evidence quality from the commercial outcome.`,
      `A buyer should release a payment-state dictionary, source hierarchy, pause and restart rules, customer-safe wording, conflict owner, expected response interval, and prohibited claims about fees, coverage, service continuity, or settlement. Callers can repeat an approved status, preserve the customer’s material statement, and route discrepancies. Billing and contract owners retain interpretation, account corrections, service decisions, and every financial commitment.`
    ]
  }
];

export const oct02ResearchPosts = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: '2026-10-02' as const,
  image: '/thank-you-hero.png',
  body: [
    ...study.deepDive,
    `Sources: ${study.sources.map((source) => `${source.title} | ${source.publisher} | ${source.url} | checked ${source.checked}`).join(' || ')}`,
  ],
  handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this research to define evidence, decision boundaries, and owner handoffs before planning ${study.service} with a Philippines-based team.` },
}));
