import { type Source } from './sep18-run2-research';

const checked = '2026-10-05';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'National Privacy Commission of the Philippines', url: 'https://privacy.gov.ph/data-privacy-act/', checked };
const tsr: Source = { title: 'Complying with the Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls/Texts - Phone', publisher: 'Federal Communications Commission', url: 'https://consumercomplaints.fcc.gov/hc/en-us/articles/115002234203-Unwanted-Calls-Texts-Phone', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };
const aapor: Source = { title: 'Best Practices for Survey Research', publisher: 'American Association for Public Opinion Research', url: 'https://aapor.org/standards-and-ethics/best-practices/', checked };

type Article = {
  slug: string;
  title: string;
  excerpt: string;
  service: string;
  link: string;
  sources: Source[];
  body: string[];
};

const articles: Article[] = [
  {
    slug: 'lead-qualification-budget-currency-evidence-research',
    title: 'Which currency does a qualification-call budget actually describe?',
    excerpt: 'A lead-qualification study for preserving currency, period, scope, tax treatment, and uncertainty before a budget statement enters a sales handoff.',
    service: 'lead qualification calls',
    link: '/services/outbound-lead-qualification',
    sources: [tsr, calls, privacy, security, records],
    body: [
      `A budget figure is not usable evidence until the record identifies what the number measures. A prospect may say “fifty thousand” while thinking in local currency, an annual department ceiling, a monthly operating allowance, or an implementation phase that excludes licenses and taxes. A caller who stores only 50,000 creates apparent precision while discarding the dimensions a sales owner needs. This research asks whether a Philippines-based qualification workflow can preserve those dimensions without turning the caller into a pricing adviser or forcing a prospect to disclose information they do not have.`,
      `Methodology. Build a prospective cohort of qualification calls in which the approved brief permits a budget question. Freeze the exact question wording, permitted follow-ups, currency codes, period codes, scope fields, refusal code, and escalation rule before collection. The observation unit is one budget exchange linked to the released lead, script version, caller note, and sales-owner review. Two reviewers independently reconstruct what the prospect actually supplied, then compare that reconstruction with the structured handoff. Later opportunity value stays hidden during the first review so hindsight cannot upgrade an ambiguous statement.`,
      `The evidence model should separate six objects: the numeric amount or range, currency, time basis, covered items, source of the figure, and approval state. “Our team spends about 5,000 a month” supplies an estimate and period but may not identify currency or the services included. “The board approved USD 60,000 for the project” supplies stronger approval language but still leaves allocation and timing questions. “That sounds expensive” contains price sensitivity, not a budget. Reviewers should preserve the prospect’s material words beside every code so sales can see where classification ends and interpretation begins.`,
      `Use deliberately mixed test cases during calibration. One prospect reads a website price in dollars but answers from a Philippine-peso operating plan. Another gives a quarterly amount including advertising, while the proposed calling work is only one line. A third contact names a ceiling but says procurement has not approved it. A fourth declines to discuss budget and asks for a capability outline. Each case needs a different state. The goal is not to extract a number from every person; it is to prevent unlike statements from becoming one comparable field.`,
      `Primary measures should include currency explicitly captured, period explicitly captured, covered scope recorded, conditional language retained, refusal distinguished from unknown, approval language attributed to the speaker, and sales-owner correction. Report complete evidence chains and each missing dimension separately. Do not grade success by how many leads have a number, because that rewards invented precision. A defensible unknown with a clear next question is more useful than an unsupported amount that quietly distorts forecasting, routing, or salesperson preparation.`,
      `A counterfactual audit can expose hindsight bias. Ask what a reviewer could conclude if the later proposal, exchange rate, and deal outcome were removed. If the original call supports only “approximately 50,000 for the initiative,” the record cannot later become “USD 50,000 annual approved budget” because a proposal happened to use those terms. Conversely, a deal that does not proceed does not invalidate an accurately recorded statement. The study concerns evidence fidelity at the call boundary, not whether the prospect predicted future procurement correctly.`,
      `Currency conversion should remain outside the caller’s evidence field. If the client wants a normalized planning value, retain the original amount, currency, exchange-rate source, rate timestamp, conversion method, and person or system responsible. Never overwrite the prospect’s figure with a converted estimate. Exchange rates move, card or bank rates differ, and tax treatment may change the commercial comparison. The caller may clarify which currency the speaker means when the approved script allows it; selecting a convenient currency from phone country code, accent, company address, or caller location is inference.`,
      `Privacy and proportionality matter because budget questions can reveal internal plans. The study copy should contain only the minimum statement and workflow fields needed for classification, with pseudonymous record identifiers and bounded reviewer access. The NIST Privacy Framework offers a voluntary structure for managing privacy risk, while FTC security guidance emphasizes knowing what personal information is held, limiting retention, and restricting access. Those sources support control design; they do not establish that every budget figure is personal information or decide the duties of a particular campaign.`,
      `Operationally, the caller needs a compact sequence: ask the released budget-context question, repeat the amount only when clarification is permitted, ask which currency and period the amount describes, preserve named inclusions or conditions, and stop when the person declines or lacks the answer. The caller should not argue about affordability, convert currencies, recommend a package, imply approval, or mark a lead unqualified unless the client’s released rule explicitly supports that action. Pricing, fit, probability, and pursuit remain sales-owner decisions.`,
      `The final report should show eligible exchanges, stated amounts, ranges, explicit currencies, explicit periods, scope-qualified figures, approval-qualified figures, refusals, unknowns, caller inferences corrected by owners, and cases still unresolved at cutoff. Break down results by script version and lead source where sample sizes allow. Publish denominators for every rate. A single “budget captured” percentage conceals whether the captured values mean the same thing and encourages downstream users to compare figures that were never commensurable.`,
      `Owner review should use a correction taxonomy rather than silently replacing caller notes. Separate wrong currency, missing period, unsupported approval, mixed scope, transcription error, changed prospect position, and sales-added interpretation. Retain the earlier value, editor, time, reason, and evidence. This distinguishes a coaching need from a weak question or a later commercial judgment. Repeated corrections on one dimension can justify changing the brief; scattered changes after new evidence do not necessarily show that callers performed poorly.`,
      `Timing also affects meaning. A budget described for the current fiscal year can expire before a buying process starts, while a monthly run rate may coexist with a separate implementation allowance. The protocol should capture the reference period the speaker used and the date of the conversation, without asking callers to calculate fiscal calendars. If the prospect supplies no reference period, record that gap. Sales can then decide whether a later clarification is worth another contact rather than treating an old number as permanently current.`,
      `Before launch, sales managers should classify fictional notes without seeing each other’s answers. Require them to identify amount, currency, period, scope, evidence strength, and the one permitted conclusion. If managers disagree, the schema is not ready for caller scoring. Revise the codebook and repeat the exercise after CRM or pricing-process changes. This calibration protects callers from being judged against private expectations and gives the handoff reader a common meaning for every structured state.`,
      `Limitations and non-claims. A contact can misunderstand internal finances, change plans, speak in shorthand, or use a currency symbol shared by several jurisdictions. Reviewers can agree on a code without proving that the budget exists or is authorized. The sample may reflect one campaign, season, or market, and later sales notes may be incomplete. This protocol makes no claim about OutsourcedCallers.com performance, conversion, client pricing, or legal compliance. It evaluates whether one qualification workflow preserves the meaning and uncertainty of budget statements.`,
      `Niche-specific conclusion. A buyer considering Filipino qualification callers should inspect whether the handoff retains amount, currency, period, scope, conditions, speaker role, and unresolved questions. The useful outcome is not a fuller-looking CRM field; it is a sales record that shows exactly what can and cannot be concluded. Train callers to clarify bounded dimensions and protect refusals, then let the client’s sales team decide commercial meaning. That division gives an outsourced caller a practical task without transferring pricing authority or forecast ownership.`,
    ],
  },
  {
    slug: 'event-group-registration-authority-research',
    title: 'Who may confirm seats in a group event registration?',
    excerpt: 'An event-registration study for separating a coordinator’s roster submission from each attendee’s eligibility, communication choice, and final seat state.',
    service: 'event registration calls',
    link: '/services/event-registration-calls',
    sources: [privacy, security, dpa, records, calls],
    body: [
      `Group registration looks efficient because one coordinator can provide several names at once, but it combines distinct decisions. The coordinator may be allowed to reserve capacity, may only nominate possible attendees, or may have authority for billing while each person must still accept notices and participation terms. A caller needs a workflow that preserves those differences. This study focuses on the evidence that connects a coordinator, a roster version, each proposed participant, the event rule, and the final seat ledger without assuming that possession of names equals authority to confirm everyone.`,
      `Start by mapping the event’s actual state machines rather than the phone script. Capacity may move through held, offered, accepted, released, and waitlisted. A participant may move through nominated, contacted, eligible, declined, substituted, and confirmed. Payment can have its own pending and settled states. The research should not collapse these tracks into one “registered” label. A group can be paid while names remain incomplete, or every attendee can accept while the organizer still has not assigned limited-session places.`,
      `Methodology. Observe consecutive group-registration requests during a fixed enrollment window and intentionally add cases involving substitutions, inaccessible contact details, duplicate names, capacity limits, and late roster changes. Before review, freeze a rights matrix identifying who may submit, replace, remove, receive private event material, and commit payment for each registration class. The unit is one group request plus participant-level branches. Reviewers independently compare the source rule, coordinator statement, caller action, participant communication, organizer decision, and authoritative roster at a declared cutoff.`,
      `The roster requires version control. Retain a group identifier, version number, received time, source, coordinator identity state, participant keys, change reason, and the owner who accepted the update. Do not email spreadsheets back and forth as if the latest attachment were self-evident. A corrected spelling is different from replacing a person; replacing a person is different from adding capacity; changing an email may alter where access material is sent. Each event should be attributable so an organizer can reconstruct why the final roster differs from the first submission.`,
      `Test authority with concrete contrasts. An employer books ten seats and names staff later under an explicit contract rule. A community coordinator shares ten interested people but cannot accept privacy notices for them. A parent registers dependents under a released age policy. An assistant submits executives’ details but cannot decide accessibility arrangements. A travel arranger pays while the participants control communication preferences. These examples prevent “group leader” from becoming a universal permission label and reveal where the event owner must define separate roles.`,
      `Participant contact should be proportionate to purpose. The caller may need a name, approved contact route, event selection, and one unresolved eligibility or support question. A coordinator should not be asked for unrelated personal history, and participants should not receive another attendee’s details. If a shared address is used, record that fact and apply the organizer’s delivery rule rather than pretending every notice reached an individual. Privacy review should examine exported rosters, call notes, invitation links, and deletion after the event, not only the registration form.`,
      `Capacity analysis needs a conserved quantity. At each time point, reconcile total capacity with confirmed seats, time-bounded holds, open offers, waitlist allocations, cancellations, and owner-held exceptions. A participant’s verbal interest does not necessarily consume a seat, and a coordinator’s bulk request should not create an indefinite hold unless policy says so. Track expired holds and simultaneous updates explicitly. This ledger lets the study find oversubscription, stranded capacity, and ambiguous offers without blaming a caller for system latency or an organizer’s undefined rule.`,
      `Measure group-level and participant-level outcomes separately. Group measures include valid requester role, accepted roster version, billed quantity, capacity reconciliation, and coordinator notification. Participant measures include eligibility evidence, permitted contact, accurate seat state, unanswered questions, substitutions, and final notice. Report late and unresolved cases at cutoff. A high group completion rate can hide people who never agreed, while a low individual contact rate may be expected when an authorized coordinator legitimately owns communications under the event rule.`,
      `The caller’s safe role is operational. They can identify the request type, use the current roster template, explain published steps, record a proposed change, contact people through released channels, and route exceptions. They should not invent a coordinator’s authority, promise admission, adjudicate eligibility, disclose the roster, approve accommodations, or expand capacity. If the governing rule is missing, the correct disposition is owner review with the exact decision needed, not a confident workaround created during the call.`,
      `Review reversals as carefully as confirmations. When a coordinator withdraws a group, one participant opts out, or the organizer rejects a substitution, the workflow should release the right seat, deactivate obsolete access, retain the audit event, and notify the right parties without exposing others. A process that can add names but cannot unwind them safely is incomplete. Include cases where an invitation was forwarded outside the roster, because final attendance alone cannot prove that access was appropriately granted.`,
      `Notification evidence deserves separate treatment. Sending a message is not the same as delivery, and delivery is not the same as participant understanding or acceptance. Define which event moves a participant between states and which failures return the case to the coordinator or organizer. A shared inbox, bounced invitation, unanswered call, or forwarded link should not be coded as confirmation. Where the event rule allows coordinator-only notices, record that rule explicitly so the study does not penalize a legitimate group communication model.`,
      `Group substitutions require a clean comparison between outgoing and incoming participants. Preserve the outgoing seat state, replacement request, requester role, eligibility evidence, access revocation, new invitation, and organizer decision. Do not copy the former participant’s private answers or accommodation details to the replacement. If payment or entitlement attaches to the group rather than the individual, say so; if it attaches to a named person, the caller must not assume it transfers merely because total headcount stays constant.`,
      `A readiness pilot should begin with one low-risk registration class and a small capacity block. Reconcile the roster and capacity ledger daily, sample participant notices, and exercise one cancellation and one substitution before expanding. Track rule questions that callers send to the organizer and update the rights matrix only through controlled versions. This makes unclear policy visible early and avoids turning an improvised exception on one call into the de facto rule for every group.`,
      `For reporting, publish an exception queue beside the roster totals. Name the unresolved authority question, affected seat state, oldest event, responsible organizer, and next review condition without exposing participant details unnecessarily. Aging matters because a pending substitution can block both the outgoing and incoming person while capacity appears balanced. A visible exception ledger lets the organizer resolve policy questions before callers repeat inconsistent answers.`,
      `Limitations and non-claims. Event rules vary widely by age, venue, payment model, invitation class, accessibility process, and jurisdiction. Calendar or registration logs may not show forwarded links or offline organizer approvals. Attendance does not prove authority, consent, eligibility, or a correct roster. This study does not report OutsourcedCallers.com performance, guarantee attendance, interpret contracts, or provide legal advice. Findings apply only to the observed event rule, systems, population, and enrollment window.`,
      `Niche-specific conclusion. A Philippines-based registration caller can add real value when the buyer supplies a rights matrix, participant states, roster-version process, capacity ledger, and named organizer route. Evaluate whether every seat traces to an authorized request and final state, not whether one bulk call produced many “registrations.” Keeping coordinator authority, participant choice, payment, and capacity separate protects the event experience and gives the caller a bounded workflow that can be reviewed and reversed.`,
    ],
  },
  {
    slug: 'survey-questionnaire-version-transition-research',
    title: 'When can telephone survey results cross questionnaire versions?',
    excerpt: 'A survey-calling protocol for identifying whether wording, order, response choices, or routing changes leave answers comparable across versions.',
    service: 'survey calling',
    link: '/services/survey-calling',
    sources: [aapor, privacy, dpa, records, calls],
    body: [
      `A questionnaire update can look minor in a document diff while changing what an answer means. Replacing “satisfied” with “very or somewhat satisfied,” moving a sensitive item later, adding an interviewer instruction, or changing a skip rule may alter response behavior and eligibility. This research does not ask whether the newer wording is better in the abstract. It asks what evidence a survey owner needs before combining telephone responses gathered under different versions, and which controls an outsourced calling team needs during the transition.`,
      `Methodology. Create a version register before fieldwork that assigns an immutable identifier to every released instrument, language variant, response list, prompt, skip rule, introduction, and interviewer instruction. Define the intended estimand and comparison groups in advance. During a controlled transition, randomly assign versions when ethically and operationally appropriate, or document the nonrandom release mechanism when it is not. The observation unit is one eligible sampled contact linked to release time, version, interviewer, attempt history, item path, final disposition, and any correction event.`,
      `Begin with a semantic change map, not line counts. For each altered item, classify changes to construct, reference period, subject, response scale, order, mode instruction, eligibility, routing, and requiredness. A punctuation edit may be immaterial; inserting “in the last 30 days” changes the reference period. Adding “including online support” changes scope. Reordering choices can change primacy or recency effects. Reviewers should explain why comparability is expected, uncertain, or rejected for each output, rather than assigning one status to the entire instrument.`,
      `Field controls must prevent version blending. The calling interface should display one released version, log the identifier automatically, and stop an interviewer from copying a convenient question from an older guide. When a respondent resumes later, the protocol must say whether to continue, restart, or preserve a partial under the original version. If a routing defect is discovered, quarantine affected paths and retain the actual questions shown. Silently correcting the stored version after the call destroys the evidence needed to understand the responses.`,
      `Use paradata to locate transition effects without treating them as proof. Compare item nonresponse, breakoff position, clarification requests, changed answers, interview duration, routing anomalies, and interviewer comments across versions. Differences may reflect wording, but also sample composition, time of day, campaign events, caller assignment, or technical changes. A predeclared model can adjust for observed differences, yet unmeasured confounding remains. The report should describe alternative explanations and resist turning a correlation into a claim that one wording caused behavior.`,
      `Interviewer calibration should use paired practice cases. Callers administer each version exactly as released, including response options and neutral probes, while observers record deviations by item. Training must not ask callers to make the versions sound equivalent through improvised paraphrase; that masks the difference the study needs to evaluate. When respondents ask what changed, callers use owner-approved language and do not suggest the desired answer. Record coaching separately from production results so learning effects do not vanish into the trend.`,
      `The analysis should define three outputs. Version-specific results describe each instrument on its own terms. Bridged results use only items with a documented comparability rationale and show version as a variable. Non-comparable results remain separated or are retired. Publish sample counts, contact and cooperation dispositions, missingness, item paths, and uncertainty for each. A single pooled percentage is unacceptable when the denominator, question meaning, or response options changed, even if combining produces a more stable-looking number.`,
      `A bridge sample can strengthen the decision, but it has limits. If feasible, administer both forms to equivalent randomly assigned samples during an overlap window, keeping contact rules and interviewer allocation balanced. Do not give both versions of the same item to one respondent without studying order and carryover effects. Predefine the smallest operationally important difference and avoid claiming equivalence merely because a small sample found no statistically detectable gap. Lack of evidence for a difference is not proof of sameness.`,
      `Privacy controls should cover both answers and the version history. Retain only fields needed to understand eligibility, routing, response, and quality; use pseudonymous identifiers in the analysis; separate contact details from response files; restrict exports; and define deletion and correction procedures. The Philippines Data Privacy Act and NIST Privacy Framework are relevant first-party sources for governance, while the AAPOR best-practices material informs survey design and disclosure. Their presence does not itself make a campaign compliant or methodologically valid.`,
      `Translation versions need more than a shared version number. Record the source instrument, translator and review process, release date, language and locale, and any item whose meaning could not be mapped directly. Back-translation or expert review can reveal differences, but neither guarantees equivalent respondent interpretation. Analyze language groups separately when evidence for pooling is weak. Callers should use the assigned language instrument and flag a requested language switch; they should not translate an item spontaneously during the interview and store it as if the approved wording was used.`,
      `Corrections must preserve the raw event. If an interviewer selects the wrong response and corrects it under protocol, retain the original entry, corrected value, reason, time, and permitted actor. If software routed a respondent past an item, mark the answer structurally missing rather than inventing a response. Post-field cleaning rules should be written before analysts see attractive results. An auditable correction trail lets the survey owner separate respondent answers, interviewer errors, platform defects, and analyst transformations.`,
      `The report should include an item-level comparability table. For every published measure, name the versions included, exact construct, denominator, response mapping, missingness rule, bridge evidence, and residual uncertainty. Also list measures excluded from trend reporting and explain why. This negative inventory is valuable: it stops future users from rediscovering an old column and pooling it without context. Archive the decision alongside the instrument so comparability judgments survive staff turnover and dashboard redesign.`,
      `Set a release gate for dashboards and downstream files. A new version should not enter a continuous trend until the survey owner records the comparability decision, approves mappings, and labels excluded items. Automated exports must carry the version identifier and should reject unknown mappings. This gate turns methodological review into an operational control and prevents an analyst from accidentally joining columns that share a name but no longer measure the same thing.`,
      `The outsourced caller’s boundary is precise administration. They may read the assigned introduction and items, use the released neutral probes, apply the displayed route, record a respondent correction, and flag a suspected defect. They should not choose versions based on respondent characteristics, repair confusing language from memory, skip an uncomfortable item outside protocol, infer a missing answer, or promise how results will be used. The survey owner controls the instrument, sample, analysis, disclosures, and every decision to combine data.`,
      `Limitations and non-claims. Random assignment may be unavailable, overlap samples can be underpowered, translation changes may interact with culture or interviewer delivery, and external events may coincide with release. Paradata cannot reveal every reason for a response. This research does not produce a benchmark for OutsourcedCallers.com or Filipino survey callers, establish causation automatically, or guarantee population inference. It offers a protocol for making version changes visible and for limiting conclusions to evidence the design supports.`,
      `Niche-specific conclusion. A buyer using a Philippines-based survey team should demand automatic version capture, immutable instruments, trained neutral delivery, defect escalation, and version-aware reporting before reviewing toplines. The essential question is not whether callers completed the new script. It is whether every answer can be traced to the wording, choices, route, sample conditions, and version that produced it. When that trace is incomplete, the honest output is separated results and explicit uncertainty, not a cosmetically continuous trend.`,
    ],
  },
  {
    slug: 'database-shared-mailbox-ownership-research',
    title: 'Who owns a shared mailbox found during database verification?',
    excerpt: 'A database-verification study for distinguishing a deliverable shared address from a verified person, role owner, or permission to change a customer record.',
    service: 'database verification calls',
    link: '/services/database-verification-calls',
    sources: [privacy, security, dpa, records, calls],
    body: [
      `Addresses such as sales@, support@, or office@ can be valid communication routes without belonging to one verified person. A caller may learn that several employees monitor a mailbox, that ownership changed, or that the address is only an intake channel. Treating deliverability as identity creates false confidence; treating every shared address as unusable discards legitimate business contact paths. This study examines how a verification call can record function, access, permitted purpose, and update authority as separate claims.`,
      `Methodology. Draw a stratified sample of database records containing role-like addresses, addresses reported as shared during a call, and personal-looking addresses later shown to have multiple users. Before contact, freeze the verification script, identity step, allowed fields, correction authority, result codes, and trusted owner route. The unit is one address-record relationship, including prior source and timestamp, account context, caller question, respondent statement, caller action, owner review, later delivery evidence, and authoritative record at cutoff.`,
      `Build a claim matrix. Deliverability asks whether the system can accept mail. Function asks what work the mailbox receives. Access asks which roles, not necessarily names, can read it. Representation asks whether replies may speak for the organization. Update authority asks who can change the database record. Contact preference asks whether the route is permitted for this purpose. A respondent can answer one claim without proving the others. The final note should show which claim was tested and which remain unknown.`,
      `Calibration cases should include a monitored support queue with documented ownership, a former employee’s address forwarded to a manager, a public sales alias that rejects customer-service requests, an external contractor sharing access, an address used only for automated notices, and a personal mailbox supplied for business contact. Reviewers classify the evidence independently and identify the next responsible owner. These contrasts stop “email verified” from hiding important differences in purpose, confidentiality, continuity, and record authority.`,
      `Do not use a successful message as proof of human ownership. Delivery events can confirm that a receiving system accepted the message, while opens may be produced by security scanners or privacy features. A reply supplies stronger evidence about current use but may still come from an unknown team member or automation. Telephone confirmation supplies a statement from the reached person under the approved identity process; it does not automatically grant authority to rename, merge, or transfer the underlying account.`,
      `Measure the evidence chain by claim. Report addresses with current source provenance, explicit shared status, stated function, defined access role, purpose-compatible contact preference, authorized correction, owner acknowledgement, and reconciled final state. Track bounced messages and later corrections as separate observations, not as simple proof that the original call succeeded or failed. Include refused, unknown, and disputed states. A verification rate that counts every deliverable mailbox as a verified decision-maker will overstate what the workflow established.`,
      `Security review should ask what the caller reveals before ownership is known. Reading an account name, open case, renewal date, attendee list, or transaction detail to a shared mailbox monitor can expose information beyond the routing purpose. Use a minimal confirmation message and trusted return route. Do not send passwords, one-time codes, full identifiers, payment information, or sensitive attachments. FTC business guidance supports minimizing retained personal information and controlling access, while NIST provides a broader privacy-risk framework; apply them to the actual system design.`,
      `Change control needs its own evidence. If the respondent says the old mailbox should be replaced, capture the old masked value, proposed route, reason, source, identity state, and decision requested. The caller can perform only the field updates expressly released by the client. Changes that alter account control, billing, authentication, suppression, consent, or sensitive notifications should route to a named owner. A confident request from someone monitoring a shared inbox is not sufficient authority by itself.`,
      `Test continuity over time. At a predeclared follow-up point, examine whether the role mailbox still functions, whether replies reached the intended team, whether ownership changes were recorded, and whether obsolete personal routes were retired under policy. Avoid repeated test messages that create noise or expose customer context. Continuity evidence helps distinguish a durable role channel from a temporary forward, but it still does not prove that every future reader has the same authority or confidentiality obligations.`,
      `Duplicate-record handling is another risk. The same shared address may appear on several accounts legitimately, or it may be a default inserted when individual details were unknown. Do not merge records solely on an email match. Compare organization, account relationship, source, purpose, and client merge rules, then route uncertainty. Report how often one mailbox links to multiple entities and whether the relationship was expected. This keeps a useful central inbox from accidentally joining unrelated customer histories.`,
      `A domain check provides context, not ownership. Matching an organization’s public domain can support plausibility, while a free-mail address can still be an authorized business route. Websites, DNS records, and signatures can be stale or manipulated. The caller should not conduct ad hoc technical investigations or tell a respondent that a domain proves identity. If the buyer uses automated enrichment, retain the provider, field, timestamp, confidence, and review rule separately from evidence collected on the call.`,
      `Quality sampling should include apparently clean confirmations, not only disputes. Review the spoken claim, coded claim type, source, permitted action, final database field, and any outbound message generated afterward. A polite, successful call can still assign a person to a role mailbox without evidence. Conversely, a caller who leaves authority unknown may have followed the brief exactly. Scoring should reward faithful boundaries and usable routing, rather than maximizing the number of definitive labels.`,
      `The final study table should report each claim type with its own denominator: deliverability tested, function stated, shared access disclosed, purpose permitted, correction authorized, and owner reconciled. Add unknown and conflicting states explicitly. Also publish the age and provenance of the pre-call record. This prevents a fresh functional confirmation from laundering a years-old ownership assumption and shows buyers which database fields need policy repair rather than another verification attempt.`,
      `The caller’s useful output is a bounded route description: “shared support mailbox, monitored by customer-care role, suitable for case-intake notices under current client rule; account-change authority not established.” That is more actionable than “email confirmed.” Caller training should emphasize asking what the address is used for and who owns record changes, while accepting unknown as a valid result. Owners then decide access, purpose, retention, and whether a sensitive workflow needs an individual route.`,
      `Limitations and non-claims. Mail systems, forwarding rules, staffing, automation, and access can change after observation. Respondents may not know every person with access, and technical logs may be unavailable or misleading. A shared mailbox can be appropriate for one purpose and inappropriate for another. This protocol does not certify identity, cybersecurity, privacy compliance, or OutsourcedCallers.com accuracy. It evaluates whether the database distinguishes communication-route evidence from person, authority, and permission claims.`,
      `Niche-specific conclusion. A Philippines-based verification caller should not be judged by the number of fields marked confirmed. Buyers should inspect whether each mailbox record identifies its source, function, shared status, allowed purpose, correction authority, unresolved risks, and owner. A carefully coded shared route can improve continuity; an overconfident identity label can misroute private information or hand control to the wrong party. The right brief gives callers small verification questions and reserves sensitive changes for accountable client owners.`,
    ],
  },
  {
    slug: 'customer-follow-up-channel-switch-permission-research',
    title: 'Does permission for one follow-up channel carry to another?',
    excerpt: 'A customer follow-up study for separating a request for help from permission to call, text, email, or leave a message on each available route.',
    service: 'customer follow-up calls',
    link: '/services/customer-follow-up-calls',
    sources: [tsr, calls, privacy, security, dpa],
    body: [
      `A customer who asks for help has expressed a purpose, but not necessarily permission for every available channel. They may request an email receipt, accept a call at work, reject text messages, or permit voicemail only without account detail. Operational pressure can flatten those choices into “contact allowed,” especially when one channel fails. This research asks how a follow-up workflow can preserve channel-specific instructions, purpose, timing, and revocation before an outsourced caller switches routes.`,
      `Methodology. Follow a prospective cohort of customer requests that include at least one permitted return channel and a defined service purpose. Freeze channel codes, purpose codes, safe-message rules, source hierarchy, retry limits, stop handling, and owner escalation before collection. The observation unit is one request lineage: intake statement, recorded preference, channel attempts, delivery or connection evidence, customer correction, suppression event, owner acknowledgement, and final resolution at a declared cutoff. Reviewers first judge the evidence available before each attempt, not what later contact made convenient.`,
      `Model permission as a vector rather than a single flag. For voice, text, email, messaging platform, and voicemail, record allowed, declined, unknown, unavailable, or owner-review; then attach purpose, time window, destination, source, and recorded date. A phone number appearing in an account is not the same as a request to call it. Permission to discuss appointment logistics may not extend to marketing. A customer saying “send it to me” requires clarification when the channel is not already established by the released workflow.`,
      `Create a source hierarchy with conflict rules. A fresh statement during an authenticated interaction may update an older general preference when client policy permits. A do-not-contact or channel stop should not be overwritten by a stale form default. A staff note such as “prefers phone” needs date, scope, and provenance before it defeats a later email-only request. When sources conflict, callers route the conflict or use the most restrictive released rule; they do not select whichever channel is fastest.`,
      `Study switching events separately. Identify why the first channel failed: invalid address, busy signal, no answer, full voicemail, bounced message, platform outage, unsafe recipient, or customer instruction. Each reason supports different next actions. No answer does not prove refusal, and a bounce does not authorize a call. Record the rule that permitted the next channel, the evidence checked immediately before use, and whether the content was reduced for that route. This makes switching a reviewable decision instead of an invisible retry tactic.`,
      `Message content must follow channel risk. A voicemail or shared email may need only the business name, neutral callback purpose, trusted number, and reference that reveals nothing sensitive. A connected call can still require identity checks before account detail. Text messages can appear on lock screens. The study should audit what was actually disclosed, not merely whether the route was allowed. Permission to use a channel does not automatically authorize every detail associated with the customer’s request.`,
      `Primary outcomes include preference provenance, channel-purpose match, pre-attempt suppression check, permitted switching rule, content minimization, stop propagation, owner receipt, and resolution. Secondary outcomes can include successful connection and elapsed time, but neither validates an unsupported attempt. Report customers, request lineages, and attempts as different denominators. One customer with five retries should not look like five independent opportunities, and a connected call after four inappropriate attempts should not be summarized as success without the preceding exposure.`,
      `Test revocation propagation across live systems. When a customer says “do not text me,” record the exact scope, time, caller action, source system, downstream queues, and acknowledgement. Observe whether scheduled messages, campaign lists, and manual notes reconcile before another attempt. If the person says “email me instead,” keep the text stop distinct from the email instruction. The caller can confirm the bounded wording released by the client; deciding legal effect across campaigns and affiliates belongs to qualified owners.`,
      `Bias can enter through observability. Connected calls create richer notes than unanswered attempts, email delivery logs differ from human reading, and staff may document exceptions more carefully after a complaint. Keep failed and unknown outcomes in the cohort. Compare channels only after considering customer selection, request type, urgency, time of day, and data quality. This is an operational evidence study, not a randomized test that one channel produces better customer outcomes.`,
      `Households and shared workplaces complicate destination evidence. A number can reach several people, an email alias can be team-monitored, and a messaging account can remain signed in on multiple devices. The workflow should distinguish destination ownership, safe-message instruction, and identity confirmation during the interaction. Even when the customer supplied the route, callers should follow the released disclosure boundary. A successful callback to the device does not by itself prove the person answering may receive account details.`,
      `Time windows need a stated timezone and expiry. “Call after five” is incomplete when the customer, caller, and account owner operate in different places. Record the timezone if the customer supplies it or the approved system has an attributable source; otherwise route the ambiguity or use a conservative released window. Do not infer current location from a mobile number. When the preference expires after one case, close it with the request instead of silently converting it into a permanent profile rule.`,
      `Reconciliation should compare every active queue after a change. Sample CRM tasks, dialer lists, messaging schedules, help-desk automations, and manual owner notes using pseudonymous keys. Record propagation time and stale attempts, then distinguish system delay from caller noncompliance. A preference visible in one application but absent from the dialer is a workflow defect. Coaching a caller cannot fix it; the buyer needs an accountable synchronization rule, monitoring, and a safe pause when systems disagree.`,
      `A prelaunch simulation should exercise four paths: the requested channel works, the first channel fails, the customer changes preference, and a stop arrives while another attempt is scheduled. Reviewers verify the source, disclosure level, queue state, and owner receipt at every transition. Repeat the simulation after integrations or campaign rules change. This gives callers practice with the boundaries and reveals system races before a real customer receives an avoidable message.`,
      `The caller’s boundary is to check the current channel-purpose state, use a released route and script, apply the approved retry rule, preserve a new preference or stop, and send unresolved conflicts to the owner. Callers should not infer broad permission from urgency, prior purchases, a number on file, or success reaching the person elsewhere. They should not promise resolution merely because contact occurred. The client retains preference governance, campaign scope, legal interpretation, and the underlying service decision.`,
      `Limitations and non-claims. Channel permissions and legal requirements depend on purpose, relationship, technology, jurisdiction, and the exact communication. Delivery receipts do not prove reading, caller ID can be misunderstood, and people can share devices or accounts. The cohort may overrepresent customers who respond. This protocol is not legal advice, does not establish consent, and makes no claim about OutsourcedCallers.com results. It tests whether one workflow preserves source, scope, switching authority, and uncertainty.`,
      `Niche-specific conclusion. A buyer using Filipino callers for customer follow-up should release a channel-by-purpose matrix, source hierarchy, safe-message rules, retry limits, suppression sync, and named conflict owner. Review the complete attempt lineage rather than only the final connection. The best handoff shows why each route was used, what was disclosed, what the customer changed, and whether every queue honored it. That gives callers a clear service task while keeping permission policy and sensitive decisions with the client.`,
    ],
  },
];

export const oct05ResearchPosts = articles.map((article) => ({
  slug: article.slug,
  title: article.title,
  excerpt: article.excerpt,
  published: '2026-10-06' as const,
  image: '/thank-you-hero.png',
  body: [
    ...article.body,
    `Sources: ${article.sources.map((source) => `${source.title} | ${source.publisher} | ${source.url} | checked ${source.checked}`).join(' || ')}`,
  ],
  handoff: {
    href: article.link,
    label: `Review ${article.service}`,
    text: `Use this research to define evidence, decision boundaries, and owner handoffs before planning ${article.service} with a Philippines-based team.`,
  },
}));
