type Topic = { slug:string; title:string; excerpt:string; lane:string; situation:string; facts:string; owner:string; forbidden:string; opening:string; detail:string };

const topics: Topic[] = [
  {slug:'filipino-caller-local-holiday-coverage-release',title:'Filipino caller local holiday coverage release',excerpt:'A queue-release routine for Philippine holiday coverage that keeps approved hours, owners, and customer expectations clear.',lane:'daily caller operations',situation:'a Philippine holiday changes staffing coverage while a client queue remains scheduled',facts:'the approved coverage window, assigned callers, released queue size, client time zone, escalation owner, and deferred work',owner:'client queue manager',forbidden:'extend calling hours without approval, imply full coverage, or move deferred records into another campaign',opening:'I am confirming today\'s approved coverage window and the queue that can be completed within it.',detail:'Holiday coverage begins with a smaller, explicit release rather than an unchanged queue and an unspoken expectation.'},
  {slug:'appointment-invitation-bounce-recovery',title:'Appointment invitation bounce recovery',excerpt:'A recovery path when a meeting invitation bounces after a Filipino caller records an accepted time.',lane:'appointment setting',situation:'the calendar system reports that a meeting invitation could not be delivered',facts:'the meeting request, agreed time and zone, bounced address, delivery event, alternate contact permission, and calendar owner',owner:'calendar owner',forbidden:'guess a corrected address, mark the meeting confirmed, or contact an alternate channel without permission',opening:'The invitation did not reach the address provided. I can verify the approved contact route and return the correction to the calendar owner.',detail:'A spoken agreement and successful invitation delivery are separate appointment states, and the record should preserve both.'},
  {slug:'outbound-gatekeeper-callback-permission',title:'Outbound gatekeeper callback permission',excerpt:'How to record a gatekeeper\'s callback instruction without treating it as consent from the intended contact.',lane:'outbound calling',situation:'a gatekeeper offers a better callback time or route for the intended contact',facts:'the person reached, intended contact, callback instruction, source number, permission limit, attempt time, and next review',owner:'campaign owner',forbidden:'claim the intended contact requested the call, disclose private campaign context, or broaden the contact purpose',opening:'Thank you. I will record the routing instruction without attributing it to the intended contact.',detail:'A gatekeeper can supply routing context, but that context does not become the intended person\'s preference or authorization.'},
  {slug:'customer-follow-up-multiple-owner-deadlock',title:'Customer follow-up multiple-owner deadlock',excerpt:'A practical way to resolve a follow-up record passed between teams without asking the caller to choose the final owner.',lane:'customer follow-up',situation:'two business teams have each routed the same unresolved customer question to the other',facts:'the original question, both handoff events, owner responses, customer deadline, current contact preference, and open decision',owner:'operations manager',forbidden:'send another circular handoff, choose policy ownership, or tell the customer the issue is resolved',opening:'I can see this question has moved between teams. I will preserve both handoffs and send it to the operations owner for assignment.',detail:'A routing loop is an ownership defect. Another transfer repeats the defect instead of moving the customer request forward.'},
  {slug:'inbound-after-hours-safety-boundary',title:'Inbound after-hours safety boundary',excerpt:'An after-hours reception boundary for urgent language when the caller needs emergency help beyond the business workflow.',lane:'inbound call handling',situation:'an after-hours caller describes immediate danger or asks for emergency assistance',facts:'the caller\'s stated concern, location only if offered and required by the approved script, callback detail, time, route used, and stop state',owner:'business safety owner',forbidden:'diagnose the danger, promise emergency response, keep the person waiting for a business callback, or improvise instructions',opening:'This line cannot provide emergency assistance. Please contact the emergency service appropriate to your location now.',detail:'An outsourced reception line needs a direct safety boundary because a routine escalation queue is not an emergency service.'},
  {slug:'lead-qualification-job-title-ambiguity',title:'Lead qualification job title ambiguity',excerpt:'A question sequence for understanding decision involvement when a prospect\'s title does not reveal their role in the purchase.',lane:'lead qualification',situation:'a prospect gives a job title that does not clearly establish decision authority or participation',facts:'the stated title, responsibilities described, decision process, other participants, timing, open questions, and agreed follow-up',owner:'sales owner',forbidden:'infer authority from seniority, downgrade the contact, or press for an organizational chart',opening:'Titles vary between companies, so I will ask how you participate in this particular decision.',detail:'Qualification improves when the caller records the person\'s described role rather than assigning authority from a title alone.'},
  {slug:'database-verification-shared-phone-line',title:'Database verification shared phone line',excerpt:'A privacy-minded verification routine when one number is shared by several people or departments.',lane:'database verification',situation:'the person answering says the listed phone number is shared',facts:'the source record, shared-line statement, intended contact or department, safe message limit, preferred routing detail, and review status',owner:'data steward',forbidden:'read personal fields aloud, assume every user of the line has account authority, or replace the source record immediately',opening:'I will limit the information discussed on this shared line and send the routing detail for record review.',detail:'A working number can still be an unsafe place to disclose record details when several people answer it.'},
  {slug:'event-registration-capacity-waitlist-handoff',title:'Event registration capacity waitlist handoff',excerpt:'A controlled response when registration reaches capacity and the event owner, not the caller, manages any waitlist.',lane:'event registration calls',situation:'an attendee asks to join an event that the released registration view shows as full',facts:'the event reference, capacity state, attendee request, waitlist availability shown, contact preference, accessibility note if volunteered, and owner',owner:'event registration owner',forbidden:'promise a seat, create an unofficial list, remove another attendee, or predict when capacity will open',opening:'The released registration view shows the event as full. I can record your request through the approved waitlist route if one is available.',detail:'A full event changes the caller\'s task from registration to accurate expectation setting and owner-controlled routing.'},
  {slug:'renewal-reminder-legal-name-mismatch',title:'Renewal reminder legal name mismatch',excerpt:'A pause-and-review routine when the name on a renewal record differs from the name given by the customer.',lane:'renewal reminder calls',situation:'the customer states a legal or business name that differs from the released renewal record',facts:'the renewal reference, displayed name, correction stated, identity check result, requested response channel, renewal date, and hold state',owner:'account data owner',forbidden:'change the legal name, disclose contract details, infer a merger, or continue as if the mismatch were resolved',opening:'I will record the name difference and pause the renewal discussion for account review.',detail:'A name mismatch can be a simple correction or a change in account authority. The reminder caller should not decide which.'},
  {slug:'order-confirmation-duplicate-order-concern',title:'Order confirmation duplicate order concern',excerpt:'How a Filipino caller should record a possible duplicate order without canceling either record or promising a refund.',lane:'order confirmation calls',situation:'a customer says two released order references may represent the same purchase',facts:'both order references, items only as permitted, order times, customer statement, fulfillment state shown, desired response, and owner',owner:'fulfillment owner',forbidden:'cancel an order, promise a refund, decide which record is valid, or request payment credentials',opening:'I can record the possible duplicate and ask fulfillment to review both order references before either is changed.',detail:'Two similar orders are evidence for review, not proof that one should be canceled.'},
  {slug:'survey-language-switch-record',title:'Survey language switch record',excerpt:'A neutral record for pausing or transferring a survey when the respondent requests a different supported language.',lane:'survey calling',situation:'a respondent asks to continue the questionnaire in another language',facts:'the requested language, question last completed, consent state, approved language availability, transfer result, callback permission, and disposition',owner:'survey operations owner',forbidden:'translate questions from memory, paraphrase the scale, pressure the respondent to continue, or copy partial answers into a new record without the protocol',opening:'I will pause here and check the approved survey route for your requested language.',detail:'A language switch can change how questions are understood, so the questionnaire version and partial responses need a controlled handoff.'},
  {slug:'call-quality-background-noise-attribution',title:'Call quality background noise attribution',excerpt:'A review method for background noise that separates caller behavior, connection conditions, and customer environment.',lane:'call quality review',situation:'a recording contains background noise but its source is not immediately clear',facts:'the affected timestamps, audible source if observable, speech clarity, notices given, corrective action, customer response, and reviewer confidence',owner:'quality calibration lead',forbidden:'attribute the noise to the Filipino caller without evidence, score accent instead of intelligibility, or ignore lost information',opening:'I will score the observable effect on the call and record the noise source as unknown unless the evidence identifies it.',detail:'Noise matters when it changes understanding or professionalism, but fair review begins by separating its effect from an unsupported guess about its source.'}
];

const sources = [
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'},
  {name:'National Privacy Commission of the Philippines',url:'https://privacy.gov.ph/data-privacy-act/'}
];

function makeDetail(t: Topic) {
  const paragraphs = [
    `${t.detail} Use this routine when ${t.situation}. In ${t.lane}, the caller's job is to preserve the record and make the next action obvious.`,
    `Start with the released call purpose and the fields the caller may use. Capture ${t.facts}. If the source and the conversation disagree, keep both versions rather than smoothing the conflict away.`,
    `Say what happened in plain language. Quote a short phrase when the exact wording affects the route. Otherwise, summarize the request without adding a motive, diagnosis, or prediction.`,
    `The caller must not ${t.forbidden}. That boundary belongs in the script, not only in a training deck, because the difficult moment happens while another person is waiting on the line.`,
    `Give the ${t.owner} a note that can be acted on without replaying the conversation. Include the record identifier, the new evidence, the unresolved decision, the requested response channel, and any real deadline.`,
    `Choose a specific queue state after the call. Awaiting owner review, correction requested, contact stopped, and closed are more useful than a generic escalated label. Add the owner and review due time.`,
    `Prepare the queue for this case before a Filipino caller encounters it. The record should show the approved purpose, the source that supplied the contact, the latest review time, and the exact instruction that applies when ${t.situation}. A caller should not have to search a training folder while the person waits. Put the usable instruction beside the record and give it a version that a quality reviewer can identify later.`,
    `Keep identity checks proportional to the conversation. The caller needs enough assurance to avoid disclosing information to the wrong person, but should not collect extra personal data merely to make the note look complete. When identity remains uncertain, record the limit and move the item to the approved hold. The ${t.owner} can decide whether another verified channel is appropriate.`,
    `The result label should describe the observed state, not the result the team hoped to obtain. A positive tone does not turn an unresolved question into approval. A quick conversation does not prove the record is correct. For ${t.lane}, reviewers should be able to trace the label to a sentence, field, or system event that supports it. If they cannot, the label needs correction before the next action is released.`,
    `Write the note for the next person who has not heard the call. Put the purpose first, then the new information, the unresolved point, and the requested response. Separate a direct statement from the caller's interpretation. If an exact phrase changes the route, preserve only that short phrase and avoid copying unrelated personal detail. A concise evidence trail is more useful than a polished narrative that hides uncertainty.`,
    `Timing belongs in the control because calling queues keep moving. Record when the contact happened, when the owner should review it, and when any approved next attempt becomes eligible. A due point is not permission to call again. The queue must also show that contact preferences and suppression checks still allow the action. This distinction prevents an old reminder from overriding a newer request to stop or change channels.`,
    `Design the escalation so it can fail visibly. If the ${t.owner} is unavailable, the item should remain in a named review state with an alternate owner or a defined next review point. Do not send the same question through several channels and hope one person acts. Duplicate escalation can create contradictory answers, while an ownerless message can disappear. One accountable route gives the caller and reviewer a clear place to check.`,
    `Daily reporting should keep activity separate from resolution. Count the conversation as contact only under the queue's definition. Count the handoff as sent when the approved route accepts it. Count the issue as resolved only after the responsible owner records a decision or completed action. These distinctions stop a busy calling day from masking open work and make the report useful to the business that owns the queue.`,
    `Quality review should examine the difficult moment, not just the greeting and close. Listen or read around the point where ${t.situation}. Check whether the caller used the released wording, captured ${t.facts}, and avoided the prohibited action. Then compare the note with the queue state. A coaching comment should identify the exact choice to repeat or repair rather than offer a broad instruction to communicate better.`,
    `A script change needs controlled release. When this case exposes unclear wording, the business owner should approve a revised line, record why it changed, and remove the superseded version from active use. Filipino callers should acknowledge the new instruction before receiving affected records. Review the first few relevant contacts under the new version, because a sentence that reads clearly in a document can still create confusion in conversation.`,
    `Access should follow the role boundary. Show the caller only the fields, communication tools, and history needed to handle ${t.lane}. Restrict exports, sensitive account views, broad customer searches, and settings that change authoritative records unless the role explicitly requires them. Limited access is not a substitute for training, but it reduces the chance that a routine call becomes an unauthorized account or policy decision.`,
    `When the owner resolves the item, preserve the original evidence and append the decision. Do not rewrite the caller's note so it appears the answer was known during the conversation. The difference between what the caller knew and what the owner later decided helps managers test the brief fairly. It also reveals whether the same exception is recurring often enough to deserve a new queue rule, system field, or owner response standard.`,
    `Review a small sample of these cases at the end of the operating period. Look for repeated missing fields, conflicting source systems, delayed owner responses, stale scripts, and attempted contacts that should have remained held. The remedy should match the defect. Repair the intake when context is absent, the route when ownership is unclear, and the script when callers interpret the same instruction differently. More calling does not repair a broken release rule.`,
    `At daily close, compare the note with the live queue. Confirm that restrictions reached the active list and that open decisions still have an owner. The note is only half the control; the system state must agree with it.`,
    `Coach this situation with one real example. Ask the caller to point to the source fact, the fact learned on the call, and the decision they deliberately left with the owner. Repair the exact field or script line that caused confusion.`,
    `For OutsourcedCallers.com teams, this split lets Filipino callers handle careful conversations and accountable notes while the client keeps authority over policy, accounts, commercial terms, sensitive data, and exceptions.`
  ];
  return {published:'2026-09-03',mainKeyword:t.title,metaLabel:'Philippines staffing blog',directAnswerHeading:`How to respond when ${t.situation}`,
    summary:paragraphs[0],takeaways:[`Record ${t.facts}.`,'Keep source data separate from the caller response.',`Route the unresolved decision to the ${t.owner}.`,'Reconcile the queue after review.'],
    decisionTable:[
      {lane:'Prepare',caller:'Checks purpose, permitted fields, and current source.',owner:'Releases the queue and boundary.',measure:'Source and script version are visible'},
      {lane:'Listen',caller:'Records the response without inference.',owner:'Defines which evidence changes the route.',measure:'Observed facts stay separate'},
      {lane:'Stop point',caller:'Uses the approved boundary and handoff.',owner:`The ${t.owner} decides the exception.`,measure:'No unsupported promise'},
      {lane:'Close',caller:'Checks the note against the queue.',owner:'Records the final decision and reason.',measure:'Queue and review state agree'}],
    planningBands:[{label:'Purpose',value:'Checked',note:t.lane},{label:'Evidence',value:'Named',note:'Source plus response'},{label:'Owner',value:'Assigned',note:t.owner},{label:'Queue',value:'Matched',note:'Final state'}],
    sections:[{heading:'Read the source before responding',paragraphs:paragraphs.slice(0,2)},{heading:'Record the difference without inventing context',paragraphs:paragraphs.slice(2,4)},{heading:'Send a decision-ready handoff',paragraphs:paragraphs.slice(4,6)},{heading:'Check the live queue at close',paragraphs:paragraphs.slice(6,7)},{heading:'Coach the boundary from a real call',paragraphs:paragraphs.slice(7)}],
    scripts:[{title:'Opening',text:t.opening},{title:'Boundary',text:'I can record the correction, but I cannot approve the account or policy change from this call.'},{title:'Close',text:`I have sent the open decision to the ${t.owner} through the approved route.`}],
    workflow:[{step:'1',title:'Check',text:'Read the released purpose and source.'},{step:'2',title:'Hear',text:'Capture the person\'s own words.'},{step:'3',title:'Separate',text:'Preserve both source and response.'},{step:'4',title:'Route',text:`Assign the decision to the ${t.owner}.`},{step:'5',title:'Match',text:'Reconcile the note and queue.'}],
    faqs:[{q:'What may the caller decide?',a:'The caller may choose the accurate call result and approved route. The business owner decides exceptions and authoritative changes.'},{q:'What belongs in the handoff?',a:`Include ${t.facts}, the unresolved decision, requested response, and named owner.`},{q:'What if the owner has not replied?',a:'Keep the record awaiting review, surface it in the exception report, and do not replace the owner decision with a caller guess.'}],
    related:[{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Inbound call handling',href:'/services/inbound-call-handling'},{label:'Call quality review',href:'/services/call-quality-review'}],sources};
}

export const sep03BlogPosts = topics.map((t) => ({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:10,published:'2026-09-03',image:''}));
export const sep03BlogDetails = Object.fromEntries(topics.map((t) => [t.slug,makeDetail(t)]));
