type Topic={slug:string;title:string;excerpt:string;question:string;unit:string;comparison:string;limit:string;fields:string};
const topics:Topic[]=[
 {slug:'appointment-double-booking-recovery-research',title:'How often do possible double bookings reach a clean resolution?',excerpt:'A cautious design for comparing reminder windows without claiming that timing alone causes attendance.',question:'how possible appointment conflicts move from detection to a documented calendar outcome',unit:'one eligible appointment and its permitted reminder sequence',comparison:'same-day, one-day, and multi-day timing bands across delivery, response, correction, and attendance',limit:'observational timing differences cannot show that a reminder caused attendance',fields:'appointment ID, consented channel, local timezone, reminder time, delivery state, reply, reschedule, and attendance'},
 {slug:'gatekeeper-message-detail-research',title:'What message detail is actually preserved through a gatekeeper?',excerpt:'A measurement plan for list-source review that keeps data quality separate from campaign performance.',question:'which approved callback details survive when a caller leaves a message with an intermediary',unit:'one released phone record and its final identity-verification outcome',comparison:'source, age band, duplicate state, wrong-party result, corrected record, and suppression completion',limit:'a wrong-number rate does not measure consent, intent, caller skill, or commercial value',fields:'source label, acquisition date, verification date, record ID, attempt result, correction, and suppression time'},
 {slug:'inbound-callback-number-mismatch-research',title:'What happens after an inbound callback number conflicts with the record?',excerpt:'An evidence model for separating timely attempts from the time required to resolve the underlying question.',question:'how callback-number mismatches are reviewed and resolved across inbound message workflows',unit:'one customer-accepted callback window and its linked case history',comparison:'owner groups, issue types, on-time attempts, transfers, reopenings, and resolution intervals',limit:'a closed status may not mean the customer agrees that the issue was resolved',fields:'promise source, timezone, window, owner, attempt times, transfer events, close reason, and customer response'},
 {slug:'survey-language-switch-breakoff-research',title:'How should survey teams study language-switch requests and breakoffs?',excerpt:'A review method for comparing interviewer clarifications while respecting respondent choice and study wording.',question:'how requests to switch language relate to routing, return attempts, partial completion, and breakoff',unit:'one clarification request, the relevant survey item, and the interviewer response',comparison:'items, language versions, interviewers, clarification types, answer changes, and breakoffs',limit:'agreement with a script does not prove that respondents understood the question',fields:'study version, item ID, language, request timestamp, response category, answer state, and disposition'},
 {slug:'qa-transcript-audio-disagreement-research',title:'How often do transcript errors change a call-quality score?',excerpt:'A restrained study design for tracking repeated scorecard findings without overstating coaching effects.',question:'when transcript and audible recording disagreements change the classification of an eligible QA item',unit:'one scored finding, its coaching record, and a prespecified follow-up sample',comparison:'criterion, severity, coach, time window, opportunity count, repeated findings, and adjudications',limit:'improvement after coaching may reflect case mix, experience, monitoring, or scorecard changes rather than coaching alone',fields:'caller pseudonym, call lane, criterion, evidence timestamp, coaching date, action, sample rule, and later result'}
];
const sources='Sources: NIST Privacy Framework (https://www.nist.gov/privacy-framework); FTC Telemarketing Sales Rule (https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule); AAPOR Best Practices (https://aapor.org/standards-and-ethics/best-practices/); Philippines National Privacy Commission, Data Privacy Act guidance (https://privacy.gov.ph/data-privacy-act/).';
function body(t:Topic){return [`Published: September 8, 2026. This research note asks ${t.question}. It is a measurement design for OutsourcedCallers.com operations, not a claim that one practice is universally best.`,`Define the unit as ${t.unit}. Freeze eligibility, observation windows, and exclusion rules before reviewing outcomes. Include unsuccessful records so the dataset does not become a success-only story.`,`Collect ${t.fields}. Minimize identifiers, restrict access, set a retention period, and keep consent and suppression controls independent from the study dataset.`,`Compare ${t.comparison}. Publish counts and denominators for each group, show missing values, and use uncertainty intervals only when the sample and design support them.`,`Scope and limitations: this analysis can describe associations inside the released sample and period. ${t.limit}. Seasonality, source quality, customer mix, caller assignment, and workflow changes may also explain differences.`,`Pilot the codebook on a small sample. Have a second reviewer classify ambiguous records without seeing the first decision, then report exclusions, protocol changes, and unresolved disagreement.`,`Keep the operational conclusion narrow: use a finding to improve a field definition, choose the next controlled test, or identify a handoff for review. Do not turn an aggregate pattern into a promise about an individual call.`,sources];}
export const sep08ResearchPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,published:'2026-09-08',image:'/thank-you-hero.png',body:body(t)}));
