type Topic={slug:string;title:string;excerpt:string;scenario:string;record:string;owner:string;stop:string};

const topics:Topic[]=[
 {slug:'appointment-setting-double-booking-review',title:'Review a possible double booking before confirming the meeting',excerpt:'A practical pre-send routine that keeps calendar times clear for prospects and meeting owners.',scenario:'a proposed appointment overlaps another event or a calendar sync leaves the slot uncertain',record:'the proposed time, IANA timezone, attendee locale, calendar owner, and source message',owner:'calendar owner',stop:'guess the attendee’s timezone or translate an ambiguous abbreviation'},
 {slug:'outbound-calling-gatekeeper-message-consent',title:'Ask before leaving a detailed message with a gatekeeper',excerpt:'How to protect the next shift from repeatedly calling a number that belongs to someone else.',scenario:'someone other than the intended contact offers to take a message',record:'record ID, dialed number, exact result, requested restriction, list source, and attempt time',owner:'campaign data owner',stop:'ask for the intended person’s new number or keep the record active'},
 {slug:'customer-follow-up-case-owner-absence',title:'Keep a customer follow-up moving when the case owner is absent',excerpt:'A caller handoff for missing files that separates delivery evidence from assumptions.',scenario:'the named case owner is unavailable when a customer asks for an update',record:'message ID if available, file label, approved recipient address, send time, and customer report',owner:'case owner',stop:'resend an unverified file or expose another recipient’s details'},
 {slug:'inbound-call-callback-number-mismatch',title:'Pause an inbound message when the callback number does not match',excerpt:'A short reception habit that reduces avoidable name errors without lengthening every call.',scenario:'the caller gives a callback number different from the number visible in the released record',record:'the name as spoken, the caller’s spelling, callback number, company, and message owner',owner:'reception lead',stop:'correct the caller’s name from an unrelated database record'},
 {slug:'lead-qualification-decision-timeline-uncertainty',title:'Record an uncertain buying timeline without forcing a date',excerpt:'A qualification routine for prospects who prefer not to share a budget range.',scenario:'a prospect describes a need but says the decision timeline is not settled',record:'the question asked, the decline, stated need, decision process, and accepted next step',owner:'sales owner',stop:'invent a range or treat privacy as lack of interest'},
 {slug:'database-verification-shared-phone-number',title:'Review a phone number shared by more than one database record',excerpt:'A controlled way to preserve evidence when a business contact has left the organization.',scenario:'the same phone number appears on two or more released contact records',record:'record ID, source, verification time, exact response, general switchboard details, and restriction',owner:'data steward',stop:'replace the contact with an unverified person'},
 {slug:'renewal-reminder-payment-detail-request',title:'Route payment-detail questions raised during a renewal reminder',excerpt:'How callers can acknowledge the question without interpreting terms or promising a renewal outcome.',scenario:'a contact asks to discuss account-specific payment details during a reminder call',record:'account reference, version labels visible, renewal date, exact question, and preferred response channel',owner:'account owner',stop:'interpret terms or choose the controlling document'},
 {slug:'order-confirmation-substitution-request',title:'Hold an order confirmation when the customer requests a substitution',excerpt:'A safe call workflow for recording a requested address change before fulfillment review.',scenario:'a customer asks to replace an item while confirming an order',record:'order reference, original locality, requested locality, dispatch state, and customer callback details',owner:'fulfillment owner',stop:'edit the address or promise the carrier can redirect it'},
 {slug:'survey-calling-language-switch-request',title:'Handle a language-switch request during a survey call',excerpt:'A consent-aware close when a respondent wants to continue at another time.',scenario:'a respondent asks to continue the survey in another language',record:'survey ID, consent state, last completed item, approved callback window, language, and close code',owner:'survey operations owner',stop:'promise saved answers or a callback unless the study protocol allows both'},
 {slug:'win-back-offer-expiry-uncertainty',title:'Pause a win-back call when the offer expiry is unclear',excerpt:'A simple route for moving a conversation only when the campaign permits the requested channel.',scenario:'the contact asks how long an offer remains valid but the released brief and system disagree',record:'record ID, request wording, approved email status, offer version, suppression state, and next owner',owner:'retention campaign owner',stop:'send marketing email or copy an address without the approved basis'},
 {slug:'reception-overflow-legal-document-delivery',title:'Route a legal-document delivery call without accepting service',excerpt:'A reception boundary for vendor questions that belong with accounts payable.',scenario:'a caller asks where or how to deliver a legal notice or formal document',record:'vendor name, invoice reference, callback details, stated due date, and intended department',owner:'accounts-payable owner',stop:'confirm receipt, approval, balance, or payment timing'},
 {slug:'call-quality-review-transcript-audio-conflict',title:'Resolve a transcript and audio conflict before scoring the call',excerpt:'A fair QA check that distinguishes unexplained dead air from holds, system waits, and listening time.',scenario:'a transcript line changes the apparent meaning of an audible call segment',record:'recording timestamp, duration, surrounding dialogue, system event, disclosure, and scorecard version',owner:'quality lead',stop:'infer inattentiveness from audio alone'}
];

const sources=[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'},{name:'Philippines National Privacy Commission',url:'https://privacy.gov.ph/data-privacy-act/'}];
function detail(t:Topic){const p=[
 `Use this routine when ${t.scenario}. The goal is a truthful record and a clean handoff, while the ${t.owner} keeps the decision that belongs with the business.`,
 `Open the released brief before responding. Capture ${t.record}. Mark which fact came from the system and which came from the person on the call so later reviewers can reconstruct the moment.`,
 `The caller must not ${t.stop}. State the boundary in ordinary language, acknowledge the request, and move the record into the approved review state.`,
 `Write a handoff that includes the record, the new evidence, the unresolved question, the requested outcome, a real deadline, and the ${t.owner}. Avoid urgency labels unless the operating rule or the person’s own words supports one.`,
 `Before shift close, compare the call note, queue, and restriction fields. If they disagree, keep the work paused and surface the mismatch rather than letting a tidy note hide an unsafe next action.`,
 `Coach from the actual call sample: identify the observed fact, the inherited system value, the decision left open, and the sentence used to explain the boundary. This produces specific feedback without rewarding confident guesses.`,
 `At OutsourcedCallers.com, this routine supports a dependable daily cadence for Filipino calling specialists: prepare, listen, document, route, and reconcile.`];return {published:'2026-09-08',mainKeyword:t.title,metaLabel:'Philippines staffing blog',directAnswerHeading:`What to do when ${t.scenario}`,summary:p[0],takeaways:[`Capture ${t.record}.`,`Do not ${t.stop}.`,`Give the open decision to the ${t.owner}.`,'Match the note to the live queue before close.'],decisionTable:[{lane:'Prepare',caller:'Checks the released brief and source.',owner:'Defines access and release rules.',measure:'Correct record is open'},{lane:'Listen',caller:'Separates the person’s words from system values.',owner:'Sets the decision boundary.',measure:'Evidence stays attributed'},{lane:'Handoff',caller:'Names the question, owner, and due time.',owner:`The ${t.owner} resolves the exception.`,measure:'No unsupported promise'},{lane:'Close',caller:'Matches the note, restriction, and queue.',owner:'Records the final disposition.',measure:'Systems agree'}],planningBands:[{label:'Source',value:'Checked',note:'Released record'},{label:'Boundary',value:'Clear',note:'No guesswork'},{label:'Owner',value:'Named',note:t.owner},{label:'Queue',value:'Matched',note:'Close review'}],sections:[{heading:'Start with the released record',paragraphs:p.slice(0,2)},{heading:'Explain the boundary without sounding evasive',paragraphs:p.slice(2,3)},{heading:'Make the handoff answerable',paragraphs:p.slice(3,4)},{heading:'Reconcile every system before close',paragraphs:p.slice(4,5)},{heading:'Coach the evidence, not the personality',paragraphs:p.slice(5)}],scripts:[{title:'Pause',text:'I can record that request, but I cannot make that change from this call brief.'},{title:'Handoff',text:`I will send the facts and open question to the ${t.owner}.`},{title:'Close',text:'I have noted what changed and the next permitted step.'}],workflow:[{step:'1',title:'Open',text:'Check the approved source.'},{step:'2',title:'Listen',text:'Attribute each new fact.'},{step:'3',title:'Pause',text:'Hold the stated boundary.'},{step:'4',title:'Route',text:`Assign the ${t.owner}.`},{step:'5',title:'Match',text:'Reconcile the queue.'}],faqs:[{q:'What can the caller decide?',a:'The caller can choose the accurate approved result and route, but cannot make the owner decision.'},{q:'What makes the note useful?',a:`It preserves ${t.record}, the open question, an owner, and a due time.`},{q:'What happens while review is pending?',a:'Keep the record in its defined review state and resume only after an authorized decision is recorded.'}],related:[{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Customer follow-up calls',href:'/services/customer-follow-up-calls'},{label:'Call quality review',href:'/services/call-quality-review'}],sources,image:'/thank-you-hero.png'};}
export const sep08BlogPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:10,published:'2026-09-08',image:'/thank-you-hero.png'}));
export const sep08BlogDetails=Object.fromEntries(topics.map(t=>[t.slug,detail(t)]));
