type Topic = { slug:string; title:string; excerpt:string; lane:string; situation:string; facts:string; owner:string; forbidden:string; opening:string; detail:string };

const topics: Topic[] = [
  {slug:'appointment-setting-time-zone-readback-routine',title:'Appointment setting time zone readback routine',excerpt:'A short confirmation routine that prevents a convenient meeting time from becoming the wrong meeting time.',lane:'appointment setting',situation:'a prospect and calendar owner may be speaking from different time zones',facts:'the stated local time, named time zone, calendar time, date, and attendee',owner:'calendar owner',forbidden:'guess a location from the phone number or silently convert an ambiguous time',opening:'Before I save this, I will read the time back with the date and time zone.',detail:'A 9:00 meeting is not fully specified until the record says whose 9:00 it is.'},
  {slug:'outbound-call-voicemail-name-mismatch-stop',title:'Outbound call voicemail name mismatch stop',excerpt:'What a caller should do when the voicemail greeting and the outbound record name do not agree.',lane:'outbound calling',situation:'the voicemail greeting names someone other than the person on the released record',facts:'the dialed number, source record, greeting name if permitted, attempt time, and stopped disposition',owner:'campaign data owner',forbidden:'leave a message for the intended person or assume the number still reaches them',opening:'The greeting does not match the record, so I will stop this attempt and flag the number for review.',detail:'A voicemail mismatch is evidence about the number, not permission to investigate its current holder.'},
  {slug:'customer-follow-up-promised-callback-missed-route',title:'Customer follow-up missed callback recovery route',excerpt:'A practical recovery path when a promised owner callback did not happen on time.',lane:'customer follow-up',situation:'a customer says an expected callback never arrived',facts:'the original promise, due time, named owner, customer availability, and current question',owner:'customer operations owner',forbidden:'invent a reason for the miss or promise a new time without owner confirmation',opening:'I can see the callback was expected. I will confirm the open question and send the missed commitment to the owner.',detail:'The recovery note should preserve the first commitment instead of replacing it with a fresh vague promise.'},
  {slug:'inbound-call-transfer-returned-to-queue',title:'Inbound call transfer returned to queue',excerpt:'How to handle a transferred call that comes back unanswered without making the caller repeat everything.',lane:'inbound call handling',situation:'a live transfer returns to reception because the destination did not answer',facts:'the intended recipient, transfer time, caller purpose, callback details, and urgency in the caller\'s words',owner:'receiving team owner',forbidden:'claim the recipient is unavailable for a specific reason or loop the transfer indefinitely',opening:'The transfer came back unanswered. I have your original details, so I only need to confirm the best next step.',detail:'A returned transfer is a routing event. It should not erase the intake already completed.'},
  {slug:'lead-qualification-budget-refusal-note',title:'Lead qualification budget refusal note',excerpt:'A respectful way to record that a prospect declined a budget question without treating the refusal as a failed lead.',lane:'lead qualification',situation:'a prospect will discuss the need but declines to state a budget',facts:'the question asked, the refusal wording, known requirements, decision participants, and agreed next action',owner:'sales owner',forbidden:'pressure for a number, infer purchasing power, or label the prospect unqualified on that fact alone',opening:'That is fine. I will record that budget was not discussed and continue only with the approved questions.',detail:'Unknown and refused are different data states. A useful qualification record keeps them separate.'},
  {slug:'database-verification-former-employee-contact',title:'Database verification former employee contact',excerpt:'A controlled correction path when a business says the listed contact no longer works there.',lane:'database verification',situation:'the person reached says the named contact has left the organization',facts:'the source record, correction received, whether a replacement was volunteered, and the verification date',owner:'data steward',forbidden:'solicit personal details about the former employee or overwrite the authoritative record',opening:'Thank you. I will mark the contact for review and will not ask for personal information about the former employee.',detail:'The call can establish that the current route is disputed. It does not establish why the person left.'},
  {slug:'renewal-reminder-contract-owner-changed',title:'Renewal reminder contract owner changed',excerpt:'A clean handoff when the person responsible for a renewal has changed since the list was prepared.',lane:'renewal reminders',situation:'the listed renewal contact says another person now owns the contract',facts:'the contract reference, prior contact, new role or routing detail volunteered, renewal date, and contact preference',owner:'account owner',forbidden:'disclose contract terms to an unverified replacement or transfer account authority',opening:'I can record the new routing detail, but the account owner must verify access before contract information is shared.',detail:'A new job title does not by itself grant access to account or pricing details.'},
  {slug:'order-confirmation-address-correction-boundary',title:'Order confirmation address correction boundary',excerpt:'A caller script and handoff for delivery address corrections that arrive during confirmation.',lane:'order confirmation',situation:'a customer gives a delivery address different from the released order',facts:'the order reference, identity check state, original address identifier, requested correction, and dispatch deadline',owner:'fulfillment owner',forbidden:'edit the order, repeat unnecessary address data, or guarantee rerouting',opening:'I can record the requested address correction. Fulfillment must confirm whether the order can still be changed.',detail:'Read back only the minimum address information needed for confirmation, especially on a shared line.'},
  {slug:'survey-call-partial-completion-close',title:'Survey call partial completion close',excerpt:'How to close and code a survey when the respondent stops after answering only some questions.',lane:'survey calling',situation:'a respondent ends the interview before the questionnaire is complete',facts:'the last completed question, stop wording, completion status, consent state, and time ended',owner:'survey method owner',forbidden:'fill unanswered items, convert the record to a refusal without the defined rule, or restart persuasion',opening:'Thank you for the answers you chose to provide. I will close the survey here.',detail:'Partial completion should remain visible so analysts can distinguish it from a completed interview or no contact.'},
  {slug:'win-back-call-current-customer-discovery',title:'Win-back call current customer discovery',excerpt:'A stop rule for a win-back record when the person says they are already a current customer.',lane:'win-back calling',situation:'a former-customer list reaches someone who says the relationship is active',facts:'the campaign source, customer statement, account reference if volunteered, call time, and suppressed campaign state',owner:'retention data owner',forbidden:'continue the win-back offer, discuss account status, or decide which database is correct',opening:'Thank you for correcting that. I will stop the win-back message and send the record for account review.',detail:'The response exposes a list conflict. It is not an invitation to review the active account on a campaign call.'},
  {slug:'reception-overflow-repeat-caller-linking',title:'Reception overflow repeat caller linking',excerpt:'A note pattern for linking repeat messages while keeping each call and its stated urgency intact.',lane:'reception overflow',situation:'a caller contacts the overflow line again about an unresolved message',facts:'the earlier message reference, new call time, changed details, requested recipient, and urgency stated now',owner:'receiving business owner',forbidden:'merge away the second contact or raise urgency solely because the caller called twice',opening:'I found the earlier message. I will link today\'s update so the recipient can see what changed.',detail:'A repeat call adds an event to the history. The second note should not overwrite what the caller said first.'},
  {slug:'call-quality-review-audio-gap-disposition',title:'Call quality review audio gap disposition',excerpt:'A fair review method when part of a recorded call is missing or unintelligible.',lane:'call quality review',situation:'a scorecard item depends on audio that the reviewer cannot hear',facts:'the affected timestamp, missing duration, scorecard item, other available evidence, and review status',owner:'quality lead',forbidden:'score the inaudible moment as a caller failure or reconstruct words from the later outcome',opening:'This item cannot be observed in the available audio, so I will mark it unscorable and request the approved review path.',detail:'Unscorable is a finding about evidence quality, not a neutral score for caller performance.'}
];

const sources = [
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'},
  {name:'National Privacy Commission of the Philippines',url:'https://privacy.gov.ph/data-privacy-act/'}
];

function makeDetail(t: Topic) {
  const paragraphs = [
    `${t.detail} Use this routine when ${t.situation}. In ${t.lane}, the caller's job is to preserve the record and make the next action obvious.`,
    `Start with the released call purpose and the fields the caller may use. Capture ${t.facts}. If the source and the conversation disagree, keep both versions rather than smoothing the conflict away.`,
    `Say what happened in plain language. Quote a short phrase when the exact wording affects the route. Otherwise, summarize the request without adding a motive, diagnosis, or prediction.`,
    `The caller must not ${t.forbidden}. That boundary belongs in the script, not only in a training deck, because the difficult moment happens while another person is waiting on the line.`,
    `Give the ${t.owner} a note that can be acted on without replaying the conversation. Include the record identifier, the new evidence, the unresolved decision, the requested response channel, and any real deadline.`,
    `Choose a specific queue state after the call. Awaiting owner review, correction requested, contact stopped, and closed are more useful than a generic escalated label. Add the owner and review due time.`,
    `At daily close, compare the note with the live queue. Confirm that restrictions reached the active list and that open decisions still have an owner. The note is only half the control; the system state must agree with it.`,
    `Coach this situation with one real example. Ask the caller to point to the source fact, the fact learned on the call, and the decision they deliberately left with the owner. Repair the exact field or script line that caused confusion.`,
    `For OutsourcedCallers.com teams, this split lets Filipino callers handle careful conversations and accountable notes while the client keeps authority over policy, accounts, pricing, sensitive data, and exceptions.`
  ];
  return {published:'2026-09-02',mainKeyword:t.title,metaLabel:'Philippines staffing blog',directAnswerHeading:`How to respond when ${t.situation}`,
    summary:paragraphs[0],takeaways:[`Record ${t.facts}.`,'Keep source data separate from the caller response.',`Route the unresolved decision to the ${t.owner}.`,'Reconcile the queue after review.'],
    decisionTable:[
      {lane:'Prepare',caller:'Checks purpose, permitted fields, and current source.',owner:'Releases the queue and boundary.',measure:'Source and script version are visible'},
      {lane:'Listen',caller:'Records the response without inference.',owner:'Defines which evidence changes the route.',measure:'Observed facts stay separate'},
      {lane:'Stop point',caller:'Uses the approved boundary and handoff.',owner:`The ${t.owner} decides the exception.`,measure:'No unsupported promise'},
      {lane:'Close',caller:'Checks the note against the queue.',owner:'Records the final decision and reason.',measure:'Queue and review state agree'}],
    planningBands:[{label:'Purpose',value:'Checked',note:t.lane},{label:'Evidence',value:'Named',note:'Source plus response'},{label:'Owner',value:'Assigned',note:t.owner},{label:'Queue',value:'Matched',note:'Final state'}],
    sections:[{heading:'Read the source before responding',paragraphs:paragraphs.slice(0,2)},{heading:'Record the difference without inventing context',paragraphs:paragraphs.slice(2,4)},{heading:'Send a decision-ready handoff',paragraphs:paragraphs.slice(4,6)},{heading:'Check the live queue at close',paragraphs:paragraphs.slice(6,7)},{heading:'Coach the boundary from a real call',paragraphs:paragraphs.slice(7)}],
    scripts:[{title:'Opening',text:t.opening},{title:'Boundary',text:'I can record the correction, but I cannot approve the account or policy change from this call.'},{title:'Close',text:`I have sent the open decision to the ${t.owner} through the approved route.`}],
    workflow:[{step:'1',title:'Check',text:'Read the released purpose and source.'},{step:'2',title:'Hear',text:'Capture the person\'s own words.'},{step:'3',title:'Separate',text:'Preserve both source and response.'},{step:'4',title:'Route',text:`Assign the decision to the ${t.owner}.`},{step:'5',title:'Match',text:'Reconcile the note and queue.'}],
    faqs:[{q:'What may the caller decide?',a:'The caller may choose the accurate call result and approved route. The business owner decides exceptions and authoritative changes.'},{q:'What belongs in the handoff?',a:`Include ${t.facts}, the unresolved decision, requested response, and named owner.`},{q:'What if the owner has not replied?',a:'Keep the record awaiting review, surface it in the exception report, and do not replace the owner decision with a caller guess.'}],
    related:[{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Inbound call handling',href:'/services/inbound-call-handling'},{label:'Call quality review',href:'/services/call-quality-review'}],sources};
}

export const sep02BlogPosts = topics.map((t) => ({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:10,published:'2026-09-02',image:''}));
export const sep02BlogDetails = Object.fromEntries(topics.map((t) => [t.slug,makeDetail(t)]));
