type Topic={slug:string;title:string;excerpt:string;question:string;unit:string;comparison:string;limit:string;fields:string};
const topics:Topic[]=[
 {slug:'appointment-confirmation-channel-reliability-research',title:'Which appointment confirmation channel is most reliable?',excerpt:'A cautious study design for comparing confirmation outcomes without confusing channel choice with attendee intent.',question:'whether email, SMS, or a live call produces a usable confirmation record',unit:'one scheduled meeting and its permitted confirmation attempts',comparison:'delivery, reply, calendar acceptance, correction, and attendance events',limit:'observational results cannot prove that the channel caused attendance',fields:'meeting ID, channel permission, attempt time, delivery state, response, correction, and attendance'},
 {slug:'outbound-list-age-contactability-research',title:'How does outbound list age relate to contactability?',excerpt:'A research plan for measuring list decay while separating stale records from calling execution.',question:'how contact outcomes change as the interval since source verification grows',unit:'one released contact record and its approved attempt sequence',comparison:'age bands, source types, wrong-party results, unreachable closes, and verified conversations',limit:'contactability does not establish consent, lead quality, or commercial fit',fields:'source, verification date, release date, attempt count, outcomes, suppression state, and correction'},
 {slug:'customer-callback-window-adherence-research',title:'How should callback-window adherence be measured?',excerpt:'An evidence model for testing whether promised callbacks occur inside the window the customer actually accepted.',question:'whether the operational record preserves and meets customer callback commitments',unit:'one accepted callback window, owner assignment, attempts, and final outcome',comparison:'on-time attempts, early attempts, late attempts, rescheduled windows, and unattempted commitments',limit:'an attempt inside the window does not prove the customer received a resolution',fields:'promise source, local time zone, window bounds, owner, attempt timestamp, result, and follow-on action'},
 {slug:'bilingual-survey-breakoff-patterns-research',title:'How can bilingual survey breakoff patterns be studied?',excerpt:'A method for examining where respondents stop while avoiding claims about language preference that the data cannot support.',question:'whether breakoff points differ across approved language versions and routing paths',unit:'one sampled respondent, chosen language, question sequence, and end state',comparison:'completed interviews, respondent stops, technical interruptions, and language-transfer failures',limit:'differences between language groups may reflect sampling, topic, interviewer, or access effects',fields:'sample source, language choice, version, interviewer, timestamps, last completed item, stop code, and retry'},
 {slug:'quality-review-adjudication-drift-research',title:'How can teams detect quality-review adjudication drift?',excerpt:'A repeatable design for checking whether QA interpretations change after disputed scores are resolved.',question:'whether adjudication decisions are applied consistently in later reviews',unit:'one disputed score, cited evidence, adjudicated rule, and a later blind sample',comparison:'reviewers, scorecard versions, call lanes, criteria, and periods before and after adjudication',limit:'agreement can reflect shared bias and should not be treated as proof that a rule is valid',fields:'sample ID, reviewer, version, criterion, initial score, evidence timestamp, adjudication, and later score'}
];
const sources='Sources: NIST Privacy Framework (https://www.nist.gov/privacy-framework); FTC Telemarketing Sales Rule (https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule); AAPOR Best Practices (https://aapor.org/standards-and-ethics/best-practices/); Philippines Data Privacy Act guidance (https://privacy.gov.ph/data-privacy-act/).';
function body(t:Topic){return [`Published: September 4, 2026. This note asks ${t.question}. It is a measurement design for OutsourcedCallers.com operations, not a claim that one workflow is universally best.`,`Define the unit as ${t.unit}. Freeze eligibility rules before reviewing results, and include unsuccessful as well as successful contacts so the sample does not quietly become a success-only report.`,`Collect ${t.fields}. Minimize identifiers, restrict access, document retention, and preserve suppression or consent controls independently of the study dataset.`,`Compare ${t.comparison}. Report counts and denominators for every group. Use confidence intervals when the sample supports them, and show missingness rather than silently dropping incomplete records.`,`Evidence scope: the analysis can describe associations inside the released sample and period. ${t.limit}. Seasonality, list source, customer mix, caller assignment, and workflow changes may also explain an observed difference.`,`Run a small pilot and have a second reviewer test ambiguous classifications without seeing the first decision. Publish the codebook, exclusions, changes made after launch, and disagreements that remain unresolved.`,`Operational use should stay narrow: use the finding to choose the next controlled test, improve a field definition, or identify a handoff for review. Do not turn a descriptive difference into a promise about an individual call.`,sources];}
export const sep04ResearchPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,published:'2026-09-04',image:'/thank-you-hero.png',body:body(t)}));
