type Topic={slug:string;title:string;excerpt:string;scenario:string;record:string;owner:string;stop:string};

const topics:Topic[]=[
 {slug:'appointment-setting-double-booking-recovery',title:'Appointment setting double-booking recovery routine',excerpt:'A practical caller routine for resolving two meetings placed in the same calendar window.',scenario:'a calendar shows two accepted meetings in the same slot',record:'both invitation identifiers, attendee replies, time zones, and the calendar conflict',owner:'calendar owner',stop:'cancel, move, or rank either meeting'},
 {slug:'outbound-calling-consent-source-missing-stop',title:'Outbound calling missing consent source stop',excerpt:'What a caller should record when a released lead has no visible outreach basis.',scenario:'the dialing record lacks the campaign consent or lawful-basis field required by the brief',record:'list name, record identifier, missing field, release time, and stopped state',owner:'campaign compliance owner',stop:'dial the record or reconstruct consent from unrelated notes'},
 {slug:'customer-follow-up-owner-out-of-office-route',title:'Customer follow-up owner out-of-office route',excerpt:'A clear handoff when a promised follow-up owner is away and the customer still needs an answer.',scenario:'the assigned owner is unavailable beyond a customer commitment',record:'the original question, promise, due time, absence notice, and customer contact preference',owner:'customer operations lead',stop:'explain the absence or invent a replacement deadline'},
 {slug:'inbound-call-shared-mailbox-verification',title:'Inbound call shared mailbox verification',excerpt:'A short check before routing caller details to a shared team inbox.',scenario:'a caller asks for a message to be sent to a shared mailbox',record:'caller purpose, intended team, approved mailbox label, sensitivity flag, and callback route',owner:'reception owner',stop:'send sensitive details to an address supplied only by the caller'},
 {slug:'lead-qualification-decision-timeline-unknown',title:'Lead qualification unknown decision timeline note',excerpt:'How to preserve an unknown buying timeline without forcing a speculative date.',scenario:'a prospect understands the need but cannot name a decision date',record:'stated need, timing answer, known participants, dependency, and agreed next action',owner:'sales owner',stop:'convert uncertainty into a forecast date'},
 {slug:'database-verification-duplicate-phone-owner-review',title:'Database verification duplicate phone owner review',excerpt:'A controlled review when one phone number appears on several business records.',scenario:'the same number is attached to records with different names or organizations',record:'record identifiers, source systems, last-verified dates, call result, and conflict',owner:'data steward',stop:'merge records or decide which identity is authoritative'},
 {slug:'renewal-reminder-payment-question-handoff',title:'Renewal reminder payment question handoff',excerpt:'A safe boundary when a routine renewal reminder turns into a payment-status question.',scenario:'the contact asks whether a payment was received or an account balance is correct',record:'account reference, question in the contact’s words, reminder date, verification state, and response preference',owner:'account owner',stop:'confirm payment, balance, or account standing'},
 {slug:'order-confirmation-substitution-request-route',title:'Order confirmation substitution request route',excerpt:'A caller workflow for recording a requested item substitution without promising fulfillment.',scenario:'a customer requests a different product during an order-confirmation call',record:'order reference, original item, requested substitute, quantity, reason volunteered, and dispatch cutoff',owner:'fulfillment owner',stop:'edit inventory, approve pricing, or guarantee the substitution'},
 {slug:'survey-calling-language-switch-consent',title:'Survey calling language-switch consent check',excerpt:'How to pause and confirm participation when a respondent requests another language.',scenario:'a respondent asks to continue the survey in a different language',record:'requested language, consent state, completed question, interpreter or queue availability, and close code',owner:'survey method owner',stop:'improvise translated questions or infer answers'},
 {slug:'win-back-offer-expired-script-stop',title:'Win-back expired offer script stop',excerpt:'A clean stop when the approved win-back offer has passed its validity window.',scenario:'the campaign script contains an offer whose end date has passed',record:'campaign version, offer identifier, expiry date, record identifier, and queue pause time',owner:'retention campaign owner',stop:'extend the offer or substitute different terms'},
 {slug:'reception-overflow-emergency-claim-boundary',title:'Reception overflow emergency claim boundary',excerpt:'A routing routine for urgent claims without asking a caller to prove the emergency.',scenario:'a caller describes an emergency on a business overflow line',record:'the caller’s exact urgency words, location if volunteered, callback number, intended recipient, and route time',owner:'receiving business owner',stop:'diagnose risk, promise a response time, or replace emergency services'},
 {slug:'call-quality-review-script-version-mismatch',title:'Call quality review script-version mismatch',excerpt:'A fair QA method when the caller and reviewer were given different script versions.',scenario:'a reviewed call used a script version different from the scorecard reference',record:'call time, caller version, reviewer version, affected criteria, evidence, and adjudication state',owner:'quality lead',stop:'score version-dependent wording as an individual failure'}
];

const sources=[{name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},{name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'},{name:'Philippines National Privacy Commission',url:'https://privacy.gov.ph/data-privacy-act/'}];
function detail(t:Topic){const p=[
 `Use this routine when ${t.scenario}. The immediate job is to keep the conversation accurate while protecting the decision that still belongs to the ${t.owner}.`,
 `Before responding, open the released brief and capture ${t.record}. Keep what the system said separate from what the person said; a neat note is not useful if it erases the conflict.`,
 `The caller must not ${t.stop}. Say the boundary plainly, record the unresolved question, and use the route already approved for this call lane.`,
 `A decision-ready handoff names the record, new evidence, requested outcome, true deadline, and ${t.owner}. Avoid labels such as urgent unless the caller’s own words or the operating rule supports them.`,
 `At shift close, compare the call note with the live queue. Confirm the restriction, owner, due time, and next permitted action. If the systems disagree, leave the record paused and surface the mismatch.`,
 `Coach the case from one real sample. Ask which fact was observed, which was inherited from the source, and which decision was deliberately left open. That makes feedback specific without rewarding guesses.`,
 `For OutsourcedCallers.com, this routine gives Filipino calling specialists a repeatable daily habit: prepare the record, speak within the brief, document the result, and send exceptions to the client owner.`];return {published:'2026-09-04',mainKeyword:t.title,metaLabel:'Philippines staffing blog',directAnswerHeading:`What to do when ${t.scenario}`,summary:p[0],takeaways:[`Capture ${t.record}.`,`Do not ${t.stop}.`,`Assign the open decision to the ${t.owner}.`,'Reconcile the note with the live queue.'],decisionTable:[{lane:'Prepare',caller:'Checks the source and approved brief.',owner:'Defines access and release rules.',measure:'Correct version is visible'},{lane:'Respond',caller:'Records observed facts without inference.',owner:'Sets the decision boundary.',measure:'Source and response stay separate'},{lane:'Handoff',caller:'Names the question, owner, and due time.',owner:`The ${t.owner} decides the exception.`,measure:'No unsupported promise'},{lane:'Close',caller:'Matches note, restriction, and queue.',owner:'Records the final disposition.',measure:'Systems agree'}],planningBands:[{label:'Source',value:'Checked',note:'Released record'},{label:'Boundary',value:'Stated',note:'No guesswork'},{label:'Owner',value:'Named',note:t.owner},{label:'Queue',value:'Matched',note:'Close review'}],sections:[{heading:'Read the released record first',paragraphs:p.slice(0,2)},{heading:'Hold the decision boundary',paragraphs:p.slice(2,3)},{heading:'Build a handoff someone can act on',paragraphs:p.slice(3,4)},{heading:'Reconcile the queue before close',paragraphs:p.slice(4,5)},{heading:'Coach from evidence',paragraphs:p.slice(5)}],scripts:[{title:'Pause',text:'I need to pause here because this decision is outside the approved call brief.'},{title:'Handoff',text:`I will record the facts and send the open question to the ${t.owner}.`},{title:'Close',text:'I have recorded what changed and the permitted next step.'}],workflow:[{step:'1',title:'Open',text:'Check the released source.'},{step:'2',title:'Compare',text:'Separate source and response.'},{step:'3',title:'Pause',text:'Apply the approved stop.'},{step:'4',title:'Route',text:`Assign the ${t.owner}.`},{step:'5',title:'Match',text:'Reconcile the queue.'}],faqs:[{q:'What can the caller decide?',a:'The caller can select the accurate result and approved route, but cannot make the owner decision.'},{q:'What makes the handoff useful?',a:`It includes ${t.record}, the unresolved question, an owner, and a real due time.`},{q:'What happens while review is pending?',a:'Keep the record in the defined review state and do not resume work until the authorized decision is recorded.'}],related:[{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Inbound call handling',href:'/services/inbound-call-handling'},{label:'Call quality review',href:'/services/call-quality-review'}],sources,image:'/thank-you-hero.png'};}
export const sep04BlogPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:10,published:'2026-09-04',image:'/thank-you-hero.png'}));
export const sep04BlogDetails=Object.fromEntries(topics.map(t=>[t.slug,detail(t)]));
