type Topic = { slug:string; title:string; excerpt:string; lane:string; trigger:string; evidence:string; owner:string; limit:string; opening:string };

const topics: Topic[] = [
  {slug:'appointment-setting-agenda-change-confirmation',title:'Appointment setting agenda change confirmation',excerpt:'A caller-ready routine for recording a changed meeting agenda without silently replacing the purpose the attendee accepted.',lane:'appointment setting',trigger:'an attendee changes the meeting agenda after accepting a time',evidence:'the original purpose, requested change, participants, and open questions',owner:'calendar owner',limit:'approve a new agenda or speak for other participants',opening:'I have the original meeting purpose here. May I record what you would like changed?'},
  {slug:'customer-follow-up-unresolved-answer-handoff',title:'Customer follow-up unresolved answer handoff',excerpt:'How to return an unanswered customer question to a named owner with enough context for a useful response.',lane:'customer follow-up',trigger:'the approved information does not answer the customer\'s question',evidence:'the exact question, information already provided, and requested reply channel',owner:'customer account owner',limit:'invent an answer or imply that silence means approval',opening:'I do not have an approved answer for that point, but I can record the question for the account owner.'},
  {slug:'inbound-call-caller-identity-uncertainty-note',title:'Inbound call caller identity uncertainty note',excerpt:'A practical note format for inbound callers whose identity cannot be confirmed through the released reception process.',lane:'inbound call handling',trigger:'the caller gives details that do not match the available record',evidence:'the check attempted, fields that differed, stated purpose, and safe reply route',owner:'reception security owner',limit:'disclose account details or decide that a near match is good enough',opening:'I cannot confirm the record from the details available, so I will note the request without discussing the account.'},
  {slug:'outbound-calling-wrong-number-suppression-route',title:'Outbound calling wrong-number suppression route',excerpt:'A clean workflow for removing a wrong number from the active queue while preserving the correction for list owners.',lane:'outbound calling',trigger:'the person reached says the number belongs to someone else',evidence:'the dialed number, source record, response, timestamp, and suppression state',owner:'campaign data owner',limit:'ask the new holder for the intended person or keep retrying the number',opening:'Thank you for correcting the record. I will mark this number so it is not used for this contact again.'},
  {slug:'lead-qualification-decision-timeline-note',title:'Lead qualification decision timeline note',excerpt:'A bounded way to capture buying timeline language without converting interest into a forecast or commitment.',lane:'lead qualification',trigger:'a prospect describes an uncertain or conditional decision date',evidence:'the prospect\'s own timing words, conditions, participants, and agreed next step',owner:'sales owner',limit:'turn a tentative date into a close forecast or promise availability',opening:'What would need to happen before that timing becomes firm?'},
  {slug:'database-verification-source-conflict-escalation',title:'Database verification source conflict escalation',excerpt:'A step-by-step escalation when a caller finds two credible sources that disagree on a customer field.',lane:'database verification',trigger:'two released sources show different values for the same field',evidence:'both values, their source names, timestamps, and the customer response if available',owner:'data steward',limit:'overwrite either source or declare one authoritative',opening:'I can see two different values for this field. May I read back the item we are permitted to verify?'},
  {slug:'renewal-reminder-invoice-question-handoff',title:'Renewal reminder invoice question handoff',excerpt:'How a renewal caller can capture an invoice question and route it without interpreting charges or payment terms.',lane:'renewal reminders',trigger:'a customer asks why an invoice amount or term differs from expectation',evidence:'the invoice reference, customer wording, approved reminder details, and requested response',owner:'billing owner',limit:'explain an unverified charge, change terms, or promise a credit',opening:'I can record the invoice question for billing and include the reference you are looking at.'},
  {slug:'order-confirmation-item-substitution-request',title:'Order confirmation item substitution request',excerpt:'A safe pause for order-confirmation calls when the customer asks to replace an item in the released order.',lane:'order confirmation',trigger:'the customer requests a different item, size, or variant',evidence:'the released item, requested substitute, quantity, identity state, and deadline mentioned',owner:'fulfillment owner',limit:'edit inventory, accept a price difference, or guarantee dispatch',opening:'I can record the requested substitution, but fulfillment must confirm whether the order can be changed.'},
  {slug:'survey-calling-answer-correction-log',title:'Survey calling answer correction log',excerpt:'A neutral correction routine when a respondent changes an earlier survey answer before the interview ends.',lane:'survey calling',trigger:'a respondent asks to revise an answer already recorded',evidence:'the question identifier, original response, corrected response, and point in the interview',owner:'survey method owner',limit:'persuade the respondent to keep either answer or erase the correction trail',opening:'I can update that response. I will record that you corrected it during this interview.'},
  {slug:'win-back-call-offer-eligibility-boundary',title:'Win-back call offer eligibility boundary',excerpt:'A caller boundary for former customers who ask whether they qualify for an offer not confirmed in the released brief.',lane:'win-back calling',trigger:'a former customer asks for an offer whose eligibility is unclear',evidence:'the named offer, released eligibility fields, customer question, and prior account reference',owner:'retention owner',limit:'declare eligibility, extend an expiry date, or improvise a discount',opening:'I can check the approved details in this brief and send any eligibility question to the retention owner.'},
  {slug:'reception-overflow-sensitive-message-minimization',title:'Reception overflow sensitive message minimization',excerpt:'A short intake pattern that keeps sensitive details out of an overflow message unless the receiving owner needs them.',lane:'reception overflow',trigger:'a caller begins sharing medical, financial, legal, or other sensitive context',evidence:'the minimum callback details, general purpose, urgency stated by the caller, and intended recipient',owner:'receiving business owner',limit:'solicit detailed sensitive information or repeat it across broad channels',opening:'I can take the minimum details needed for the right person to return your call.'},
  {slug:'call-quality-review-disputed-score-note',title:'Call quality review disputed score note',excerpt:'A review note that records why a caller or manager disputes a score and what evidence will settle the point.',lane:'call quality review',trigger:'a caller or reviewer challenges one scored item',evidence:'the scorecard item, cited call moment, released instruction, reviewer rationale, and final decision',owner:'quality lead',limit:'change the score without a reason or treat a disagreement as misconduct',opening:'Let us tie this item to the call evidence and the instruction that applied at that time.'}
];

const sources = [
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'FTC Telemarketing Sales Rule',url:'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule'},
  {name:'FCC consumer guidance on unwanted calls',url:'https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts'}
];

function makeDetail(topic: Topic) {
  const p = [
    `This ${topic.title.toLowerCase()} applies when ${topic.trigger}. In ${topic.lane}, the useful outcome is an accurate record and a clear next owner. Capture ${topic.evidence}.`,
    `Check the released queue before responding. Confirm the purpose, script version, contact preference, and fields the caller may see. If the record no longer supports this call, place it on hold and tell the ${topic.owner} why.`,
    `Use the person's own words for the disputed or changed detail. Keep the source value separate from what was heard on the call. That separation lets the next reviewer see whether the issue came from an old record, a misunderstanding, or a new request.`,
    `The caller must not ${topic.limit}. A natural conversation can still stay inside a firm boundary. State what can be recorded, then route the remaining decision without suggesting an outcome.`,
    `A usable note starts with the record identifier and call purpose. It then shows the evidence received, any uncertainty, the requested response, and the ${topic.owner}. Leave out background that the owner does not need to decide the next step.`,
    `Set a real status after the handoff: awaiting review, returned for clarification, approved action, declined action, or closed. Add the responsible person and due point. "Escalated" alone does not tell anyone whether the work reached the right desk.`,
    `During the daily close, compare the call note with the queue state. Check that the open request still has an owner and that a suppression or correction reached every relevant list. A completed note is not proof of a completed owner action.`,
    `Review one example after training and another after the caller encounters the situation live. If the same confusion returns, adjust the field definition, script line, or route. General reminders rarely repair a specific process gap.`,
    `For OutsourcedCallers.com teams, this division keeps Filipino callers responsible for careful communication and faithful records. The client retains decisions about accounts, policy, pricing, sensitive data, and exceptions. The handoff shows exactly where one responsibility ends and the next begins.`
  ];
  return {
    published:'2026-09-01', mainKeyword:topic.title, metaLabel:'Philippines staffing blog', directAnswerHeading:`What to do when ${topic.trigger}`,
    summary:p[0], takeaways:['Check the purpose and permitted fields first.',`Preserve ${topic.evidence}.`,'Keep observations separate from owner decisions.',`Send the unresolved action to the ${topic.owner}.`],
    decisionTable:[
      {lane:'Before contact',caller:'Checks the queue, purpose, and preferences.',owner:'Releases the brief and permitted fields.',measure:'Current source and script are visible'},
      {lane:'During contact',caller:'Records the person\'s words and uncertainty.',owner:'Defines the allowed response.',measure:'Evidence is separate from inference'},
      {lane:'At the boundary',caller:'Pauses and creates a complete handoff.',owner:`The ${topic.owner} decides the request.`,measure:'No unsupported commitment'},
      {lane:'After review',caller:'Uses the returned decision in later work.',owner:'Records the final state and reason.',measure:'Queue and owner state agree'}
    ],
    planningBands:[{label:'Purpose',value:'Released',note:topic.lane},{label:'Evidence',value:'Separated',note:'Source and call'},{label:'Decision',value:'Assigned',note:topic.owner},{label:'Close',value:'Reconciled',note:'Note and system state'}],
    sections:[
      {heading:'Check the released call purpose',paragraphs:p.slice(0,2)},
      {heading:'Write down evidence without filling gaps',paragraphs:p.slice(2,4)},
      {heading:'Build a handoff another person can use',paragraphs:p.slice(4,6)},
      {heading:'Reconcile the note with the final state',paragraphs:p.slice(6,7)},
      {heading:'Coach from a real example',paragraphs:p.slice(7)}
    ],
    scripts:[{title:'Opening',text:topic.opening},{title:'Boundary',text:'I can record that request, but I cannot approve the change from this call.'},{title:'Close',text:`I have sent the open point to the ${topic.owner} through the approved route.`}],
    workflow:[{step:'1',title:'Check',text:'Confirm purpose and access.'},{step:'2',title:'Listen',text:'Capture the person\'s wording.'},{step:'3',title:'Separate',text:'Keep source, response, and uncertainty distinct.'},{step:'4',title:'Route',text:`Assign the decision to the ${topic.owner}.`},{step:'5',title:'Reconcile',text:'Compare the note with the final state.'}],
    faqs:[{q:'What does the caller decide?',a:'The caller chooses the accurate result label and prepares the approved handoff. The business owner decides exceptions and system changes.'},{q:'How much context belongs in the note?',a:`Include the call purpose, ${topic.evidence}, uncertainty, requested response, and named owner.`},{q:'What if the owner does not respond?',a:'Keep the item in an awaiting-review state, surface it in the exception report, and do not substitute a caller decision.'}],
    related:[{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Customer follow-up calls',href:'/services/customer-follow-up-calls'},{label:'Call quality review',href:'/services/call-quality-review'}], sources
  };
}

export const sep01BlogPosts = topics.map((topic) => ({slug:topic.slug,title:topic.title,excerpt:topic.excerpt,minutes:10,published:'2026-09-01',image:''}));
export const sep01BlogDetails = Object.fromEntries(topics.map((topic) => [topic.slug, makeDetail(topic)]));
