type Study={slug:string;title:string;excerpt:string;question:string;unit:string;caseStudy:string;risk:string;owner:string;limits:string;sources:string[]};
const studies:Study[]=[
{slug:'inbound-repeat-contact-linkage-research',title:'When should two inbound calls be treated as the same unresolved request?',excerpt:'Research on linking repeat inbound contacts without erasing corrections or creating duplicate owner work.',question:'When should two inbound calls be linked as one continuing request rather than recorded as unrelated work',unit:'an initial message, each later contact referring to it, changed facts, assignments, and the final decision',caseStudy:'A customer calls about delivery, then calls later to correct the order reference and request email instead of a return call.',risk:'duplicate tasks reach different owners, or a materially different request disappears under an older ticket',owner:'inbound message owner',limits:'Shared numbers weaken identity inference, people describe the same matter differently, and linkage cannot prove identity.',sources:['https://www.nist.gov/privacy-framework','https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business','https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm']},
{slug:'outbound-script-disclosure-order-recall-research',title:'Does disclosure order change what a person understands on an outbound call?',excerpt:'A study design for testing whether callers state identity, purpose, and choice in an order people can follow.',question:'Does the order of caller identity, business purpose, and contact choice affect accurate recall',unit:'an eligible conversation, script version, opening actually spoken, response, clarification, and disposition',caseStudy:'One approved opening names the business before its purpose; another gives the purpose first, then names the business before asking whether the person can continue.',risk:'a shorter opening is rewarded although people misunderstand who is calling or why',owner:'campaign policy owner',limits:'Tone, prior familiarity, audio quality, language, list source, and call purpose may affect recall.',sources:['https://www.ftc.gov/business-guidance/advertising-marketing/telemarketing','https://www.fcc.gov/consumers/guides/stop-unwanted-robocalls-and-texts','https://www.nist.gov/privacy-framework']},
{slug:'customer-followup-promised-action-ownership-research',title:'What evidence makes a promised follow-up action accountable?',excerpt:'Research separating a customer request, a caller note, and an owner-approved commitment.',question:'What evidence shows that a follow-up action was promised and assigned rather than merely mentioned',unit:'a request, permitted response, saved action, accepting owner, due point, and eventual disposition',caseStudy:'A customer requests an account correction by Friday. The caller records the request but cannot promise approval or completion by that date.',risk:'a customer expects work nobody owns while the caller is judged against an unauthorized commitment',owner:'customer follow-up owner',limits:'A note cannot prove customer understanding, downstream work may occur elsewhere, and no public source sets a universal response time.',sources:['https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm','https://www.nist.gov/privacy-framework','https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business']},
{slug:'survey-breakoff-position-bias-research',title:'What can the point of survey breakoff reveal about the calling instrument?',excerpt:'A method for studying where respondents stop without recoding partial interviews as failures.',question:'Can the question position where a respondent stops reveal burden, sensitivity, or routing defects',unit:'an eligible contact, instrument version, answered items, breakoff point, duration, and response code',caseStudy:'Several respondents answer service-use questions but stop when the instrument unexpectedly shifts to a detailed household question.',risk:'a survey caller receives coaching for respondent behavior while the instrument contains a confusing transition',owner:'survey method owner',limits:'Breakoff does not prove discomfort with the last question, small samples are unstable, and outside interruption may explain the stop.',sources:['https://aapor.org/standards-and-ethics/best-practices/','https://www.census.gov/about/policies/quality/standards.html','https://www.nist.gov/privacy-framework']},
{slug:'event-registration-waitlist-authority-research',title:'When may an event registration caller discuss a waitlist?',excerpt:'Research on capacity evidence, attendee choice, and the boundary between interest and promised admission.',question:'When does a registration caller have enough current evidence to describe a waitlist without implying a reserved place',unit:'an inquiry, released capacity state, waitlist rule, attendee choice, owner route, and admission decision',caseStudy:'An attendee asks whether joining guarantees a seat. The caller can explain notification steps but cannot predict cancellations or admission.',risk:'an expression of interest becomes a reservation or stale capacity information is repeated',owner:'event registration owner',limits:'Capacity changes quickly, systems update asynchronously, and this study cannot establish contractual obligations.',sources:['https://www.nist.gov/privacy-framework','https://www.ftc.gov/business-guidance/advertising-marketing','https://www.bls.gov/ooh/office-and-administrative-support/customer-service-representatives.htm']}
];
function body(s:Study){return [
`Published: September 3, 2026. Research question: ${s.question}? For an OutsourcedCallers.com client, the answer affects what a Filipino caller may record, what must stop, and what needs an owner decision. The evidence unit is ${s.unit}. A call count alone cannot answer the question because activity is not proof of understanding, authority, or resolution.`,
`Methodology and evidence scope: freeze a defined cohort before reviewing outcomes. Preserve dated source records, the approved purpose, script version, contact state, words spoken, caller note, assignment history, and final owner action. Compare clean cases with refusals, partial contacts, reopened records, technical interruptions, and unknown outcomes. The sources provide research, privacy, or communication principles; none measures OutsourcedCallers.com or establishes a performance benchmark.`,
`Start with what the caller could see when the record was released. Later reviewers often know more, so scoring with hindsight would be unfair. Record the source timestamp, permitted fields, current suppression state, and named route. If any item is missing, label the gap. Do not reconstruct it from the final result or assume the caller had access to information stored elsewhere.`,
`The principal risk is that ${s.risk}. The study should measure observable transitions rather than a preferred commercial result. A completed dial, friendly exchange, short handle time, or polished note does not establish that a request was understood or accepted. Every status needs evidence another reviewer can locate without guessing at the caller's intent.`,
`Consider this case: ${s.caseStudy} Code the direct statement, the released source fact, the caller's permitted response, and the unresolved decision separately. The ${s.owner} needs those distinctions to act without replaying the whole conversation. Unrelated personal details add exposure without helping the decision and should stay out of the handoff.`,
`A Filipino caller may use the approved script, ask a permitted clarification, record an answer, honor a stop request, apply an evidence-supported disposition, and send uncertainty through the released route. The caller should not invent identity, consent, urgency, eligibility, capacity, account state, commercial terms, or a future owner action. The client retains those decisions.`,
`Reviewers should separate fact from analysis. Facts include source values, spoken responses, timestamps, system events, and dated owner actions. Analysis explains why the process may have failed. Require a record citation for each factual code and retain competing explanations when the evidence cannot distinguish them. Confidence should not turn an interpretation into an observed event.`,
`Sampling only positive outcomes would distort the result. Keep wrong parties, refusals, incomplete conversations, language-route requests, missing evidence, unresolved owner work, and records later reopened. These cases reveal whether the released process handles uncertainty. They also keep the denominator stable when teams compare script versions, callers, lists, or review periods.`,
`Test reviewer agreement on a small blinded sample. Give two reviewers the same definitions and prevent them from seeing each other's codes. When they disagree, locate the missing definition or evidence field. Do not settle the dispute by choosing the more favorable result. Revise the guide, document the reason, and recode every affected case consistently.`,
`The remedy should match the stage where evidence failed. Missing context requires an intake repair. Conflicting wording requires script version control. An ownerless handoff requires a routing change. A correct note followed by a stale queue requires downstream reconciliation. Demanding more calls or faster closure cannot repair those defects and may create another unsupported action.`,
`Daily reporting should show the frozen cohort, evaluated records, exclusions with reasons, unknown states, owner reviews, and final decisions. Caller activity and client-controlled resolution belong in different columns. If the source population, script, or policy changes during the study, split the periods and disclose the break instead of blending unlike records into one rate.`,
`Role-based access is part of the research design. Show the caller only the fields and history needed for the released purpose. A broad account view can expose unrelated details and tempt an unsupported inference. The ${s.owner} should control sensitive records, authoritative changes, policy exceptions, and the decision to release another contact attempt.`,
`The review should also follow corrections over time. Preserve the original note, append the later evidence, and identify who changed the operational state. Silently rewriting the first record makes the process look cleaner but destroys the evidence needed to decide whether intake, calling, routing, or owner follow-through caused the mismatch.`,
`Limitations: ${s.limits} Jurisdiction, technology, audience, and client policy can change the permitted action. Findings apply to the sampled records and definitions, not every caller or customer. Regulated or sensitive work needs client-approved rules and appropriate professional advice.`,
`Evidence-led conclusion: the ${s.owner} should adopt a rule only when the evidence chain remains traceable from release through conversation to disposition. For OutsourcedCallers.com teams, a strong result makes uncertainty visible and gives the client a bounded decision. It does not force every contact into a success label.`,
`Sources: ${s.sources.join(' | ')}`];}
export const sep03ResearchPosts=studies.map(s=>({...s,published:'2026-09-03' as const,image:'',body:body(s)}));
