type Topic = {slug:string;title:string;excerpt:string;question:string;unit:string;comparison:string;owner:string;limit:string;fields:string};

const topics: Topic[] = [
  {slug:'appointment-setting-time-zone-error-rate-research',title:'How should teams measure appointment time zone errors?',excerpt:'A research design for finding where time zone ambiguity enters an appointment-setting workflow.',question:'where time zone ambiguity enters a meeting record and how often it survives to the final invitation',unit:'one setting conversation, its call note, the calendar draft, the sent invitation, and any correction',comparison:'an explicitly named zone, a location-only assumption, an automatic calendar conversion, and a manual correction',owner:'appointment program owner',limit:'the review cannot attribute every missed meeting to a time zone field',fields:'spoken time, spoken zone, attendee location if volunteered, calendar zone, invitation timestamp, correction event, and attendance status'},
  {slug:'outbound-wrong-party-suppression-latency-research',title:'How can teams study wrong-party suppression latency?',excerpt:'A method for measuring how long a wrong-party report remains exposed to another outbound attempt.',question:'how quickly a wrong-party response moves from the call note into every active dialing list',unit:'one dialed number, the source records that contain it, the wrong-party event, suppression writes, and later attempts',comparison:'caller disposition time, primary-list suppression time, downstream-list suppression time, and the first clean queue refresh',owner:'campaign compliance owner',limit:'the study cannot establish the identity or consent of the current number holder',fields:'number token, source list, response code, event time, suppression time by system, queue refresh, and any later attempt'},
  {slug:'customer-follow-up-reopened-case-measurement-research',title:'When should a customer follow-up case count as reopened?',excerpt:'Research guidance for distinguishing a new question from the return of an unresolved earlier case.',question:'which evidence supports calling a customer contact a reopened case rather than a new request',unit:'the original question, every owner handoff, closure reason, customer confirmation, and later contact',comparison:'a confirmed resolution, an administrative close, a repeated symptom, and a separate request on the same account',owner:'customer operations owner',limit:'matching words or account identifiers alone do not prove that two contacts concern the same unresolved issue',fields:'case identifier, customer wording, promised action, owner decision, close code, confirmation event, later wording, and reviewer link reason'},
  {slug:'survey-partial-completion-bias-review',title:'How should partial survey completions be reviewed?',excerpt:'A cautious framework for checking whether partial interviews differ from completed surveys before analysts discard them.',question:'what partial completions reveal about questionnaire position, respondent choice, and the limits of a completed-only analysis',unit:'one sampled contact, consent event, answered items, stop point, stop wording, call duration, and final disposition',comparison:'a completed interview, a respondent-led stop, a technical interruption, and an interviewer-led termination',owner:'survey method owner',limit:'a partial record cannot supply the answers that the respondent did not give',fields:'sample source, contact outcome, item order, responses, last completed item, stop code, duration, and any approved retry'},
  {slug:'call-recording-gap-score-impact-research',title:'What does a call recording gap do to quality scores?',excerpt:'A study plan for separating caller performance from missing or unintelligible review evidence.',question:'how recording gaps affect item scores, reviewer agreement, and the fairness of aggregate quality results',unit:'one recorded call, audio availability by timestamp, applicable scorecard items, independent reviews, and adjudication',comparison:'fully audible evidence, a gap unrelated to the item, a gap covering the scored behavior, and a completely missing recording',owner:'quality assurance owner',limit:'reviewers cannot reconstruct inaudible words from the call note or eventual outcome',fields:'recording identifier, gap start and end, affected item, reviewer code, cited evidence, score treatment, and adjudicated result'}
];

const sources = [
  'https://www.nist.gov/privacy-framework','https://www.nist.gov/cyberframework','https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule','https://www.ftc.gov/business-guidance/advertising-marketing/telemarketing','https://www.ftc.gov/business-guidance/privacy-security/data-security','https://www.fcc.gov/general/telemarketing-and-telephone-consumer-protection-act','https://www.donotcall.gov/','https://privacy.gov.ph/data-privacy-act/','https://aapor.org/standards-and-ethics/best-practices/'
];

function makeBody(t: Topic) { return [
  `Published: September 2, 2026. Research question: ${t.question}? This article describes an operational review method for OutsourcedCallers.com readers. It does not report a measured result for OutsourcedCallers.com or for Filipino callers.`,
  `Define the review unit before reading outcomes: ${t.unit}. Keep incomplete and disputed records when they belong to the released sample. Removing inconvenient cases after review would change the study population.`,
  `Code the difference between ${t.comparison}. Write a definition and one counterexample for each code. Reviewers should use unknown when the record does not support a decision.`,
  `Collect only the fields needed for the question: ${t.fields}. Preserve timestamps and the version of the queue, script, or scorecard that existed when the event occurred.`,
  `Separate what the caller could observe from later owner action. The Filipino caller owns accurate capture and the released handoff. The ${t.owner} owns policy, authoritative system changes, and the interpretation used for a business decision.`,
  `Use independent review for a small sample before scaling the coding work. When reviewers differ, require both to cite the record field or call moment behind the code. Adjudication should preserve the first ratings so disagreement remains measurable.`,
  `Report the numerator and denominator beside any rate. Also show missingness by reason. A neat percentage can hide records that lacked audio, timestamps, owner decisions, or a reliable link between systems.`,
  `Test whether the result changes under a second reasonable definition. If a narrow and broad rule lead to different conclusions, publish both and explain the operational choice instead of selecting the tidier number.`,
  `The main limitation is that ${t.limit}. Treat association as a prompt for process review, not proof that one caller action caused the later result.`,
  `A practical close gives the ${t.owner} three items: the field definition that failed most often, a short set of example records, and the next bounded review. The owner can then change the source, route, or instruction and test the same measure again.`,
  `Sources: ${sources.join(' | ')}`,
  `Method note: Retain exclusions, unknown values, reviewer disagreements, and version dates. Do not publish personal contact details or infer protected or sensitive traits from a call record. FAQ: What is the unit? ${t.unit}. Who owns interpretation? The ${t.owner}. What happens when evidence conflicts? Preserve both codes and send the case to adjudication.`
]; }

export const sep02ResearchPosts = topics.map((t) => ({slug:t.slug,title:t.title,excerpt:t.excerpt,published:'2026-09-02',image:'/thank-you-hero.png',body:makeBody(t)}));
