type Source = { title: string; publisher: string; url: string; checked: string };
type Study = { slug: string; title: string; excerpt: string; service: string; decision: string; unit: string; scenario: string; failure: string; owner: string; link: string; sources: Source[] };

const checked = '2026-09-18';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'Official Gazette of the Republic of the Philippines', url: 'https://www.officialgazette.gov.ph/2012/08/15/republic-act-no-10173/', checked };
const tsr: Source = { title: 'Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };

const studies: Study[] = [
  { slug: 'lead-qualification-budget-evidence-research', title: 'What counts as budget evidence in a lead qualification call?', excerpt: 'A prospective study for separating a prospect’s stated budget context from caller inference, scoring, and commercial approval.', service: 'lead qualification calls', decision: 'whether the record contains usable budget evidence for sales review without treating an estimate, objection, or caller assumption as purchasing authority', unit: 'one released lead, the approved qualification question, the prospect’s material words, the caller note, the qualification state, and the sales owner’s later decision', scenario: 'A prospect says the proposed range may be workable if implementation can wait until the next quarter. The statement supplies conditional context, but it does not prove an approved budget, authority to buy, or acceptance of price.', failure: 'a tentative range becomes a confirmed budget, a caller score replaces the prospect’s words, or missing budget information is treated as disqualification even when the client brief permits a later sales conversation', owner: 'sales or qualification owner', link: '/services/outbound-lead-qualification', sources: [tsr, calls, privacy, security, dpa] },
  { slug: 'reception-overflow-after-hours-privacy-research', title: 'How much information should after-hours reception collect?', excerpt: 'A data-minimization study for capturing an actionable after-hours message without gathering unnecessary personal or account details.', service: 'reception overflow', decision: 'which fields are necessary to route an after-hours message and which details should wait for an authorized owner or secure channel', unit: 'one after-hours inbound contact, the stated purpose, fields requested, fields recorded, route selected, recipient acknowledgement, and final handling state', scenario: 'A caller wants help with an account and begins volunteering sensitive background before an authorized account specialist is available. The overflow brief supports name, safe callback details, a bounded reason, and urgency routing, but not account investigation.', failure: 'the caller is encouraged to disclose more than the receiving owner needs, or minimization is interpreted so narrowly that the message lacks a safe callback method, purpose, or routing signal', owner: 'reception or privacy owner', link: '/services/reception-overflow', sources: [privacy, security, dpa, records, calls] },
  { slug: 'appointment-cancellation-ownership-research', title: 'Who owns an appointment cancellation request?', excerpt: 'A workflow study for distinguishing a requested cancellation from a calendar change that an authorized owner has actually completed.', service: 'appointment setting', decision: 'whether the caller may update the calendar directly, must preserve a cancellation request for the owner, or needs a bounded clarification before routing', unit: 'one scheduled appointment, its current calendar version, the contact’s exact request, caller action, owner receipt, calendar event, and final notification state', scenario: 'A participant asks to cancel a meeting that includes several attendees and an internal host. The caller can record the request, but the released workflow does not establish whether that participant may cancel for everyone or whether the host must decide.', failure: 'a request is reported as a completed cancellation, the calendar is changed without authority, or a valid stop request remains hidden because the workflow has only booked and rescheduled outcome codes', owner: 'calendar or appointment owner', link: '/services/appointment-setting', sources: [privacy, security, dpa, records, calls] },
  { slug: 'customer-follow-up-promise-reconciliation-research', title: 'How should customer follow-up teams reconcile promised next steps?', excerpt: 'An evidence-chain study connecting a customer-facing commitment to its source, owner, due condition, and verified completion state.', service: 'customer follow-up calls', decision: 'whether a stated next step is an approved commitment, a customer request, an estimate, or an unresolved action that requires owner confirmation', unit: 'one customer interaction containing a future action, its source wording, responsible owner, due condition, follow-up event, and final evidence of completion or correction', scenario: 'A prior note says someone will call back “tomorrow,” but it does not name the owner, timezone, approval source, or condition that starts the deadline. A follow-up caller must not convert that ambiguous note into a new guarantee.', failure: 'an unowned intention is repeated as a promise, completion is inferred from a closed task, or the customer receives repeated reassurance while the underlying action remains unresolved', owner: 'customer service or account owner', link: '/services/customer-follow-up-calls', sources: [privacy, security, dpa, records, tsr] },
  { slug: 'outbound-calling-local-time-control-research', title: 'How should an outbound calling queue control local contact time?', excerpt: 'A queue-governance study for using contact location, timezone confidence, campaign rules, and suppression state before an outbound attempt.', service: 'outbound calling', decision: 'whether a record is eligible to dial now, needs timezone review, or must remain suppressed under the client’s approved contact-window policy', unit: 'one released contact record, its location source, derived timezone and confidence, campaign window, dial event, correction, suppression state, and owner disposition', scenario: 'A business record has a headquarters address in one timezone, a mobile number associated with another area, and a note that the contact travels. The queue cannot establish the person’s current location from those clues alone.', failure: 'a derived timezone is treated as known current location, daylight-saving changes are missed, or uncertain records are dialed because the queue lacks a review state between eligible and suppressed', owner: 'campaign or compliance owner', link: '/services/outbound-lead-qualification', sources: [tsr, calls, privacy, security, dpa] },
];

function body(s: Study): string[] {
  const sourceNames = s.sources.map((x) => `${x.title} — ${x.publisher}`).join('; ');
  return [
    `Research question and decision context. This study asks: ${s.title} For a business evaluating Filipino callers for ${s.service}, the operational decision is ${s.decision}. The question is intentionally narrower than whether calls are productive. A decision-grade answer must preserve what the released record showed, what the contact actually said, what the approved workflow allowed, and what a named client owner later decided. Familiarity, confidence, a clean disposition, or a plausible interpretation is not a substitute for evidence.`,
    `Methodology. Use a prospective record review with definitions fixed before the observation window. Treat ${s.unit} as the observation unit. Define eligibility, required evidence, exclusions, outcome codes, time boundaries, and workflow versions before sampling. Give each unit a pseudonymous study identifier that links the release, contact, handoff, owner action, and final state without copying unrelated personal information into the analysis file. Record the study dates and every material rule change.`,
    `The study scenario should remain concrete: ${s.scenario} Preserve the material source fields and the contact’s words separately from the caller’s classification. Then capture the smallest permitted caller action, any stop or escalation, the receiving owner, an observable receipt event, and the final authoritative state. Reviewers must be able to distinguish “the source displayed,” “the contact stated,” “the caller recorded,” and “the owner approved.”`,
    `Primary outcomes. Score source fidelity, authority alignment, note completeness, routing accuracy, owner receipt, and final-state reconciliation separately. Source fidelity means a repeated fact traces to a named, dated source available at contact time. Authority alignment means the action stayed inside the released brief. A complete handoff names the material fact or request, the unresolved decision, the recipient, and the due or review condition. Receipt requires an observable acknowledgement or queue event, not an assumption that sending equals seeing.`,
    `Failure hypothesis. The principal risk is that ${s.failure}. Test that explanation against alternatives: stale source data, an unclear client rule, a missing workflow state, inaccessible ownership, system synchronization, caller departure from the brief, or later changes outside the calling team. Code stages independently. A downstream mismatch should not automatically be attributed to the caller, and a correct final result should not excuse unsupported wording or an unauthorized intermediate action.`,
    `Sampling plan. Combine a consecutive baseline sample with an intentional exception sample. The baseline estimates how often evidence states appear in ordinary work; the exception sample supplies enough difficult cases to test the boundary. Report them separately so oversampling does not imply exceptions are typical. Include successful contacts, refusals, no-answer attempts followed by contact, corrections, transfers, unresolved records, and records changed after the call. Count exclusions and missing chains rather than silently dropping them.`,
    `Data collection. Capture only what answers the research question: released purpose, source name and timestamp, relevant status, workflow version, suppression or permission state, contact event, material statement, caller disposition, escalation route, owner receipt, owner action, and final record state. Use controlled codes plus a short evidence note. Do not copy full recordings, passwords, payment data, government identifiers, health details, or unrelated history into the research dataset. The ${s.owner} should approve access, retention, correction, and deletion rules.`,
    `Facts, analysis, inference, and uncertainty. A timestamped source field is a fact when its provenance is retained. Comparing that field with the final record is analysis. Claiming that a wording choice caused behavior is an inference unless the design tests causation. Missing audio, overwritten values, unavailable acknowledgements, conflicting clocks, and actions in an unobserved system create uncertainty. The report should label these categories and retain plausible competing explanations rather than forcing every unit into a confident story.`,
    `Reviewer reliability. Create a codebook with positive examples, negative examples, and explicit cannot-determine rules. Two reviewers should independently code a blinded pilot containing routine and difficult units. Report agreement for each critical field, discuss disagreements, revise ambiguous definitions, and recode affected pilot units under the final guide. Adjudication may settle the study classification, but it must not rewrite the underlying source, caller note, or genuine conflict between records.`,
    `Analysis. Begin with counts and denominators: records released, attempts, contacts, qualifying scenarios, complete evidence chains, aligned actions, acknowledged handoffs, reconciled final states, exclusions, and unknowns. Show both counts and proportions where group size permits. Compare workflow versions only when populations and observation windows are reasonably similar. Keep completeness distinct from correctness: a fully populated record can document an unsupported action, while a sparse record may hide a correct action.`,
    `Bias and sensitivity. Queue age, campaign source, contact mix, caller schedule, language, owner staffing, system availability, policy changes, and missing evidence may affect results. Predefine these variables when practical. Separate records released before and after material workflow changes. Treat missingness as a finding because late notes or absent receipts may cluster in difficult cases. Recalculate conclusions with unknowns classified conservatively and report whether the operational decision changes.`,
    `Operational boundaries. A Filipino caller can follow a current brief, ask an approved clarification, preserve material words, honor a stop request, apply a permitted disposition, and route uncertainty to the named owner. The caller should not invent consent, location, authority, identity, eligibility, commercial terms, urgency, or final record status. The ${s.owner} retains policy, sensitive exceptions, and irreversible decisions unless a specific bounded action has been expressly released with an authoritative source.`,
    `Privacy and security. Apply minimization to both production work and the study copy. Use role-based access, named accounts, bounded exports, secure transfer, and a retention period tied to purpose. Preserve corrections without erasing the evidence trail. The NIST Privacy Framework provides a voluntary privacy-risk structure, FTC business guidance emphasizes limiting retained personal information and controlling access, and the Philippines Data Privacy Act is a relevant first-party statutory source. Qualified advisers must determine duties for the actual data, people, technology, and jurisdictions.`,
    `Implementation test. Translate one observed gap into the smallest prospective control: a required source timestamp, confidence field, distinct review state, named recipient, receipt acknowledgement, or structured reason for correction. Pilot one control with a defined sample and time window. Compare evidence completeness, boundary alignment, and unresolved-case visibility before wider adoption. Avoid changing scripts, queue rules, and review policy simultaneously because the study would not reveal which change mattered.`,
    `Limitations and non-claims. This protocol does not report OutsourcedCallers.com performance, promise a result, decide legal compliance, or establish causation from descriptive records. A sample can be small, selected, or affected by unobserved work. Source timestamps can disagree, recordings can be partial, and owners may act outside the reviewed system. Results apply to the studied workflow, population, versions, and period; they should not be generalized to every caller, campaign, customer, or jurisdiction.`,
    `Niche-specific conclusion. For ${s.service}, the useful evidence chain runs from the released source through the contact and caller action to owner receipt and the client-controlled final state. The standard is not that every record closes neatly. It is that permitted action is visible, uncertainty stops at the correct boundary, the ${s.owner} receives a usable decision packet, and later reviewers can reconcile the outcome without guessing. A buyer should inspect these fields, states, and ownership rules before relying on volume totals.`,
    `Source method and checked date. Sources were chosen for first-party law, regulation, privacy-risk, information-security, records, or communications guidance relevant to the protocol: ${sourceNames}. Each source link was checked on ${checked}. They frame controls and limitations; they do not provide performance findings about OutsourcedCallers.com, Filipino callers, or this proposed study. Applicability depends on the real campaign and jurisdiction.`,
    `Sources: ${s.sources.map((x) => `${x.title} | ${x.publisher} | ${x.url} | checked ${x.checked}`).join(' || ')}`,
  ];
}

export const sep18Run2ResearchPosts = studies.map((study) => ({ slug: study.slug, title: study.title, excerpt: study.excerpt, published: '2026-09-18' as const, image: '/thank-you-hero.png', body: body(study), handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this protocol to define the evidence, decision boundaries, and owner handoff before planning ${study.service} with a Philippines-based team.` } }));
