export type Topic = {
  slug: string; title: string; excerpt: string; question: string; buyer: string;
  queue: string; owner: string; evidence: string; boundary: string; example: string;
  metric: string; failure: string; service: string;
};

const published = '2026-09-18';

const topics: Topic[] = [
  {slug:'outsourced-calling-provider-evaluation-scorecard',title:'How to evaluate an outsourced calling provider: a practical scorecard',excerpt:'Compare outsourced calling providers on queue design, supervision, data handling, quality review, and handoffs instead of relying on a polished sales call.',question:'How can a buyer compare outsourced calling providers before choosing one?',buyer:'an operations leader comparing providers for a first calling program',queue:'a representative sample of the real follow-up or appointment-setting queue',owner:'the buyer who owns the business process and final vendor decision',evidence:'a written workflow, sample call notes, a quality scorecard, access controls, and named escalation routes',boundary:'Treat a presentation, staffing claim, or sample script as evidence of live delivery without testing it.',example:'Give each finalist the same ten anonymized scenarios: an ordinary follow-up, a refusal, an unclear identity, a pricing question, a reschedule, a duplicate record, an opt-out, a complaint, an unreachable contact, and an owner-only decision.',metric:'scenarios handled within the written boundary, with a usable note and correct next owner',failure:'selecting on headline price while leaving supervision, rework, security, and internal review effort unmeasured',service:'call-quality-review'},
  {slug:'outsourced-calling-rfp-requirements-checklist',title:'Outsourced calling RFP checklist for a decision-ready proposal',excerpt:'Write an RFP that shows providers the call purpose, list condition, tools, hours, controls, reporting needs, and decisions that remain with your team.',question:'What belongs in an RFP for outsourced calling services?',buyer:'a manager preparing a request for proposal for calling support',queue:'one clearly named call lane with volume, record age, expected outcomes, and seasonal constraints',owner:'the internal RFP owner who can answer process, security, and commercial questions',evidence:'queue samples, field definitions, required hours, system diagrams, policy constraints, and acceptance criteria',boundary:'Ask bidders to invent a scope or quote a reliable workload from only a monthly dial count.',example:'Describe 2,000 follow-up records by source, age band, time zone, known suppression status, and required result fields. State which records need a live call, which can receive voicemail, and what ends the sequence.',metric:'proposal assumptions that are explicit enough to compare and later test',failure:'receiving low-looking bids that depend on different staffing, list quality, review work, or definitions of a completed call',service:'outbound-lead-qualification'},
  {slug:'dedicated-vs-shared-outsourced-callers',title:'Dedicated vs shared outsourced callers: which model fits the queue?',excerpt:'Choose between dedicated and shared caller coverage by looking at context depth, schedule, variability, coaching load, and handoff risk.',question:'Should a business use a dedicated caller or a shared calling team?',buyer:'a business owner choosing a staffing model for recurring calls',queue:'the actual weekly queue split into steady work, predictable peaks, and true exceptions',owner:'the operations manager responsible for coverage and service continuity',evidence:'hourly arrival patterns, average handling bands, after-call work, training needs, and owner response time',boundary:'Assume a dedicated seat is always better or that a shared pool is automatically cheaper.',example:'A steady appointment-setting queue with product-specific qualification may justify one dedicated caller. A short overflow window with a narrow message form may fit a shared team if routing and privacy controls are strong.',metric:'coverage, context accuracy, useful handoffs, and paid idle or overflow time',failure:'choosing a staffing label before measuring how much context each call requires and when work actually arrives',service:'appointment-setting'},
  {slug:'outsourced-calling-cost-drivers-budget-guide',title:'Outsourced calling cost drivers: how to build a realistic budget',excerpt:'Build a calling budget around paid coverage, supervision, tools, telecom, training, quality review, and rework without inventing a universal rate.',question:'What determines the cost of outsourced calling?',buyer:'a finance or operations lead building a first outsourced calling budget',queue:'a workload forecast that separates attempts, conversations, after-call work, callbacks, and manager review',owner:'the budget owner who approves scope and commercial terms',evidence:'coverage hours, call-length bands, occupancy assumptions, tool licenses, telecom rules, training time, and review effort',boundary:'Publish or accept a cost-per-call estimate without defining what counts as a call and what work happens afterward.',example:'Model a ten-minute connected conversation separately from an unanswered attempt. Add the time required to read the record, leave a voicemail when allowed, write the note, schedule the next action, and route an exception.',metric:'total operating cost per useful outcome, with assumptions visible',failure:'comparing hourly rates while ignoring management time, low-quality records, callbacks, software, telecom, and correction work',service:'customer-follow-up-calls'},
  {slug:'outsourced-caller-onboarding-plan',title:'A 30-day onboarding plan for outsourced callers',excerpt:'Move a new outsourced caller from process training to supervised calls with written gates for access, scripts, notes, exceptions, and quality.',question:'How should a business onboard an outsourced caller during the first 30 days?',buyer:'a manager preparing a Filipino caller to work a live queue',queue:'a small, recent, low-risk sample that represents the work without exposing the full database',owner:'the process owner who can approve readiness and answer exceptions',evidence:'role brief, current script, approved examples, system access list, scorecard, and daily coaching notes',boundary:'Release the full queue because the caller completed tool training or read the script once.',example:'Use week one for process and practice, week two for closely reviewed live samples, week three for a larger bounded queue, and week four for a readiness review based on notes, outcomes, boundaries, and escalation behavior.',metric:'accurate calls and records that pass the same written readiness standard',failure:'treating attendance at training as proof that the caller can handle ambiguous live conversations',service:'call-quality-review'},
  {slug:'outsourced-caller-crm-access-matrix',title:'CRM access matrix for outsourced callers',excerpt:'Give callers the smallest CRM permissions needed for the released queue, with separate rights for viewing, editing, exporting, deleting, and administering records.',question:'What CRM access should an outsourced caller receive?',buyer:'a system owner granting a calling team access to customer records',queue:'the approved calling view with only the fields needed to prepare, call, record, and hand off',owner:'the CRM or data owner who grants, reviews, and removes access',evidence:'field inventory, role permissions, authentication controls, audit logs, retention rules, and a removal procedure',boundary:'Use one broad shared account or let convenience decide which customer data the caller can see.',example:'A caller may need to view a name, approved number, call purpose, time zone, and prior outcome while editing only disposition, neutral notes, next action, and suppression status. Export, deletion, billing, and administrator rights can remain unavailable.',metric:'authorized work completed without excess access or untraceable changes',failure:'copying an internal sales profile whose permissions include bulk export, record deletion, automations, or unrelated customer segments',service:'database-verification-calls'},
  {slug:'outsourced-calling-service-level-agreement',title:'How to write an outsourced calling service level agreement',excerpt:'Define service levels around queue acceptance, coverage, escalation, note completion, suppression handling, reporting, and recovery rather than raw dial volume.',question:'What should an SLA for outsourced calling services measure?',buyer:'a service owner turning a proposed calling scope into operating commitments',queue:'a named queue whose entry rules, priority bands, hours, and completion states are written down',owner:'the service owner who approves targets and handles tradeoffs',evidence:'timestamp definitions, calendars, priority rules, dependencies, measurement sources, exclusions, and remedy steps',boundary:'Use a response-time number without defining when the clock starts, stops, pauses, or depends on the client.',example:'For urgent callback messages, start the timer only when an eligible record reaches the released queue. Stop it when a complete handoff reaches the named owner, not when the caller simply marks the task done.',metric:'eligible records meeting the defined service state within the agreed window',failure:'rewarding fast dials that produce incomplete notes, unsupported promises, or unresolved exceptions',service:'reception-overflow'},
  {slug:'outsourced-calling-capacity-plan',title:'Outsourced calling capacity planning without dial-count guesswork',excerpt:'Estimate caller capacity from queue readiness, contact patterns, handling time, after-call work, occupancy, callbacks, training, and review demands.',question:'How many outsourced callers does a calling queue need?',buyer:'an operations planner deciding initial headcount and coverage',queue:'four weeks of eligible workload grouped by hour, day, call lane, and expected contact pattern',owner:'the workforce or operations owner who can change priorities and staffing',evidence:'attempt volume, connection bands, talk time, hold time, after-call work, shrinkage, concurrency limits, and backlog age',boundary:'Divide monthly records by working days and call the result a staffing plan.',example:'A list of 4,000 records does not reveal required seats. Some records may be stale or suppressed, several attempts may be allowed, connected calls may run longer than expected, and each result may create a callback or owner task.',metric:'eligible work completed within its window while quality and backlog remain stable',failure:'planning for average volume and discovering that peaks, coaching, meetings, outages, and owner delays consume the apparent spare capacity',service:'outbound-lead-qualification'},
  {slug:'outsourced-call-quality-calibration-session',title:'How to run an outsourced call quality calibration session',excerpt:'Calibrate reviewers with the same calls, evidence, scorecard, and decision rules so coaching does not depend on who happened to listen.',question:'How can managers calibrate outsourced call quality reviews?',buyer:'a quality lead whose reviewers score calls or call records',queue:'a balanced sample containing ordinary outcomes, refusals, exceptions, weak audio, and difficult handoffs',owner:'the quality owner who maintains the scorecard and resolves ambiguous rules',evidence:'recordings or approved transcripts, source records, final notes, dispositions, score definitions, and reviewer rationales',boundary:'Average conflicting scores before discovering why reviewers interpreted the evidence differently.',example:'Have each reviewer score the same five cases independently. Compare each field, identify whether disagreement came from missing evidence or an unclear rule, and revise only the rule that caused the gap.',metric:'reviewer agreement by scorecard item and the number of unresolved definitions',failure:'using one total score that hides disagreement about consent, identity, accuracy, tone, notes, or escalation',service:'call-quality-review'},
  {slug:'outsourced-calling-business-continuity-plan',title:'Business continuity planning for outsourced calling operations',excerpt:'Prepare alternate connectivity, contact trees, queue controls, data safeguards, and customer messaging before a power, network, system, or site disruption.',question:'What should a business continuity plan cover for outsourced callers?',buyer:'an operations owner whose calling program depends on remote people and cloud systems',queue:'critical and deferrable call lanes ranked by customer impact, safety, consent, and time sensitivity',owner:'the continuity owner authorized to pause, reroute, or restore work',evidence:'dependency map, recovery contacts, alternate procedures, approved outage messages, access controls, and exercise records',boundary:'Tell callers to improvise with personal devices, local files, or unapproved channels during an outage.',example:'If the CRM is unavailable, pause calls that require current account status. A narrow inbound message lane might continue only if the approved fallback records the minimum fields securely and reconciles them after restoration.',metric:'safe restoration of approved work, including reconciliation of every fallback record',failure:'restoring dial activity before confirming list version, suppression state, account data, recordings, and owner availability',service:'inbound-call-handling'},
  {slug:'outsourced-calling-vendor-exit-plan',title:'Outsourced calling vendor exit plan and data return checklist',excerpt:'Plan queue transfer, account removal, data return, retention evidence, open handoffs, number ownership, and customer continuity before a vendor relationship ends.',question:'How should a business exit an outsourced calling provider?',buyer:'a client preparing to transition or close a calling service',queue:'all active, paused, scheduled, suppressed, and unresolved records owned by the program',owner:'the client transition owner with authority across operations, security, legal, and systems',evidence:'asset register, account list, phone-number ownership, data locations, open actions, retention terms, and deletion attestations',boundary:'Disable the main login and assume that the queue, recordings, exports, account access, and open promises are resolved.',example:'Freeze new assignments, reconcile every active record, export only the agreed data through an approved route, transfer owned numbers and scripts, remove named access, and verify the destination queue before calls resume.',metric:'records, access, assets, and customer commitments reconciled with named owners',failure:'discovering after cutover that numbers, recordings, suppression evidence, scheduled callbacks, or administrator accounts remain with the former provider',service:'customer-follow-up-calls'},
  {slug:'manage-outsourced-calling-team-weekly-cadence',title:'How to manage an outsourced calling team: a weekly operating cadence',excerpt:'Use short daily exception checks and a focused weekly review to manage queue health, quality, coaching, owner decisions, and process changes.',question:'What management cadence keeps an outsourced calling team effective?',buyer:'a manager taking responsibility for an active outsourced calling program',queue:'the live queue plus its backlog, exceptions, suppression changes, callbacks, and owner-owned decisions',owner:'the client manager who changes priorities, approves scripts, and clears blocked work',evidence:'daily exception view, weekly trend report, sampled calls, note audit, change log, and action register',boundary:'Manage the team from a monthly dial total or wait for the provider to discover client-side blockers.',example:'Use a fifteen-minute daily check for safety, suppressions, blocked tools, urgent callbacks, and owner decisions. Use the weekly session for list health, sample quality, coaching patterns, capacity, script changes, and the next controlled improvement.',metric:'clean outcomes, aging exceptions, completed owner actions, and repeat defects',failure:'turning every review into a status meeting with no decision, owner, due time, or change to the operating brief',service:'call-quality-review'}
];

const sources = [
  {name:'Philippines National Privacy Commission, Data Privacy Act of 2012',url:'https://privacy.gov.ph/data-privacy-act/'},
  {name:'NIST Privacy Framework',url:'https://www.nist.gov/privacy-framework'},
  {name:'NIST Cybersecurity Framework 2.0',url:'https://www.nist.gov/cyberframework'},
  {name:'FTC guidance for complying with the Telemarketing Sales Rule',url:'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule'}
];

export function makeBuyerGuideDetail(t: Topic, publicationDate = published) {
  const sections = [
    {heading:'Start with the decision, not the vendor pitch',paragraphs:[
      `${t.question} Start by writing down the decision the business needs to make and the queue that decision affects. For ${t.buyer}, the working unit should be ${t.queue}. That is more useful than a broad request for "calling support" because a provider can see the work, the limits, and the handoff that must happen after each conversation.`,
      `Keep the buyer's responsibility visible. The ${t.owner} still owns policy, commercial commitments, sensitive account changes, and exceptions. Outsourcing transfers defined work, not accountability. A useful scope says what the caller may do, what evidence they may rely on, what they must record, and the exact point where an internal owner takes over.`
    ]},
    {heading:'Build the baseline from real queue evidence',paragraphs:[
      `Use current records rather than a clean hypothetical list. The minimum evidence for this decision is ${t.evidence}. Remove personal information from planning samples when it is not needed, but preserve the awkward cases that shape the workload. A sample made only of easy successes will understate training, review, and escalation needs.`,
      `Check how the queue is created and who can change it. Record age, duplicates, suppression state, time zone, missing fields, and prior attempts can alter the work before a caller speaks to anyone. If the source list cannot support a safe next action, fix the source or route it for review. Do not ask the caller to repair uncertain business rules during a live conversation.`
    ]},
    {heading:'Test the operating boundary with examples',paragraphs:[
      `${t.example} Ask the provider and the internal owner to walk through what the caller sees, says, records, and escalates. The answer should name a system field and an accountable person, not rely on "use good judgment" as the control.`,
      `${t.boundary} This is a firm stop because the client must be able to explain why a contact was called, what information was used, and who approved the next step. A caller can acknowledge a question and capture it accurately without deciding it. That distinction protects the customer conversation and makes the handoff reviewable.`
    ]},
    {heading:'Measure an outcome the next person can use',paragraphs:[
      `The central measure is ${t.metric}. Put the numerator, denominator, source system, reporting window, and exclusions beside the metric. Separate attempts, contacts, useful outcomes, refusals, suppressions, owner reviews, and unresolved records. One large activity number can hide a weak list or incomplete follow-up.`,
      `Review quality beside productivity. A fast caller who leaves vague notes creates work for the next person. A careful caller working a damaged list may appear slow while correctly stopping unsafe records. Compare the recording or approved evidence with the saved disposition, note, next action, owner, and due time. The systems should tell the same story.`
    ]},
    {heading:'Run a bounded proof before expanding',paragraphs:[
      `Release a small batch that includes common work and known exceptions. Decide in advance what will pause the test, who may correct the script, and how changed instructions reach every caller. Review early records closely enough to catch a bad field definition before it spreads across the full queue. Expansion should follow evidence that the workflow works, not pressure to consume the list.`,
      `The most likely planning error is ${t.failure}. Keep an assumptions register and give each assumption an owner. When actual handling time, contact patterns, review effort, or exception volume differs from the plan, update capacity and cost together. Do not preserve an attractive target by quietly removing difficult records from the report.`
    ]},
    {heading:'Protect personal information throughout the work',paragraphs:[
      `Calling records often contain personal information. The Philippines Data Privacy Act describes transparency, legitimate purpose, proportionality, accuracy, retention, security, and accountability principles. The client and provider should apply the laws and contractual duties that cover the actual people, numbers, locations, call purposes, and systems in the campaign. This guide is operational guidance, not legal advice.`,
      `Give each person a named account and only the fields needed for the released task. Control downloads, local storage, recordings, exports, and administrator rights separately. Set a retention rule for notes and audio, preserve suppression evidence in its authoritative system, review access on a schedule, and remove it promptly when the role or relationship ends.`
    ]},
    {heading:'Make the handoff part of the service',paragraphs:[
      `A completed call is not complete work when the next person cannot act. Require the note to show the source record, the contact's words where they matter, the approved disposition, any unresolved question, the next owner, and the due time. Keep the caller's observation separate from an internal decision made later.`,
      `Close each reporting period by reconciling open callbacks, owner questions, suppressions, complaints, failed records, and system mismatches. Age the exceptions instead of burying them in free text. The ${t.owner} should be able to see which decisions are blocking the queue and which instruction needs to change before another caller reaches the same situation.`
    ]},
    {heading:'Turn the review into a clear buying decision',paragraphs:[
      `Summarize the result in plain terms: what queue was tested, which rules were stable, what quality evidence passed, which exceptions remained, how much internal attention the work required, and what would change at a larger volume. Keep costs tied to the tested staffing and control model so the buyer does not compare unlike offers.`,
      `If the evidence is incomplete, narrow the release or extend the test. Do not fill gaps with promises about generic caller quality or national talent. A sound decision is specific to the call purpose, the client process, the selected people, and the controls around them. OutsourcedCallers.com can help scope a Philippines-based calling desk, while the client retains the final approval of access, scripts, policy, and customer commitments.`
    ]}
  ];
  return {
    published: publicationDate, mainKeyword:t.title, metaLabel:'Outsourced calling buyer guide',
    directAnswerHeading:t.question,
    summary:`Define ${t.queue}, keep the ${t.owner} accountable, test the workflow with real examples, and judge the provider on ${t.metric}. Expand only after the records, calls, notes, and handoffs agree.`,
    takeaways:[`Scope ${t.queue}.`,`Require ${t.evidence}.`,`Keep decisions with ${t.owner}.`,`Measure ${t.metric}.`],
    decisionTable:[
      {lane:'Scope',caller:'Reviews only the released queue and current brief.',owner:`The ${t.owner} defines purpose, access, and limits.`,measure:'Eligible work is identifiable'},
      {lane:'Call',caller:'Uses approved language and records attributable facts.',owner:'Maintains policy and approved answers.',measure:'No unsupported commitment'},
      {lane:'Exception',caller:'Pauses and routes the unresolved question.',owner:'Makes and records the decision.',measure:'One named next owner'},
      {lane:'Close',caller:'Reconciles outcome, note, and next action.',owner:'Reviews quality and changes the brief.',measure:t.metric}
    ],
    planningBands:[{label:'Queue',value:'Defined',note:t.queue},{label:'Evidence',value:'Named',note:'Source and record agree'},{label:'Boundary',value:'Written',note:t.owner},{label:'Review',value:'Sampled',note:t.metric}],
    sections,
    scripts:[
      {title:'Opening',text:'I am calling about the specific request in the record. Is now a suitable time to confirm the approved details?'},
      {title:'Boundary',text:'I can record that question accurately, but the named owner must make that decision.'},
      {title:'Close',text:'I have recorded the outcome, the next action, who owns it, and when the follow-up is due.'}
    ],
    workflow:[
      {step:'1',title:'Define',text:`Release ${t.queue}.`},{step:'2',title:'Test',text:'Work common cases and known exceptions.'},{step:'3',title:'Compare',text:'Check source, call, note, and outcome.'},{step:'4',title:'Repair',text:'Correct the rule or field causing the defect.'},{step:'5',title:'Decide',text:'Expand, narrow, or stop based on evidence.'}
    ],
    faqs:[
      {q:'What should the client decide before a provider starts?',a:`The client should approve the queue purpose, permitted records, script, access, dispositions, escalation owners, contact rules, and quality standard. The ${t.owner} remains accountable for decisions outside that brief.`},
      {q:'What is the most useful first metric?',a:`Use ${t.metric}. Report the eligible denominator and show exceptions rather than mixing them into a general activity count.`},
      {q:'When should the workflow pause?',a:`Pause when identity, permission, source data, suppression state, system availability, or owner authority is unclear. Also pause when the caller would need to ${t.boundary.charAt(0).toLowerCase()+t.boundary.slice(1)}`}
    ],
    related:[{label:t.title.includes('CRM')?'Database verification calls':'Outbound lead qualification',href:`/services/${t.service}`},{label:'Appointment setting',href:'/services/appointment-setting'},{label:'Plan a calling desk',href:'/contact'}],
    sources,image:'/thank-you-hero.png'
  };
}

export const sep18BlogPosts = topics.map(t => ({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:12,published,image:'/thank-you-hero.png'}));
export const sep18BlogDetails = Object.fromEntries(topics.map(t => [t.slug,makeBuyerGuideDetail(t)]));
