type T={slug:string;title:string;excerpt:string;unit:string;population:string;window:string;limit:string};
const topics:T[]=[
['shared-number-suppression-scope-research','How are shared-number opt-out requests resolved across linked records?','A prospective audit of stops, scope review, and later dialing.','one opt-out request from a number linked to multiple records','eligible shared-number records with an opt-out request','eight intake weeks plus fourteen days of monitoring','The audit cannot determine legal scope or prove causation.'],
['duplicate-case-follow-up-reliability-research','Do duplicate case references create inconsistent follow-up outcomes?','A record-linkage study of duplicate identifiers and dispositions.','one cluster sharing an external case reference','active records detected by the exact-match rule','twelve weekly snapshots plus thirty days','Exact matching misses variants; association does not prove cause.'],
['voicemail-disclosure-boundary-research','How consistently are unclear voicemail permissions routed?','A protocol study of disclosure ambiguity and callback state.','one callback request with undefined voicemail detail','eligible inbound requests in participating queues','six weeks through callback or closure','Records do not prove informed consent or identity.'],
['survey-age-eligibility-escalation-research','What happens when survey calls surface an age concern?','An evidence-minimizing review of stops and outcomes.','one interaction with a possible age concern','surveys whose script contains an age criterion','one fieldwork wave plus twenty-one days','A signal is not proof of age or consent validity.'],
['missing-consent-audio-quality-research','How do reviewers score calls when consent audio is missing?','A blinded reliability design for incomplete recordings.','one recording beginning after the consent point','recordings with a verified late start','a ten-week sample plus fifteen business days','Missing audio cannot prove consent; agreement is not compliance.']
].map(([slug,title,excerpt,unit,population,window,limit])=>({slug,title,excerpt,unit,population,window,limit}));
const refs='Sources/References: NIST Privacy Framework (https://www.nist.gov/privacy-framework); FTC Telemarketing Sales Rule (https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule); AAPOR Best Practices (https://aapor.org/standards-and-ethics/best-practices/); Philippines National Privacy Commission (https://privacy.gov.ph/data-privacy-act/).';
function body(t:T){return [`Published: September 11, 2026. This protocol examines ${t.title.toLowerCase()} It reports no measured effect or promised result.`,`Methodology: use ${t.unit} as the observation unit. Pre-register eligibility, exclusions, fields, missing-data codes, and comparisons.`,`Scope/population: ${t.population}. Observation window: ${t.window}. Do not generalize beyond these workflows, dates, and systems.`,`Data collection should preserve pseudonymous IDs, sources, timestamps, queue states, owner decisions, outcomes, exclusions, and missingness.`,`Analysis should report counts and denominators by workflow, case band, reviewer, action, and outcome. Use intervals only when supported.`,`Inference and causal boundaries: ${t.limit} Case mix, source age, staffing, season, scripts, and workflow changes are competing explanations.`,`Quality control: pilot a codebook, blind a second reviewer, and report agreement, adjudications, exclusions, and rule changes.`,`Limitations: incomplete audio, late notes, inconsistent timestamps, small groups, selection, and unobserved actions can bias results. Quantify each.`,`Use findings narrowly to improve a field, queue rule, reviewer guide, or prospective test; never judge an individual from aggregates.`,refs];}
export const sep11ResearchPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,published:'2026-09-11',image:'/thank-you-hero.png',body:body(t)}));
