import { buildResearchBody, type Source, type Study } from './sep18-run2-research';

const checked = '2026-09-28';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'National Privacy Commission of the Philippines', url: 'https://privacy.gov.ph/data-privacy-act/', checked };
const tsr: Source = { title: 'Complying with the Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };

type ExpandedStudy = Study & { deepDive: string[] };

const studies: ExpandedStudy[] = [
  {
    slug: 'inbound-identity-before-disclosure-research',
    title: 'What may an inbound caller hear before identity is confirmed?',
    excerpt: 'A disclosure-boundary study for giving useful reception help without revealing account, relationship, or case details to an unverified caller.',
    service: 'inbound call handling',
    decision: 'which neutral information may be shared immediately, which account-linked facts require the client’s approved identity check, and when the caller must be transferred or offered a safe callback path',
    unit: 'one inbound request for account-linked information, the number called, claimed identity and relationship, verification path offered, fields disclosed or withheld, transfer route, owner receipt, and final resolution',
    scenario: 'A person calling from a familiar number asks whether a named customer has an open service case. The caller knows contextual details, but caller ID and familiarity do not establish authority to receive the status.',
    failure: 'helpfulness turns into confirmation that a person is a customer, a rigid script blocks harmless public information, knowledge-based questions collect more sensitive data than the request warrants, or a failed check leaves no usable service path',
    owner: 'client privacy or service owner',
    link: '/services/inbound-call-handling',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `Decision model. Divide possible responses into public, relationship-revealing, account-specific, and action-authorizing classes before listening to sample calls. Public hours or a published mailing address can normally be repeated from an approved source. Confirming that a named person has an account, ticket, appointment, balance, delivery, or complaint reveals a relationship even when no details follow. Account-specific status adds another layer, while changing a record or making a commitment requires explicit authority. The study should test whether agents recognize the transition between classes rather than merely count completed verifications.`,
      `A useful verification design is proportional. The caller should not be invited to recite an entire address, date of birth, payment number, or other sensitive history when the requested answer does not require it. The client defines approved factors, fallback channels, proxy rules, and high-risk subjects. The caller records which path was used and whether it passed, but not secret answers in a free-text note. This distinguishes evidence that a check occurred from a new repository of authentication material.`,
      `Test four branches separately. In the public-information branch, the agent answers from a released source without confirming a customer relationship. In the successful-check branch, the response stays within the permissions attached to that identity and request. In the unsuccessful branch, the agent preserves the request, explains the next safe step, and avoids hints about which answer failed. In the unavailable-system branch, the agent does not improvise from memory; the record shows an outage route and named owner.`,
      `Proxy callers need their own observation category. An assistant, family member, colleague, interpreter, or caregiver may possess accurate context without having permission for every disclosure or action. Measure whether the workflow separates identity, relationship, and authority, and whether authority is specific to the requested task. A note that someone “usually calls for the customer” is evidence to route for review, not durable authorization. The client should decide how revocation, expiration, and emergency exceptions are represented.`,
      `The strongest outcome is not verification pass rate. Report avoidable disclosure, unnecessary collection, safe-resolution rate, transfer completion, repeated-contact rate, and unresolved requests. Review false reassurance as well as refusal: an agent may say nothing sensitive yet imply that a case exists through wording such as “I cannot discuss that ticket.” Compare this with neutral wording that neither confirms nor denies the relationship and still offers a path to an authorized team.`,
      `Quality review should reconstruct only the minimum sequence: request class, approved source or verification version, factor result, response class, and handoff. Reviewers should not reward agents for extracting extra personal detail or punish them when a correctly bounded call remains unresolved. A cannot-determine code is appropriate when recording starts late, the verification screen is absent, or the client system does not expose the authority record. Those gaps belong in system findings, not caller coaching by default.`,
      `For buyers of outsourced inbound support, the practical control is a disclosure matrix paired with example phrases and routing states. It should name information that is public, information that indirectly confirms a relationship, permitted verification methods, proxy handling, outage handling, and actions reserved to the client. Pilot it on deliberately mixed scenarios. If reviewers disagree on a boundary, revise the matrix before increasing volume. A faster average handle time is not evidence that disclosure decisions are sound.`
    ]
  },
  {
    slug: 'appointment-double-booking-conflict-research',
    title: 'How should appointment setters resolve a double-booking conflict?',
    excerpt: 'A calendar-control study for detecting overlapping commitments without letting a caller silently choose which meeting survives.',
    service: 'appointment setting',
    decision: 'whether an apparent overlap is real, which facts can be clarified, and which cancellation, reschedule, priority, or exception decision belongs to the calendar owner',
    unit: 'one overlap alert containing both event identifiers, calendar versions, organizers, participants, time zones, status, buffers, source invitations, caller contact, proposed options, owner decision, and notifications',
    scenario: 'A prospect accepts a new meeting while an internal hold occupies part of the slot. The hold has no description and may be movable, but the appointment setter has no released priority rule permitting its deletion.',
    failure: 'the newer event automatically displaces the older one, a tentative hold is treated as meaningless, time-zone display differences create a false conflict, or the caller promises a replacement slot before every required calendar accepts it',
    owner: 'calendar or appointment owner',
    link: '/services/appointment-setting',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `Conflict definition. Fix the calendar conditions that count as an overlap before auditing outcomes. Include event status, start and end instants, authoritative time zone, travel or preparation buffers, shared-resource constraints, and whether tentative events reserve capacity. Two colored blocks touching on a screen are not enough. Conversely, meetings displayed on different calendars may compete for the same host. The evidence unit should preserve the versions visible when the caller offered a time, because later edits can otherwise make a correct decision appear careless.`,
      `Separate detection from resolution. A caller can detect that two commitments overlap, verify whether the prospect has flexibility, and collect bounded alternatives. Choosing which organizer has priority, cancelling an existing event, shortening a meeting, removing a participant, or waiving a buffer may alter commitments outside the caller’s authority. The workflow needs an explicit owner and response window. If that owner is unavailable, the safe state is conflict pending, not a fabricated confirmation or quiet calendar edit.`,
      `A prospective test should seed several conflict types: exact overlap, partial overlap, recurring-series exception, daylight-saving conversion, all-day block, tentative internal hold, shared-room collision, and post-booking calendar change. For each, record whether detection occurred before confirmation, what evidence the caller saw, what alternatives were captured, and whether an authorized decision reached every affected calendar. Report each type separately because a system can handle exact overlaps well while missing series exceptions.`,
      `Notifications are part of the outcome, not administrative residue. A technically corrected calendar can still fail if the prospect retains the original invitation, the host receives no update, or a conferencing link points to the displaced event. Reconcile organizer copy, attendee response, link, reminders, and final start time. The study should distinguish sent, delivered, accepted, and merely present in the scheduling tool. None is automatically equivalent to a person understanding the change.`,
      `Measure confirmed-without-conflict rate, conflicts detected before promise, owner response time, unauthorized calendar mutations, participant acknowledgement, repeated reschedules, and unresolved overlaps at the observation cutoff. Use the original event as the denominator, not each email generated by one conflict. A low conflict count may indicate clean availability data, but it may also reflect missing calendars or a workflow that never records warnings. Audit a sample of apparently clean bookings for hidden resource collisions.`,
      `Fair comparisons require calendar-version controls. A new availability rule, host roster, buffer policy, or integration can change both exposure and detection. Stratify by workflow version and booking channel. Preserve unknowns where the source calendar was unavailable. Do not infer that an offshore appointment setter caused a collision merely because the setter created the visible event; the conflict may originate in stale synchronization, an owner’s later edit, or an incomplete release of availability.`,
      `A buyer-ready operating packet includes the authoritative calendar list, display-time standard, buffer rules, tentative-event treatment, allowed clarification questions, escalation owner, response deadline, and approved notification templates. Run a shadow pilot in which conflicts are identified but calendar decisions remain with the client. Expand authority only for precisely defined actions whose audit trail and reversal path are tested. The goal is reliable commitment control, not maximizing booked slots by treating uncertainty as availability.`
    ]
  },
  {
    slug: 'order-substitution-authorization-research',
    title: 'What evidence authorizes a product substitution during order confirmation?',
    excerpt: 'An order-control study for separating customer preference, inventory suggestion, commercial approval, and the final fulfillment instruction.',
    service: 'order confirmation calls',
    decision: 'whether the caller may record a substitution choice, must obtain explicit approval for changed price or attributes, or should hold the order for a commerce or fulfillment owner',
    unit: 'one proposed substitution, original item and terms, approved alternatives, inventory timestamp, material differences, customer statement, caller readback, commercial authorization, fulfillment acknowledgement, and final shipment record',
    scenario: 'The ordered size is unavailable and a nearby model is in stock. It looks equivalent, but its warranty, dimensions, delivery date, and price are not identical, and the confirmation caller cannot invent equivalence.',
    failure: 'availability becomes authority to substitute, silence is coded as consent, material differences are omitted, a customer choice exceeds the approved catalog, or fulfillment acts on an old note after inventory or terms change',
    owner: 'commerce or fulfillment owner',
    link: '/services/order-confirmation-calls',
    sources: [privacy, security, dpa, records, tsr],
    deepDive: [
      `Define the substitution object before measuring calls. It includes the original stock-keeping unit, quantity, price, taxes or fees, promised timing, warranty or return terms, and attributes the client marks material. The alternative needs the same fields plus an expiry or inventory timestamp. A statement that two products are “similar” is analysis unless the released catalog identifies the permitted equivalence. The research record should retain identifiers and differences, not copy unrelated payment details or the customer’s broader purchase history.`,
      `Authorization has at least three layers. The client authorizes which alternatives a caller may present. The customer chooses or rejects an available option after hearing material differences. The commerce system or named owner accepts the choice into the executable order. A successful conversation does not prove the final layer occurred, and a warehouse substitution does not prove the customer approved it. Score each layer independently and reconcile them against the shipped or cancelled state.`,
      `Build the observation set from every order entering a substitution state, not only completed replacement sales. Include unreachable customers, refusals, requests for another option, price objections, inaccessible-language cases, depleted alternatives, split fulfillment, and orders that return to the original item. This denominator prevents the study from praising a high acceptance rate produced by excluding difficult cases. Preserve the original order path so later catalog changes cannot rewrite what was offered.`,
      `Readback is a testable control. The agent names the alternative, quantity, changed material attributes, total or price difference when provided, delivery consequence, and what will happen next. The customer’s material response is recorded without converting hesitation into approval. Review whether the system requires an affirmative code and whether the caller can distinguish “I would prefer that” from “please change my order now” when an additional owner approval is required.`,
      `Primary measures include complete-difference disclosure, affirmative-choice evidence, catalog-bound alternative rate, owner or system acceptance, final-order reconciliation, preventable repeat contacts, and unauthorized substitutions. Add cannot-determine outcomes for missing audio or overwritten versions. Compare by exception type rather than by caller alone. Inventory volatility or an ambiguous catalog may dominate results, and coaching cannot repair a system that removes the proposed alternative before fulfillment receives it.`,
      `Sensitivity analysis should treat every uncertain authorization as not authorized, then repeat with unknowns excluded. If the conclusion changes, report that dependence instead of selecting the favorable estimate. Review lag between customer choice and fulfillment acceptance, because longer lag increases exposure to inventory changes. Separate customer-caused changes from business-initiated substitutions, since their scripts, evidence burdens, and commercial implications may differ.`,
      `For an outsourced-calling buyer, the launch gate is an approved substitution table, material-difference fields, readback language, explicit response codes, price and exception boundaries, expiry behavior, and a named fulfillment queue with acknowledgement. Pilot against real catalog versions but avoid live irreversible changes until the evidence chain is proven. A caller can make the choice legible and route it quickly; the client remains responsible for product claims, commercial rules, inventory truth, and execution.`
    ]
  },
  {
    slug: 'renewal-grace-period-ambiguity-research',
    title: 'How should renewal reminder calls handle an unclear grace period?',
    excerpt: 'A renewal-state study for preventing a caller from turning incomplete dates or status labels into unsupported coverage and deadline promises.',
    service: 'renewal reminder calls',
    decision: 'whether the source supports a reminder with a definite date, requires a bounded explanation of uncertainty, or must be referred to the contract, billing, or account owner',
    unit: 'one renewal record with governing term version, stated expiration, billing status, grace-period source, timezone, customer question, caller wording, owner handoff, and final authoritative state',
    scenario: 'A dashboard shows “grace” after the listed renewal date, but it does not say whether service continues, payment remains possible, fees accrue, or the label is only an internal collection state.',
    failure: 'an internal label becomes a promise of uninterrupted service, a general policy overrides customer-specific terms, the caller calculates a deadline from an unknown timezone, or uncertainty is hidden behind a confident reminder',
    owner: 'contract, billing, or account owner',
    link: '/services/renewal-reminder-calls',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `The study begins with a state model rather than a script. Distinguish approaching renewal, due, expired, administratively pending, payment processing, grace status, suspended, cancelled, and unknown. For each state, identify the authoritative source and permitted caller statement. A display label may summarize several underlying conditions and should not be expanded into legal, coverage, access, pricing, or fee claims unless the released source says so. Preserve the exact label and timestamp available during the call.`,
      `Dates require provenance. Record the source date, relevant timezone, calculation rule, and whether the date is inclusive or exclusive. If a term says “within ten days,” the calling team should not choose a counting convention. If systems disagree, the caller can report the approved neutral fact and route the conflict. The research question is whether uncertainty reaches the correct owner before the customer relies on it, not whether agents can perform increasingly elaborate date arithmetic.`,
      `Sample all records showing a grace-related label during a fixed window, then trace a stratified set through final disposition. Include customers who renew, decline, dispute the date, report payment, request cancellation, cannot be reached, or ask about continued service. Also inspect a sample without the label to detect missed states. Exclude test accounts explicitly and count records lacking a governing term; do not drop them as data cleaning because their absence is an operational finding.`,
      `Code caller language as source quotation, approved explanation, calculation, inference, or promise. This makes the key boundary observable. “The portal lists September 30” differs from “you are covered through September 30,” even though both mention one date. Record whether the caller acknowledged an uncertainty, named the receiving owner, supplied the question and source conflict, and avoided restarting repeated reminders while that decision remained pending.`,
      `Report accurate-state statement, unsupported-assurance rate, source-conflict detection, owner acknowledgement, corrected reminder rate, duplicate contact during pending review, and final reconciliation. A renewal conversion is not a quality proxy: a customer may renew after misleading wording, while a correct call may end without payment. Likewise, short calls may reflect clear sources or premature dismissal. Pair outcome measures with evidence-quality measures and show denominators.`,
      `Look for systematic causes by contract family, billing platform, migrated account, timezone, and workflow version. Missing or ambiguous terms may cluster in older records. Owner response delays may make agents repeat stale language. Treat these as process hypotheses and test them; do not assign cause from correlation. Recalculate results with unresolved cases counted as failures and then as unknowns, and disclose whether the operational recommendation changes.`,
      `The buyer-facing control set is a renewal state dictionary, source hierarchy, date display standard, prohibited promises, customer-question codes, pause rule for disputed reminders, and a named decision queue. Test it with boundary examples before production use. Outsourced callers can deliver consistent notices and preserve customer questions, but the client owns contract interpretation, billing corrections, service-continuity decisions, and any statement about fees or rights.`
    ]
  },
  {
    slug: 'call-quality-hold-silence-research',
    title: 'How should quality reviews score long holds and silence?',
    excerpt: 'A call-quality study for distinguishing necessary hold time, system delay, abandoned contact, and avoidable dead air without guessing intent from audio alone.',
    service: 'call quality review',
    decision: 'which intervals count as announced holds, unexplained silence, system latency, customer-side absence, or unobservable time, and what evidence supports coaching or process escalation',
    unit: 'one call timeline with connected and disconnected events, audio channels, speech activity, hold signals, announcements, system actions, transfers, customer response, caller notes, and final disposition',
    scenario: 'A recording contains ninety seconds without speech after the agent announces a lookup. The event log shows a delayed client screen, but the audio does not establish whether the customer remained connected or heard hold media.',
    failure: 'all silence is blamed on the agent, an announced hold excuses unlimited delay, missing audio is treated as dead air, talk-time targets encourage premature return without an answer, or a system defect disappears inside individual scores',
    owner: 'quality or operations owner',
    link: '/services/call-quality-review',
    sources: [privacy, security, dpa, records, calls],
    deepDive: [
      `Create a timeline taxonomy before reviewers listen. Candidate states include active conversation, announced hold, hold media, muted consultation, system wait, transfer ring, customer-side silence, agent-side silence, disconnected audio, and recording gap. Audio energy alone cannot reliably distinguish them. Require the smallest corroborating events available and use unobservable when channels or logs are missing. The study should test classification reliability as well as duration, because precise seconds attached to the wrong state create false confidence.`,
      `Segment boundaries need rules. Define how brief pauses, overlapping speech, repeated hold announcements, music interruptions, and transfers are joined or split. Keep raw timestamps separate from the reviewer’s state label. If an agent announces a lookup and returns periodically, report both total hold exposure and longest unacknowledged interval. This supports operational decisions without pretending that one universal duration is appropriate across every request, accessibility need, language, or client system.`,
      `Use a consecutive sample across shifts plus an enriched sample of calls flagged for high silence, long handle time, transfer, or abandonment. Report those groups separately. Include successful resolutions and failed contacts so the analysis does not equate long calls with poor calls. Preserve service type, system status, workflow version, and whether the customer explicitly agreed to hold. Remove unrelated personal content from the research copy and limit access to the minimum review team.`,
      `Two reviewers should label a blinded pilot at the interval level. Measure agreement on state and boundary placement, not merely the final pass or fail. Discuss cases where call audio conflicts with platform events, revise examples, and retain cannot-determine. Automated speech-activity detection may help locate intervals, but it does not identify cause, permission, customer experience, or responsibility. Validate any automated flag against human-coded samples before using it for coaching.`,
      `Outcomes should include total and longest interval by state, announcement and return-check presence, customer abandonment following an interval, successful resolution, system-error evidence, transfer completion, and reviewer agreement. Show distributions rather than only averages because a few extreme calls can dominate the mean. Do not combine customer-side silence with agent-side delay. If channels are not separated, state that limitation and avoid person-level conclusions unsupported by the recording.`,
      `Test alternative explanations for every coaching candidate. The agent may be searching an unfamiliar tool, waiting on authorization, reading a required disclosure, managing a transfer, or experiencing latency. The workflow may lack a callback option. Conversely, a system event does not automatically justify the interaction; the caller may still need to explain the wait or offer an approved alternative. Attribute the interval, communication behavior, and root-cause hypothesis as separate fields.`,
      `For buyers, the useful deliverable is a state codebook, observable thresholds for review rather than automatic failure, evidence requirements, system-incident route, coaching boundary, and callback or escalation options. Pilot it across multiple services because normal lookup time varies. The goal is to make avoidable silence visible while protecting callers from unsupported blame and customers from unexplained waiting. A quality score is credible only when the underlying timeline can be reconstructed.`
    ]
  }
];

export const sep28ResearchPosts = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: '2026-09-28' as const,
  image: '/thank-you-hero.png',
  body: [...buildResearchBody(study).slice(0, -2), ...study.deepDive, ...buildResearchBody(study).slice(-2)],
  handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this research to define evidence, decision boundaries, and owner handoffs before planning ${study.service} with a Philippines-based team.` },
}));
