import { buildResearchBody, type Source, type Study } from './sep18-run2-research';

const checked = '2026-09-25';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'National Privacy Commission of the Philippines', url: 'https://privacy.gov.ph/data-privacy-act/', checked };
const tsr: Source = { title: 'Complying with the Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };

const studies: Study[] = [
  { slug: 'inbound-duplicate-callback-request-research', title: 'How should inbound teams reconcile duplicate callback requests?', excerpt: 'A callback-control study for joining repeated requests without losing urgency, ownership, consent, or the customer’s latest instructions.', service: 'inbound call handling', decision: 'whether repeated contacts describe one open callback, a changed request, a separate issue, or an escalation that needs a named service owner', unit: 'one callback request lineage, each inbound contact and timestamp, safe return channel, stated purpose, urgency evidence, assigned owner, acknowledgement, attempted callback, and final resolution state', scenario: 'A customer calls twice about the same unresolved issue, gives a different safe callback window on the second call, and reaches another agent. The records look similar, but simply closing one as a duplicate could discard the newer instruction.', failure: 'two teams make competing callbacks, the newer contact details are lost, repeated contact is treated as proof of emergency, or a duplicate label hides that no owner accepted the original request', owner: 'inbound service or account owner', link: '/services/inbound-call-handling', sources: [privacy, security, dpa, records, calls] },
  { slug: 'appointment-no-show-disposition-research', title: 'What evidence supports an appointment no-show disposition?', excerpt: 'A scheduling-evidence study for separating an apparent absence from invitation, time-zone, access, cancellation, and host-side failures.', service: 'appointment setting', decision: 'whether the record supports a no-show classification, an organizer-side failure, a participant-side access problem, or an unresolved outcome requiring calendar-owner review', unit: 'one scheduled appointment, invitation version, participant confirmation, time zone, access instructions, reminders, cancellation messages, join evidence, host availability, follow-up contact, and final owner disposition', scenario: 'A prospect does not appear in the meeting room, but the invitation was updated shortly before start time and the system does not show whether the participant received the changed link. Absence alone does not establish a participant no-show.', failure: 'an invitation or host failure is attributed to the participant, an unverified no-show triggers an inappropriate follow-up sequence, or a calendar status is treated as proof that the intended meeting was reachable', owner: 'calendar or appointment owner', link: '/services/appointment-setting', sources: [privacy, security, dpa, records, calls] },
  { slug: 'database-unverifiable-correction-research', title: 'How should database verification calls record an unverifiable correction?', excerpt: 'A correction-governance study for preserving a caller-supplied change without overwriting an authoritative field that cannot yet be corroborated.', service: 'database verification calls', decision: 'whether a stated correction can be confirmed under the released verification rule, must remain a pending claim, or should be routed to the data owner for source resolution', unit: 'one field-level correction claim, original value and provenance, approved verification questions, respondent statement, confidence boundary, caller action, owner acknowledgement, source review, and final audit event', scenario: 'A person says the organization name in the record is outdated but cannot point to an approved corroborating source during the call. The statement is material evidence, yet it does not by itself authorize an irreversible overwrite.', failure: 'a plausible statement silently replaces sourced data, the caller rejects a useful correction merely because it is not immediately provable, or a later import restores the old value because the pending claim lacks provenance', owner: 'data or privacy owner', link: '/services/database-verification-calls', sources: [privacy, security, dpa, records, calls] },
  { slug: 'event-waitlist-release-research', title: 'What evidence should release a waitlisted event registration?', excerpt: 'A capacity-control study for connecting an available place, eligibility rule, invitation window, attendee response, and final registration state.', service: 'event registration calls', decision: 'whether a waitlisted attendee may receive an offer, has accepted within the approved window, needs an accommodation handoff, or remains pending with the event owner', unit: 'one waitlist position, governing rule version, capacity event, attendee eligibility, released offer, contact attempts, response deadline, attendee statement, organizer acknowledgement, and final registration state', scenario: 'A place opens and a caller reaches an attendee who wants to participate but asks whether an accessibility request can be supported. Interest does not prove final registration, and the caller cannot promise an arrangement the organizer has not confirmed.', failure: 'queue order is changed without an attributable rule, a verbal expression of interest consumes capacity indefinitely, an accommodation question is mistaken for refusal, or simultaneous offers create more confirmations than places', owner: 'event or registration owner', link: '/services/event-registration-calls', sources: [privacy, security, dpa, records, calls] },
  { slug: 'call-quality-missing-recording-research', title: 'How should quality reviews handle a missing or incomplete call recording?', excerpt: 'An evidence-availability study for preventing missing audio from becoming an automatic pass, failure, or unsupported reconstruction of caller behavior.', service: 'call quality review', decision: 'whether available evidence supports scoring particular fields, requires a cannot-determine code, reveals a recording-control defect, or warrants a separate operational review', unit: 'one selected quality-review unit, sampling reason, recording expectation, available audio span, call-event metadata, approved script version, disposition and notes, reviewer codes, system investigation, and final quality action', scenario: 'A selected call has complete metadata and a detailed outcome note, but the recording begins after the greeting and ends before the customer confirms the next step. Those artifacts may support some fields but cannot reconstruct the missing conversation.', failure: 'missing audio is scored as caller failure, a clean note is treated as proof of every spoken requirement, incomplete calls are silently replaced in the sample, or a recurring recording defect disappears inside individual coaching results', owner: 'quality or operations owner', link: '/services/call-quality-review', sources: [privacy, security, dpa, records, calls] },
];

export const sep25ResearchPosts = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: '2026-09-25' as const,
  image: '/thank-you-hero.png',
  body: buildResearchBody(study),
  handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this protocol to define evidence, decision boundaries, and owner handoffs before planning ${study.service} with a Philippines-based team.` },
}));
