import { buildResearchBody, type Source, type Study } from './sep18-run2-research';

const checked = '2026-09-24';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'National Privacy Commission of the Philippines', url: 'https://privacy.gov.ph/data-privacy-act/', checked };
const tsr: Source = { title: 'Complying with the Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };
const surveys: Source = { title: 'Best Practices for Survey Research', publisher: 'American Association for Public Opinion Research', url: 'https://aapor.org/standards-and-ethics/best-practices/', checked };

const studies: Study[] = [
  { slug: 'order-confirmation-partial-fulfillment-research', title: 'How should order-confirmation calls handle partial fulfillment?', excerpt: 'A fulfillment-evidence study for separating items that can ship, items on hold, customer preferences, and decisions that remain with the order owner.', service: 'order confirmation calls', decision: 'whether the caller can confirm the currently released fulfillment state, must collect a bounded customer preference, or should pause because availability, substitution, timing, or commercial terms need owner approval', unit: 'one order version, each line-item state and source timestamp, approved confirmation script, customer statement, caller disposition, fulfillment-owner receipt, later order event, and final customer notice', scenario: 'An order contains three items, but the current system shows one line on hold and does not say whether separate shipping is approved. The caller may confirm visible facts and record the customer preference, but cannot invent inventory, delivery timing, a substitute, or a refund.', failure: 'a partially available order is described as fully ready, a customer preference is saved as an approved fulfillment change, or a later system update overwrites the evidence showing what the caller and customer could know at contact time', owner: 'order or fulfillment owner', link: '/services/order-confirmation-calls', sources: [privacy, security, dpa, records, tsr] },
  { slug: 'lead-qualification-multiple-stakeholder-research', title: 'How should lead qualification calls distinguish multiple stakeholders?', excerpt: 'A buying-group evidence study for separating each person’s stated role, influence, question, and next step without inferring authority from job title.', service: 'lead qualification calls', decision: 'whether the record supports a person-specific qualification fact, identifies an unresolved stakeholder question, or needs sales-owner review before any authority or organizational fit is claimed', unit: 'one account-level lead, each contacted person and attributable statement, source and timestamp, approved qualification question, caller note, proposed relationship between contacts, sales-owner receipt, and later verified account map', scenario: 'One employee describes the operational problem, another controls calendar access, and a third appears on an older list with a senior title. The caller cannot merge their statements or assume that seniority proves budget, purchasing authority, or final approval.', failure: 'statements from different people become one fictional decision-maker profile, a title is used as a proxy for authority, or a shared account note loses which person supplied each fact and who agreed to the next contact', owner: 'sales or qualification owner', link: '/services/outbound-lead-qualification', sources: [tsr, calls, privacy, security, dpa, records] },
  { slug: 'win-back-suppression-propagation-research', title: 'How quickly must a win-back stop request reach every calling queue?', excerpt: 'A suppression-propagation study for tracing a contact-level stop request through lists, dialers, vendors, retries, and later campaign releases.', service: 'win-back campaign support', decision: 'whether a stop request is durably represented across every in-scope queue before another attempt can be released, while leaving legal scope decisions to the campaign owner', unit: 'one stop request, the exact wording and channel, receiving record, entity or campaign scope code, suppression event, each downstream list or dialer, attempted re-entry, owner review, and final reconciled state', scenario: 'A former customer asks not to receive more sales calls after a win-back conversation, but a separately prepared retry file is already waiting for upload. Closing only the active dialer record does not show that the request reached the staged file.', failure: 'the live record is suppressed while copied queues remain callable, ambiguous scope is narrowed without owner review, or a successful block in one system is reported as end-to-end propagation without checking later imports', owner: 'campaign or compliance owner', link: '/services/win-back-campaign-support', sources: [tsr, calls, privacy, security, dpa, records] },
  { slug: 'survey-proxy-respondent-boundary-research', title: 'When may a telephone survey accept answers from a proxy respondent?', excerpt: 'A respondent-eligibility study for distinguishing direct answers, permitted proxy reporting, household screening, and responses that the approved instrument cannot use.', service: 'survey calling', decision: 'whether the instrument and sample design permit another person to answer, require contact with the selected respondent, allow only a bounded eligibility screen, or require a refusal or unknown outcome', unit: 'one sampled unit, selection rule, person reached, claimed relationship, instrument version, consent or refusal state, questions answered, interviewer disposition, research-owner review, and analysis treatment', scenario: 'A household member answers the sampled telephone and offers to complete the survey for someone who is unavailable. Their willingness and familiarity do not establish that the study permits proxy answers or that they can report the selected person’s attitudes.', failure: 'a convenient household answer is attributed to the selected respondent, proxy and direct responses are analyzed together without disclosure, or callers collect extra identity details while trying to prove eligibility beyond the approved screen', owner: 'survey research owner', link: '/services/survey-calling', sources: [surveys, privacy, security, dpa, records, calls] },
  { slug: 'outbound-caller-id-mismatch-research', title: 'What should happen when an outbound call displays the wrong caller ID?', excerpt: 'A release-control study for detecting mismatches between the approved calling identity, transmitted number, callback route, campaign record, and recipient experience.', service: 'outbound calling', decision: 'whether a queue should remain released after a caller-ID mismatch or pause until the campaign owner verifies the transmitted identity and a safe, functioning callback route', unit: 'one approved campaign identity, configured originating number, test call, carrier or dialer event, recipient display, callback result, production attempt, complaint or correction, owner decision, and release state', scenario: 'The script names the client correctly, but a test recipient sees an unfamiliar number and the return call reaches a generic route with no campaign context. The caller cannot repair that infrastructure mismatch through more confident wording.', failure: 'a configuration defect is treated as a caller coaching issue, a single successful display is assumed to represent every carrier or route, or production continues while recipients cannot reconcile the stated business with the number and callback experience', owner: 'campaign or telephony owner', link: '/services/outbound-lead-qualification', sources: [tsr, calls, privacy, security, records] },
];

export const sep24ResearchPosts = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: '2026-09-24' as const,
  image: '/thank-you-hero.png',
  body: buildResearchBody(study),
  handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this protocol to define evidence, decision boundaries, and owner handoffs before planning ${study.service} with a Philippines-based team.` },
}));
