import { buildResearchBody, type Source, type Study } from './sep18-run2-research';

const checked = '2026-09-23';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'Official Gazette of the Republic of the Philippines', url: 'https://www.officialgazette.gov.ph/2012/08/15/republic-act-no-10173/', checked };
const tsr: Source = { title: 'Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };

const studies: Study[] = [
  { slug: 'lead-qualification-source-recency-research', title: 'How recent should lead data be before a qualification call?', excerpt: 'A source-recency study for separating a usable lead record from stale employer, role, contact, consent, or account context.', service: 'lead qualification calls', decision: 'whether a released lead has sufficiently recent, attributable evidence for the approved qualification contact or should pause for list-owner review', unit: 'one released lead, each material source and timestamp, permission or suppression state, contact attempt, prospect correction, caller disposition, owner receipt, and reconciled record', scenario: 'A list shows a senior title and company domain from an older enrichment event, while a newer public or first-party signal suggests the person changed roles. The caller cannot treat the older title as current merely because it remains in the dialer.', failure: 'stale role data is presented as current fact, a prospect correction is overwritten by the next import, or an undated field is used to justify qualification when its provenance and permitted use are unknown', owner: 'sales operations or list owner', link: '/services/outbound-lead-qualification', sources: [tsr, calls, privacy, security, dpa, records] },
  { slug: 'reception-failed-transfer-recovery-research', title: 'What should happen after a reception transfer fails?', excerpt: 'A recovery-path study for preserving caller context, privacy, and ownership when a warm or direct transfer does not connect.', service: 'reception overflow', decision: 'whether to retry an approved destination, take a bounded message, arrange a callback, or escalate without making the caller repeat sensitive details', unit: 'one attempted transfer, caller purpose, identity state, approved destination, transfer result, retained context, fallback choice, receiving-owner acknowledgement, and final disposition', scenario: 'A caller has already given a concise account-related purpose, but the intended recipient does not answer after the caller is placed on hold. The fallback must preserve enough context without exposing the account matter to an unapproved person.', failure: 'a failed transfer becomes an abandoned contact, the caller must repeat sensitive information to several people, or a generic message loses the destination, purpose, safe callback route, and unresolved request', owner: 'reception or service owner', link: '/services/reception-overflow', sources: [privacy, security, dpa, records, calls] },
  { slug: 'appointment-participant-timezone-confirmation-research', title: 'How should appointment setters confirm participant time zones?', excerpt: 'A scheduling-evidence study for distinguishing a participant-stated time zone from inferred location, calendar display settings, and daylight-saving assumptions.', service: 'appointment setting', decision: 'whether the proposed time is confirmed for every required participant or needs clarification before the calendar invitation is treated as ready', unit: 'one proposed appointment, participant-stated location or time zone, source and timestamp, calendar zone, offset on the meeting date, confirmation wording, invitation event, and later correction', scenario: 'A prospect gives availability as 10 a.m. without naming a time zone, their phone number has an unrelated area code, and the meeting date falls near a daylight-saving transition. Those clues do not establish the intended instant.', failure: 'an area code is treated as current location, an abbreviation with multiple meanings is accepted without confirmation, or the organizer sees a converted calendar time and assumes every participant confirmed it', owner: 'calendar or appointment owner', link: '/services/appointment-setting', sources: [privacy, security, dpa, records, calls] },
  { slug: 'customer-follow-up-owner-change-research', title: 'How should follow-up calls handle a change in action owner?', excerpt: 'An ownership-continuity study for keeping a customer request visible when responsibility moves between people, queues, or teams.', service: 'customer follow-up calls', decision: 'whether the newly assigned owner has accepted the complete action, due condition, customer-safe update, and unresolved decision before the prior owner is removed', unit: 'one open customer action, original evidence, former owner, reassignment reason, new owner, acknowledgement event, due condition, customer contact, and authoritative completion state', scenario: 'An account contact leaves a team while a customer is waiting for a promised review. Reassigning the task changes responsibility, but it does not prove that the new owner saw the source evidence or accepted the prior commitment.', failure: 'a routing change is reported as progress, the customer receives conflicting promises from successive callers, or the action disappears because each queue assumes another team owns the next step', owner: 'customer service or account owner', link: '/services/customer-follow-up-calls', sources: [privacy, security, dpa, records, tsr] },
  { slug: 'survey-partial-interview-continuation-research', title: 'When can a partial telephone survey be continued later?', excerpt: 'A protocol-integrity study for deciding whether an interrupted interview may resume without duplicating answers, changing respondent context, or weakening consent.', service: 'survey calling', decision: 'whether the approved instrument permits a later continuation, requires a restart, records a partial completion, or must stop after refusal or withdrawn permission', unit: 'one interrupted interview, respondent and consent state, instrument version, completed item boundary, interruption reason, approved resume rule, later contact, final status, and analysis treatment', scenario: 'A respondent answers several questions and then must end the call. They say another time may work, but the instrument does not clearly state how long answers remain valid or whether a different interviewer may resume.', failure: 'a polite interruption is coded as consent to repeated calls, earlier answers are duplicated or silently changed, or a resumed interview crosses instrument versions and is analyzed as one consistent session', owner: 'survey research owner', link: '/services/survey-calling', sources: [privacy, security, dpa, records, calls] },
];

export const sep23ResearchPosts = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: '2026-09-23' as const,
  image: '/thank-you-hero.png',
  body: buildResearchBody(study),
  handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this protocol to define evidence, decision boundaries, and owner handoffs before planning ${study.service} with a Philippines-based team.` },
}));
