import { buildResearchBody, type Source, type Study } from './sep18-run2-research';

const checked = '2026-09-22';
const privacy: Source = { title: 'NIST Privacy Framework', publisher: 'National Institute of Standards and Technology', url: 'https://www.nist.gov/privacy-framework', checked };
const security: Source = { title: 'Protecting Personal Information: A Guide for Business', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business', checked };
const dpa: Source = { title: 'Republic Act No. 10173: Data Privacy Act of 2012', publisher: 'Official Gazette of the Republic of the Philippines', url: 'https://www.officialgazette.gov.ph/2012/08/15/republic-act-no-10173/', checked };
const tsr: Source = { title: 'Telemarketing Sales Rule', publisher: 'Federal Trade Commission', url: 'https://www.ftc.gov/legal-library/browse/rules/telemarketing-sales-rule', checked };
const calls: Source = { title: 'Unwanted Calls, Texts, and Faxes', publisher: 'Federal Communications Commission', url: 'https://www.fcc.gov/general/unwanted-calls-texts-and-faxes', checked };
const records: Source = { title: 'Records Management Regulations, Policy, and Guidance', publisher: 'National Archives and Records Administration', url: 'https://www.archives.gov/records-mgmt/policy', checked };

const studies: Study[] = [
  { slug: 'event-registration-accommodation-handoff-research', title: 'How should event registration callers hand off accessibility requests?', excerpt: 'A prospective study of how a registration caller can preserve an attendee’s requested accommodation without interpreting needs or promising an unapproved arrangement.', service: 'event registration calls', decision: 'whether the registration record gives the event owner enough exact, minimized context to confirm an accommodation while keeping feasibility and sensitive decisions with that owner', unit: 'one registration interaction containing an accommodation request, the caller’s exact-note field, consented contact route, named recipient, acknowledgement event, and final organizer response', scenario: 'An attendee asks whether live captions can be provided and starts explaining personal medical history. The caller needs the requested communication support and a safe reply route, but the organizer—not the caller—must confirm what the event can provide.', failure: 'a request is reduced to an ambiguous special-needs label, unnecessary health detail is copied into the registration record, or a caller’s reassurance is later mistaken for organizer confirmation', owner: 'event or accessibility owner', link: '/services/event-registration-calls', sources: [privacy, security, dpa, records, calls] },
  { slug: 'call-quality-calibration-drift-research', title: 'How can a call quality team detect scorecard calibration drift?', excerpt: 'A reviewer-reliability study for separating real changes in caller performance from changes in how reviewers interpret a quality scorecard.', service: 'call quality review', decision: 'whether a score movement reflects the reviewed calls, a changed rubric, uneven evidence access, or reviewer interpretation that requires recalibration before operational action', unit: 'one pseudonymous call sample, its frozen rubric version, permitted evidence packet, independent reviewer scores, disagreement codes, adjudication result, and any later coaching decision', scenario: 'Two reviewers agree that a caller captured the outcome but disagree on whether the note meets the completeness standard because one expects an owner and due condition that the published rubric does not name.', failure: 'reviewer strictness is reported as caller deterioration, adjudication silently rewrites the rubric, or aggregate agreement hides repeated disagreement on a critical compliance or handoff field', owner: 'quality or operations owner', link: '/services/call-quality-review', sources: [privacy, security, dpa, records, calls] },
  { slug: 'renewal-reminder-status-freshness-research', title: 'How fresh should account status be before a renewal reminder call?', excerpt: 'A source-freshness study for preventing stale renewal status, recent payment, cancellation, or preference changes from becoming a misleading reminder.', service: 'renewal reminder calls', decision: 'whether the released account state is recent and authoritative enough to support the approved reminder or should be stopped for owner review', unit: 'one renewal record, source system and timestamp, release time, contact preference, caller-visible status, attempt event, customer correction, owner receipt, and reconciled account state', scenario: 'A queue exported overnight still shows a renewal as due, but a payment or cancellation may have posted in another system before the scheduled call. The caller cannot infer the current state from the export alone.', failure: 'a stale due state is stated as current fact, a customer correction is treated as proof of back-office completion, or the next batch repeats the reminder because no acknowledgement closes the correction loop', owner: 'account or renewal owner', link: '/services/renewal-reminder-calls', sources: [tsr, calls, privacy, security, dpa, records] },
  { slug: 'order-confirmation-substitution-boundary-research', title: 'What evidence is needed before recording an order substitution?', excerpt: 'A decision-boundary study for distinguishing a customer’s product preference from an authorized and fulfilled substitution.', service: 'order confirmation calls', decision: 'whether the caller may record a bounded substitution request, needs a clarification, or must stop for inventory, pricing, fulfillment, or payment review', unit: 'one order line, the authoritative ordered item, approved substitution options, customer words, caller action, fulfillment acknowledgement, price state, and final order version', scenario: 'A customer says a similar color would be acceptable if the ordered item is unavailable. That conditional preference is not evidence that inventory is unavailable, the price is unchanged, or fulfillment has approved a replacement.', failure: 'conditional preference becomes a completed substitution, an unapproved alternative changes price or terms, or the fulfillment team receives a vague note that cannot be reconciled to the original line item', owner: 'fulfillment or order owner', link: '/services/order-confirmation-calls', sources: [privacy, security, dpa, records, calls] },
  { slug: 'database-verification-conflicting-identity-research', title: 'How should callers handle conflicting identity evidence during database verification?', excerpt: 'An evidence-provenance study for routing conflicting identifiers without merging records, overwriting authoritative fields, or collecting unnecessary data.', service: 'database verification calls', decision: 'whether the presented evidence supports a permitted field confirmation, requires a correction request, or must stop for the data owner to resolve identity and record linkage', unit: 'one verification contact, minimum approved identity checks, candidate records, source provenance and timestamps, conflicting fields, caller note, owner decision, and final audit event', scenario: 'A caller reaches a person whose name and phone match one record while the email and organization align with another. The match is not enough to prove that the records belong to one person or should be merged.', failure: 'partial matches are treated as identity proof, a caller overwrites one record to make the conflict disappear, or excessive personal information is collected in an attempt to resolve a decision owned by the data controller', owner: 'data or privacy owner', link: '/services/database-verification-calls', sources: [privacy, security, dpa, records, calls] },
];

export const sep22ResearchPosts = studies.map((study) => ({
  slug: study.slug,
  title: study.title,
  excerpt: study.excerpt,
  published: '2026-09-22' as const,
  image: '/thank-you-hero.png',
  body: buildResearchBody(study),
  handoff: { href: study.link, label: `Review ${study.service}`, text: `Use this protocol to define evidence, decision boundaries, and owner handoffs before planning ${study.service} with a Philippines-based team.` },
}));
