import type { RoutePost } from '../aug19-blog-route-types';
import { makeAug19RouteDetail } from '../aug19-blog-source-repair-shared';

// Route identity: appointment-setting-precall-research-boundary; publication date: 2026-08-19; source body: 16 substantive paragraphs.
export const post: RoutePost = {
  slug: 'appointment-setting-meeting-purpose-confirmation',
  title: 'Appointment setting pre-call research boundary',
  excerpt: 'A practical boundary for preparing appointment-setting calls without turning research into unsupported assumptions.',
  minutes: 14,
  published: '2026-08-19',
  focus: 'pre-call research',
  question: 'What should the caller record and when should the owner decide?',
  owner: 'the workflow owner',
  angles: ["approved fields","research freshness","neutral questions","participant context","calendar fit","exception routing","note quality","review sampling"],
  sourceBody: [
    'Start by naming the operating question and the record that gives it context. A Filipino caller should see the purpose, permitted fields, current script, result labels, and owner before speaking with anyone. That preparation narrows the task to an observable action and prevents a caller from inventing policy while trying to be helpful. In this guide, the specific checkpoint is approved fields, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Treat the customer’s words as evidence, not as a shortcut to a conclusion. The caller can record what was said, what was declined, and what remains unclear. The note should distinguish a confirmed fact from a request, preference, concern, or assumption so the receiving owner knows what still needs a decision. In this guide, the specific checkpoint is research freshness, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Use the smallest practical record view. Showing every available field encourages unnecessary questions and makes it harder to tell which detail mattered. Release only the context required for the call, keep sensitive values masked, and document the source of a field when the workflow depends on its accuracy. In this guide, the specific checkpoint is neutral questions, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Write the opening around the reason for contact rather than around a broad sales claim. A focused introduction helps the person decide whether the call is relevant. It also gives a caller a respectful way to stop when the record, requested outcome, or permission does not fit the approved lane. In this guide, the specific checkpoint is participant context, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Build one neutral clarification into the procedure. Clarification should resolve a defined ambiguity, not lead the conversation toward an answer the business wants. If the clarification does not settle the point, label the uncertainty and route it instead of repeating the same question until the contact gives a convenient answer. In this guide, the specific checkpoint is calendar fit, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Give every exception a visible disposition. A refused answer, conflicting record, requested change, opt-out, complaint, language need, or missing owner is useful operational information. The disposition should say what happened and what must happen next; it should not disguise an unresolved case as a completed call. In this guide, the specific checkpoint is exception routing, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Define the caller’s boundary beside the owner’s boundary. Routine confirmation, note-taking, and approved scheduling may belong to the caller. A policy choice, sensitive data decision, commercial commitment, identity dispute, or unusual request belongs to the named owner. The handoff is stronger when both sides are explicit. In this guide, the specific checkpoint is note quality, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Make the next action concrete. A useful note includes the record reference, the relevant answer, the unresolved point, the receiving person or team, and a due window when one exists. “Follow up later” is not a plan unless the workflow also states who will follow up, through which route, and under what condition. In this guide, the specific checkpoint is review sampling, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Review the queue before volume begins. Remove records that are suppressed, stale, duplicated, missing a reason, or outside the approved calling window. This protects caller time and prevents the team from learning that a bad list was a caller-performance problem. In this guide, the specific checkpoint is approved fields, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'During the call, use one question at a time and allow the contact to finish. A caller who rushes to the next field can miss a correction or a boundary. Notes should preserve meaningful qualifiers such as “only,” “not yet,” “after approval,” or “do not call this number again.” In this guide, the specific checkpoint is research freshness, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'At close, compare the conversation with the saved system state. The result label, callback route, appointment detail, suppression status, or escalation should match the note. If they do not match, pause the record for review rather than allowing a neat label to conceal a messy handoff. In this guide, the specific checkpoint is neutral questions, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Managers can improve the routine by sampling the decisions that matter most. Listen or read for source fidelity, complete dispositions, respectful language, accurate boundaries, and useful next actions. Activity counts can show workload, but they cannot prove that the right customer context reached the right owner. In this guide, the specific checkpoint is participant context, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Use version control in the ordinary operational sense: identify the current brief, retire old wording, and tell callers when a rule changes. A change is not complete when a document is edited; it is complete when the queue, script, note fields, and reviewer all reflect the same instruction. In this guide, the specific checkpoint is calendar fit, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'Keep public guidance factually bounded. An outsourced calling team can execute a defined workflow, but it should not claim authority it does not have. When a customer asks for an answer outside the release, a clear escalation protects trust better than a confident but unsupported promise. In this guide, the specific checkpoint is exception routing, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'End each working day with a short reconciliation. Count completed dispositions separately from attempts, list open exceptions, identify records waiting on an owner, and capture a small adjustment for the next release. This turns recurring calling into a process that can be inspected and improved. In this guide, the specific checkpoint is note quality, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
    'A durable routine makes uncertainty easy to see. The goal is not to force every conversation into a success label; it is to ensure that each record has an honest state, an appropriate boundary, and a next person who can act. That is the standard that makes outsourced calling useful to an existing team. In this guide, the specific checkpoint is review sampling, which gives the pre-call research routine a concrete review point rather than a generic activity target.',
  ].join('\\n\\n'),
};

export const detail = makeAug19RouteDetail(post);
